// Otomatik üretildi: Ironsworn Bölüm 1 "The Basics" (PDF s.12–38) sayfa-sayfa.
// Görseller static/basics/*.webp; metinler /ceviri (Opus, glossary) ile çevrildi.

export interface BasicsPage {
	page: number;
	img: string;
	title_en: string;
	title_tr: string;
	text_en: string;
	text_tr: string;
	diagram?: 'action-roll' | 'move' | 'sheet';
}

export const basicsPages: BasicsPage[] = [
	{
		"page": 1,
		"img": "/basics/p01.webp",
		"title_en": "Playing Ironsworn",
		"title_tr": "Ironsworn Oynamak",
		"text_en": "In the *Ironsworn* tabletop roleplaying game, you are a hero sworn to undertake perilous quests in the dark fantasy setting of the Ironlands. You will explore untracked wilds, fight desperate battles, forge bonds with isolated communities, and reveal the secrets of this harsh land. Most importantly, you will swear iron vows and see them fulfilled—no matter the cost.\n\nTo play *Ironsworn*, you create your character, make some decisions about the world you inhabit, and set the story in motion. When you encounter something dangerous or uncertain, your choices and the dice determine the outcome.\n\n*Ironsworn* supports three modes of play.\n\n- __Guided:__ One or more players take the role of their characters, the protagonists in your story, while a gamemaster (GM) moderates the session. The GM helps bring the world to life, portrays the people and creatures you encounter, and makes decisions about the outcome of your actions.\n- __Cooperative (Co-Op):__ You and one or more friends play together to overcome challenges and complete quests. A GM is not required. The *Ironsworn* game system will help you explore the dramatic stories of your characters and their fateful vows.\n- __Solo:__ As with cooperative play, no GM is necessary. You portray a lone heroic character in a dangerous world. Good luck!\n\n*Ironsworn* is primarily intended for solo and small group play. One to four players (plus a GM in guided mode) is ideal. The characters portrayed by other players are referred to in these rules as your allies.\n\n## What You Need\n\nIf you're playing solo, just grab some materials and get started. A session can be as long as you like, from a few minutes to a few hours.\n\nIf you're playing with one or more friends—either guided or co-op—you probably want to dedicate enough time to make some progress in your quests. Plan on a couple of hours or more.",
		"text_tr": "*Ironsworn* masaüstü rol yapma oyununda sen, Demir Diyarlar'ın karanlık fantezi dünyasında tehlikeli görevlere ant içmiş bir kahramansın. İzi sürülmemiş yabanları keşfedecek, umutsuz savaşlar verecek, yalıtılmış topluluklarla bağlar kuracak ve bu çetin diyarın sırlarını açığa çıkaracaksın. En önemlisi, demir antlar (iron vows) içecek ve bedeli ne olursa olsun onları yerine getireceksin.\n\n*Ironsworn* oynamak için karakterini yaratır, yaşadığın dünyaya dair kararlar verir ve hikâyeyi harekete geçirirsin. Tehlikeli ya da belirsiz bir şeyle karşılaştığında, sonucu senin seçimlerin ve zarlar belirler.\n\n*Ironsworn* üç oyun modunu destekler.\n\n- __Rehberli (Guided):__ Bir ya da daha fazla oyuncu, hikâyenin başkahramanları olan karakterlerini canlandırır; bir oyun yöneticisi (GM) ise oturumu yönetir. Oyun Yöneticisi dünyayı canlandırmaya yardım eder, karşılaştığın insanları ve yaratıkları temsil eder ve eylemlerinin sonuçlarına dair kararlar verir.\n- __Ortak (Co-Op):__ Sen ve bir ya da daha fazla arkadaşın, zorlukları aşmak ve görevleri tamamlamak için birlikte oynarsınız. Oyun Yöneticisi gerekmez. *Ironsworn* oyun sistemi, karakterlerinizin ve kader yüklü antlarının çarpıcı hikâyelerini keşfetmenize yardım eder.\n- __Solo:__ Ortak oyunda olduğu gibi, Oyun Yöneticisi gerekmez. Tehlikeli bir dünyada yalnız bir kahramanı canlandırırsın. Bol şans!\n\n*Ironsworn* öncelikle solo ve küçük grup oyunu için tasarlanmıştır. Bir ile dört oyuncu (rehberli modda artı bir Oyun Yöneticisi) idealdir. Diğer oyuncuların canlandırdığı karakterlere bu kurallarda müttefiklerin denir.\n\n## Neye İhtiyacın Var\n\nSolo oynuyorsan, birkaç malzeme kapıp başlayabilirsin. Bir oturum birkaç dakikadan birkaç saate dek istediğin uzunlukta olabilir.\n\nBir ya da daha fazla arkadaşınla oynuyorsan—rehberli ya da ortak—muhtemelen görevlerinde ilerleme kaydedecek kadar zaman ayırmak istersin. Birkaç saat ya da fazlasına hazırlan."
	},
	{
		"page": 2,
		"img": "/basics/p02.webp",
		"title_en": "Mechanics and the Fiction",
		"title_tr": "Mekanikler ve Kurgu",
		"text_en": "Make sure you have:\n\n- Two ten-sided dice (d10) for each player. These are your challenge dice.\n- One six-sided die (d6) for each player. This is your action die.\n- Optionally, another pair of ten-sided dice to use as your oracle dice.\n- A printed character sheet for each player and printed asset cards (available at ironswornrpg.com).\n- Some counters for marking status tracks on your character sheet. You can use paper clips, beads, dice, coins, tokens from other games, or whatever is convenient.\n\nNot required, but helpful: printed reference sheets for moves, the blank Ironlands map, and other worksheets available at ironswornrpg.com.\n\n## Mechanics and the Fiction\n\n*Ironsworn* uses various mechanics, such as rolling dice and managing the stats and resources on your character sheet. As a player, you will often make decisions based on a desired mechanical outcome. For example, you might choose a particular action to get a bonus on your die roll. The basic mechanics of *Ironsworn* are introduced in this chapter.\n\n*Ironsworn* is also heavily reliant on the fiction, which is the imagined characters, situations, and places within your game. You will play from the perspective of your character. You will interpret actions and events in a way that is consistent with the dramatic, fictional reality you have forged for your story and your world.\n\nTo learn more about how the mechanics and fiction interact, see page 203.\n\n## The Setting\n\nThe default setting for your adventures is the Ironlands. It is a rugged peninsula of isolated communities and untracked wilds on the frontier of the known world. You can learn more about the setting starting on page 111. For now, here's a summary of some default assumptions.\n\n- Two generations ago, your people were driven to the Ironlands from their former homes in the Old World.\n- The weather here is harsh. Winters are brutal. The rugged terrain makes travel and trade difficult and dangerous.",
		"text_tr": "Elinde şunlar olduğundan emin ol:\n\n- Her oyuncu için iki adet on yüzlü zar (d10). Bunlar senin zorluk zarlarındır.\n- Her oyuncu için bir adet altı yüzlü zar (d6). Bu senin eylem zarındır.\n- İsteğe bağlı, kehanet zarı olarak kullanacağın bir çift on yüzlü zar daha.\n- Her oyuncu için basılı bir karakter sayfası ve basılı yetenek kartları (ironswornrpg.com'da bulunur).\n- Karakter sayfandaki durum izlerini işaretlemek için birkaç sayaç. Ataç, boncuk, zar, madeni para, başka oyunlardan jeton ya da elinde ne uygunsa kullanabilirsin.\n\nGerekli değil ama yararlı: hamleler için basılı başvuru sayfaları, boş Demir Diyarlar haritası ve ironswornrpg.com'da bulunan diğer çalışma kâğıtları.\n\n## Mekanikler ve Kurgu\n\n*Ironsworn*, zar atmak ve karakter sayfandaki statları ve kaynakları yönetmek gibi çeşitli mekanikler kullanır. Oyuncu olarak çoğu zaman istediğin bir mekanik sonuca göre kararlar verirsin. Örneğin, zar atışında bonus almak için belirli bir eylemi seçebilirsin. *Ironsworn*'ün temel mekanikleri bu bölümde tanıtılır.\n\n*Ironsworn* aynı zamanda büyük ölçüde kurguya dayanır; yani oyunundaki hayal edilen karakterler, durumlar ve yerlere. Oyunu karakterinin bakış açısından oynarsın. Eylemleri ve olayları, hikâyen ve dünyan için kurduğun çarpıcı, kurgusal gerçeklikle tutarlı bir biçimde yorumlarsın.\n\nMekaniklerin ve kurgunun nasıl etkileştiğini öğrenmek için bkz. sayfa 203.\n\n## Dünya\n\nMaceralarının varsayılan dünyası Demir Diyarlar'dır (the Ironlands). Bilinen dünyanın sınırında, yalıtılmış toplulukların ve izi sürülmemiş yabanların bulunduğu çetin bir yarımadadır. Dünya hakkında daha fazlasını sayfa 111'den itibaren öğrenebilirsin. Şimdilik, bazı varsayılan kabullerin bir özeti şöyle:\n\n- İki kuşak önce, halkın Eski Dünya'daki (the Old World) eski yurtlarından Demir Diyarlar'a sürüldü.\n- Buranın havası çetindir. Kışlar amansızdır. Engebeli arazi, seyahati ve ticareti zor ve tehlikeli kılar."
	},
	{
		"page": 3,
		"img": "/basics/p03.webp",
		"title_en": "The Setting",
		"title_tr": "Dünya",
		"text_en": "- There are no thriving cities. Instead, Ironlanders live in isolated villages or steadings. Their homes are modest buildings of wood, stone, and thatch.\n- Many areas of the Ironlands are unexplored and uninhabited except by the firstborn—beings such as elves, giants, and the wolf-like varou.\n- Coins have little value here. Most commerce is made through barter and favors.\n- Some communities remain isolated and independent, while others trade in basic goods such as iron, grain, wood, livestock, wool, and coal.\n- There is a diverse mix of peoples and cultures within the Ironlands, even within a single community. You can envision your character and those you interact with however you like, unbound by considerations of geography, lineage, sexual orientation, and gender.\n- Communities sometimes band together under a powerful leader, but there are no kingdoms. Territorial lines are sketchily drawn, if at all.\n- Large-scale warfare is unheard of, but raiding parties and skirmishes between communities are a constant menace. Some communities subsist entirely on raiding.\n- Spear, axe, shield, and bow are the dominant weapons. Swords are rare and highly prized. Some warriors choose to wade into battle clad in iron, while others trust in their prowess or in the strength of their shields.\n- Magic is subtle and mysterious. Mystics seek to ward away the darkness through the practice of magic, but often succumb to it. Rituals are performed as blessings and to gain insight.\n- Supernatural creatures and beasts are rare, frightening, and dangerous.\n\nYou are encouraged to make *Ironsworn* your own, and to bend the setting to your liking. Your version of the Ironlands will be unique because you'll define aspects such as the history of your people, magic, mythic beasts, and more. The choices you make will help inspire the personal vows driving your character.\n\nYou can also ignore the Ironlands entirely and play in your own world, or explore a setting inspired by media, history, or another roleplaying game. The *Ironsworn* rules are flexible enough to accommodate many forms of gritty fantasy or historical fiction.\n\nWith a bit of work, you can even adapt these rules to different genres. See page 237 for more on hacking *Ironsworn*.",
		"text_tr": "- Refah içindeki şehirler yoktur. Bunun yerine Demir Diyar sakinleri yalıtılmış köylerde ya da yerleşimlerde yaşar. Evleri ahşap, taş ve samandan yapılma mütevazı yapılardır.\n- Demir Diyarlar'ın birçok bölgesi keşfedilmemiştir ve İlk Doğanlar'dan başka kimse oralarda yaşamaz—elfler, devler ve kurt benzeri varou gibi varlıklar.\n- Burada madeni paranın değeri azdır. Ticaretin çoğu takas ve iyilikler yoluyla yapılır.\n- Bazı topluluklar yalıtılmış ve bağımsız kalır; bazılarıysa demir, tahıl, odun, hayvan, yün ve kömür gibi temel mallar üzerinden ticaret yapar.\n- Demir Diyarlar'da, tek bir topluluk içinde bile, çeşitli halkların ve kültürlerin karışımı vardır. Karakterini ve etkileştiğin kişileri coğrafya, soy, cinsel yönelim ve cinsiyet kaygılarından bağımsız olarak istediğin gibi hayal edebilirsin.\n- Topluluklar bazen güçlü bir önderin altında bir araya gelir ama krallıklar yoktur. Sınır çizgileri, varsa bile, ancak baştan savma çizilmiştir.\n- Büyük çaplı savaşlar görülmemiştir ama yağmacı grupları ve topluluklar arası çatışmalar sürekli bir tehdittir. Bazı topluluklar tümüyle yağmayla geçinir.\n- Mızrak, balta, kalkan ve yay başat silahlardır. Kılıçlar nadir ve çok değerlidir. Bazı savaşçılar muharebeye demir kuşanarak girmeyi seçer; bazılarıysa hünerine ya da kalkanlarının gücüne güvenir.\n- Büyü incelikli ve gizemlidir. Mistikler büyü uygulayarak karanlığı uzak tutmaya çalışır ama çoğu zaman ona yenik düşer. Ritüeller, kutsama olarak ve sezgi kazanmak için yapılır.\n- Doğaüstü yaratıklar ve canavarlar nadir, ürkütücü ve tehlikelidir.\n\n*Ironsworn*'ü kendine mal etmen ve dünyayı zevkine göre bükmen teşvik edilir. Demir Diyarlar'ın senin sürümün eşsiz olacak, çünkü halkının tarihi, büyü, efsanevi canavarlar ve daha fazlası gibi yönleri sen tanımlayacaksın. Verdiğin seçimler, karakterini güden kişisel antlara ilham verecek.\n\nDemir Diyarlar'ı tamamen göz ardı edip kendi dünyanda da oynayabilir ya da medyadan, tarihten veya başka bir rol yapma oyunundan esinlenen bir dünyayı keşfedebilirsin. *Ironsworn* kuralları, sert fantazinin ya da tarihî kurgunun birçok biçimine uyacak kadar esnektir.\n\nBiraz çabayla bu kuralları farklı türlere bile uyarlayabilirsin. *Ironsworn*'ü değiştirmek hakkında daha fazlası için bkz. sayfa 237."
	},
	{
		"page": 4,
		"img": "/basics/p04.webp",
		"title_en": "Iron Vows",
		"title_tr": "Demir Antlar",
		"text_en": "## Iron Vows\n\nIn the Ironlands, a vow is sacred. When you declare your solemn promise to serve or aid someone, or to complete a personal quest, your honor is bound to that vow. Abandoning or recanting an oath is the worst sort of failure.\n\nWhen you swear a vow, you touch a piece of iron. It can be an iron coin, a weapon, or your armor. It's an old tradition. Some say the iron, a piece of the primal world, serves as a conduit to the old gods—so they may better hear your promise.\n\nVows are the core of playing *Ironsworn*. It is your vows that drive you. These goals create the context for your adventures and challenges. As you complete vows, you gain experience and new abilities.\n\nWhen you create your character, you start with a background vow. When you set up your campaign, you envision or encounter an inciting incident which triggers a new vow. There are several prompts for vows associated with the details of the world in chapter 4 (page 111), and with foes and encounters in chapter 5 (page 133). You can select something which fits your vision for the world and your character's goals, or just come up with something yourself. If you are playing in co-op mode, you and your fellow players may have shared vows and personal vows.\n\nTo learn more about your first vows and starting your campaign, see page 193.\n\n## Your Character\n\nYou use your character sheet to track your stats, overall condition, and progress in your quests. You also have assets (page 21), which are abilities you choose when you create your character and when you gain experience. These components help you determine the outcome when things get dangerous or uncertain.\n\nHowever, your character is more than these mechanical bits. You are the protagonist in a rich story. You have hopes and fears, virtues and failings. You have a history. You are, or were, part of a community. This is the fiction of your character. Consider a few of these details as you create your character, but don't sweat it. You'll evolve it through play. At the start of your game, put your character on stage to see what happens. Fill in the blanks—for your character and your world—as you go.\n\nTo learn more about creating your character and the components that make up your character, see page 31.",
		"text_tr": "## Demir Antlar\n\nDemir Diyarlar'da ant kutsaldır. Birine hizmet etmek ya da yardım etmek, veya kişisel bir görevi tamamlamak için ciddi bir söz verdiğinde, onurun o anda bağlanır. Bir andı terk etmek ya da ondan dönmek, en kötü türden başarısızlıktır.\n\nBir ant içtiğinde bir demir parçasına dokunursun. Bu bir demir para, bir silah ya da zırhın olabilir. Eski bir gelenektir. Kimileri der ki demir, ilksel dünyanın bir parçası olarak, eski tanrılara açılan bir kanaldır—öyle ki sözünü daha iyi duysunlar.\n\nAntlar, *Ironsworn* oynamanın çekirdeğidir. Seni güden, antlarındır. Bu amaçlar, maceralarının ve zorluklarının bağlamını oluşturur. Antlarını tamamladıkça deneyim ve yeni yetenekler kazanırsın.\n\nKarakterini yarattığında bir geçmiş andıyla başlarsın. Seferini kurarken, yeni bir andı tetikleyen kışkırtıcı bir olayı hayal eder ya da onunla karşılaşırsın. Bölüm 4'te (sayfa 111) dünyanın ayrıntılarına bağlı, Bölüm 5'te (sayfa 133) ise düşmanlara ve karşılaşmalara bağlı antlar için çeşitli esinler vardır. Dünyaya dair vizyonuna ve karakterinin amaçlarına uyan bir şey seçebilir ya da kendin bir şey uydurabilirsin. Ortak modda oynuyorsan, sen ve oyun arkadaşların ortak antlara ve kişisel antlara sahip olabilirsiniz.\n\nİlk antların ve seferine başlamak hakkında daha fazlasını öğrenmek için bkz. sayfa 193.\n\n## Karakterin\n\nStatlarını, genel durumunu ve görevlerindeki ilerlemeni izlemek için karakter sayfanı kullanırsın. Ayrıca yetenek kartların (sayfa 21) vardır; bunlar karakterini yarattığında ve deneyim kazandığında seçtiğin yeteneklerdir. Bu bileşenler, işler tehlikeli ya da belirsiz hâle geldiğinde sonucu belirlemene yardım eder.\n\nNe var ki karakterin bu mekanik parçalardan ibaret değildir. Sen, zengin bir hikâyenin başkahramanısın. Umutların ve korkuların, erdemlerin ve kusurların var. Bir geçmişin var. Bir topluluğun parçasısın ya da öyleydin. Bu, karakterinin kurgusudur. Karakterini yaratırken bu ayrıntılardan birkaçını düşün ama fazla kafanı yorma. Onu oyun boyunca geliştireceksin. Oyununun başında, ne olacağını görmek için karakterini sahneye çıkar. Boşlukları—karakterin ve dünyan için—ilerledikçe doldur.\n\nKarakterini yaratmak ve karakterini oluşturan bileşenler hakkında daha fazlasını öğrenmek için bkz. sayfa 31."
	},
	{
		"page": 5,
		"img": "/basics/p05.webp",
		"title_en": "The Components of Your Character",
		"title_tr": "Karakterinin Bileşenleri",
		"text_en": "Your character is made up of several components, tracked on your character sheet.\n\n- __Vows__ (page 35) are your sacred oaths to complete perilous quests. Each vow has a rank and is managed through a progress track.\n- __Stats:__ You have five stats (page 33) which represent the core aspects of your character. These are often added as a bonus when you take action.\n- __Experience:__ As you fulfill vows, you earn experience (page 44). You spend experience to gain new assets.\n- __Status tracks:__ You have status tracks for health, spirit, and supply (page 33). These represent your current condition and readiness.\n- __Debilities:__ You suffer debilities (page 36) as you face harrowing challenges. Some debilities are temporary and easily mended; others are permanent.\n- __Momentum:__ As you take action, you build or lose momentum (page 11). Positive momentum can help improve the result of an action. Negative momentum can undermine an otherwise successful action.",
		"text_tr": "Karakterin, karakter sayfanda izlenen birkaç bileşenden oluşur.\n\n- __Antlar (Vows)__ (sayfa 35), tehlikeli görevleri tamamlamak için içtiğin kutsal yeminlerdir. Her andın bir derecesi vardır ve bir ilerleme izi (progress track) üzerinden yönetilir.\n- __Statlar:__ Karakterinin temel yönlerini temsil eden beş statın (sayfa 33) vardır. Bunlar, eyleme geçtiğinde çoğu zaman bonus olarak eklenir.\n- __Deneyim:__ Antlarını yerine getirdikçe deneyim (sayfa 44) kazanırsın. Yeni yetenek kartları edinmek için deneyim harcarsın.\n- __Durum izleri:__ Can (health), ruh (spirit) ve ikmal (supply) için durum izlerin (sayfa 33) vardır. Bunlar şu anki durumunu ve hazır oluşunu temsil eder.\n- __Olumsuz etkiler:__ Sarsıcı zorluklarla yüzleştikçe olumsuz etkilere (sayfa 36) maruz kalırsın. Bazı olumsuz etkiler geçicidir ve kolayca iyileşir; bazılarıysa kalıcıdır.\n- __Momentum:__ Eyleme geçtikçe Momentum biriktirir ya da kaybedersin (sayfa 11). Pozitif Momentum bir eylemin sonucunu iyileştirmeye yardım edebilir. Negatif Momentum, başka türlü başarılı olacak bir eylemi baltalayabilir.",
		"diagram": "sheet"
	},
	{
		"page": 6,
		"img": "/basics/p06.webp",
		"title_en": "Moves",
		"title_tr": "Hamleler",
		"text_en": "## Moves\n\nMoves are self-contained systems to resolve a specific action, scene, or question. There is a move for most common situations you encounter in *Ironsworn*. They have specific triggers, phrased as \"When you [blank].\" When your character does that thing, or you encounter that situation, refer to the move to see what happens.\n\nMoves are organized by activities.\n\n- __Adventure moves__ (page 60) cover a variety of dangers, conducting investigations, traveling, making camp, and healing.\n- __Relationship moves__ (page 69) involve persuading others to do something, building bonds with people and communities, resting and recuperating within a community, aiding your allies, and initiating duels.\n- __Combat moves__ (page 78) are used when fighting (but not exclusively; other moves may come into play as well).\n- __Suffer moves__ (page 90) occur when you endure hardship, such as suffering physical harm or facing a dispiriting challenge.\n- __Quest moves__ (page 98) encompass iron vows, making progress in a sworn quest, and improving your character.\n- __Fate moves__ (page 104) help you decide what happens in solo and co-op play, or support the GM's decisions and brainstorming in guided play.\n\nWhen a move's name is referenced within these rules or by another move, you'll see it as italicized text.\n\nMost moves are based on risky actions you are taking. You are attacking with your sword, making a dangerous climb, or healing an ally. These moves use dice to determine the outcome. This is called an action roll (page 8).\n\nSome moves measure your headway against an extended challenge, such as a journey or fight, using a progress track (page 14). When you are ready to resolve the challenge, you make a progress roll (page 18).\n\nOther moves utilize a different kind of dice roll, called an oracle roll (page 22). These moves help determine the outcome of uncertain events out of your character's control. If you're playing solo or co-op, you can use the *Ask the Oracle* move (page 107) to answer questions about the world, resolve how other characters respond, or determine what happens next.\n\nSome moves don't require a roll. They might support or reference a separate move, or simply help you resolve a mechanical or narrative situation. Don't roll dice unless a move tells you to. To learn more about moves, see page 49.",
		"text_tr": "## Hamleler\n\nHamleler (Moves), belirli bir eylemi, sahneyi ya da soruyu çözmek için kendi içinde bütün sistemlerdir. *Ironsworn*'de karşılaştığın çoğu yaygın durum için bir hamle vardır. Belirli tetikleyicileri vardır; \"[Şunu] yaptığında\" biçiminde ifade edilir. Karakterin o şeyi yaptığında ya da o durumla karşılaştığında, ne olacağını görmek için hamleye başvur.\n\nHamleler etkinliklere göre düzenlenmiştir.\n\n- __Macera hamleleri__ (sayfa 60) çeşitli tehlikeleri, soruşturma yürütmeyi, seyahat etmeyi, kamp kurmayı ve şifa bulmayı kapsar.\n- __İlişki hamleleri__ (sayfa 69) başkalarını bir şey yapmaya ikna etmeyi, insanlarla ve topluluklarla bağ kurmayı, bir toplulukta dinlenip toparlanmayı, müttefiklerine yardım etmeyi ve düellolar başlatmayı içerir.\n- __Savaş hamleleri__ (sayfa 78) dövüşürken kullanılır (ama yalnızca o zaman değil; başka hamleler de işin içine girebilir).\n- __Katlanma hamleleri__ (sayfa 90) zorluğa katlandığında ortaya çıkar; örneğin fiziksel hasara uğramak ya da yıldırıcı bir zorlukla yüzleşmek gibi.\n- __Görev hamleleri__ (sayfa 98) demir antları, ant içilmiş bir görevde ilerleme kaydetmeyi ve karakterini geliştirmeyi kapsar.\n- __Kader hamleleri__ (sayfa 104) solo ve ortak oyunda ne olacağına karar vermene yardım eder ya da rehberli oyunda Oyun Yöneticisi'nin kararlarını ve fikir üretmesini destekler.\n\nBir hamlenin adı bu kurallarda ya da başka bir hamlede anıldığında, onu italik metin olarak görürsün.\n\nÇoğu hamle, üstlendiğin riskli eylemlere dayanır. Kılıcınla saldırıyor, tehlikeli bir tırmanış yapıyor ya da bir müttefikine şifa veriyorsundur. Bu hamleler sonucu belirlemek için zar kullanır. Buna eylem atışı (action roll) denir (sayfa 8).\n\nBazı hamleler, bir yolculuk ya da dövüş gibi uzun süreli bir zorluğa karşı kaydettiğin mesafeyi bir ilerleme izi (sayfa 14) kullanarak ölçer. Zorluğu çözmeye hazır olduğunda bir ilerleme atışı (progress roll) yaparsın (sayfa 18).\n\nDiğer hamleler, kehanet atışı (oracle roll) adı verilen farklı türde bir zar atışı kullanır (sayfa 22). Bu hamleler, karakterinin denetimi dışındaki belirsiz olayların sonucunu belirlemeye yardım eder. Solo ya da ortak oynuyorsan, dünya hakkında soruları yanıtlamak, diğer karakterlerin nasıl tepki verdiğini çözmek ya da sırada ne olacağını belirlemek için *Kehanetin Sesini Dinle* hamlesini (sayfa 107) kullanabilirsin.\n\nBazı hamleler atış gerektirmez. Ayrı bir hamleyi destekleyebilir ya da ona atıfta bulunabilir, veya mekanik ya da anlatısal bir durumu çözmene yardım edebilirler. Bir hamle söylemedikçe zar atma. Hamleler hakkında daha fazlasını öğrenmek için bkz. sayfa 49."
	},
	{
		"page": 7,
		"img": "/basics/p07.webp",
		"title_en": "Anatomy of a Move",
		"title_tr": "Bir Hamlenin Anatomisi",
		"text_en": "Each move has a name and a trigger. When you do this thing, or encounter this situation, make the move.\n\nMoves which require an action roll will tell you which stat to add to your roll, and may give you an option to include other bonuses (called adds). Moves with an action roll include three levels of possible results: a strong hit, a weak hit, and a miss. When a move is referenced within another move, you'll see it as italicized text.\n\n## Gather Information\n\nWhen you search an area, ask questions, conduct an investigation, or follow a track, roll +wits. If you act within a community or ask questions of a person with whom you share a bond, add +1.\n\nOn a __strong hit__, you discover something helpful and specific. The path you must follow or action you must take to make progress is made clear. Envision what you learn (*Ask the Oracle* if unsure), and take +2 momentum.\n\nOn a __weak hit__, the information complicates your quest or introduces a new danger. Envision what you discover (*Ask the Oracle* if unsure), and take +1 momentum.\n\nOn a __miss__, your investigation unearths a dire threat or reveals an unwelcome truth that undermines your quest. *Pay the Price*.",
		"text_tr": "Her hamlenin bir adı ve bir tetikleyicisi vardır. Bu şeyi yaptığında ya da bu durumla karşılaştığında hamleyi yaparsın.\n\nBir eylem atışı gerektiren hamleler, atışına hangi statı ekleyeceğini söyler ve sana başka bonuslar (eklemeler denir) katma seçeneği verebilir. Eylem atışlı hamleler üç olası sonuç düzeyi içerir: Güçlü Başarı, Zayıf Başarı ve Başarısızlık. Bir hamle başka bir hamlede anıldığında, onu italik metin olarak görürsün.\n\n## Bilgi Topla\n\nBir bölgeyi araştırdığında, sorular sorduğunda, bir soruşturma yürüttüğünde ya da bir izi takip ettiğinde, Zar at +Wits. Bir topluluk içinde hareket ediyorsan ya da bağ paylaştığın birine sorular soruyorsan, +1 ekle.\n\n__Güçlü Başarı__'da, yararlı ve belirli bir şey keşfedersin. İlerlemek için izlemen gereken yol ya da yapman gereken eylem açıklığa kavuşur. Ne öğrendiğini hayal et (emin değilsen *Kehanetin Sesini Dinle*) ve +2 Momentum al.\n\n__Zayıf Başarı__'da, bilgi görevini karmaşıklaştırır ya da yeni bir tehlike getirir. Ne keşfettiğini hayal et (emin değilsen *Kehanetin Sesini Dinle*) ve +1 Momentum al.\n\n__Başarısızlık__'ta, soruşturman korkunç bir tehdidi ortaya çıkarır ya da görevini baltalayan istenmeyen bir gerçeği açığa vurur. *Bedelini Öde*.",
		"diagram": "move"
	},
	{
		"page": 8,
		"img": "/basics/p08.webp",
		"title_en": "The Action Roll",
		"title_tr": "Eylem Atışı",
		"text_en": "## The Action Roll\n\nWhen you make a move representing a risky or uncertain action, you roll three dice at once.\n\n- __Challenge dice:__ Two ten-sided dice (d10)\n- __Action die:__ A six-sided die (d6)\n\nAdd your relevant stat to your action die. The move will tell you which stat to add, or may give you a choice. Some moves will tell you to use one of your tracks, such as health or supply, in place of a stat. Based on the move or your character's assets, you may also have an opportunity to apply one or more bonuses called adds.\n\nThe total of your action die, your stat, and any adds is your action score. Your action score is never greater than 10—anything over that is ignored.\n\nTo determine the outcome of your move, compare the action score to each of the challenge dice. You want it to be greater than the individual value of those dice.",
		"text_tr": "## Eylem Atışı\n\nRiskli ya da belirsiz bir eylemi temsil eden bir hamle yaptığında, üç zarı bir kerede atarsın.\n\n- __Zorluk zarları:__ İki on yüzlü zar (d10)\n- __Eylem zarı:__ Bir altı yüzlü zar (d6)\n\nİlgili statını eylem zarına ekle. Hamle hangi statı ekleyeceğini söyler ya da sana bir seçim sunabilir. Bazı hamleler, bir stat yerine can ya da ikmal gibi izlerinden birini kullanmanı söyler. Hamleye ya da karakterinin yetenek kartlarına bağlı olarak, eklemeler denen bir ya da daha fazla bonusu uygulama fırsatın da olabilir.\n\nEylem zarının, statının ve varsa eklemelerin toplamı senin eylem puanındır (action score). Eylem puanın asla 10'dan büyük olamaz—bunun üzerindeki her şey göz ardı edilir.\n\nHamlenin sonucunu belirlemek için eylem puanını zorluk zarlarının her biriyle karşılaştır. Onun, o zarların tek tek değerinden büyük olmasını istersin.",
		"diagram": "action-roll"
	},
	{
		"page": 9,
		"img": "/basics/p09.webp",
		"title_en": "Reading the Result",
		"title_tr": "Sonucu Okumak",
		"text_en": "There are three possible results for a move.\n\n- __Strong Hit:__ Your action score is greater than both the challenge dice. You succeed at what you are trying to do.\n- __Weak Hit:__ Your action score is greater than only one of the challenge dice. You probably succeeded, but with a lesser effect or cost.\n- __Miss:__ Your action score isn't greater than either of the challenge dice. You failed, or need to make some serious concessions.\n\nThe move will tell you how to interpret the outcome of your action, or offer a choice. The result may include mechanical changes to your character's status and narrative changes to the current situation.\n\nWhen you score a miss on a move, you'll usually see a prompt to *Pay the Price*. This is a special move that lets you pick a likely negative outcome or roll to see what happens. If you're playing with a GM, they may consult with this move, or just tell you the price.\n\nThe main thing to remember on a miss: __something always happens.__ The situation gets more complex, dramatic, or dangerous. To learn more about the *Pay the Price* move, see page 105.\n\nTies always go to the challenge dice. Your action score needs to exceed—not equal—the challenge dice to count as a hit.\n\nWhen you roll for a move, you should be on the lookout for a __match__ on the challenge dice. In cooperative and solo play, this is your trigger to add a twist, create a new complication, or otherwise mix things up. Something interesting, unexpected, or unusual happens. If you're unsure, you *Ask the Oracle*, which is a move you use to ask questions or check for inspiration. If you're playing with a GM, a match on the challenge dice can be their prompt to introduce a surprising turn of events.",
		"text_tr": "Bir hamle için üç olası sonuç vardır.\n\n- __Güçlü Başarı:__ Eylem puanın her iki zorluk zarından da büyüktür. Yapmaya çalıştığın şeyde başarılı olursun.\n- __Zayıf Başarı:__ Eylem puanın zorluk zarlarından yalnızca birinden büyüktür. Muhtemelen başardın ama daha düşük bir etkiyle ya da bir bedelle.\n- __Başarısızlık:__ Eylem puanın zorluk zarlarının hiçbirinden büyük değildir. Başarısız oldun ya da ciddi ödünler vermen gerekiyor.\n\nHamle, eyleminin sonucunu nasıl yorumlayacağını söyler ya da bir seçim sunar. Sonuç, karakterinin durumunda mekanik değişiklikler ve mevcut duruma anlatısal değişiklikler içerebilir.\n\nBir hamlede Başarısızlık aldığında, genellikle *Bedelini Öde* yönergesini görürsün. Bu, olası bir olumsuz sonucu seçmene ya da ne olacağını görmek için zar atmana izin veren özel bir hamledir. Bir Oyun Yöneticisi ile oynuyorsan, o bu hamleye başvurabilir ya da bedeli sana doğrudan söyleyebilir.\n\nBaşarısızlıkta hatırlanması gereken asıl şey: __her zaman bir şey olur.__ Durum daha karmaşık, daha çarpıcı ya da daha tehlikeli hâle gelir. *Bedelini Öde* hamlesi hakkında daha fazlasını öğrenmek için bkz. sayfa 105.\n\nBeraberlikler her zaman zorluk zarlarının lehinedir. Bir başarı sayılması için eylem puanının zorluk zarlarını aşması gerekir—eşit olması yetmez.\n\nBir hamle için zar attığında, zorluk zarlarındaki bir eşleşmeyi (match) gözlemen gerekir. Ortak ve solo oyunda bu, bir kıvrım eklemen, yeni bir karmaşa yaratman ya da işleri başka türlü değiştirmen için tetikleyicidir. İlginç, beklenmedik ya da olağandışı bir şey olur. Emin değilsen *Kehanetin Sesini Dinle*; bu, soru sormak ya da ilham aramak için kullandığın bir hamledir. Bir Oyun Yöneticisi ile oynuyorsan, zorluk zarlarındaki bir eşleşme, onun şaşırtıcı bir gelişme sunması için bir işaret olabilir."
	},
	{
		"page": 10,
		"img": "/basics/p10.webp",
		"title_en": "Interpreting a Match",
		"title_tr": "Bir Eşleşmeyi Yorumlamak",
		"text_en": "The outcome of a match should be evaluated based on the result of your move.\n\n- __Strong hit:__ The match should represent a twist in the narrative, something interesting, or a new opportunity.\n- __Miss:__ The match should represent a heightened negative outcome, a complication, or new danger. Things get worse for you in an unexpected way.\n\nYou can also let the intensity of your success or failure frame how you interpret a match. Rolling matched 10's on your challenge dice should prompt you to introduce a harrowing turn of events or a dire failure. It's as bad as things get.\n\n## GMs and the Dice\n\nIf you are playing as a GM, you can focus on guiding the game and responding to your player's questions and actions. Since NPCs don't make moves, you won't need to make action rolls. However, you might want to have a pair of d10's available for oracle rolls (page 22).",
		"text_tr": "Bir eşleşmenin sonucu, hamlenin sonucuna göre değerlendirilmelidir.\n\n- __Güçlü Başarı:__ Eşleşme, anlatıda bir kıvrımı, ilginç bir şeyi ya da yeni bir fırsatı temsil etmelidir.\n- __Başarısızlık:__ Eşleşme, şiddetlenen bir olumsuz sonucu, bir karmaşayı ya da yeni bir tehlikeyi temsil etmelidir. İşler senin için beklenmedik bir biçimde kötüleşir.\n\nBir eşleşmeyi nasıl yorumlayacağını, başarının ya da başarısızlığının şiddetinin çerçevelemesine de izin verebilirsin. Zorluk zarlarında eşleşen 10'lar atmak, seni sarsıcı bir gelişme ya da korkunç bir başarısızlık sunmaya itmelidir. İşlerin gidebileceği en kötü hâl budur.\n\n## Oyun Yöneticileri ve Zarlar\n\nOyun Yöneticisi olarak oynuyorsan, oyunu yönlendirmeye ve oyuncunun sorularına ve eylemlerine karşılık vermeye odaklanabilirsin. OYK'lar hamle yapmadığından, eylem atışları yapmana gerek olmaz. Ne var ki kehanet atışları (sayfa 22) için bir çift d10 bulundurmak isteyebilirsin."
	},
	{
		"page": 11,
		"img": "/basics/p11.webp",
		"title_en": "Momentum",
		"title_tr": "Momentum",
		"text_en": "## Momentum\n\nMomentum is a special mechanic which is central to playing *Ironsworn*. Your momentum value ranges from -6 to +10 and represents how you are faring in your quests. Move results may tell you to increase or decrease momentum. The momentum track is on the left side of your character sheet. You can use a paper clip or token to mark the current value.\n\nWhen you have positive momentum, things are going your way. You have the advantage. You are in control. Your path is clear. You are properly positioned for success.\n\nWhen you have negative momentum, the tide has turned against you. You face tough odds. You are outmatched. Your next steps are uncertain.\n\nMomentum persists through scenes and between gaming sessions. When you finish a session, write down your current momentum value. Then, pick up where you left off when you return to the game.\n\n## Gaining Momentum\n\nYou gain momentum as an outcome or option when making moves. This represents securing advantages, acquiring new insight, and making progress in your quests. If a move tells you to add momentum (phrased as \"take +X momentum\"), increase your momentum track by the value indicated. The choices you make in a move, or the assets you use to support the move, may modify the amount rewarded.\n\nIn general, taking +1 momentum represents a minor advantage. Taking +2 momentum (or more) represents a major advantage.\n\n## Losing Momentum\n\nYou can lose momentum as a choice when making moves, or as an outcome of a move—particularly on a weak hit or miss. If a move tells you to suffer a specific loss of momentum (phrased as \"suffer -X momentum\"), you reduce your momentum track by the value indicated. The options you choose in a move, or the assets you leverage, may alter this penalty.",
		"text_tr": "## Momentum\n\nMomentum, *Ironsworn* oynamanın merkezinde yer alan özel bir mekaniktir. Momentum değerin -6 ile +10 arasında değişir ve görevlerinde nasıl gittiğini temsil eder. Hamle sonuçları sana Momentum'u artırmanı ya da azaltmanı söyleyebilir. Momentum izi, karakter sayfanın sol tarafındadır. Şu anki değeri işaretlemek için bir ataç ya da jeton kullanabilirsin.\n\nPozitif Momentum'a sahip olduğunda işler senin lehine gidiyordur. Üstünlük sendedir. Denetim sende. Yolun açıktır. Başarı için doğru konumdasındır.\n\nNegatif Momentum'a sahip olduğunda, gidişat aleyhine dönmüştür. Zorlu ihtimallerle karşı karşıyasındır. Sana karşı baskınlardır. Bir sonraki adımların belirsizdir.\n\nMomentum sahneler boyunca ve oyun oturumları arasında kalıcıdır. Bir oturumu bitirdiğinde, şu anki Momentum değerini yaz. Sonra oyuna döndüğünde kaldığın yerden devam et.\n\n## Momentum Kazanmak\n\nHamle yaparken bir sonuç ya da seçenek olarak Momentum kazanırsın. Bu, avantajlar elde etmeyi, yeni sezgi edinmeyi ve görevlerinde ilerleme kaydetmeyi temsil eder. Bir hamle sana Momentum eklemeni söylüyorsa (\"+X Momentum al\" biçiminde ifade edilir), Momentum izini belirtilen değer kadar artır. Bir hamlede verdiğin seçimler ya da hamleyi desteklemek için kullandığın yetenek kartları, ödüllendirilen miktarı değiştirebilir.\n\nGenel olarak +1 Momentum almak küçük bir avantajı temsil eder. +2 Momentum (ya da daha fazla) almak büyük bir avantajı temsil eder.\n\n## Momentum Kaybetmek\n\nHamle yaparken bir seçim olarak ya da bir hamlenin sonucu olarak—özellikle Zayıf Başarı ya da Başarısızlık'ta—Momentum kaybedebilirsin. Bir hamle sana belirli bir Momentum kaybına uğramanı söylüyorsa (\"-X Momentum'a uğra\" biçiminde ifade edilir), Momentum izini belirtilen değer kadar azaltırsın. Bir hamlede seçtiğin seçenekler ya da yararlandığın yetenek kartları bu cezayı değiştirebilir."
	},
	{
		"page": 12,
		"img": "/basics/p12.webp",
		"title_en": "Burning Momentum",
		"title_tr": "Momentum Yakmak",
		"text_en": "If you lose momentum as a result of a narrative outcome without a defined value, such as when you make the *Pay the Price* move (page 105), you should suffer a reduction appropriate to the narrative circumstances.\n\n- For a minor disadvantage or complication, suffer -1 momentum.\n- For a major disadvantage or complication, suffer -2 momentum.\n\nSome moves and assets give you the option to suffer a loss of momentum in exchange for temporary advantages. If you take this option, adjust your momentum track by the amount indicated.\n\n## Burning Momentum\n\nBurning momentum is a powerful option to build on your success and deliver a decisive result or avoid dire failure. When you have positive momentum, after you roll your move, you may cancel any challenge dice that are less than your current momentum value. This gives you an automatic hit.\n\nIf both challenge dice are less than your momentum value, you may cancel them both for a strong hit. If you burn momentum when only one of the challenge dice is less than your momentum value, the result of the other die stands—giving you a weak hit.\n\nFor example, your momentum track is at +6 and your action score is 4. You roll a 5 and an 8 on your challenge dice. You may burn momentum to cancel the 5, but not the 8. This shifts your result from a miss to a weak hit.\n\nBurning momentum is never required. Even if you score a miss on a move and have enough momentum to cancel the challenge dice, you can choose to suffer the failure and save your momentum for a more crucial moment.\n\nAfter you burn momentum, you must reset your momentum. See the next page for how that works.",
		"text_tr": "Tanımlı bir değeri olmayan anlatısal bir sonuç yüzünden Momentum kaybediyorsan—örneğin *Bedelini Öde* hamlesini (sayfa 105) yaptığında—anlatısal koşullara uygun bir azalmaya uğramalısın.\n\n- Küçük bir dezavantaj ya da karmaşa için -1 Momentum'a uğra.\n- Büyük bir dezavantaj ya da karmaşa için -2 Momentum'a uğra.\n\nBazı hamleler ve yetenek kartları, geçici avantajlar karşılığında Momentum kaybına uğrama seçeneği verir. Bu seçeneği alırsan, Momentum izini belirtilen miktar kadar ayarla.\n\n## Momentum Yakmak\n\nMomentum yakmak, başarının üstüne koymak ve kesin bir sonuç vermek ya da korkunç bir başarısızlıktan kaçınmak için güçlü bir seçenektir. Pozitif Momentum'a sahip olduğunda, hamleni attıktan sonra, şu anki Momentum değerinden küçük olan zorluk zarlarını iptal edebilirsin. Bu sana otomatik bir başarı kazandırır.\n\nHer iki zorluk zarı da Momentum değerinden küçükse, Güçlü Başarı için ikisini birden iptal edebilirsin. Yalnızca zorluk zarlarından biri Momentum değerinden küçükken Momentum yakarsan, diğer zarın sonucu geçerli kalır—bu sana Zayıf Başarı verir.\n\nÖrneğin, Momentum izin +6'da ve eylem puanın 4. Zorluk zarlarında bir 5 ve bir 8 atıyorsun. 5'i iptal etmek için Momentum yakabilirsin ama 8'i iptal edemezsin. Bu, sonucunu bir Başarısızlık'tan bir Zayıf Başarı'ya kaydırır.\n\nMomentum yakmak asla zorunlu değildir. Bir hamlede Başarısızlık alsan ve zorluk zarlarını iptal etmeye yetecek Momentum'un olsa bile, başarısızlığa katlanmayı ve Momentum'unu daha can alıcı bir an için saklamayı seçebilirsin.\n\nMomentum yaktıktan sonra Momentum'unu sıfırlaman gerekir. Bunun nasıl işlediği için bir sonraki sayfaya bak."
	},
	{
		"page": 13,
		"img": "/basics/p13.webp",
		"title_en": "Resetting Momentum",
		"title_tr": "Momentum'u Sıfırlamak",
		"text_en": "## Resetting Momentum\n\nAfter you burn momentum, you must adjust your momentum track to your momentum reset value. The default reset is +2. This value may be lowered when your character suffers from a debility (page 36). Debilities are conditions such as wounded, shaken, or unprepared. They are marked on your character sheet as a result of a move or a narrative event.\n\n- If you have one debility marked, your momentum reset is +1.\n- If you have more than one debility marked, your momentum reset is 0.\n\nThere is a box below the momentum track where you can record your current momentum reset.\n\n## Suffering Negative Momentum\n\nWhen your momentum is less than 0, and it matches the value of your action die, you must cancel your action die. You still check the success of your move by comparing your stat plus your adds to the challenge dice, but you won't have your action die to help you.\n\n## Minimum Momentum\n\nYour momentum cannot drop lower than -6. This is your minimum momentum. If a move tells you to lower your momentum, and your momentum is already at its minimum, you will instead make the *Face a Setback* move (page 97). As a result of this move, you reduce your health, spirit, or supply (or some combination thereof) by that amount, or undermine your progress in a current quest, journey, or fight.\n\nMake moves such as *Secure an Advantage* (page 61) to increase your momentum.",
		"text_tr": "## Momentum'u Sıfırlamak\n\nMomentum yaktıktan sonra, Momentum izini Momentum sıfırlama değerine ayarlaman gerekir. Varsayılan sıfırlama +2'dir. Bu değer, karakterin bir olumsuz etkiye (sayfa 36) maruz kaldığında düşürülebilir. Olumsuz etkiler, Yaralı, Yıkılmış ya da Hazırlıksız gibi durumlardır. Bir hamlenin ya da anlatısal bir olayın sonucu olarak karakter sayfanda işaretlenir.\n\n- İşaretli bir olumsuz etkin varsa, Momentum sıfırlaman +1'dir.\n- İşaretli birden fazla olumsuz etkin varsa, Momentum sıfırlaman 0'dır.\n\nMomentum izinin altında, şu anki Momentum sıfırlamanı kaydedebileceğin bir kutu vardır.\n\n## Negatif Momentum'a Uğramak\n\nMomentum'un 0'dan küçük olduğunda ve eylem zarının değeriyle eşleştiğinde, eylem zarını iptal etmen gerekir. Hamlenin başarısını yine de statını artı eklemelerini zorluk zarlarıyla karşılaştırarak denetlersin ama sana yardım edecek eylem zarın olmaz.\n\n## Asgari Momentum\n\nMomentum'un -6'dan daha aşağı düşemez. Bu senin asgari Momentum'undur. Bir hamle sana Momentum'unu düşürmeni söylüyorsa ve Momentum'un zaten asgari düzeydeyse, bunun yerine *Aksilikle Yüzleş* hamlesini (sayfa 97) yaparsın. Bu hamlenin sonucu olarak canını, ruhunu ya da ikmalini (veya bunların bir bileşimini) o miktar kadar azaltır, ya da mevcut bir görevdeki, yolculuktaki veya dövüşteki ilerlemeni baltalarsın.\n\nMomentum'unu artırmak için *Avantaj Sağla* (sayfa 61) gibi hamleler yap."
	},
	{
		"page": 14,
		"img": "/basics/p14.webp",
		"title_en": "Progress Tracks",
		"title_tr": "İlerleme İzleri",
		"text_en": "## Max Momentum\n\nYour max momentum starts at +10, and is reduced by 1 for every marked debility. There's a spot on your character sheet to record this value. You can't increase momentum over your max. If you are at your max and a move gives you an option to increase your momentum, you can't take that benefit.\n\n## Progress Tracks\n\nA progress track is used to measure your pace and determine the outcome of a goal or challenge in specific situations.\n\n- When you *Swear an Iron Vow* (page 98), a progress track represents the challenges you overcome on your way to achieving your ultimate goal.\n- When you *Undertake a Journey* (page 65), a progress track represents how far you've gone and how favorable the travel has been.\n- When you *Enter the Fray* (page 78), a progress track represents your advantage as you weaken or wound your foes in combat.\n- When you establish a new relationship with a character in your world and *Forge a Bond* (page 74), you mark your bond on a progress track.\n\nProgress tracks are drawn as a row of ten boxes which you fill in—or mark—as you make headway toward a goal. When you initiate a challenge, these boxes are empty.\n\nSince making progress on your quests may stretch over many sessions, your character sheet includes progress tracks for vows. Your character sheet also includes a progress track for your bonds. For journeys and fights, you can sketch out your progress tracks on whatever is convenient, or use the challenge worksheets provided at ironswornrpg.com.\n\n## Challenge Ranks\n\nWhen you engage in a fight, initiate a journey, or swear a vow, you give your challenge a rank. In increasing order of difficulty, the ranks are troublesome, dangerous, formidable, extreme, and epic. You (or the GM) will choose a rank appropriate to the situation and how quickly or easily it should be resolved. Troublesome is used for simple challenges. A typical challenge is dangerous or formidable. Epic and extreme challenges require great effort and luck to overcome. Guidelines for foes are on page 134, and for journeys on page 111.",
		"text_tr": "## Azami Momentum\n\nAzami Momentum'un +10'da başlar ve her işaretli olumsuz etki için 1 azalır. Karakter sayfanda bu değeri kaydedeceğin bir yer vardır. Momentum'unu azaminin üzerine çıkaramazsın. Azamindeysen ve bir hamle sana Momentum'unu artırma seçeneği verirse, o faydayı alamazsın.\n\n## İlerleme İzleri\n\nBir ilerleme izi (progress track), temponu ölçmek ve belirli durumlarda bir amacın ya da zorluğun sonucunu belirlemek için kullanılır.\n\n- *Demir Ant İç*tiğinde (sayfa 98), bir ilerleme izi, nihai amacına ulaşma yolunda aştığın zorlukları temsil eder.\n- *Yolculuğa Çık*tığında (sayfa 65), bir ilerleme izi, ne kadar yol aldığını ve seyahatin ne kadar elverişli geçtiğini temsil eder.\n- *Savaşa Gir*diğinde (sayfa 78), bir ilerleme izi, dövüşte düşmanlarını zayıflattıkça ya da yaraladıkça elde ettiğin avantajı temsil eder.\n- Dünyandaki bir karakterle yeni bir ilişki kurup *Bağ Kur*duğunda (sayfa 74), bağını bir ilerleme izi üzerinde işaretlersin.\n\nİlerleme izleri, bir amaca doğru mesafe katettikçe doldurduğun—ya da işaretlediğin—on kutuluk bir sıra olarak çizilir. Bir zorluğu başlattığında bu kutular boştur.\n\nGörevlerinde ilerleme kaydetmek birçok oturuma yayılabileceğinden, karakter sayfan antlar için ilerleme izleri içerir. Karakter sayfan ayrıca bağların için bir ilerleme izi de içerir. Yolculuklar ve dövüşler için ilerleme izlerini elinde ne uygunsa ona çizebilir ya da ironswornrpg.com'da sunulan zorluk çalışma kâğıtlarını kullanabilirsin.\n\n## Zorluk Dereceleri\n\nBir dövüşe giriştiğinde, bir yolculuk başlattığında ya da bir ant içtiğinde, zorluğuna bir derece verirsin. Artan güçlük sırasıyla dereceler Sıradan, Tehlikeli, Zorlu, Aşırı ve Destansı'dır. Sen (ya da Oyun Yöneticisi) duruma ve zorluğun ne kadar hızlı ya da kolay çözülmesi gerektiğine uygun bir derece seçersin. Sıradan, basit zorluklar için kullanılır. Tipik bir zorluk Tehlikeli ya da Zorlu'dur. Destansı ve Aşırı zorlukların üstesinden gelmek büyük çaba ve şans gerektirir. Düşmanlar için yönergeler sayfa 134'te, yolculuklar için ise sayfa 111'dedir."
	},
	{
		"page": 15,
		"img": "/basics/p15.webp",
		"title_en": "Marking Progress",
		"title_tr": "İlerleme İşaretlemek",
		"text_en": "Give your vows a rank appropriate to the complexity of your quest and the amount of emphasis you want to give the vow in your story.\n\n## Marking Progress\n\nYou will perform specific moves to advance toward your goal. For example, as you travel across perilous lands, you *Undertake a Journey* and mark progress when you successfully reach waypoints in your travel.\n\n## Undertake a Journey\n\nWhen you travel across hazardous or unfamiliar lands, first determine the rank of your journey (*Ask the Oracle* if unsure).\n\n- Troublesome journey: 3 progress per waypoint.\n- Dangerous journey: 2 progress per waypoint.\n- Formidable journey: 1 progress per waypoint.\n- Extreme journey: 2 ticks per waypoint.\n- Epic journey: 1 tick per waypoint.\n\nThen, for each segment of your journey, roll +wits. If you are setting off from a community with which you share a bond, add +1 to your initial roll.\n\nOn a __strong hit__, you reach a waypoint. If the waypoint is unknown to you, envision it (*Ask the Oracle* if unsure). Then, choose one.\n\n- You make good use of your resources: Mark progress.\n- You move at speed: Mark progress and take +1 momentum, but suffer -1 supply.\n\nOn a __weak hit__, you reach a waypoint and mark progress, but suffer -1 supply.\n\nOn a __miss__, you are waylaid by a perilous event. *Pay the Price*.\n\nSimilarly, when you fight, you *Strike* (page 79) or *Clash* (page 80) to inflict harm on your foe. To move forward in your quest, you use the *Reach a Milestone* move (page 100). These incremental moves let you amass advantages to have the best chance of success when you are ready to resolve your challenge.",
		"text_tr": "Antlarına, görevinin karmaşıklığına ve hikâyende anda vermek istediğin ağırlığa uygun bir derece ver.\n\n## İlerleme İşaretlemek\n\nAmacına doğru ilerlemek için belirli hamleler yaparsın. Örneğin, tehlikeli diyarları aşarken *Yolculuğa Çık*ar ve seyahatinde yol noktalarına başarıyla ulaştığında ilerleme işaretlersin.\n\n## Yolculuğa Çık\n\nTehlikeli ya da tanımadığın diyarları aşarak seyahat ettiğinde, önce yolculuğunun derecesini belirle (emin değilsen *Kehanetin Sesini Dinle*).\n\n- Sıradan yolculuk: yol noktası başına 3 ilerleme.\n- Tehlikeli yolculuk: yol noktası başına 2 ilerleme.\n- Zorlu yolculuk: yol noktası başına 1 ilerleme.\n- Aşırı yolculuk: yol noktası başına 2 çentik.\n- Destansı yolculuk: yol noktası başına 1 çentik.\n\nSonra, yolculuğunun her bölümü için Zar at +Wits. Bağ paylaştığın bir topluluktan yola çıkıyorsan, ilk atışına +1 ekle.\n\n__Güçlü Başarı__'da, bir yol noktasına ulaşırsın. Yol noktası sana bilinmiyorsa, onu hayal et (emin değilsen *Kehanetin Sesini Dinle*). Sonra birini seç.\n\n- Kaynaklarını iyi kullanırsın: İlerleme işaretle.\n- Hızlı hareket edersin: İlerleme işaretle ve +1 Momentum al ama -1 ikmale uğra.\n\n__Zayıf Başarı__'da, bir yol noktasına ulaşır ve ilerleme işaretlersin ama -1 ikmale uğrarsın.\n\n__Başarısızlık__'ta, tehlikeli bir olay yolunu keser. *Bedelini Öde*.\n\nBenzer şekilde, dövüştüğünde, düşmanına hasar vermek için *Saldır*ır (sayfa 79) ya da *Çatış*ırsın (sayfa 80). Görevinde ileri gitmek için *Bir Dönüm Noktasına Ulaş* hamlesini (sayfa 100) kullanırsın. Bu kademeli hamleler, zorluğunu çözmeye hazır olduğunda en iyi başarı şansına sahip olmak için avantajlar biriktirmeni sağlar."
	},
	{
		"page": 16,
		"img": "/basics/p16.webp",
		"title_en": "Marking Progress on the Track",
		"title_tr": "İz Üzerinde İlerleme İşaretlemek",
		"text_en": "Whenever you successfully move toward your goal, you partially or fully fill in a box on your progress track. You fill progress boxes with lines—called ticks. A full progress box consists of four ticks in a star-shaped pattern. When a move tells you to mark progress, fill in the appropriate number of ticks or progress boxes based on the rank of your challenge.\n\n- __Troublesome:__ mark 3 progress\n- __Dangerous:__ mark 2 progress\n- __Formidable:__ mark 1 progress\n- __Extreme:__ mark 2 ticks\n- __Epic:__ mark 1 tick\n\n## Marking Progress for Bonds\n\nIf you are marking progress on your bonds progress track, you always mark 1 tick unless a move tells you otherwise. Bonds are not given a challenge rank. To learn more about bonds, see page 24.",
		"text_tr": "Amacına doğru başarıyla her ilerlediğinde, ilerleme izindeki bir kutuyu kısmen ya da tamamen doldurursun. İlerleme kutularını çentik denen çizgilerle doldurursun. Dolu bir ilerleme kutusu, yıldız biçiminde dizili dört çentikten oluşur. Bir hamle sana ilerleme işaretlemeni söylediğinde, zorluğunun derecesine göre uygun sayıda çentik ya da ilerleme kutusu doldur.\n\n- __Sıradan:__ 3 ilerleme işaretle\n- __Tehlikeli:__ 2 ilerleme işaretle\n- __Zorlu:__ 1 ilerleme işaretle\n- __Aşırı:__ 2 çentik işaretle\n- __Destansı:__ 1 çentik işaretle\n\n## Bağlar İçin İlerleme İşaretlemek\n\nBağlar ilerleme izinde ilerleme işaretliyorsan, bir hamle aksini söylemedikçe her zaman 1 çentik işaretlersin. Bağlara zorluk derecesi verilmez. Bağlar hakkında daha fazlasını öğrenmek için bkz. sayfa 24."
	},
	{
		"page": 17,
		"img": "/basics/p17.webp",
		"title_en": "Progress Moves",
		"title_tr": "İlerleme Hamleleri",
		"text_en": "## Progress Moves\n\nThere are four moves, called progress moves, which utilize progress tracks to resolve the outcome of a goal or challenge.\n\n- To resolve a quest, *Fulfill Your Vow* (page 101).\n- To end your journey, *Reach Your Destination* (page 68).\n- To decide the outcome of combat, *End the Fight* (page 82).\n- When you retire from your life as Ironsworn, *Write Your Epilogue* (page 77).\n\nA progress move uses a progress roll instead of an action roll (see the next page for how it works).\n\n## Reach Your Destination\n\n*Progress Move*\n\nWhen your journey comes to an end, roll the challenge dice and compare to your progress. Momentum is ignored on this roll.\n\nOn a __strong hit__, the situation at your destination favors you. Choose one.\n\n- Make another move now and add +1.\n- Take +1 momentum.\n\nOn a __weak hit__, you arrive but face an unforeseen hazard or complication. Envision what you find (*Ask the Oracle* if unsure).\n\nOn a __miss__, you have gone hopelessly astray, your objective is lost to you, or you were misled about your destination. If your journey continues, clear all but one filled progress, and raise the journey's rank by one (if not already epic).",
		"text_tr": "## İlerleme Hamleleri\n\nBir amacın ya da zorluğun sonucunu çözmek için ilerleme izlerini kullanan, ilerleme hamleleri (progress moves) denen dört hamle vardır.\n\n- Bir görevi çözmek için *Antını Tamamla* (sayfa 101).\n- Yolculuğunu bitirmek için *Hedefe Ulaş* (sayfa 68).\n- Savaşın sonucuna karar vermek için *Savaşı Bitir* (sayfa 82).\n- Demir-Andlı olarak hayatından çekildiğinde *Sonsözünü Yaz* (sayfa 77).\n\nBir ilerleme hamlesi, eylem atışı yerine bir ilerleme atışı kullanır (nasıl işlediği için bir sonraki sayfaya bak).\n\n## Hedefe Ulaş\n\n*İlerleme Hamlesi*\n\nYolculuğun sona erdiğinde, zorluk zarlarını at ve ilerlemenle karşılaştır. Bu atışta Momentum göz ardı edilir.\n\n__Güçlü Başarı__'da, hedefindeki durum senin lehinedir. Birini seç.\n\n- Şimdi başka bir hamle yap ve +1 ekle.\n- +1 Momentum al.\n\n__Zayıf Başarı__'da, varırsın ama öngörülmemiş bir tehlike ya da karmaşayla yüzleşirsin. Ne bulduğunu hayal et (emin değilsen *Kehanetin Sesini Dinle*).\n\n__Başarısızlık__'ta, umutsuzca yoldan sapmışsındır, hedefin senden kopmuştur ya da varış noktan hakkında yanıltılmışsındır. Yolculuğun sürerse, bir tane dışında tüm dolu ilerlemeyi temizle ve yolculuğun derecesini bir artır (zaten Destansı değilse)."
	},
	{
		"page": 18,
		"img": "/basics/p18.webp",
		"title_en": "Progress Rolls",
		"title_tr": "İlerleme Atışları",
		"text_en": "## Progress Rolls\n\nYou don't make an action roll when you make a progress move. Instead, you tally the number of fully filled progress boxes (those with four ticks). This is your progress score. Then, roll your challenge dice and compare your progress score to the value of the dice.\n\nAs with an action roll, if your progress score is greater than both challenge dice, it's a strong hit. If you beat one of the challenge dice, it's a weak hit. If you fail to beat either die, it's a miss. The progress move will tell you how to resolve the challenge based on the outcome of your roll. Also, keep an eye out for a match, which represents a surprising twist or unusual complication.\n\nIn the example below, you would compare your +6 progress score to your challenge dice when making your progress move. The seventh progress box is only partially filled in, and won't count toward the progress score.\n\nWhen deciding whether to make your progress move, you need to weigh your chance of success against the risk of continuing to make preparatory moves. One thing to remember: it's not necessary to fill your progress track before making your progress move. In fact, a weak hit or miss on a progress roll can lead to exciting new story possibilities.\n\n## Momentum and Progress Rolls\n\nMomentum is ignored when you make a progress move. You cannot burn momentum on a progress roll, and you do not suffer from negative momentum.\n\n## Sharing Progress Tracks with Allies\n\nWhen you and your allies are working together to resolve a challenge—a quest, a journey, or a fight—you share a progress track and mark progress together. When you make a progress move, only one of you rolls the dice. The result will stand for the group.",
		"text_tr": "## İlerleme Atışları\n\nBir ilerleme hamlesi yaptığında eylem atışı yapmazsın. Bunun yerine tamamen dolu ilerleme kutularının (dört çentikli olanların) sayısını toplarsın. Bu senin ilerleme puanındır (progress score). Sonra zorluk zarlarını at ve ilerleme puanını zarların değeriyle karşılaştır.\n\nEylem atışında olduğu gibi, ilerleme puanın her iki zorluk zarından da büyükse, bu bir Güçlü Başarı'dır. Zorluk zarlarından birini geçersen, bu bir Zayıf Başarı'dır. İki zarı da geçemezsen, bu bir Başarısızlık'tır. İlerleme hamlesi, atışının sonucuna göre zorluğu nasıl çözeceğini söyler. Ayrıca, şaşırtıcı bir kıvrımı ya da olağandışı bir karmaşayı temsil eden bir eşleşmeye dikkat et.\n\nAşağıdaki örnekte, ilerleme hamleni yaparken +6 ilerleme puanını zorluk zarlarınla karşılaştırırsın. Yedinci ilerleme kutusu yalnızca kısmen dolmuştur ve ilerleme puanına sayılmaz.\n\nİlerleme hamleni yapıp yapmayacağına karar verirken, başarı şansını hazırlık hamleleri yapmayı sürdürmenin riskine karşı tartman gerekir. Hatırlanması gereken bir şey: İlerleme hamleni yapmadan önce ilerleme izini doldurman gerekmez. Aslında, bir ilerleme atışında Zayıf Başarı ya da Başarısızlık, heyecan verici yeni hikâye olasılıklarına yol açabilir.\n\n## Momentum ve İlerleme Atışları\n\nBir ilerleme hamlesi yaptığında Momentum göz ardı edilir. Bir ilerleme atışında Momentum yakamazsın ve negatif Momentum'dan etkilenmezsin.\n\n## İlerleme İzlerini Müttefiklerle Paylaşmak\n\nSen ve müttefiklerin bir zorluğu—bir görevi, bir yolculuğu ya da bir dövüşü—çözmek için birlikte çalışırken, bir ilerleme izini paylaşır ve ilerlemeyi birlikte işaretlersiniz. Bir ilerleme hamlesi yaptığınızda, yalnızca biriniz zar atar. Sonuç grubun tamamı için geçerli olur."
	},
	{
		"page": 19,
		"img": "/basics/p19.webp",
		"title_en": "Harm",
		"title_tr": "Hasar",
		"text_en": "## Harm\n\nHarm represents physical damage and fatigue. You inflict harm on your foes in combat, and you *Endure Harm* when you are attacked or fail to overcome a physical hazard or ordeal.\n\n## Inflicting Harm\n\nWhen you successfully attack a foe using the *Strike* (page 79) or *Clash* (page 80) moves, you inflict harm. If you are armed with a deadly weapon (such as a sword, axe, spear, or bow), you inflict 2 harm. If you are unarmed or using an improvised or simple weapon (such as a shield, stick, club, staff, or rock), you inflict 1 harm. You may have an option to inflict additional harm through the choices you make in a move.\n\nEach point of harm you inflict is marked as progress on your foe's progress track, as appropriate to their rank. For example, each point of harm equals 2 ticks when fighting an extreme enemy, or 2 full progress boxes when fighting a dangerous enemy.\n\n## Enduring Harm\n\nWhen you face physical injury or hardship, make the *Endure Harm* move (page 91). As part of that move, you reduce your health track by the amount of harm suffered. There are five ranks of harm.\n\n- __Troublesome (1 harm):__ An attack by a minor foe, a painful injury, or a tiring effort.\n- __Dangerous (2 harm):__ An attack by a skilled foe or deadly creature, a nasty injury, or a demanding effort.\n- __Formidable (3 harm):__ An attack by an exceptional foe or mighty creature, a serious injury, or an exhausting effort.\n- __Extreme (4 harm):__ An overwhelming attack by a monster or beast, a grievous injury, or a debilitating effort.\n- __Epic (5 harm):__ An attack by a legendary foe of mythic power, a horrific injury, or a consuming effort.\n\nWhen you are fighting a foe, they inflict harm based on their rank. Sample foes are in chapter 5 (page 133).\n\nIf you are at 0 health, a miss on the *Endure Harm* move puts you at risk of suffering a debility or dying. You can recover health through rest and recuperation, using moves such as *Heal* (page 63), *Make Camp* (page 64), and *Sojourn* (page 71).",
		"text_tr": "## Hasar\n\nHasar (Harm), fiziksel zararı ve yorgunluğu temsil eder. Dövüşte düşmanlarına hasar verir ve saldırıya uğradığında ya da fiziksel bir tehlikenin veya çilenin üstesinden gelemediğinde *Hasara Katlan*ırsın.\n\n## Hasar Vermek\n\n*Saldır* (sayfa 79) ya da *Çatış* (sayfa 80) hamlelerini kullanarak bir düşmana başarıyla saldırdığında, hasar verirsin. Ölümcül bir silahla (kılıç, balta, mızrak ya da yay gibi) silahlıysan, 2 hasar verirsin. Silahsızsan ya da derme çatma veya basit bir silah (kalkan, sopa, gürz, asa ya da taş gibi) kullanıyorsan, 1 hasar verirsin. Bir hamlede verdiğin seçimler yoluyla ek hasar verme seçeneğin olabilir.\n\nVerdiğin her hasar puanı, düşmanının derecesine uygun olarak onun ilerleme izinde ilerleme olarak işaretlenir. Örneğin, Aşırı bir düşmanla dövüşürken her hasar puanı 2 çentiğe eşittir; Tehlikeli bir düşmanla dövüşürken ise 2 dolu ilerleme kutusuna.\n\n## Hasara Katlanmak\n\nFiziksel yaralanma ya da zorlukla yüzleştiğinde, *Hasara Katlan* hamlesini (sayfa 91) yap. O hamlenin bir parçası olarak, can izini uğradığın hasar kadar azaltırsın. Beş hasar derecesi vardır.\n\n- __Sıradan (1 hasar):__ Önemsiz bir düşmanın saldırısı, acı veren bir yaralanma ya da yorucu bir çaba.\n- __Tehlikeli (2 hasar):__ Usta bir düşmanın ya da ölümcül bir yaratığın saldırısı, kötü bir yaralanma ya da çetin bir çaba.\n- __Zorlu (3 hasar):__ Olağanüstü bir düşmanın ya da güçlü bir yaratığın saldırısı, ciddi bir yaralanma ya da tüketici bir çaba.\n- __Aşırı (4 hasar):__ Bir canavarın ya da hayvanın ezici saldırısı, ağır bir yaralanma ya da güçten düşürücü bir çaba.\n- __Destansı (5 hasar):__ Efsanevi, mitik güçte bir düşmanın saldırısı, dehşet verici bir yaralanma ya da içini bitiren bir çaba.\n\nBir düşmanla dövüşürken, onlar derecelerine göre hasar verir. Örnek düşmanlar Bölüm 5'tedir (sayfa 133).\n\n0 candaysan, *Hasara Katlan* hamlesinde bir Başarısızlık seni bir olumsuz etkiye uğrama ya da ölme riskine sokar. *Şifa Bul* (sayfa 63), *Kamp Kur* (sayfa 64) ve *Konaklama* (sayfa 71) gibi hamleleri kullanarak dinlenme ve toparlanma yoluyla can geri kazanabilirsin."
	},
	{
		"page": 20,
		"img": "/basics/p20.webp",
		"title_en": "Stress",
		"title_tr": "Stres",
		"text_en": "## Stress\n\nStress represents mental burdens and trauma. When you face mental shock or despair, make the *Endure Stress* move (page 95). As part of that move, you reduce your spirit track by the amount of stress suffered. There are five ranks of stress.\n\n- __Troublesome (1 stress):__ An unsettling incident or frustrating failure.\n- __Dangerous (2 stress):__ A distressing incident or upsetting failure.\n- __Formidable (3 stress):__ A horrifying incident or demoralizing failure.\n- __Extreme (4 stress):__ A heart-rending incident or traumatic failure.\n- __Epic (5 stress):__ A soul-shattering incident or the loss of all hope.\n\nWhen you are opposing a foe, they can inflict stress (such as a terrifying visage or demoralizing taunt) based on their rank. Sample foes are in chapter 5 (page 133).\n\nWhen you *Endure Stress*, you reduce your spirit track by the amount of stress suffered. If you are at 0 spirit, you are in danger of suffering a debility or falling into desolation.\n\nYou can recover spirit by relaxing when you *Make Camp* (page 64), finding fellowship when you *Sojourn* (page 71), or when you *Forge a Bond* (page 74).\n\nUnlike harm, you do not inflict stress on others—at least not mechanically. If you attempt to frighten or demoralize another character, make an appropriate move to see what happens.",
		"text_tr": "## Stres\n\nStres, zihinsel yükleri ve travmayı temsil eder. Zihinsel bir sarsıntıyla ya da umutsuzlukla yüzleştiğinde, *Strese Katlan* hamlesini (sayfa 95) yap. O hamlenin bir parçası olarak, ruh izini uğradığın stres kadar azaltırsın. Beş stres derecesi vardır.\n\n- __Sıradan (1 stres):__ Rahatsız edici bir olay ya da sinir bozucu bir başarısızlık.\n- __Tehlikeli (2 stres):__ Üzücü bir olay ya da kederlendiren bir başarısızlık.\n- __Zorlu (3 stres):__ Dehşet verici bir olay ya da moral bozucu bir başarısızlık.\n- __Aşırı (4 stres):__ Yürek parçalayıcı bir olay ya da travmatik bir başarısızlık.\n- __Destansı (5 stres):__ Ruhu paramparça eden bir olay ya da tüm umudun yitirilmesi.\n\nBir düşmana karşı durduğunda, onlar derecelerine göre stres verebilir (ürkütücü bir görünüm ya da moral bozucu bir alay gibi). Örnek düşmanlar Bölüm 5'tedir (sayfa 133).\n\n*Strese Katlan*dığında, ruh izini uğradığın stres kadar azaltırsın. 0 ruhtaysan, bir olumsuz etkiye uğrama ya da yıkıma düşme tehlikesindesin.\n\nRuhunu, *Kamp Kur*duğunda dinlenerek (sayfa 64), *Konaklama* yaptığında dostluk bularak (sayfa 71) ya da *Bağ Kur*duğunda (sayfa 74) geri kazanabilirsin.\n\nHasardan farklı olarak, başkalarına stres vermezsin—en azından mekanik olarak. Başka bir karakteri korkutmaya ya da moralini bozmaya çalışırsan, ne olacağını görmek için uygun bir hamle yap."
	},
	{
		"page": 21,
		"img": "/basics/p21.webp",
		"title_en": "Assets",
		"title_tr": "Yetenek Kartları",
		"text_en": "## Assets\n\nAssets are a key component of your character. They give you additional options and bonuses when making a move, and may include their own special moves. When you create your character (page 31), you select your starting assets. When you *Fulfill Your Vow* and gain experience (page 44), you can *Advance* to spend your experience on new assets or upgrade current assets. To learn more about assets, see page 39.\n\nYou can mix-and-match assets however you like. There are no designated assets based on character classes or roles. However, you should avoid picking the same asset as another player.\n\nEach asset has a type. When you pick an asset, you choose from companions, paths, combat talents, and rituals. Most assets include a default ability, represented by a filled-in circle. If it doesn't have a starting ability, you get to pick one.\n\nAssets usually modify moves by giving you a bonus or allow you to use the move in a different way. Some assets include their own unique moves. As you gain experience, you can purchase upgrades for your assets. When you purchase an upgrade, you fill in the circle to show that you now have that ability.\n\n## Slayer\n\n*Path*\n\n- When you *Gather Information* by tracking a beast or horror, or when you *Secure an Advantage* by readying yourself for a fight against them, add +1 and take +1 momentum on a hit.\n- When you *Swear an Iron Vow* to slay a beast or horror, you may reroll any dice. When you *Fulfill Your Vow* and mark experience, take +1 experience.\n- When you slay a beast or horror (at least formidable), you may take a trophy and choose one.\n  - __Power a ritual:__ When you or an ally make a ritual move, reroll any dice (one time only).\n  - __Prove your worth:__ When you *Sojourn*, reroll any dice (one time only).",
		"text_tr": "## Yetenek Kartları\n\nYetenek kartları (Assets), karakterinin kilit bir bileşenidir. Bir hamle yaparken sana ek seçenekler ve bonuslar verir ve kendi özel hamlelerini içerebilir. Karakterini yarattığında (sayfa 31), başlangıç yetenek kartlarını seçersin. *Antını Tamamla*yıp deneyim kazandığında (sayfa 44), deneyimini yeni yetenek kartlarına harcamak ya da mevcut yetenek kartlarını yükseltmek için *İlerle*yebilirsin. Yetenek kartları hakkında daha fazlasını öğrenmek için bkz. sayfa 39.\n\nYetenek kartlarını istediğin gibi karıştırıp eşleştirebilirsin. Karakter sınıflarına ya da rollere dayalı belirlenmiş yetenek kartları yoktur. Ne var ki başka bir oyuncuyla aynı yetenek kartını seçmekten kaçınmalısın.\n\nHer yetenek kartının bir türü vardır. Bir yetenek kartı seçtiğinde Yoldaşlar, Yollar, Savaş Yetenekleri ve Ritüeller arasından seçim yaparsın. Çoğu yetenek kartı, dolu bir daireyle temsil edilen varsayılan bir yetenek içerir. Başlangıç yeteneği yoksa, bir tane seçersin.\n\nYetenek kartları genellikle sana bir bonus vererek hamleleri değiştirir ya da hamleyi farklı bir biçimde kullanmana olanak tanır. Bazı yetenek kartları kendi özgün hamlelerini içerir. Deneyim kazandıkça yetenek kartların için yükseltmeler satın alabilirsin. Bir yükseltme satın aldığında, artık o yeteneğe sahip olduğunu göstermek için daireyi doldurursun.\n\n## Canavar Avcısı\n\n*Yol*\n\n- Bir canavarın ya da dehşetin izini sürerek *Bilgi Topla*dığında veya onlara karşı bir dövüşe hazırlanarak *Avantaj Sağla*dığında, +1 ekle ve bir başarıda +1 Momentum al.\n- Bir canavarı ya da dehşeti öldürmek için *Demir Ant İç*tiğinde, herhangi bir zarı yeniden atabilirsin. *Antını Tamamla*yıp deneyim işaretlediğinde, +1 deneyim al.\n- Bir canavarı ya da dehşeti (en az Zorlu) öldürdüğünde, bir ganimet alabilir ve birini seçebilirsin.\n  - __Bir ritüele güç ver:__ Sen ya da bir müttefikin bir ritüel hamlesi yaptığında, herhangi bir zarı yeniden at (yalnızca bir kez).\n  - __Değerini kanıtla:__ *Konaklama* yaptığında, herhangi bir zarı yeniden at (yalnızca bir kez)."
	},
	{
		"page": 22,
		"img": "/basics/p22.webp",
		"title_en": "Oracles",
		"title_tr": "Kehanetler",
		"text_en": "## Oracles\n\nSome moves may prompt you to roll on a table to generate a result between 1 and 100. There are also a set of creative prompts in chapter 6 (page 165), which you can use to reveal details, trigger events, and guide the actions of other characters in your world. These oracles help answer questions in solo or co-op games, or provide inspiration for the GM in guided play.\n\n## Rolling Oracle Dice\n\nWhenever you are prompted by a move or an oracle table to generate a result between 1 and 100, roll two ten-sided dice.\n\nOne of your oracle dice may include tens digits on its faces. If so, you'd read a result of an 80 and a 3 as 83.\n\nYou can also use two d10s of different colors, and decide before rolling which represents the tens digit and which is the units. You'd read a 3 and a 6 as 36.\n\nYou might want to use a special set of dice for your oracle rolls, shared by everyone at the table. It'll make those dice feel special and unique.",
		"text_tr": "## Kehanetler\n\nBazı hamleler, 1 ile 100 arasında bir sonuç üretmek için bir tabloda zar atmanı isteyebilir. Bölüm 6'da (sayfa 165) ayrıca bir dizi yaratıcı esin vardır; bunları ayrıntıları açığa çıkarmak, olayları tetiklemek ve dünyandaki diğer karakterlerin eylemlerini yönlendirmek için kullanabilirsin. Bu kehanetler, solo ya da ortak oyunlarda soruları yanıtlamaya yardım eder veya rehberli oyunda Oyun Yöneticisi'ne ilham sağlar.\n\n## Kehanet Zarlarını Atmak\n\nBir hamle ya da bir kehanet tablosu seni 1 ile 100 arasında bir sonuç üretmeye yönelttiğinde, iki on yüzlü zar at.\n\nKehanet zarlarından birinin yüzlerinde onlar basamağı bulunabilir. Öyleyse, bir 80 ile bir 3'lük sonucu 83 olarak okursun.\n\nFarklı renklerde iki d10 da kullanabilir ve atmadan önce hangisinin onlar basamağını, hangisinin birler basamağını temsil ettiğine karar verebilirsin. Bir 3 ile bir 6'yı 36 olarak okursun.\n\nKehanet atışların için, masadaki herkesin paylaştığı özel bir zar takımı kullanmak isteyebilirsin. Bu, o zarların özel ve eşsiz hissettirmesini sağlar."
	},
	{
		"page": 23,
		"img": "/basics/p23.webp",
		"title_en": "Seeking Answers",
		"title_tr": "Cevap Aramak",
		"text_en": "## Seeking Answers\n\nIf you are playing solo or co-op, you can *Ask the Oracle* to help guide your game session and trigger ideas when you need to know what happens next. Its most basic function is to answer a \"yes\" or \"no\" question. Combined with your own instincts and creativity, this move—and other random prompts—can push your story in surprising and exciting directions. To learn more about this move, see page 107.\n\n## Ask the Oracle\n\nWhen you seek to resolve questions, discover details in the world, determine how other characters respond, or trigger encounters or events, you may…\n\n- __Draw a conclusion:__ Decide the answer based on the most interesting and obvious result.\n- __Ask a yes/no question:__ Decide the odds of a 'yes', and roll on the table below to check the answer.\n- __Pick two:__ Envision two options. Rate one as 'likely', and roll on the table below to see if it is true. If not, it is the other.\n- __Spark an idea:__ Brainstorm or use a random prompt.\n\n__The answer is ‘yes’ if you roll…__\n\n- __Almost Certain:__ 11 or greater\n- __Likely:__ 26 or greater\n- __50/50:__ 51 or greater\n- __Unlikely:__ 76 or greater\n- __Small Chance:__ 91 or greater\n\nOn a match, an extreme result or twist has occurred.\n\nIf you are playing with a GM, they are the oracle. When you see a prompt to *Ask the Oracle*, turn to your GM. The GM is free to leverage random tools and creative prompts to come up with the answers.\n\nKeep in mind that—even when playing with a GM—*Ironsworn* is about shared storytelling. Offer suggestions. Talk it out. The GM is the final arbiter of what happens next, but everyone at the table should participate in building the world and creating the narrative of your game.",
		"text_tr": "## Cevap Aramak\n\nSolo ya da ortak oynuyorsan, oyun oturumunu yönlendirmeye yardım etmesi ve sırada ne olacağını bilmen gerektiğinde fikirleri tetiklemesi için *Kehanetin Sesini Dinle*yebilirsin. En temel işlevi bir \"evet\" ya da \"hayır\" sorusunu yanıtlamaktır. Kendi sezgilerin ve yaratıcılığınla birleştiğinde bu hamle—ve diğer rastgele esinler—hikâyeni şaşırtıcı ve heyecan verici yönlere itebilir. Bu hamle hakkında daha fazlasını öğrenmek için bkz. sayfa 107.\n\n## Kehanetin Sesini Dinle\n\nSoruları çözmeye, dünyada ayrıntılar keşfetmeye, diğer karakterlerin nasıl tepki verdiğini belirlemeye ya da karşılaşmaları veya olayları tetiklemeye çalıştığında, şunları yapabilirsin…\n\n- __Bir sonuca var:__ Cevabı en ilginç ve en bariz sonuca göre belirle.\n- __Bir evet/hayır sorusu sor:__ Bir 'evet'in ihtimallerini belirle ve cevabı denetlemek için aşağıdaki tabloda zar at.\n- __İki tane seç:__ İki seçenek hayal et. Birini 'olası' olarak değerlendir ve doğru olup olmadığını görmek için aşağıdaki tabloda zar at. Değilse, diğeridir.\n- __Bir fikir ateşle:__ Fikir üret ya da rastgele bir esin kullan.\n\n__Bir 'evet' için ihtimaller__ (kehanet zarı 1–100 at, eşikle karşılaştır):\n\n- __Neredeyse Kesin:__ 11 ya da büyük\n- __Olası:__ 26 ya da büyük\n- __50/50:__ 51 ya da büyük\n- __Olası Değil:__ 76 ya da büyük\n- __Küçük İhtimal:__ 91 ya da büyük\n\nBir eşleşmede, aşırı bir sonuç ya da kıvrım ortaya çıkmıştır.\n\nBir Oyun Yöneticisi ile oynuyorsan, kehanet odur. *Kehanetin Sesini Dinle* yönergesini gördüğünde, Oyun Yöneticine dön. Oyun Yöneticisi, cevapları bulmak için rastgele araçlardan ve yaratıcı esinlerden serbestçe yararlanabilir.\n\nUnutma ki—bir Oyun Yöneticisi ile oynarken bile—*Ironsworn* ortak hikâye anlatıcılığıyla ilgilidir. Önerilerde bulun. Konuşarak çöz. Sırada ne olacağının nihai hakemi Oyun Yöneticisi'dir ama masadaki herkes dünyayı kurmaya ve oyununuzun anlatısını yaratmaya katılmalıdır."
	},
	{
		"page": 24,
		"img": "/basics/p24.webp",
		"title_en": "More Randomness and Bonds",
		"title_tr": "Daha Fazla Rastlantı ve Bağlar",
		"text_en": "## More Randomness\n\nYou'll find a set of random tables in chapter 6 (page 165). These provide inspirational prompts and random results for common situations. You can also use whatever random generators you prefer, including those drawn from another game, online generators, or visual tools such as tarot cards.\n\n## Trust Your Instincts\n\nThese random generators will never replace your own imagination and intuition. If it's interesting, dramatic, and pushes the story forward, make it happen. Too much reliance on random generators to answer questions about \"what happens next\" can kill the momentum of your game or make it feel disconnected and incoherent.\n\nKeep it moving. Ask a question. If an answer leaps to mind, go with it. If you're not sure, *Ask the Oracle*. Then, play.\n\n## Bonds\n\nAs you explore your world and complete quests, you create bonds with people and communities by making the *Forge a Bond* move (page 74). Bonds give you advantages for specific moves when interacting with those you have bonded with. For example, if you attempt to *Compel* someone (page 69), and you share a bond with them, you add +1 to your action score. The moves tell you when having a bond provides this advantage.\n\nBonds also help determine your fate when you retire from your life as an adventurer. The more bonds you create, the more connections you have with people and communities, the better your chance to live out your days peacefully in the company of others.\n\nYour character sheet has a special progress track for bonds. When you successfully *Forge a Bond*, mark 1 tick on this progress track. When your adventures are complete and you *Write Your Epilogue* (page 77), tally your bonds and make a progress roll (page 18) to wrap up your character's story.\n\n## Other Characters\n\nThe mechanics of *Ironsworn* are almost entirely character-facing—meaning they reference the capabilities and actions of your character. Other non-player characters and creatures (NPCs) don't have mechanical detail. In fact, they may only have a single stat—their rank—for tracking progress against them in a combat scene. Further, NPCs do not make moves. You won't roll dice for them to determine the outcome of their actions. When you attempt to…",
		"text_tr": "## Daha Fazla Rastlantı\n\nBölüm 6'da (sayfa 165) bir dizi rastgele tablo bulacaksın. Bunlar, yaygın durumlar için ilham verici esinler ve rastgele sonuçlar sunar. Başka bir oyundan alınanlar, çevrimiçi üreticiler ya da tarot kartları gibi görsel araçlar dâhil, tercih ettiğin herhangi bir rastgele üreticiyi de kullanabilirsin.\n\n## Sezgilerine Güven\n\nBu rastgele üreticiler, kendi hayal gücünün ve sezginin yerini asla tutmaz. Bir şey ilginç, çarpıcıysa ve hikâyeyi ileri itiyorsa, onu gerçekleştir. \"Sırada ne olacak\" sorularını yanıtlamak için rastgele üreticilere fazla bel bağlamak, oyununun Momentum'unu öldürebilir ya da onu kopuk ve tutarsız hissettirebilir.\n\nHızı koru. Bir soru sor. Aklına bir cevap geliyorsa, onunla git. Emin değilsen, *Kehanetin Sesini Dinle*. Sonra oyna.\n\n## Bağlar\n\nDünyanı keşfettikçe ve görevleri tamamladıkça, *Bağ Kur* hamlesini (sayfa 74) yaparak insanlarla ve topluluklarla bağlar oluşturursun. Bağlar, bağ kurduğun kişilerle etkileşirken belirli hamleler için sana avantajlar verir. Örneğin, birini *İkna Et*meye çalışırsan (sayfa 69) ve onunla bir bağ paylaşıyorsan, eylem puanına +1 eklersin. Bir bağa sahip olmanın bu avantajı ne zaman sağladığını hamleler söyler.\n\nBağlar ayrıca, bir maceracı olarak hayatından çekildiğinde kaderini belirlemeye de yardım eder. Ne kadar çok bağ oluşturursan, insanlarla ve topluluklarla ne kadar çok bağlantın olursa, günlerini başkalarının eşliğinde huzur içinde geçirme şansın o kadar artar.\n\nKarakter sayfanın bağlar için özel bir ilerleme izi vardır. Başarıyla *Bağ Kur*duğunda, bu ilerleme izinde 1 çentik işaretle. Maceraların tamamlandığında ve *Sonsözünü Yaz*dığında (sayfa 77), bağlarını topla ve karakterinin hikâyesini sonlandırmak için bir ilerleme atışı (sayfa 18) yap.\n\n## Diğer Karakterler\n\n*Ironsworn*'ün mekanikleri neredeyse tümüyle karaktere dönüktür—yani karakterinin yeteneklerine ve eylemlerine atıfta bulunur. Diğer oyuncu yönetmeyen karakterlerin ve yaratıkların (OYK'lar) mekanik ayrıntısı yoktur. Aslında, bir dövüş sahnesinde onlara karşı ilerlemeyi izlemek için tek bir statları—dereceleri—olabilir. Ayrıca OYK'lar hamle yapmaz. Eylemlerinin sonucunu belirlemek için onlar adına zar atmazsın. Onları…"
	},
	{
		"page": 25,
		"img": "/basics/p25.webp",
		"title_en": "Allies, Companions, and Equipment",
		"title_tr": "Müttefikler, Yoldaşlar ve Teçhizat",
		"text_en": "…influence them, oppose them, resist them, or aid them, make moves as your character. If you have questions about an NPC's motivations or what they do next, *Ask the Oracle*. To learn more, see page 133.\n\n## Allies and Companions\n\nIf you are playing a co-op or guided game with other players, their characters are referred to in these rules and in moves as your allies.\n\nA companion is a special type of asset. Unlike normal NPCs, they can provide mechanical benefits through their abilities, and they have a health track to record harm. If the text of a move refers to a companion, it means a companion asset. To learn more about companions, see page 39.\n\n## Equipment\n\nIn *Ironsworn*, you won't worry too much about equipment. Your supply track (page 34) is an abstract representation of your general readiness, clothes, ammo, food, water, and mundane gear.\n\nYou are armed and armored as appropriate to your vision for your character. If you wield a weapon, you can inflict harm with it. If you are armed with a deadly weapon (such as a sword, axe, spear, or bow), you inflict 2 harm. If you are unarmed or using an improvised or simple weapon (such as a shield, stick, club, staff, or rock), you inflict 1 harm.\n\nOther equipment provides narrative benefit. It enables you to make moves where that gear is important, or perhaps allows you to avoid a move altogether. For example, you need to make your way down a steep rock face. Without assistance, you'd make a *Face Danger* move to see what happens. If you had rope, the climb is not particularly risky or uncertain. In that case, you might skip the move and just narrate the result.\n\nSpecific assets (page 39) can make equipment more important and relevant to your character. For example, combat talent assets (page 40) represent your expertise in a particular weapon or fighting style. When you wield an appropriate weapon, you gain the benefit of the asset.\n\nApart from assets, you can make note of equipment at whatever level of detail you like, but don't fuss over it. If you're wondering whether you have a particular mundane item, you can *Ask the Oracle* (page 107).",
		"text_tr": "…etkilemeye, onlara karşı durmaya, onlara direnmeye ya da onlara yardım etmeye çalıştığında, karakterin olarak hamleler yap. Bir OYK'nın güdüleri ya da sırada ne yapacağı hakkında soruların varsa, *Kehanetin Sesini Dinle*. Daha fazlasını öğrenmek için bkz. sayfa 133.\n\n## Müttefikler ve Yoldaşlar\n\nDiğer oyuncularla ortak ya da rehberli bir oyun oynuyorsan, onların karakterlerine bu kurallarda ve hamlelerde müttefiklerin denir.\n\nYoldaş (companion), özel bir yetenek kartı türüdür. Normal OYK'ların aksine, yetenekleri yoluyla mekanik faydalar sağlayabilirler ve hasarı kaydetmek için bir can izleri vardır. Bir hamlenin metni bir yoldaşa atıfta bulunuyorsa, bu bir yoldaş yetenek kartı demektir. Yoldaşlar hakkında daha fazlasını öğrenmek için bkz. sayfa 39.\n\n## Teçhizat\n\n*Ironsworn*'de teçhizat hakkında pek kafa yormazsın. İkmal izin (sayfa 34), genel hazır oluşunun, giysilerinin, cephanenin, yiyeceğinin, suyunun ve sıradan donanımının soyut bir temsilidir.\n\nKarakterine dair vizyonuna uygun şekilde silahlı ve zırhlısındır. Bir silah taşıyorsan, onunla hasar verebilirsin. Ölümcül bir silahla (kılıç, balta, mızrak ya da yay gibi) silahlıysan, 2 hasar verirsin. Silahsızsan ya da derme çatma veya basit bir silah (kalkan, sopa, gürz, asa ya da taş gibi) kullanıyorsan, 1 hasar verirsin.\n\nDiğer teçhizat anlatısal fayda sağlar. O donanımın önemli olduğu hamleleri yapmanı mümkün kılar ya da belki bir hamleyi tümden atlamana olanak tanır. Örneğin, dik bir kaya yüzeyinden aşağı inmen gerekiyor. Yardım olmadan, ne olacağını görmek için bir *Tehlikeyle Yüzleş* hamlesi yapardın. İpin olsaydı, tırmanış pek riskli ya da belirsiz olmazdı. Bu durumda, hamleyi atlayıp sonucu yalnızca anlatabilirsin.\n\nBelirli yetenek kartları (sayfa 39), teçhizatı karakterin için daha önemli ve daha ilgili kılabilir. Örneğin, savaş yeteneği yetenek kartları (sayfa 40), belirli bir silahta ya da dövüş tarzında uzmanlığını temsil eder. Uygun bir silah taşıdığında, yetenek kartının faydasını edinirsin.\n\nYetenek kartlarının dışında, teçhizatı istediğin ayrıntı düzeyinde not edebilirsin ama bununla fazla uğraşma. Belirli bir sıradan eşyaya sahip olup olmadığını merak ediyorsan, *Kehanetin Sesini Dinle*yebilirsin (sayfa 107)."
	},
	{
		"page": 26,
		"img": "/basics/p26.webp",
		"title_en": "The Flow of Play",
		"title_tr": "Oyunun Akışı",
		"text_en": "## The Flow of Play\n\nLike most roleplaying games, you play primarily from the perspective of your character. What are you doing? What are you trying to achieve? What opposition and challenges do you face? Your quests, and the characters and situations you encounter, will guide the fiction and the choices you make.\n\nWhen you have questions about what you find, how other characters in your world respond, or what happens next, you can go with what feels right (if you're playing solo or co-op), or ask your GM. When you are seeking inspiration or want to put it in the hands of fate, you make the *Ask the Oracle* move (page 107). Use the yes/no questions and random prompts to generate interesting twists and new complications you might not have thought of on your own.\n\nAbove all, if it's interesting, dramatic, and fits the fiction, make it happen.\n\nIf you are doing something covered by a move, refer to the move to resolve your action. If it tells you to roll dice, do it.\n\nScoring a strong hit on a move means you are in control. You're driving the narrative. What do you do next?\n\nA weak hit or a miss means you don't have control of the situation. Instead of acting, you react. What happens next? If you're playing with a GM, they'll determine how the world responds. Otherwise, you rely on your intuition and occasional oracle rolls to drive the narrative.",
		"text_tr": "## Oyunun Akışı\n\nÇoğu rol yapma oyunu gibi, oyunu öncelikle karakterinin bakış açısından oynarsın. Ne yapıyorsun? Neyi başarmaya çalışıyorsun? Hangi muhalefet ve zorluklarla yüzleşiyorsun? Görevlerin ve karşılaştığın karakterler ile durumlar, kurguyu ve verdiğin seçimleri yönlendirecek.\n\nNe bulduğun, dünyandaki diğer karakterlerin nasıl tepki verdiği ya da sırada ne olacağı hakkında soruların olduğunda, doğru hissettiren şeyle gidebilir (solo ya da ortak oynuyorsan) veya Oyun Yöneticine sorabilirsin. İlham aradığında ya da işi kaderin eline bırakmak istediğinde, *Kehanetin Sesini Dinle* hamlesini (sayfa 107) yaparsın. Kendi başına aklına gelmeyebilecek ilginç kıvrımlar ve yeni karmaşalar üretmek için evet/hayır sorularını ve rastgele esinleri kullan.\n\nHer şeyden önce, bir şey ilginç, çarpıcıysa ve kurguya uyuyorsa, onu gerçekleştir.\n\nBir hamlenin kapsadığı bir şeyi yapıyorsan, eylemini çözmek için hamleye başvur. Sana zar atmanı söylüyorsa, at.\n\nBir hamlede Güçlü Başarı almak, denetimin sende olduğu anlamına gelir. Anlatıyı sen sürüyorsundur. Sırada ne yapacaksın?\n\nBir Zayıf Başarı ya da Başarısızlık, durumun denetiminin sende olmadığı anlamına gelir. Eyleme geçmek yerine tepki verirsin. Sırada ne olur? Bir Oyun Yöneticisi ile oynuyorsan, dünyanın nasıl karşılık vereceğini o belirler. Aksi hâlde, anlatıyı sürmek için sezgine ve ara sıra yapılan kehanet atışlarına güvenirsin."
	},
	{
		"page": 27,
		"img": "/basics/p27.webp",
		"title_en": "The Flow of Play (Summary)",
		"title_tr": "Oyunun Akışı (Özet)",
		"text_en": "__Start__\n\nEnvision the current situation and what your character is doing.\n\nAsk and answer questions about the world, other characters, and what happens next (or *Ask the Oracle*).\n\nWhen your action or the current situation triggers a move, make that move.\n\n- __Strong Hit:__ You've succeeded. You are in control. What do you do next?\n- __Weak Hit:__ You've made progress, but aren't in control. What happens next?\n- __Miss:__ You've failed, or encounter a costly turn of events. What happens next?",
		"text_tr": "__Başla__\n\nMevcut durumu ve karakterinin ne yaptığını hayal et.\n\nDünya, diğer karakterler ve sırada ne olacağı hakkında sorular sor ve yanıtla (ya da *Kehanetin Sesini Dinle*).\n\nEylemin ya da mevcut durum bir hamleyi tetiklediğinde, o hamleyi yap.\n\n- __Güçlü Başarı:__ Başardın. Denetim sende. Sırada ne yapacaksın?\n- __Zayıf Başarı:__ İlerleme kaydettin ama denetim sende değil. Sırada ne olur?\n- __Başarısızlık:__ Başarısız oldun ya da pahalıya patlayan bir gelişmeyle karşılaştın. Sırada ne olur?"
	},
	{
		"page": 28,
		"img": "/basics/p28.webp",
		"title_en": "What's Next",
		"title_tr": "Sırada Ne Var",
		"text_en": "That's the basics of playing *Ironsworn*. You'll see these concepts referenced and expanded throughout this rulebook, but you don't have to read it all before playing. To get started:\n\n- __Create your character (page 31):__ Set your stats, select your assets, and consider your background and personality.\n- __Build your world (page 111):__ Tour the Ironlands, create your vision of the setting, and find prompts for vows and quests — or play in your own world.\n- __Review the moves (page 49):__ A basic grasp of the moves and how you resolve your actions helps.\n- __Review the example of play (page 241):__ See *Ironsworn* in action — the dice, interpreting outcomes, and using prompts.\n- __Swear an Iron Vow (page 98):__ Play to see what happens.\n- __Dig deeper (page 193):__ When you're ready for campaign setup and options, see chapter 7.",
		"text_tr": "*Ironsworn* oynamanın temelleri bunlar. Bu kavramları kural kitabı boyunca tekrar görecek ve genişleteceksin, ama oynamadan önce hepsini okuman gerekmez. Başlamak için:\n\n- __Karakterini yarat (sayfa 31):__ Statlarını belirle, Yetenek Kartlarını seç, geçmişini ve kişiliğini düşün.\n- __Dünyanı kur (sayfa 111):__ Demir Diyarlar'da gez, kendi dünya vizyonunu yarat, antlar ve görevler için ilham bul — ya da kendi dünyanda oyna.\n- __Hamleleri gözden geçir (sayfa 49):__ Hamleleri ve eylemlerini nasıl çözeceğini temel düzeyde anlamak işine yarar.\n- __Oyun örneğini incele (sayfa 241):__ *Ironsworn*'ü iş başında gör — zarlar, sonuçları yorumlama ve esinleri kullanma.\n- __Demir Ant İç (sayfa 98):__ Oyna ve ne olacağını gör.\n- __Derine in (sayfa 193):__ Kampanya kurulumu ve seçenekler için hazır olduğunda Bölüm 7'ye bak."
	},
	{
		"page": 29,
		"img": "/basics/p29.webp",
		"title_en": "Ironsworn",
		"title_tr": "Demir-Andlı",
		"text_en": "The mother asked the seer to divine her new baby's fate. The old mystic looked at the sleeping child, tilted her head, closed her eyes — then drew back, frowning. No need to ask the gods. No need to roll the stones.\n\n*\"Ironsworn,\"* the seer said.\n\nShe took her price in silver and blood, and left the mother alone with the baby.\n\nThat night, the mother wept, for she knew her child would grow to live apart from her. Whether consumed by duty or vengeance, wanderlust or love, it was all the same. The trackless wilds would call, the blade and shadow would whisper their secrets, and her child would leave.\n\nShe cried for the life her child would live, and she cried for the knowing of it.",
		"text_tr": "Anne, kâhinden yeni doğan bebeğinin kaderini görmesini istedi. Yaşlı mistik uyuyan çocuğa baktı, başını yana eğdi, gözlerini kapadı — sonra kaşlarını çatarak geri çekildi. Tanrılara sormaya gerek yoktu. Taşları atmaya gerek yoktu.\n\n*\"Demir-Andlı,\"* dedi kâhin.\n\nBedelini gümüş ve kanla aldı, anneyi bebeğiyle yalnız bıraktı.\n\nO gece anne ağladı; çünkü çocuğunun büyüyüp kendisinden uzakta yaşayacağını biliyordu. İster görev ister intikam, ister gezginlik ister aşk tüketsin onu — hepsi birdi. Yolu kesilmemiş yabanlar onu çağıracak, kılıç ile gölge sırlarını fısıldayacak ve çocuğu gidecekti.\n\nÇocuğunun yaşayacağı hayata ağladı, bir de bunu bildiği için ağladı."
	}
];
