// Otomatik üretildi: Ironsworn Bölüm 4 "Your World" (PDF s.122–142) sayfa-sayfa.
// Görseller static/rulebook/dunyan/*.webp; çeviri /ceviri (Opus, glossary).
import type { RulebookPage } from './types.js';

export const dunyanPages: RulebookPage[] = [
	{
		"page": 111,
		"img": "/rulebook/dunyan/p111.webp",
		"title_en": "Welcome to the Ironlands",
		"title_tr": "Demir Diyarlar'a Hoş Geldin",
		"text_en": "## Welcome to the Ironlands\n\nThe Ironlands is a vast peninsula in the northern ocean. The people who now refer to themselves as Ironlanders settled here two generations ago, cast out of their homelands by a catastrophic event. Since that time, they have survived but not prospered. The Ironlands are a harsh, dangerous place. The winters are long and brutal. Harvests are uncertain. Depending on the choices you make as you create your version of the Ironlands, monstrous beasts and dreaded horrors may be a constant threat.\n\nThis chapter includes a brief summary for each major region of the Ironlands. It also includes a section where you define the characteristics, dangers, and mythology of your own Ironlands, creating a setting customized to your vision and preferences.\n\nThe detail here is intentionally light. Consider it a sketch on a canvas, ready to be adorned with the vibrant colors and details of your story.\n\n## Travel in the Ironlands\n\nWhen traveling through dangerous or unknown areas, make the Undertake a Journey move (page 65). You will set the rank of the journey as appropriate to the fictional circumstances—the distance, region, terrain, threats, and your character's readiness. You should also consider its importance in your quest. A higher rank means more storyline dedicated to the journey. If you want to move quicker to your destination, give it a lower rank. If this journey represents an important aspect of your character's story, or you want to create opportunities for interesting events and side quests, give it a higher rank.\n\nWhen in doubt, refer to the following for general guidelines, or Ask the Oracle.\n\n- Traveling a moderate distance within a single region is Troublesome.\n- Traveling a long distance within a single region, or across rough terrain, is Dangerous.\n- Traveling from one region to another, or across especially challenging terrain, is Formidable.\n- Traveling through multiple regions is Extreme.\n- Traveling from one end of the Ironlands to another, or to a separate land, is Epic.\n\nGenerally, don't sweat it. Travel should move at the speed of your story. Don't worry about exact measurements for distance or time. Give your journey a rank appropriate to the circumstances and your story, and make the move to see what happens.",
		"text_tr": "## Demir Diyarlar'a Hoş Geldin\n\nDemir Diyarlar (The Ironlands), kuzey okyanusundaki uçsuz bucaksız bir yarımadadır. Şimdi kendilerini Demir Diyar sakini olarak adlandıran halk, iki kuşak önce yıkıcı bir felaketle ana yurtlarından sürülerek buraya yerleşti. O günden beri hayatta kaldılar ama refaha eremediler. Demir Diyarlar sert ve tehlikeli bir yerdir. Kışlar uzun ve acımasızdır. Hasat belirsizdir. Kendi Demir Diyarlar'ını yaratırken yaptığın seçimlere bağlı olarak, canavar yaratıklar ve dehşet veren korkular sürekli bir tehdit olabilir.\n\nBu bölüm, Demir Diyarlar'ın her büyük bölgesi için kısa bir özet içerir. Ayrıca kendi Demir Diyarlar'ının özelliklerini, tehlikelerini ve mitolojisini tanımladığın, kendi vizyonuna ve tercihlerine göre biçimlendirilmiş bir dünya yarattığın bir bölüm de barındırır.\n\nBuradaki ayrıntı bilerek azdır. Onu bir tuval üzerindeki taslak olarak gör; senin hikâyenin canlı renkleri ve ayrıntılarıyla süslenmeyi bekliyor.\n\n## Demir Diyarlar'da Yolculuk\n\nTehlikeli ya da bilinmeyen bölgelerden geçerken Yolculuğa Çık (Undertake a Journey) hamlesini yap (sayfa 65). Yolculuğun derecesini kurgusal koşullara göre belirlersin — mesafe, bölge, arazi, tehditler ve karakterinin hazırlığı. Görevindeki önemini de göz önünde tut. Daha yüksek bir derece, yolculuğa daha çok hikâye ayrıldığı anlamına gelir. Hedefine daha hızlı varmak istiyorsan düşük bir derece ver. Bu yolculuk karakterinin hikâyesinin önemli bir yönünü temsil ediyorsa ya da ilginç olaylara ve yan görevlere fırsat yaratmak istiyorsan yüksek bir derece ver.\n\nKararsız kaldığında genel rehber olarak şunlara bak ya da Kehanetin Sesini Dinle.\n\n- Tek bir bölge içinde orta mesafede yolculuk Sıradan'dır.\n- Tek bir bölge içinde uzun mesafede ya da çetin arazide yolculuk Tehlikeli'dir.\n- Bir bölgeden diğerine ya da özellikle zorlu bir araziden yolculuk Zorlu'dur.\n- Birden çok bölge boyunca yolculuk Aşırı'dır.\n- Demir Diyarlar'ın bir ucundan diğerine ya da ayrı bir diyara yolculuk Destansı'dır.\n\nGenel olarak, kafana takma. Yolculuk, hikâyenin hızında ilerlemeli. Mesafe ya da zamanın tam ölçüsüyle uğraşma. Yolculuğuna koşullara ve hikâyene uygun bir derece ver ve hamleyi yaparak ne olacağını gör."
	},
	{
		"page": 112,
		"img": "/rulebook/dunyan/p112.webp",
		"title_en": "Regions of the Ironlands",
		"title_tr": "Demir Diyarlar'ın Bölgeleri",
		"text_en": "## Regions of the Ironlands\n\n1. Barrier Islands\n2. Ragged Coast\n3. Deep Wilds\n4. Flooded Lands\n5. Havens\n6. Hinterlands\n7. Tempest Hills\n8. Veiled Mountains\n9. Shattered Wastes",
		"text_tr": "## Demir Diyarlar'ın Bölgeleri\n\n1. Set Adaları\n2. Parçalı Kıyı\n3. Derin Yabanlar\n4. Su Basmış Topraklar\n5. Sığınaklar\n6. Ardtopraklar\n7. Fırtına Tepeleri\n8. Örtülü Dağlar\n9. Paramparça Çoraklıklar"
	},
	{
		"page": 113,
		"img": "/rulebook/dunyan/p113.webp",
		"title_en": "Barrier Islands",
		"title_tr": "Set Adaları",
		"text_en": "## Barrier Islands\n\n__Features:__\n\n- Crashing waves and treacherous currents\n- Jagged rocks hidden just beneath the surface\n- Snow-dappled cliffs jutting out of the sea\n- Low clouds and curling mists\n- Ferocious winds\n- Gliding seabirds\n- Decaying wrecks of wooden ships\n- Fisher-folk braving the wild sea\n- Lurking seaborne raiders\n\nThis long string of islands parallels the Ragged Coast. They are beautiful, but imposing. The slate-gray cliffs rise dramatically out of the water, topped by treeless moors. Waterfalls, fed by persistent rains, plunge over these cliffs into the raging sea. The winds are fierce and ever-present. In the winter, sleet, snow, and ocean mist can cut visibility to the length of one's arm.\n\nThe islands are sparsely populated by Ironlanders, mostly fisher-folk who brave the surrounding waters. Their settlements cling to narrow, rock-strewn shores or lie on high overlooks. At night, the dim lights of their fires and torches glimmer pitifully against the wild, storm-tossed sea.\n\n__Quest Starter:__ The spectral maiden appears at the bow of your ship, offering to guide you safely through the storm—for a price. What does she demand of you?",
		"text_tr": "## Set Adaları\n\n__Özellikler:__\n\n- Çarpan dalgalar ve hain akıntılar\n- Yüzeyin hemen altında gizlenen sivri kayalar\n- Denizden yükselen, karla benekli uçurumlar\n- Alçak bulutlar ve kıvrılan sisler\n- Vahşi rüzgârlar\n- Süzülen deniz kuşları\n- Çürüyen ahşap gemi enkazları\n- Vahşi denize meydan okuyan balıkçı halkı\n- Pusuda bekleyen denizden gelme yağmacılar\n\nBu uzun ada dizisi, Parçalı Kıyı'ya koşut uzanır. Güzel ama heybetlidirler. Arduvaz grisi uçurumlar, üstleri ağaçsız fundalıklarla taçlanmış olarak sudan çarpıcı biçimde yükselir. Aralıksız yağmurlarla beslenen şelaleler, bu uçurumlardan azgın denize dökülür. Rüzgârlar şiddetli ve her daim hazırdır. Kışın sulu kar, kar ve okyanus sisi görüş mesafesini bir kol boyuna indirebilir.\n\nAdalarda seyrek sayıda Demir Diyar sakini yaşar; çoğu, çevredeki sulara meydan okuyan balıkçı halkıdır. Yerleşimleri dar, kayalık kıyılara tutunur ya da yüksek seyir noktalarında kurulur. Geceleri, ateşlerinin ve meşalelerinin sönük ışıkları, vahşi, fırtınanın savurduğu denize karşı acınası biçimde titreşir.\n\n__Görev Başlangıcı:__ Hayalet kız, geminin pruvasında belirir ve seni fırtınadan güvenle geçirmeyi önerir — bir bedel karşılığında. Senden ne talep ediyor?"
	},
	{
		"page": 114,
		"img": "/rulebook/dunyan/p114.webp",
		"title_en": "Ragged Coast",
		"title_tr": "Parçalı Kıyı",
		"text_en": "## Ragged Coast\n\n__Features:__\n\n- Narrow fjords\n- Settlements built on rocky shores\n- Trade ships flying colorful sails\n- Shipbuilders hammering at wooden hulls\n- Raiders sounding the drums of war\n- Schools of orca gliding through the waves\n- Monstrous serpents rising from unfathomable depths\n\nThis coast is marked by massive fjords. It is a rugged land of snow-capped cliffs overlooking blue waters.\n\nIronlander settlements are located at the head of the fjords in the shelter of narrow valleys. From there, both fisher-folk and raiders set sail. Their kin gather to see them off, laying wreaths of spruce in their wake.\n\nIn the center of each settlement, at the front of the longhouse, a stack of rune-marked river stones memorialize those who did not return—one stone for each of the lost.\n\n__Quest Starter:__ A ship which set off from a coastal settlement is found washed up on shore. It is empty. This ship carried something of great importance, now lost. What was it, and why do you swear to recover it?",
		"text_tr": "## Parçalı Kıyı\n\n__Özellikler:__\n\n- Dar fiyortlar\n- Kayalık kıyılara kurulmuş yerleşimler\n- Rengârenk yelkenler açan ticaret gemileri\n- Ahşap tekneleri döven gemi yapımcıları\n- Savaş davullarını çalan yağmacılar\n- Dalgalar arasında süzülen orka sürüleri\n- Dipsiz derinliklerden yükselen canavar yılanlar\n\nBu kıyı kocaman fiyortlarla bilinir. Mavi sulara bakan, karla kaplı uçurumların oluşturduğu engebeli bir diyardır.\n\nDemir Diyar sakinlerinin yerleşimleri, fiyortların başında, dar vadilerin korunağında kurulur. Oradan hem balıkçı halkı hem de yağmacılar yelken açar. Yakınları onları uğurlamak için toplanır, ardlarına ladin çelenkleri bırakır.\n\nHer yerleşimin merkezinde, uzunevin önünde, rünlerle işaretli bir nehir taşı yığını geri dönmeyenlerin anısını yaşatır — yitirilen her kişi için bir taş.\n\n__Görev Başlangıcı:__ Bir kıyı yerleşiminden yola çıkan bir gemi, kıyıya vurmuş halde bulunur. Boştur. Bu gemi büyük önem taşıyan bir şeyi taşıyordu; o şey şimdi yitik. Neydi o ve onu geri almaya neden ant içiyorsun?"
	},
	{
		"page": 115,
		"img": "/rulebook/dunyan/p115.webp",
		"title_en": "Deep Wilds",
		"title_tr": "Derin Yabanlar",
		"text_en": "## Deep Wilds\n\n__Features:__\n\n- Unbroken woodland\n- A thick canopy casts the forest floor in shadow\n- Lingering fog\n- Constant rains\n- Elves, ever watchful\n- Ancient trees hung with moss\n- Streams winding their way through rough terrain\n- Skittering and growls from out of the mist\n\nThe Deep Wilds are a vast swath of ancient forest. The ground is a lush carpet of ferns and lichens. The gnarled branches are cloaked in hanging moss. The air is almost perpetually misty and wet. Unlike the bordering regions, heavy snow is rare here. Instead, there is the ceaseless patter of rain dripping from high boughs and the rush of river over rock. The air carries the earthy smells of damp and decay.\n\nA few Ironlanders live along the fringes of the Deep Wilds, taking advantage of the relatively temperate climate and abundant game. However, most avoid this region. This is a land of the firstborn, of monstrous beasts, of horrors that defy description. This is the world before humans.\n\n__Quest Starter:__ An Ironlander has sided with an enemy in the heart of the Wilds, and is leading attacks against Ironlander settlements. Who is this person? Who have they joined forces with? What will you do to stop these attacks?",
		"text_tr": "## Derin Yabanlar\n\n__Özellikler:__\n\n- Kesintisiz orman\n- Orman tabanını gölgeye boğan yoğun tepe örtüsü\n- Dağılmayan sis\n- Aralıksız yağmurlar\n- Hep tetikte, Elfler\n- Yosunla sarmalanmış kadim ağaçlar\n- Çetin araziden kıvrılarak akan dereler\n- Sisin içinden gelen koşuşturmalar ve hırıltılar\n\nDerin Yabanlar, kadim ormanın uçsuz bucaksız bir kuşağıdır. Zemin, eğreltiotları ve likenlerden oluşan gür bir halıdır. Çarpık dallar sarkan yosunlarla örtülüdür. Hava neredeyse hiç durmadan sisli ve nemlidir. Komşu bölgelerin aksine burada yoğun kar nadirdir. Onun yerine, yüksek dallardan damlayan yağmurun dinmeyen tıpırtısı ve nehrin kaya üstündeki gürlemesi vardır. Hava, nem ve çürümenin toprağımsı kokularını taşır.\n\nNispeten ılıman iklimden ve bol avdan yararlanan birkaç Demir Diyar sakini, Derin Yabanlar'ın kıyılarında yaşar. Ne var ki çoğu bu bölgeden kaçınır. Burası İlk Doğanlar'ın, canavar yaratıkların, tarifi imkânsız korkuların diyarıdır. Burası insandan önceki dünyadır.\n\n__Görev Başlangıcı:__ Bir Demir Diyar sakini, Yabanlar'ın kalbinde bir düşmanın yanında yer almış ve Demir Diyar sakinlerinin yerleşimlerine saldırılar düzenliyor. Kim bu kişi? Kimlerle güç birliği yapmış? Bu saldırıları durdurmak için ne yapacaksın?"
	},
	{
		"page": 116,
		"img": "/rulebook/dunyan/p116.webp",
		"title_en": "Flooded Lands",
		"title_tr": "Su Basmış Topraklar",
		"text_en": "## Flooded Lands\n\n__Features:__\n\n- Fetid wetlands\n- Dead trees poisoned by salt water\n- Networks of sluggish rivers\n- Ponds and lakes shrouded in clinging mist\n- Beguiling ghostlights, drawn to the warmth of the living\n- Biting insects\n- Creatures, just beneath the surface, laying in wait\n\nThis is a low-lying region of bogs, swamps, lakes, and slow-moving rivers. Near the coast, the water is salty and riddled with dead trees. Further north, the morass of forested wetlands and bogs is interspersed with rare patches of higher ground. Through it all, twisting rivers make their sluggish journey to the sea. The smell of these lands is rotten and dank. It is the smell of slow death.\n\nA few hardy Ironlanders live here in small settlements built atop hillocks, or in homes standing on stilts over the wetlands. Most fish and forage, making their way among the waterways on flat-bottomed boats propelled by long poles. Some dig through peat for bog iron—a cold, wet, grueling task.\n\nTravel is precarious here. One step has you on solid ground. The next sends you plunging through a thin layer of peat into a murky bog. Then, bony hands reach out to you, grasping, pulling. \"Stay with me,\" a voice whispers. \"Stay with me here in the dark.\"\n\n__Quest Starter:__ Rising flood waters threaten to overwhelm an Ironlander settlement. Escape by boat is the only option, but there are few boats and many people. What's more, there is something hungry in the water, waiting to feed.",
		"text_tr": "## Su Basmış Topraklar\n\n__Özellikler:__\n\n- Pis kokulu sulak araziler\n- Tuzlu suyla zehirlenmiş ölü ağaçlar\n- Ağır akan nehir ağları\n- Yapışkan sise bürünmüş göletler ve göller\n- Yaşayanın sıcaklığına çekilen, aldatıcı hayalet ışıkları\n- Isıran böcekler\n- Yüzeyin hemen altında pusuda yatan yaratıklar\n\nBurası bataklıkların, sazlıkların, göllerin ve ağır akan nehirlerin oluşturduğu alçak bir bölgedir. Kıyıya yakın yerlerde su tuzludur ve ölü ağaçlarla doludur. Daha kuzeyde, ormanlık sulak arazilerle bataklıkların batağı, ender görülen yüksek toprak parçalarıyla bölünür. Bütün bunların arasından kıvrılan nehirler, denize doğru ağır yolculuklarını sürdürür. Bu toprakların kokusu çürük ve küflüdür. Yavaş ölümün kokusudur bu.\n\nDayanıklı birkaç Demir Diyar sakini, tümseklerin üstüne kurulmuş küçük yerleşimlerde ya da sulak arazinin üzerinde direklere oturtulmuş evlerde yaşar. Çoğu balık tutar ve yiyecek toplar; su yolları arasında, uzun sırıklarla yürütülen düz tabanlı teknelerle ilerler. Bazıları turba kazarak bataklık demiri çıkarır — soğuk, ıslak, yıpratıcı bir uğraş.\n\nBurada yolculuk tekinsizdir. Bir adımın sağlam zemine basar. Sonraki adımın seni ince bir turba tabakasından bulanık bir bataklığa daldırır. Sonra kemikli eller sana uzanır, kavrar, çeker. \"Benimle kal,\" diye fısıldar bir ses. \"Karanlıkta benimle kal burada.\"\n\n__Görev Başlangıcı:__ Kabaran sel suları bir Demir Diyar sakini yerleşimini yutmakla tehdit ediyor. Tekneyle kaçmak tek seçenek, ama tekne az, insan çok. Üstelik suda bir şey var; aç, beslenmeyi bekliyor."
	},
	{
		"page": 117,
		"img": "/rulebook/dunyan/p117.webp",
		"title_en": "Havens",
		"title_tr": "Sığınaklar",
		"text_en": "## Havens\n\n__Features:__\n\n- Rolling hills and rocky bluffs\n- Pockets of dense wood, thick with shadow\n- Walled settlements\n- Verdant heaths\n- Wide rivers navigated by wary boatmen\n- Long, harsh winters\n\nThis is an expansive region of forests, rivers, shrubland, and low hills. After an arduous journey, after untold losses, the first Ironlander settlers looked upon the Havens as a fresh start—a relative oasis in a fierce, uncaring land. It gave them hope.\n\nYears later, that hope is fading. Even within the Havens, there is little rest or safety. The winters are long. The harvests are never enough. Raiders strike without mercy. The thick woods, deep rivers and dark nights hold secrets and lurking horrors. Some say the Ironlands is a living thing, a malevolent spirit, intent on ridding itself of the human invaders. Slowly, season by season, year by year, it is succeeding.\n\nThe Ironlander settlements in this region typically stand on hills or at the confluence of rivers. The buildings are made of wood, or sometimes stone, with roofs covered in turf. The central homes and communal structures are protected by an outer palisade fashioned from earth and wood. Outside these walls, from spring through autumn, farmers work the meager fields. In winter, the settlements are smothered by deep snow and oppressive gray clouds.\n\n__Quest Starter:__ A settlement has fallen under the unjust rule of a cruel leader. What leverage do they hold over these people? What is your connection to the community? What can be done to overthrow this tyrant?",
		"text_tr": "## Sığınaklar\n\n__Özellikler:__\n\n- Yumuşak hatlı tepeler ve kayalık yarlar\n- Gölgeye boğulmuş sık orman cepleri\n- Surlu yerleşimler\n- Yemyeşil fundalıklar\n- Tedirgin kayıkçıların geçtiği geniş nehirler\n- Uzun, sert kışlar\n\nBurası ormanların, nehirlerin, çalılıkların ve alçak tepelerin oluşturduğu geniş bir bölgedir. Çetin bir yolculuğun, sayısız kaybın ardından ilk Demir Diyar sakini yerleşimciler Sığınaklar'a yeni bir başlangıç gözüyle baktı — vahşi, vurdumduymaz bir diyarda görece bir vaha. Onlara umut verdi.\n\nYıllar sonra o umut sönüyor. Sığınaklar'ın içinde bile pek dinlenme ya da güvenlik yoktur. Kışlar uzundur. Hasat hiçbir zaman yetmez. Yağmacılar acımasızca saldırır. Sık ormanlar, derin nehirler ve karanlık geceler sırlar ve pusudaki korkular barındırır. Kimileri Demir Diyarlar'ın yaşayan bir şey, insan istilacılarından kurtulmaya kararlı kötücül bir ruh olduğunu söyler. Yavaşça, mevsim mevsim, yıl yıl, bunu başarıyor.\n\nBu bölgedeki Demir Diyar sakini yerleşimleri genellikle tepelerde ya da nehirlerin birleştiği yerlerde kurulur. Yapılar ahşaptan, kimi zaman taştan yapılır; çatıları çimenle örtülüdür. Merkezdeki evler ve ortak yapılar, topraktan ve ahşaptan yapılma bir dış çitle korunur. Bu surların dışında, ilkbahardan sonbahara dek çiftçiler cılız tarlaları işler. Kışın ise yerleşimler derin karla ve bunaltıcı gri bulutlarla boğulur.\n\n__Görev Başlangıcı:__ Bir yerleşim, zalim bir liderin haksız yönetimi altına düşmüş. Bu insanlar üzerinde nasıl bir koz tutuyor? Senin bu toplulukla bağın nedir? Bu zorbayı devirmek için ne yapılabilir?"
	},
	{
		"page": 118,
		"img": "/rulebook/dunyan/p118.webp",
		"title_en": "Hinterlands",
		"title_tr": "Ardtopraklar",
		"text_en": "## Hinterlands\n\n__Features:__\n\n- Dense forests nestled against rugged terrain\n- Hunter camps and remote settlements\n- Birdsong interspersed with sudden, unsettling stillness\n- Ironlanders, foraging and hunting game\n- Hungry beasts, stalking\n- Varou bands, howling their war song\n\nThis high terrain consists of a long string of forested hills.\n\nIsolated Ironlander settlements in this region serve primarily as bases for hunters and trappers. A few farmers do the best they can with the rocky soil, but the people depend mostly on meat, mushrooms, berries, and other bounties from the forest to sustain them during the long winters.\n\nThose winters are bitter and harsh. Snow gathers as deep as an Ironlander is tall, or more. Hunters, cloaked in heavy furs, wear snowshoes to navigate across the rough terrain. At night, they make camp. They drink and tell stories. They try to ward away the encroaching darkness with a blazing fire. They cast nervous glances at sounds just beyond the light.\n\nIn the spring and summer, the melting snow feeds tumultuous rivers. The forests burst with rich life. But, always there is a chill in the air. Always there is a reminder of the coming winter.\n\n__Quest Starter:__ A group of Ironlanders have been forced out of their Hinterland settlement. What caused them to leave? With winter coming, and food in short supply, will you attempt to reclaim their settlement or convince someone to take them in?",
		"text_tr": "## Ardtopraklar\n\n__Özellikler:__\n\n- Engebeli araziye yaslanmış sık ormanlar\n- Avcı kampları ve ücra yerleşimler\n- Ani, tedirgin edici sessizliklerle kesilen kuş cıvıltıları\n- Yiyecek toplayan ve av avlayan Demir Diyar sakinleri\n- Sinsice yaklaşan aç yaratıklar\n- Savaş şarkılarını uluyan Varou çeteleri\n\nBu yüksek arazi, ormanlık tepelerin uzun bir dizisinden oluşur.\n\nBu bölgedeki ücra Demir Diyar sakini yerleşimleri, başlıca avcılara ve tuzakçılara üs olur. Birkaç çiftçi kayalık toprakta elinden geleni yapar, ama halk uzun kışlar boyunca ayakta kalmak için çoğunlukla ete, mantarlara, yaban meyvelerine ve ormanın diğer nimetlerine bağımlıdır.\n\nO kışlar zorlu ve serttir. Kar, bir Demir Diyar sakininin boyu kadar, hatta daha derin birikir. Ağır kürklere sarınan avcılar, engebeli arazide yol almak için kar ayakkabısı giyer. Geceleri kamp kurarlar. İçer ve hikâye anlatırlar. Yaklaşan karanlığı alev alev yanan bir ateşle uzak tutmaya çalışırlar. Işığın hemen ötesindeki seslere tedirgin bakışlar atarlar.\n\nİlkbahar ve yazın eriyen kar, coşkun nehirleri besler. Ormanlar bereketli yaşamla taşar. Ama havada hep bir serinlik vardır. Hep gelmekte olan kışın bir hatırlatması vardır.\n\n__Görev Başlangıcı:__ Bir grup Demir Diyar sakini, Ardtopraklar'daki yerleşimlerinden çıkmaya zorlanmış. Onları gitmeye iten neydi? Kış gelmekteyken ve yiyecek kıtken, yerleşimlerini geri almaya mı çalışacaksın, yoksa birini onları yanına almaya mı ikna edeceksin?"
	},
	{
		"page": 119,
		"img": "/rulebook/dunyan/p119.webp",
		"title_en": "Tempest Hills",
		"title_tr": "Fırtına Tepeleri",
		"text_en": "## Tempest Hills\n\n__Features:__\n\n- Stunted forests\n- Howling winds\n- Mist-shrouded waterfalls\n- Mining settlements\n- Nomad encampments on high plateaus\n- Ironlander caravans hauling bounties of ore\n- Wary giants keeping their distance\n- Mammoths grazing in alpine meadows\n\nThese highlands are defined by rugged hills and low mountains, thin conifer woods, and wide, grassy plateaus, leading up to the heights of the Veiled Mountains. Through most seasons, the constant ill-winds break against the sides of the hills, screeching and moaning. In the dead of winter, some say these winds carry the names of those fated to die during the long cold season.\n\nNomadic Ironlanders live among the hills, herding livestock. In the spring and summer they move among high pastures. In the winter, they find some relief from the brutal weather in sheltered valleys.\n\nOthers live in mining settlements, drawing iron ore from riverbeds and shallow digs. Their furnaces, sending up plumes of black smoke, convert the ore into wrought iron, which is sent south for trade with the Havens.\n\n__Quest Starter:__ You have come across or learned of a rich source of unclaimed iron and silver among these hills. What hazards must be overcome before a mine can be established? What force opposes you or attempts to establish its own claim?",
		"text_tr": "## Fırtına Tepeleri\n\n__Özellikler:__\n\n- Bodur ormanlar\n- Uluyan rüzgârlar\n- Sise bürünmüş şelaleler\n- Madenci yerleşimleri\n- Yüksek yaylalardaki göçebe kampları\n- Cevher yükü taşıyan Demir Diyar sakini kervanları\n- Mesafesini koruyan tedirgin devler\n- Alp çayırlarında otlayan mamutlar\n\nBu yaylalar, Örtülü Dağlar'ın yüksekliklerine kadar uzanan engebeli tepeler ve alçak dağlar, seyrek iğne yapraklı ormanlar ve geniş, çimenli platolarla belirlenir. Çoğu mevsim boyunca dinmek bilmeyen uğursuz rüzgârlar, tepelerin yamaçlarına çarparak çığlık atıp inler. Kışın orta yerinde kimileri, bu rüzgârların uzun soğuk mevsimde ölmeye yazgılı olanların adlarını taşıdığını söyler.\n\nGöçebe Demir Diyar sakinleri, tepeler arasında yaşar ve hayvan güder. İlkbahar ve yazın yüksek otlaklar arasında dolaşırlar. Kışın, acımasız havadan biraz olsun korunağı, kuytu vadilerde bulurlar.\n\nDiğerleri madenci yerleşimlerinde yaşar; nehir yataklarından ve sığ kazılardan demir cevheri çıkarır. Kara duman tüten ocakları, cevheri dövme demire çevirir; bu demir de Sığınaklar'la ticaret için güneye gönderilir.\n\n__Görev Başlangıcı:__ Bu tepeler arasında, sahipsiz, zengin bir demir ve gümüş kaynağına rastladın ya da haberini aldın. Bir maden kurulabilmesi için hangi tehlikeler aşılmalı? Sana karşı koyan ya da kendi hak iddiasını kurmaya çalışan hangi güçtür?"
	},
	{
		"page": 120,
		"img": "/rulebook/dunyan/p120.webp",
		"title_en": "Veiled Mountains",
		"title_tr": "Örtülü Dağlar",
		"text_en": "## Veiled Mountains\n\n__Features:__\n\n- Massive peaks shrouded in roiling clouds\n- Howling beasts\n- Endless snows\n- Precarious mountain trails\n- Stone cairns, marking the dead\n- Abandoned settlements\n- Circling wyverns\n\nCommonly referred to as the Veils, these great mountains mark the northern bounds of the settled lands. They are almost perpetually shrouded in cloud, snow, and mist. On the rare day they are visible to those Ironlanders far south in the Havens, the sight of the towering peaks is enough to inspire a mix of fear and awe.\n\nFor a few, that feeling is a call rather than a warning. The Ironlanders who dwell here are mostly members of small mining communities. They seek fortunes in iron or silver, but often find only death in the endless, brutal cold. Even those who manage to eke out some sort of life among the Veils are sure to head south before the onset of winter. Before the long dark takes hold.\n\n__Quest Starter:__ As winter fast approaches, there is no sign of the Ironlanders who live in a small mining community on the flanks of the Veils. They should have been off the mountain weeks ago. Time is running out.",
		"text_tr": "## Örtülü Dağlar\n\n__Özellikler:__\n\n- Kaynayan bulutlara bürünmüş kocaman zirveler\n- Uluyan yaratıklar\n- Bitmek bilmeyen karlar\n- Tekinsiz dağ patikaları\n- Ölüleri işaretleyen taş yığınları\n- Terk edilmiş yerleşimler\n- Tepede dönen wyvernler\n\nGenellikle Örtüler diye anılan bu ulu dağlar, yerleşik toprakların kuzey sınırını çizer. Neredeyse hiç durmadan bulut, kar ve sise bürünürler. Sığınaklar'ın çok güneyindeki Demir Diyar sakinlerine göründükleri o ender günde, göğe yükselen zirvelerin görüntüsü korku ile hayranlığın bir karışımını uyandırmaya yeter.\n\nBirkaçı için o duygu bir uyarı değil, bir çağrıdır. Burada yaşayan Demir Diyar sakinleri çoğunlukla küçük madenci toplulukların üyesidir. Demirde ya da gümüşte servet ararlar, ama çoğu zaman bitmek bilmeyen, amansız soğukta yalnızca ölümü bulurlar. Örtüler arasında bir tür yaşam kurmayı başaranlar bile, kış bastırmadan, uzun karanlık egemen olmadan güneye gitmeye bakar.\n\n__Görev Başlangıcı:__ Kış hızla yaklaşırken, Örtüler'in yamaçlarındaki küçük bir madenci topluluğunda yaşayan Demir Diyar sakinlerinden hiç ses çıkmıyor. Haftalar önce dağdan inmiş olmalıydılar. Zaman daralıyor."
	},
	{
		"page": 121,
		"img": "/rulebook/dunyan/p121.webp",
		"title_en": "Shattered Wastes",
		"title_tr": "Paramparça Çoraklıklar",
		"text_en": "## Shattered Wastes\n\n__Features:__\n\n- Vast fields of broken ice\n- Discomforting stillness\n- Deep crevasses, plunging into darkness\n- Piercing cold\n- Unnatural horrors breaking through the ice\n\nTo the north of the Veiled Mountains lies the Shattered Wastes, a plain of jagged, broken ice.\n\nNo one knows the bounds of this land or what lies beyond. No Ironlanders dwell here, and only a handful have explored the passage into the Wastes through the Veils. Those who survived the journey returned with stories of unimaginable cold and things moving beneath the ice.\n\n__Quest Starter:__ The traveler returned from his journey into the Shattered Wastes with dead, frostbitten hands and extraordinary stories. The others scoff at him, but you believe. Why? What does he tell you? What compels you to see for yourself?",
		"text_tr": "## Paramparça Çoraklıklar\n\n__Özellikler:__\n\n- Kırık buzdan oluşan uçsuz bucaksız tarlalar\n- Tedirgin edici durgunluk\n- Karanlığa dalan derin buz yarıkları\n- Delici soğuk\n- Buzu kırıp çıkan doğadışı korkular\n\nÖrtülü Dağlar'ın kuzeyinde, sivri, kırık buzdan oluşan bir ova olan Paramparça Çoraklıklar uzanır.\n\nKimse bu diyarın sınırlarını ya da ötesinde ne olduğunu bilmez. Burada hiçbir Demir Diyar sakini yaşamaz; Örtüler'den Çoraklıklar'a açılan geçidi keşfedenler ise bir avuç kişidir. Yolculuktan sağ dönenler, akıl almaz bir soğuğun ve buzun altında kımıldayan şeylerin hikâyeleriyle geri geldiler.\n\n__Görev Başlangıcı:__ Gezgin, Paramparça Çoraklıklar'a yaptığı yolculuktan ölü, soğuktan kara kesmiş ellerle ve olağanüstü hikâyelerle döndü. Diğerleri onunla alay ediyor, ama sen ona inanıyorsun. Neden? Sana neler anlatıyor? Kendi gözlerinle görmeye seni iten nedir?"
	},
	{
		"page": 122,
		"img": "/rulebook/dunyan/p122.webp",
		"title_en": "Your Truths",
		"title_tr": "Senin Hakikatlerin",
		"text_en": "## Your Truths\n\nFor each category in this section, choose one of the three options and make it true for your version of the Ironlands. Your choices set the background and tone of your campaign, and may inspire vows through the quest starters listed with each option.\n\nNot happy with any of the choices? You can also make your own truth.\n\nSome choices in one category may contradict a choice you make in another, but you're free to bend and twist these options to fit your unique version of the Ironlands. If you find a particular choice to be evocative or interesting, make it work in the setting implied by your other choices. You can even select multiple choices within a single category. There are no rules here. Seeming contradictions can be the foundation of interesting stories.\n\nYour choices may impact your characters and the assets you might reasonably select. For example, if magic is rare or unknown in your world, rituals can be ignored or themed in such a way as to make them more about superstition and subtlety. Feel free to build your world around your characters, or let the world influence or limit your options.\n\nDon't get mired in building the detail of your setting before you start playing. Leave room for inspiration and surprises. As you play, fill in the blanks to further deepen your narrative and world. You may even discover that some of the choices you make here—which reflect the common knowledge of the people—aren't the actual truth after all.\n\nThe following section is available as a separate workbook at ironswornrpg.com, making it easy to print and mark your choices. If you are playing co-op or guided, do this as a group as part of your first session to give everyone input into your setting. See page 193 for more on starting your campaign.",
		"text_tr": "## Senin Hakikatlerin\n\nBu bölümdeki her kategori için üç seçenekten birini seç ve onu kendi Demir Diyarlar'ın için doğru kıl. Seçimlerin, seferinin arka planını ve tonunu belirler ve her seçenekle birlikte verilen görev başlangıçları aracılığıyla antlara ilham olabilir.\n\nSeçeneklerin hiçbiri hoşuna gitmedi mi? Kendi hakikatini de yaratabilirsin.\n\nBir kategorideki bazı seçimler, bir başkasında yaptığın seçimle çelişebilir, ama bu seçenekleri kendine özgü Demir Diyarlar'ına uydurmak için eğip bükmekte özgürsün. Belirli bir seçimi çağrışım yüklü ya da ilginç buluyorsan, onu diğer seçimlerinin işaret ettiği dünyada işler kıl. Tek bir kategori içinde birden çok seçimi bile seçebilirsin. Burada kural yoktur. Görünürdeki çelişkiler, ilginç hikâyelerin temeli olabilir.\n\nSeçimlerin, karakterlerini ve makul olarak seçebileceğin yetenek kartlarını etkileyebilir. Örneğin, dünyanda büyü nadir ya da bilinmiyorsa ritüeller göz ardı edilebilir ya da onları daha çok hurafe ve incelik üzerine kuracak biçimde temalandırılabilir. Dünyanı karakterlerinin etrafında kurmakta ya da dünyanın seçeneklerini etkilemesine, kısıtlamasına izin vermekte özgürsün.\n\nOynamaya başlamadan dünyanın ayrıntısını kurmaya saplanıp kalma. İlhama ve sürprizlere yer bırak. Oynadıkça boşlukları doldur; böylece anlatını ve dünyanı daha da derinleştir. Hatta burada yaptığın bazı seçimlerin — halkın ortak bilgisini yansıtan seçimlerin — aslında gerçek hakikat olmadığını bile keşfedebilirsin.\n\nAşağıdaki bölüm, ironswornrpg.com adresinde ayrı bir çalışma kitabı olarak mevcuttur; bu sayede seçimlerini yazdırıp işaretlemek kolaylaşır. Co-op ya da rehberli oynuyorsan, herkesin dünyana katkı koyabilmesi için bunu ilk oturumunun bir parçası olarak grupça yap. Seferine başlamak hakkında daha fazlası için sayfa 193'e bak."
	},
	{
		"page": 123,
		"img": "/rulebook/dunyan/p123.webp",
		"title_en": "The Old World",
		"title_tr": "Eski Dünya",
		"text_en": "## The Old World\n\n- The savage clans called the Skulde invaded the kingdoms of the Old World. Our armies fell. Most were killed or taken into slavery. Those who escaped set sail aboard anything that would float. After an arduous months-long voyage, the survivors made landfall upon the Ironlands.\n\n  __Quest Starter:__ You are a descendant of the Skulde. Because of your heritage, your family has long borne the distrust of your fellow Ironlanders. Now, a small force of Skulde have landed on our shores. Are they the harbinger of an invasion? Where do your loyalties lie?\n\n- The sickness moved like a horrible wave across the Old World, killing all in its path. Thousands fled aboard ships. However, the plague could not be outrun. On many ships, the disease was contained through ruthless measures—tossing overboard any who exhibited the slightest symptom. Other ships were forever lost. In the end, those who survived found the Ironlands and made it their new home. Some say we will forever be cursed by those we left behind.\n\n  __Quest Starter:__ A settlement is stricken by disease. Though this sickness bears some similarities to the Old World plague, it doesn't kill its victims. Instead, it changes them. How does this disease manifest? Why do you swear to seek out a cure?\n\n- The Old World could no longer sustain us. We were too large in number. We had felled the forests. Our crops withered in the barren ground. The cities and villages overflowed with desperate, hungry people. Petty kings battled for scraps. We cast our fate to the sea and found the Ironlands. A new world. A fresh start.\n\n  __Quest Starter:__ Decades ago, the exodus ended. Since then, no ships have sailed here from the Old World. Until now. Word comes of a single ship, newly arrived across the vast ocean, grounded on the rocks of the Barrier Islands. When you hear the name of this ship, you swear to uncover the fate of its passengers. Why is it so important to you?",
		"text_tr": "## Eski Dünya\n\n- Skulde denen vahşi klanlar, Eski Dünya'nın krallıklarını istila etti. Ordularımız düştü. Çoğu öldürüldü ya da köleliğe sürüklendi. Kaçabilenler, yüzebilecek ne bulduysa ona binip yelken açtı. Aylar süren çetin bir yolculuğun ardından sağ kalanlar, Demir Diyarlar'a ayak bastı.\n\n  __Görev Başlangıcı:__ Sen bir Skulde soyundansın. Bu mirasın yüzünden ailen, Demir Diyar sakini hemşehrilerinin güvensizliğini uzun süredir taşıyor. Şimdi, küçük bir Skulde gücü kıyılarımıza çıktı. Bir istilanın habercisi mi onlar? Senin sadakatin nereye?\n\n- Hastalık, Eski Dünya boyunca korkunç bir dalga gibi ilerledi ve yoluna çıkan herkesi öldürdü. Binlerce kişi gemilere binip kaçtı. Ne var ki vebadan kaçılamadı. Birçok gemide hastalık, acımasız önlemlerle dizginlendi — en ufak belirtiyi gösteren herkes denize atıldı. Başka gemiler ise sonsuza dek yitti. Sonunda sağ kalanlar Demir Diyarlar'ı buldu ve burayı yeni yurtları yaptı. Kimileri, geride bıraktıklarımız yüzünden sonsuza dek lanetli olacağımızı söyler.\n\n  __Görev Başlangıcı:__ Bir yerleşime hastalık çökmüş. Bu hastalık Eski Dünya vebasıyla bazı benzerlikler taşısa da kurbanlarını öldürmüyor. Onları değiştiriyor. Bu hastalık nasıl beliriyor? Bir çare aramaya neden ant içiyorsun?\n\n- Eski Dünya artık bizi besleyemez oldu. Sayımız çok fazlaydı. Ormanları yere sermiştik. Ekinlerimiz çorak toprakta kurudu. Şehirler ve köyler çaresiz, aç insanlarla taşıyordu. Sefil krallar artıklar için savaştı. Kaderimizi denize bıraktık ve Demir Diyarlar'ı bulduk. Yeni bir dünya. Yeni bir başlangıç.\n\n  __Görev Başlangıcı:__ Onlarca yıl önce göç sona erdi. O zamandan beri buraya Eski Dünya'dan hiç gemi gelmedi. Şimdiye dek. Tek bir geminin haberi geliyor; uçsuz bucaksız okyanusu yeni aşmış, Set Adaları'nın kayalarına oturmuş. Bu geminin adını duyduğunda, yolcularının kaderini açığa çıkarmaya ant içiyorsun. Bu senin için neden bu kadar önemli?"
	},
	{
		"page": 124,
		"img": "/rulebook/dunyan/p124.webp",
		"title_en": "Iron · Legacies",
		"title_tr": "Demir · Miraslar",
		"text_en": "## Iron\n\n- The imposing hills and mountains of the Ironlands are rich in iron ore. Most prized of all is the star-forged black iron.\n\n  __Quest Starter:__ The caravan, bound for the distant southlands, left the mining settlement last season but never arrived at its destination. It carried a bounty of black iron. Why is finding this lost caravan so important to you?\n\n- The weather is bleak. Rain and wind sweep in from the ocean. The winters are long and bitter. One of the first settlers complained, \"Only those made of iron dare live in this foul place\"—and thus our land was named.\n\n  __Quest Starter:__ The harvest fell short. The unrelenting snows left the village isolated. The food is running out. What will you do to see these people through this harsh season?\n\n- Inscrutable metal pillars are found throughout the land. They are iron gray, and smooth as river stone. No one knows their purpose. Some say they are as old as the world. Some, such as the Iron Priests, worship them and swear vows upon them. Most make the warding sign and hurry along their way when they happen across one. The pillars do not tarnish, and even the sharpest blade cannot mark them.\n\n  __Quest Starter:__ Your dreams are haunted by visions of a pillar which stands in an unfamiliar landscape. What do you see? Why are you sworn to seek it out?\n\n## Legacies\n\n- We are the first humans to walk these lands.\n\n  __Quest Starter:__ In the writings of one of the first settlers, there is a description of a glade in the heart of the Deep Wilds. The spirits of this place are said to grant a miraculous blessing. What boon does it bestow?\n\n- Other humans sailed here from the Old World untold years ago, but all that is left of them is a savage, feral people we call the broken. Is their fate to become our own?\n\n  __Quest Starter:__ You find a child—one of the broken. It is wounded, and hunted by others of its kind. Do you protect it, even at the risk of inviting the wrath of the broken tribes?\n\n- Before the Ironlanders, before even the firstborn, another people lived here. Their ancient ruins are found throughout the Ironlands.",
		"text_tr": "## Demir\n\n- Demir Diyarlar'ın heybetli tepeleri ve dağları demir cevheri bakımından zengindir. Hepsinin en değerlisi, yıldız-dövmesi kara demirdir.\n\n  __Görev Başlangıcı:__ Uzak güney topraklarına giden kervan, geçen mevsim madenci yerleşiminden ayrıldı ama hedefine hiç varmadı. Bir yük kara demir taşıyordu. Bu yitik kervanı bulmak senin için neden bu kadar önemli?\n\n- Hava kasvetlidir. Yağmur ve rüzgâr okyanustan süpürülüp gelir. Kışlar uzun ve zorludur. İlk yerleşimcilerden biri, \"Bu iğrenç yerde ancak demirden olanlar yaşamaya cüret eder,\" diye yakınmış — ve diyarımız böyle adlandırılmış.\n\n  __Görev Başlangıcı:__ Hasat yetersiz kaldı. Dinmek bilmeyen karlar köyü dışarıya kapattı. Yiyecek tükeniyor. Bu insanları bu sert mevsimden çıkarmak için ne yapacaksın?\n\n- Diyarın her yanında, anlaşılması güç metal sütunlar bulunur. Demir grisidirler ve nehir taşı gibi pürüzsüzdürler. Kimse amaçlarını bilmez. Kimileri dünya kadar eski olduklarını söyler. Demir Rahipleri gibi bazıları onlara tapar ve üzerlerine ant içer. Çoğu kişi bir tanesine rastladığında koruyucu işareti yapıp yoluna hızla devam eder. Sütunlar kararmaz ve en keskin kılıç bile onları çizemez.\n\n  __Görev Başlangıcı:__ Düşlerine, yabancı bir manzarada dikilen bir sütunun görüntüleri musallat oluyor. Ne görüyorsun? Onu aramaya neden antlısın?\n\n## Miraslar\n\n- Bu topraklarda yürüyen ilk insanlar biziz.\n\n  __Görev Başlangıcı:__ İlk yerleşimcilerden birinin yazılarında, Derin Yabanlar'ın kalbindeki bir orman açıklığının tarifi var. Bu yerin ruhlarının mucizevi bir lütuf bahşettiği söyleniyor. Nasıl bir kayra sunuyor?\n\n- Sayısız yıl önce başka insanlar Eski Dünya'dan buraya yelken açtı, ama onlardan geriye kalan tek şey, Yıkıklar dediğimiz vahşi, ürkek bir halk. Onların kaderi bizim de kaderimiz mi olacak?\n\n  __Görev Başlangıcı:__ Bir çocuk buluyorsun — Yıkıklar'dan biri. Yaralı ve kendi türünden olanlar onu avlıyor. Yıkık kabilelerin gazabını üstüne çekme riskine rağmen onu korur musun?\n\n- Demir Diyar sakinlerinden önce, hatta İlk Doğanlar'dan bile önce, burada başka bir halk yaşamış. Onların kadim harabeleri Demir Diyarlar'ın her yanında bulunur."
	},
	{
		"page": 125,
		"img": "/rulebook/dunyan/p125.webp",
		"title_en": "Communities · Leaders",
		"title_tr": "Topluluklar · Liderler",
		"text_en": "  __Quest Starter:__ Miners uncovered an underground ruin. Thereafter, the people of the settlement are haunted by strange dreams. The ruins call to them, they say. Several have disappeared in that dark, ancient place—including someone important to you.\n\n## Communities\n\n- We are few in number in this accursed land. Most rarely have contact with anyone outside our own small steading or village, and strangers are viewed with deep suspicion.\n\n  __Quest Starter:__ In the dead of winter, a desperate man arrives at a snowbound steading. He is wounded, hungry, and nearly frozen to death. His family has been taken. By whom? Will you brave the merciless winter to save them?\n\n- We live in communities called circles. These are settlements ranging in size from a steading with a few families to a village of several hundred. Some circles belong to nomadic folk. Some powerful circles might include a cluster of settlements. We trade (and sometimes feud) with other circles.\n\n  __Quest Starter:__ A decades-long feud between two circles has flared into open conflict. What is the cause of this dispute? Do you join in the fight, or swear to put a stop to it?\n\n- We have forged the Ironlands into a home. Villages within the Havens are connected by well-trod roads. Trade caravans travel between settlements in the Havens and those in outlying regions. Even so, much of this land is untamed.\n\n  __Quest Starter:__ Caravans are forced to pay for passage along a trade road. This payment, one-quarter of the goods carried, leaves several communities without sufficient winter stores. Who is making these demands? How will you set things right?\n\n## Leaders\n\n- Leadership is as varied as the people. Some communities are governed by the head of a powerful family. Or, they have a council of elders who make decisions and settle disputes. In others, the priests hold sway. For some, it is duels in the circle that decide.\n\n  __Quest Starter:__ You have vivid reoccurring dreams of an Ironlands city. It has strong stone walls, bustling markets, and a keep on a high hill. And so many people! Nowhere in the Ironlands does such a city exist. In your dreams, you are the ruler of this city. Somehow, no matter how long it takes, you must make this vision a reality.",
		"text_tr": "  __Görev Başlangıcı:__ Madenciler yeraltında bir harabe açığa çıkardı. Bundan sonra yerleşim halkına garip düşler musallat oldu. Harabeler onları çağırıyormuş, diyorlar. O karanlık, kadim yerde birkaç kişi kayboldu — senin için önemli olan biri de dahil.\n\n## Topluluklar\n\n- Bu lanetli diyarda sayıca azız. Çoğumuz kendi küçük yerleşimimizin ya da köyümüzün dışından kimseyle nadiren temas kurar, yabancılara derin bir kuşkuyla bakılır.\n\n  __Görev Başlangıcı:__ Kışın orta yerinde, çaresiz bir adam karla kaplı bir yerleşime varır. Yaralı, aç ve neredeyse donmak üzeredir. Ailesi kaçırılmıştır. Kim tarafından? Onları kurtarmak için merhametsiz kışa göğüs gerer misin?\n\n- Çemberler denen topluluklar halinde yaşarız. Bunlar, birkaç ailelik bir yerleşimden birkaç yüz kişilik bir köye kadar değişen boyutlarda yerleşimlerdir. Bazı çemberler göçebe halka aittir. Bazı güçlü çemberler bir yerleşimler kümesini içerebilir. Diğer çemberlerle ticaret yaparız (ve bazen çekişiriz).\n\n  __Görev Başlangıcı:__ İki çember arasındaki onlarca yıllık bir çekişme açık bir çatışmaya dönüşmüş. Bu kavganın nedeni nedir? Sen de kavgaya katılır mısın, yoksa onu durdurmaya mı ant içersin?\n\n- Demir Diyarlar'ı dövüp bir yurda çevirdik. Sığınaklar'daki köyler, çiğnenmiş yollarla birbirine bağlıdır. Ticaret kervanları, Sığınaklar'daki yerleşimlerle uzak bölgelerdekiler arasında gidip gelir. Yine de bu diyarın büyük bölümü evcilleşmemiştir.\n\n  __Görev Başlangıcı:__ Kervanlar, bir ticaret yolundan geçmek için ücret ödemeye zorlanıyor. Taşınan malların dörtte biri olan bu ödeme, birçok topluluğu yeterli kış stoğundan yoksun bırakıyor. Bu talepleri kim yapıyor? İşleri yoluna nasıl koyacaksın?\n\n## Liderler\n\n- Liderlik, halk kadar çeşitlidir. Bazı topluluklar güçlü bir ailenin reisi tarafından yönetilir. Ya da kararları alıp anlaşmazlıkları çözen bir ihtiyarlar meclisi vardır. Kimilerinde rahipler söz sahibidir. Bazıları için ise çemberdeki düellolar belirleyicidir.\n\n  __Görev Başlangıcı:__ Bir Demir Diyarlar şehrine dair canlı, yinelenen düşler görüyorsun. Sağlam taş surları, hareketli pazarları ve yüksek bir tepedeki bir hisarı var. Ve o kadar çok insan! Demir Diyarlar'ın hiçbir yerinde böyle bir şehir yoktur. Düşlerinde bu şehrin hükümdarı sensin. Ne kadar sürerse sürsün, bir biçimde bu görüntüyü gerçeğe dönüştürmelisin."
	},
	{
		"page": 126,
		"img": "/rulebook/dunyan/p126.webp",
		"title_en": "Leaders (cont.) · Defense",
		"title_tr": "Liderler (devam) · Savunma",
		"text_en": "- Each of our communities has its own leader, called an overseer. Every seventh spring, the people affirm their current overseer or choose a new one. Some overseers wear the iron circlet reluctantly, while others thirst for power and gain it through schemes or threats.\n\n  __Quest Starter:__ An overseer has fallen ill. She is sure to die without help, and the illness is unknown to the village healer. Poison, or perhaps even foul magic, is suspected. The families in the community are now at each other's throats as they position their preferred candidates to take up the iron circlet. Will you discover the truth of the overseer's illness and restore her to health?\n\n- Numerous clan-chiefs rule over petty domains. Most are intent on becoming the one true king. Their squabbles will be our undoing.\n\n  __Quest Starter:__ You secretly possess one-half of the True Crown, an Old World relic. Centuries ago, this crown was broken in two when an assassin's axe split the head of the supreme ruler. You are descended from that lineage. Who gave you this relic? Will you find the other half of the broken crown and attempt to unite the clans under your rule? Or, do you see another use for it?\n\n## Defense\n\n- Here in the Ironlands, supplies are too precious, and the lands are too sparsely populated, to support organized fighting forces. When a community is threatened, the people stand together to protect their own.\n\n  __Quest Starter:__ A settlement is unable, or unwilling, to defend itself against an imminent threat. Why? What peril do they face? What will you do to protect them?\n\n- The wardens are our soldiers, guards, and militia. They serve their communities by standing sentry, patrolling surrounding lands, and organizing defenses in times of crisis. Most have strong ties to their community. Others, called free wardens, are wandering mercenaries who hire on to serve a community or protect caravans.\n\n  __Quest Starter:__ You come upon a dying warden. She tells you of an important mission, and charges you with its completion. \"Swear to me,\" she says, reaching out with a bloodied hand to give you an object crucial to the quest. What is it?\n\n- Our warbands are rallied to strike at our enemies or defend our holdings. Though not nearly as impressive as the armies that once marched across the Old World, these forces are as well-trained and equipped as their communities can manage. The banners of the warbands are adorned with depictions of their Old World history and Ironland victories.",
		"text_tr": "- Topluluklarımızın her birinin, gözetici denen kendi lideri vardır. Her yedinci ilkbaharda halk, mevcut gözeticisini onaylar ya da yenisini seçer. Bazı gözeticiler demir tacı isteksizce takarken, diğerleri güce susar ve onu entrikalarla ya da tehditlerle ele geçirir.\n\n  __Görev Başlangıcı:__ Bir gözetici hastalanmış. Yardım olmadan kesinlikle ölecek ve hastalık köyün şifacısına yabancı. Zehirden, hatta belki kötü büyüden şüpheleniliyor. Topluluğun aileleri, demir tacı kapmak için kendi tercih ettikleri adayları öne sürerken birbirlerinin gırtlağına sarılmış durumda. Göceticinin hastalığının gerçeğini açığa çıkarıp onu sağlığına kavuşturacak mısın?\n\n- Sayısız klan reisi, sefil topraklar üzerinde hüküm sürer. Çoğu, tek gerçek kral olmaya kararlı. Onların didişmeleri bizim sonumuz olacak.\n\n  __Görev Başlangıcı:__ Gizlice, bir Eski Dünya kalıntısı olan Gerçek Taç'ın yarısına sahipsin. Yüzyıllar önce bir suikastçının baltası yüce hükümdarın başını ikiye böldüğünde bu taç da ikiye kırıldı. Sen o soydan geliyorsun. Bu kalıntıyı sana kim verdi? Kırık tacın diğer yarısını bulup klanları kendi yönetimin altında birleştirmeye mi çalışacaksın? Yoksa onun için başka bir kullanım mı düşünüyorsun?\n\n## Savunma\n\n- Burada, Demir Diyarlar'da, ikmal fazla değerli ve topraklar fazla seyrek nüfuslu olduğundan, örgütlü savaş güçleri beslenemez. Bir topluluk tehdit altına girdiğinde, halk kendi insanlarını korumak için bir araya gelir.\n\n  __Görev Başlangıcı:__ Bir yerleşim, yakın bir tehdide karşı kendini savunamıyor ya da savunmak istemiyor. Neden? Karşılaştıkları tehlike nedir? Onları korumak için ne yapacaksın?\n\n- Muhafızlar, bizim askerlerimiz, korumalarımız ve milisimizdir. Nöbet tutarak, çevre toprakları kollayarak ve kriz zamanlarında savunmaları örgütleyerek topluluklarına hizmet ederler. Çoğunun topluluğuyla güçlü bağları vardır. Serbest muhafız denen diğerleri ise, bir topluluğa hizmet etmek ya da kervanları korumak için kiralanan gezgin paralı askerlerdir.\n\n  __Görev Başlangıcı:__ Ölmekte olan bir muhafıza rastlarsın. Sana önemli bir görevden söz eder ve onu tamamlamayı senin sırtına yükler. \"Bana ant iç,\" der ve kanlı bir elle sana, göreve hayati bir nesne uzatır. Nedir o?\n\n- Savaş bölüklerimiz, düşmanlarımıza vurmak ya da topraklarımızı savunmak için bir araya getirilir. Bir zamanlar Eski Dünya boyunca yürüyen ordular kadar etkileyici olmasa da, bu güçler topluluklarının imkânları ölçüsünde iyi eğitimli ve donanımlıdır. Savaş bölüklerinin sancakları, Eski Dünya tarihlerinin ve Demir Diyar zaferlerinin betimlemeleriyle süslenir."
	},
	{
		"page": 127,
		"img": "/rulebook/dunyan/p127.webp",
		"title_en": "Defense (cont.) · Mysticism · Religion",
		"title_tr": "Savunma (devam) · Mistisizm · Din",
		"text_en": "  __Quest Starter:__ A warband was wiped out in a battle against an overwhelming enemy. What is your connection to this band? Who defeated them? Will you carry their banner on a quest for vengeance, or do you vow to see it brought home to a place of honor?\n\n## Mysticism\n\n- Some still find comfort in the old ways. They call on mystics to divine the fortune of their newborn, or ask them to perform rituals to invoke a bountiful harvest. Others act out of fear against those who they suspect of having power. However, most folk believe true magic—if it ever existed—is lost to us now.\n\n  __Quest Starter:__ Someone close to you is accused of cursing a settlement, causing fields to go fallow and cattle to become sick. What is the evidence of this? Will you defend this person and uncover the true cause of the settlement's troubles?\n\n- Magic is rare and dangerous, but those few who wield the power are truly gifted.\n\n  __Quest Starter:__ You have heard stories of someone who wields true power. They live in an isolated settlement far away. Who told you of this mystic? Are they feared or respected? Why do you swear to seek them out?\n\n- Magic courses through this land as the rivers flow through the hills. The power is there for those who choose to harness it, and even the common folk often know a helpful ritual or two.\n\n  __Quest Starter:__ Someone you love walked the paths of power, and succumbed to it. Who are they? Why did they fall into darkness? Where are they now? Do you seek to save them or defeat them?\n\n## Religion\n\n- A few Ironlanders still make signs or mumble prayers out of habit or tradition, but most believe the gods long ago abandoned us.\n\n  __Quest Starter:__ A charismatic Ironlander, encouraging her followers to renounce the vestiges of Old World religions, proposes a new path for this new world. What doctrine does she teach? What does she seek to achieve? Are you sworn to aid or stop her?\n\n- The people honor old gods and new. In this harsh land, a prayer is a simple but powerful comfort.\n\n  __Quest Starter:__ An Ironlander is determined to make a pilgrimage into dangerous lands. What holy place do they seek? Why do you swear to aid them on this journey? Who seeks to stop them and why?",
		"text_tr": "  __Görev Başlangıcı:__ Bir savaş bölüğü, ezici bir düşmana karşı verilen bir muharebede yok edildi. Bu bölükle bağın nedir? Onları kim yendi? Sancaklarını bir intikam göreviyle mi taşıyacaksın, yoksa onu bir onur köşesine getirmeye mi ant içiyorsun?\n\n## Mistisizm\n\n- Bazıları hâlâ eski yollarda teselli bulur. Yeni doğanlarının talihini görmek için mistikleri çağırır ya da bereketli bir hasat çağırmak için ritüel yapmalarını isterler. Diğerleri ise güç sahibi olduğundan şüphelendiklerine karşı korkudan davranır. Yine de çoğu kişi, gerçek büyünün — eğer hiç var olduysa — artık bizden yitip gittiğine inanır.\n\n  __Görev Başlangıcı:__ Sana yakın biri, bir yerleşimi lanetleyip tarlaları nadasa, sığırları hastalığa düşürmekle suçlanıyor. Bunun kanıtı nedir? Bu kişiyi savunup yerleşimin başına gelen dertlerin gerçek nedenini açığa çıkaracak mısın?\n\n- Büyü nadir ve tehlikelidir, ama o gücü kullanan o birkaç kişi gerçekten yeteneklidir.\n\n  __Görev Başlangıcı:__ Gerçek bir güç kullanan birinin hikâyelerini duydun. Uzaklarda, ücra bir yerleşimde yaşıyor. Bu mistikten sana kim söz etti? Korkuluyor mu, sayılıyor mu? Onu aramaya neden ant içiyorsun?\n\n- Büyü, nehirlerin tepeler arasından akması gibi bu diyarın içinden akar. Güç, onu dizginlemeyi seçenler için oradadır ve sıradan halk bile çoğu zaman işe yarar bir iki ritüel bilir.\n\n  __Görev Başlangıcı:__ Sevdiğin biri güç yollarında yürüdü ve ona yenik düştü. Kim onlar? Neden karanlığa düştüler? Şimdi neredeler? Onları kurtarmaya mı çalışıyorsun, yoksa yenmeye mi?\n\n## Din\n\n- Birkaç Demir Diyar sakini hâlâ alışkanlıktan ya da gelenekten işaretler yapar ya da dualar mırıldanır, ama çoğu, tanrıların bizi çoktan terk ettiğine inanır.\n\n  __Görev Başlangıcı:__ Karizmatik bir Demir Diyar sakini, izleyicilerini Eski Dünya dinlerinin kalıntılarından el çekmeye teşvik ederek bu yeni dünya için yeni bir yol öneriyor. Nasıl bir öğreti vaaz ediyor? Neyi başarmak istiyor? Ona yardım etmeye mi, yoksa onu durdurmaya mı antlısın?\n\n- Halk, eski ve yeni tanrıları onurlandırır. Bu sert diyarda bir dua, basit ama güçlü bir tesellidir.\n\n  __Görev Başlangıcı:__ Bir Demir Diyar sakini, tehlikeli topraklara bir hac yolculuğu yapmaya kararlı. Hangi kutsal yeri arıyor? Bu yolculukta ona yardım etmeye neden ant içiyorsun? Onu durdurmaya çalışan kim ve neden?"
	},
	{
		"page": 128,
		"img": "/rulebook/dunyan/p128.webp",
		"title_en": "Religion (cont.) · Firstborn · Beasts",
		"title_tr": "Din (devam) · İlk Doğanlar · Yaratıklar",
		"text_en": "- Our gods are many. They make themselves known through manifestations and miracles. Some say they even secretly walk among us. The priests convey the will of the gods and hold sway over many communities.\n\n  __Quest Starter:__ You bear the mark of a god. What is it? The priests declare this as a sign you are chosen to fulfill a destiny. Do you accept this fate, and swear to see it through, or are you determined to see it undone? What force opposes you?\n\n## Firstborn\n\n- The firstborn have passed into legend. Some say the remnants of the old tribes still dwell in deep forests or high mountains. Most believe they were never anything more than myth.\n\n  __Quest Starter:__ Someone obsessed with the firstborn wants to find evidence of their existence. This will require an expedition into the far reaches of the Ironlands. What is your role in this mission?\n\n- The firstborn live in isolation and are fiercely protective of their own lands.\n\n  __Quest Starter:__ The elf, outcast from his kind, lives with Ironlanders. Over time, he became a part of the community. Now, he is dying. He yearns to return to his people before he passes. Does he seek absolution or justice? Why do you swear to help him? What force opposes his return?\n\n- The firstborn hold sway in the Ironlands. The elves of the deep forests and the giants of the hills tolerate us and even trade with us—for now. Ironlanders fear the day they decide we are no longer welcome here.\n\n  __Quest Starter:__ Humans and giants are on the brink of war. What has happened? Who do you side with? Can anything be done to defuse the situation?\n\n## Beasts\n\n- The beasts of old are nothing but legend. A few who travel into the deep forests and high mountains return with wild tales of monstrous creatures, but they are obviously delusional. No such things exist.\n\n  __Quest Starter:__ You were witness to an attack by what you thought was an animal of monstrous proportions. No one believes you. In fact, you are accused of the murder you blame on this beast. How can you prove your innocence? Can you even trust your own memories of the event?",
		"text_tr": "- Tanrılarımız çoktur. Kendilerini tezahürlerle ve mucizelerle belli ederler. Kimileri, gizlice aramızda dolaştıklarını bile söyler. Rahipler, tanrıların iradesini iletir ve birçok topluluk üzerinde söz sahibidir.\n\n  __Görev Başlangıcı:__ Bir tanrının damgasını taşıyorsun. Nedir o? Rahipler bunu, bir kaderi tamamlamak için seçildiğinin işareti olarak ilan ediyor. Bu yazgıyı kabul edip onu sonuna dek götürmeye mi ant içiyorsun, yoksa onu bozmaya mı kararlısın? Sana karşı koyan güç nedir?\n\n## İlk Doğanlar\n\n- İlk Doğanlar efsaneye karıştı. Kimileri eski kabilelerin kalıntılarının hâlâ derin ormanlarda ya da yüksek dağlarda yaşadığını söyler. Çoğu, onların hiçbir zaman bir efsaneden öte olmadığına inanır.\n\n  __Görev Başlangıcı:__ İlk Doğanlar'a takıntılı biri, var olduklarına dair kanıt bulmak istiyor. Bu, Demir Diyarlar'ın uzak köşelerine bir sefer gerektirecek. Bu görevdeki rolün nedir?\n\n- İlk Doğanlar tecritte yaşar ve kendi topraklarını hararetle korur.\n\n  __Görev Başlangıcı:__ Kendi türünden dışlanan elf, Demir Diyar sakinleriyle yaşıyor. Zamanla topluluğun bir parçası oldu. Şimdi ölmek üzere. Ölmeden önce kendi halkına dönmeye can atıyor. Bağışlanma mı arıyor, adalet mi? Ona yardım etmeye neden ant içiyorsun? Dönüşüne karşı koyan güç nedir?\n\n- İlk Doğanlar, Demir Diyarlar'da söz sahibidir. Derin ormanların elfleri ve tepelerin devleri bize katlanıyor, hatta bizimle ticaret bile yapıyor — şimdilik. Demir Diyar sakinleri, artık burada hoş karşılanmadığımıza karar verecekleri günden korkar.\n\n  __Görev Başlangıcı:__ İnsanlar ve devler bir savaşın eşiğinde. Ne oldu? Kimin tarafını tutacaksın? Durumu yatıştırmak için bir şey yapılabilir mi?\n\n## Yaratıklar\n\n- Eski zamanların yaratıkları efsaneden başka bir şey değildir. Derin ormanlara ve yüksek dağlara yolculuk eden birkaç kişi, canavar yaratıklara dair çılgın hikâyelerle döner, ama açıkça akıllarını yitirmişlerdir. Öyle şeyler yoktur.\n\n  __Görev Başlangıcı:__ Canavar boyutlarda bir hayvan olduğunu sandığın bir şeyin saldırısına tanık oldun. Kimse sana inanmıyor. Hatta bu yaratığın üstüne attığın cinayetle suçlanıyorsun. Masumiyetini nasıl kanıtlayabilirsin? Olaya dair kendi anılarına bile güvenebilir misin?"
	},
	{
		"page": 129,
		"img": "/rulebook/dunyan/p129.webp",
		"title_en": "Beasts (cont.) · Horrors",
		"title_tr": "Yaratıklar (devam) · Korkular",
		"text_en": "- Monstrous beasts stalk the wild areas of the Ironlands.\n\n  __Quest Starter:__ A prominent Ironlander is consumed with the need to bring vengeance upon a specific beast. What makes this creature distinctive? How did it earn the wrath of this Ironlander? Do you aid this person in their quest, or act to prevent their blind hate from destroying more than just the beast?\n\n- Beasts of all sorts roam the Ironlands. They dwell primarily in the reaches, but range into the settled lands to hunt. There, they often prey on cattle, but attacks on travelers, caravans, or even settlements are not uncommon.\n\n  __Quest Starter:__ Professional slayers earn their keep by killing beasts. This particular slayer, famed throughout the Ironlands for her numerous kills, has gone missing on a hunt. Did she finally meet her match, or is something more nefarious at play. What is your connection to her?\n\n## Horrors\n\n- Nothing but stories to frighten children.\n\n  __Quest Starter:__ The murders began last season. Local gossip suggests they are the work of a vengeful horror, but there may be more mundane forces at work. What is your connection to these killings? What will you do to stop them?\n\n- We are wary of dark forests and deep waterways, for monsters lurk in those places. In the depths of the long-night, when all is wreathed in darkness, only fools venture beyond their homes.\n\n  __Quest Starter:__ You bear the scars of an attack by a horror. What was it? Are those scars physical, emotional, or both? How do you seek to make yourself whole again?\n\n- The dead do not rest in the Ironlands. At night we light torches, scatter salt, and post sentries at the gate. It is not enough. They are coming.\n\n  __Quest Starter:__ A group of Ironlanders establish a settlement in a territory cursed by a malevolent horror. What evil plagues this land? Why are the Ironlanders so intent on settling here? Will you aid them, or attempt to force them to give up this foolish undertaking?",
		"text_tr": "- Canavar yaratıklar, Demir Diyarlar'ın vahşi bölgelerinde sinsice dolaşır.\n\n  __Görev Başlangıcı:__ Tanınmış bir Demir Diyar sakini, belirli bir yaratıktan intikam alma ihtiyacıyla yanıp tutuşuyor. Bu yaratığı ayırt edici kılan nedir? Bu Demir Diyar sakininin gazabını nasıl üstüne çekti? Bu kişiye göreviyle yardım eder misin, yoksa kör nefretinin yaratıktan fazlasını yok etmesini önlemek için mi davranırsın?\n\n- Her türden yaratık, Demir Diyarlar'da dolaşır. Çoğunlukla uçtaki vahşi topraklarda yaşar, ama avlanmak için yerleşik topraklara da uzanırlar. Orada genellikle sığırlara saldırırlar, ama gezginlere, kervanlara, hatta yerleşimlere yönelik saldırılar da ender değildir.\n\n  __Görev Başlangıcı:__ Profesyonel canavar avcıları, yaratıkları öldürerek geçimlerini sağlar. Sayısız avıyla Demir Diyarlar boyunca ün salmış bu canavar avcısı, bir avda kayboldu. Sonunda dengiyle mi karşılaştı, yoksa daha alçakça bir şey mi söz konusu? Onunla bağın nedir?\n\n## Korkular\n\n- Çocukları korkutmak için anlatılan hikâyelerden başka bir şey değil.\n\n  __Görev Başlangıcı:__ Cinayetler geçen mevsim başladı. Yöre dedikoduları bunların intikamcı bir korkunun işi olduğunu söylüyor, ama daha sıradan güçler de iş başında olabilir. Bu cinayetlerle bağın nedir? Onları durdurmak için ne yapacaksın?\n\n- Karanlık ormanlardan ve derin su yollarından sakınırız, çünkü o yerlerde canavarlar pusuda bekler. Uzun gecenin derinliklerinde, her şey karanlığa sarınmışken, ancak ahmaklar evlerinin dışına çıkmaya cüret eder.\n\n  __Görev Başlangıcı:__ Bir korkunun saldırısından kalma yaralar taşıyorsun. Neydi o? O yaralar bedensel mi, ruhsal mı, yoksa ikisi de mi? Kendini yeniden bütün kılmaya nasıl çalışıyorsun?\n\n- Demir Diyarlar'da ölüler huzur bulmaz. Geceleri meşaleler yakar, tuz serper ve kapıya nöbetçiler dikeriz. Yetmiyor. Geliyorlar.\n\n  __Görev Başlangıcı:__ Bir grup Demir Diyar sakini, kötücül bir korkunun lanetlediği bir bölgede yerleşim kuruyor. Bu diyarı hangi kötülük kasıp kavuruyor? Demir Diyar sakinleri buraya yerleşmeye neden bu kadar kararlı? Onlara yardım mı edersin, yoksa bu akılsız girişimden vazgeçmeye onları zorlamaya mı çalışırsın?"
	},
	{
		"page": 130,
		"img": "/rulebook/dunyan/p130.webp",
		"title_en": "Mapping Your Journeys",
		"title_tr": "Yolculuklarını Haritalamak",
		"text_en": "## Mapping Your Journeys\n\nTo keep track of the details of your world, download the blank Ironlands map at ironswornrpg.com. Then, use a separate sheet, index cards, or a journal to create a key for the locations on your map.\n\nIndex cards work great. They give you space for a reasonable amount of information for a region or location, and it's quick and easy to dig through them to find details on-demand. Just mark the index card with a number, and mark that same number in the proper location on your Ironlands map. If you store your index cards in order, clipped to your map, it'll take all of a couple of seconds to remind yourself, \"What was the name of that village in the Hinterlands?\"\n\nYou can even use these index cards for random events. Need to know where the raiders are headed? Shuffle your index cards, turn them face down, and draw one.\n\nDon't worry about the details here. Not everything you encounter needs to be marked on the map or recorded. Focus on the people and places important to your story. Don't fuss with distances or exact positioning. There are no extra points awarded for neatness. That said, if you really enjoy detailed maps and recording your journeys, feel free to do so in whatever form works best for you.\n\nIf you're using your own map for the Ironlands or playing in a different setting altogether, you can manage the details however you like.",
		"text_tr": "## Yolculuklarını Haritalamak\n\nDünyanın ayrıntılarını takip etmek için ironswornrpg.com adresinden boş Demir Diyarlar haritasını indir. Sonra, haritandaki konumlar için bir anahtar oluşturmak üzere ayrı bir kâğıt, fiş kartları ya da bir günlük kullan.\n\nFiş kartları harika işe yarar. Bir bölge ya da konum için makul miktarda bilgiye yer açarlar ve istediğinde ayrıntıları bulmak için aralarını karıştırmak hızlı ve kolaydır. Fiş kartını bir sayıyla işaretlemen ve aynı sayıyı Demir Diyarlar haritandaki uygun konuma yazman yeter. Fiş kartlarını sırayla, haritana iliştirilmiş halde saklarsan, \"Ardtopraklar'daki o köyün adı neydi?\" diye kendine hatırlatman topu topu birkaç saniye sürer.\n\nBu fiş kartlarını rastgele olaylar için bile kullanabilirsin. Yağmacıların nereye gittiğini bilmen mi gerek? Fiş kartlarını karıştır, yüzlerini aşağı çevir ve bir tane çek.\n\nBuradaki ayrıntılara takılma. Karşılaştığın her şeyin haritada işaretlenmesi ya da kaydedilmesi gerekmez. Hikâyen için önemli olan insanlara ve yerlere odaklan. Mesafelerle ya da tam konumlandırmayla uğraşma. Düzenlilik için fazladan puan verilmez. Yine de, ayrıntılı haritalardan ve yolculuklarını kaydetmekten gerçekten keyif alıyorsan, sana en iyi gelen biçimde bunu yapmakta özgürsün.\n\nDemir Diyarlar için kendi haritanı kullanıyorsan ya da büsbütün farklı bir dünyada oynuyorsan, ayrıntıları dilediğin gibi yönetebilirsin."
	},
	{
		"page": 131,
		"img": "/rulebook/dunyan/p131.webp",
		"title_en": "Mapping Your Journeys (Example)",
		"title_tr": "Yolculuklarını Haritalamak (Örnek)",
		"text_en": "When you record the details of a community, include a note for any bonds you share. In the example below, (B) is used to signify a bond. The index cards can also be used to keep track of related quests.\n\n__1. Raven's Bluff__\n\n- Large settlement on a rocky ridge\n- Features: Strong winds; precarious rope bridge\n- People: Jilan the Overseer (B)\n- Vow: Banish the vengeful Haunt\n\n__3. Cairnhome__\n\n- Lonely fishing village\n- Features: Rotting shipwrecks; stacked stones for each of the lost\n- People: Thorsten the sea captain (B); Val the Raider (enemy)",
		"text_tr": "Bir topluluğun ayrıntılarını kaydederken, paylaştığın bağlar için bir not da ekle. Aşağıdaki örnekte, bir bağı belirtmek için (B) kullanılmıştır. Fiş kartları, ilgili görevleri takip etmek için de kullanılabilir.\n\n__1. Kuzgun Yarı__\n\n- Kayalık bir sırt üzerinde büyük yerleşim\n- Özellikler: Güçlü rüzgârlar; tekinsiz halat köprü\n- İnsanlar: Gözetici Jilan (B)\n- Ant: İntikamcı Tayf'ı sür\n\n__3. Yığıntepe__\n\n- Issız balıkçı köyü\n- Özellikler: Çürüyen gemi enkazları; yitirilen her kişi için yığılmış taşlar\n- İnsanlar: Deniz kaptanı Thorsten (B); Yağmacı Val (düşman)"
	}
];
