// Otomatik üretildi: Ironsworn Bölüm 5 "Foes & Encounters" (PDF s.144–173) sayfa-sayfa.
// Görseller static/rulebook/dusmanlar/*.webp; çeviri /ceviri (Opus, glossary).
import type { RulebookPage } from './types.js';

export const dusmanlarPages: RulebookPage[] = [
	{
		"page": 133,
		"img": "/rulebook/dusmanlar/p133.webp",
		"title_en": "NPCs in the Ironlands",
		"title_tr": "Demir Diyarlar'da OYK'lar",
		"text_en": "## NPCs in the Ironlands\n\nAn NPC (non-player character/creature) is anyone who inhabits your version of the Ironlands other than your character and those portrayed by your fellow players. They can be a person, being or creature. You will roleplay your interactions with NPCs, and make moves when you attempt to influence them, aid them, gain their help, or act against them.\n\nThis chapter includes a variety of sample NPCs, organized by category.\n\n- The Ironlanders are the humans who have settled these lands.\n- The Firstborn are beings who walked the Ironlands uncountable years before humans arrived.\n- Animals are common creatures.\n- Beasts are monstrous creatures of unusual size and cunning.\n- Horrors are supernatural beings.\n\nThese NPCs are a starting place. Use what fits your version of the Ironlands, keeping in mind the choices you made when you defined the characteristics of your setting in the previous chapter. If your world is entirely human-centric, ignore any fantastical NPCs. If you want to boost the fantasy in your campaign, you can emphasize the unreal or monstrous.\n\nUse what you like. Discard what you don't. Create what is missing. It's your world.\n\n## Components of an NPC\n\nBecause gameplay in *Ironsworn* is centered on the abilities and actions of your character, NPCs are primarily represented through your fiction rather than mechanics. They don't have stats, assets, or tracks. Instead, the sample NPCs in this chapter include some broad details to help guide their actions and the threat they pose in combat.\n\nWhen you interact with an NPC, envision their personality and motivations. A brutish character leverages their strength, or attempts to bully and intimidate. A sly character acts through manipulation or trickery. A noble character behaves according to their sense of honor. An animal, depending on its disposition, may attack when threatened or may run away. A supernatural being may act with mindless malice and hate for the living, or may have more complex needs. When you are unsure of an NPC's traits or next action, Ask the Oracle. Then, envision what they do and make moves to aid or oppose them as appropriate.",
		"text_tr": "## Demir Diyarlar'da OYK'lar\n\nBir OYK (Oyuncu Yönetmeyen Karakter/yaratık), senin karakterin ve diğer oyuncuların canlandırdıkları dışında, senin Demir Diyarlar (The Ironlands) sürümünde yaşayan herkestir. Bir insan, bir varlık ya da bir yaratık olabilir. OYK'larla etkileşimlerini rol yaparak canlandırır; onları etkilemeye, onlara yardım etmeye, yardımlarını almaya ya da onlara karşı hareket etmeye çalışırken hamleler yaparsın.\n\nBu bölüm, kategorilere göre düzenlenmiş çeşitli örnek OYK'lar içerir.\n\n- Demir Diyar sakinleri (Ironlanders), bu topraklara yerleşmiş insanlardır.\n- İlk Doğanlar (Firstborn), insanlar gelmeden sayısız yıl önce Demir Diyarlar'da yürüyen varlıklardır.\n- Hayvanlar, sıradan yaratıklardır.\n- Canavarlar, olağandışı boyutta ve kurnazlıkta canavarsı yaratıklardır.\n- Dehşetler, doğaüstü varlıklardır.\n\nBu OYK'lar bir başlangıç noktasıdır. Demir Diyarlar'ın senin sürümüne uyanı kullan; önceki bölümde dünyanın özelliklerini tanımlarken yaptığın seçimleri akılda tut. Dünyan tamamen insan merkezliyse, fantastik OYK'ları görmezden gel. Seferinde fantastik öğeyi güçlendirmek istiyorsan, gerçeküstü ya da canavarsı olanı öne çıkarabilirsin.\n\nİstediğini kullan. İstemediğini bir kenara at. Eksik olanı yarat. Bu senin dünyan.\n\n## Bir OYK'nın Bileşenleri\n\n*Ironsworn*'de oyun, senin karakterinin yetenekleri ve eylemleri etrafında döndüğünden, OYK'lar mekanikten çok kurgunla temsil edilir. Statları, Yetenek Kartları (Asset) ya da izleri yoktur. Bunun yerine, bu bölümdeki örnek OYK'lar, eylemlerine ve savaşta oluşturdukları tehdide yön vermene yardımcı olacak bazı genel ayrıntılar içerir.\n\nBir OYK'yla etkileşime girdiğinde, onun kişiliğini ve güdülerini gözünde canlandır. Kaba bir karakter gücüne yaslanır ya da gözdağı verip sindirmeye çalışır. Sinsi bir karakter manipülasyon ya da hileyle hareket eder. Soylu bir karakter onur anlayışına göre davranır. Bir hayvan, mizacına bağlı olarak tehdit edildiğinde saldırabilir ya da kaçabilir. Doğaüstü bir varlık, yaşayanlara karşı akılsızca bir kin ve nefretle hareket edebilir ya da daha karmaşık ihtiyaçları olabilir. Bir OYK'nın özelliklerinden ya da sıradaki eyleminden emin değilsen, Kehanetin Sesini Dinle. Ardından, ne yaptıklarını gözünde canlandır ve duruma göre onlara yardım etmek ya da karşı koymak için hamleler yap."
	},
	{
		"page": 134,
		"img": "/rulebook/dusmanlar/p134.webp",
		"title_en": "Rank",
		"title_tr": "Derece",
		"text_en": "## Rank\n\nNPCs have a single mechanical attribute, their rank. From this, their ability to resist and inflict harm (page 19) in combat is derived, as follows:\n\n- __Troublesome__ — Common enemies. 3 progress per harm. Inflicts 1 harm.\n- __Dangerous__ — Capable fighters and deadly creatures. 2 progress per harm. Inflicts 2 harm.\n- __Formidable__ — Exceptional fighters and mighty creatures. 1 progress per harm. Inflicts 3 harm.\n- __Extreme__ — Foes of overwhelming skill or power. 2 ticks per harm. Inflicts 4 harm.\n- __Epic__ — Legendary foes of mythic power. 1 tick per harm. Inflicts 5 harm.\n\nWhen you engage a foe in combat, give them a standard progress track (10 boxes). When you Strike or Clash and inflict harm, mark progress for each point of harm based on the foe's rank. For example, you mark 2 ticks for each point of harm inflicted on an extreme foe, and 2 progress (2 full boxes) for each point of harm against a dangerous foe.\n\nWhen you fail to defend against a foe's attack and face physical harm, you make the Endure Harm move (page 91). As part of that move, you reduce your health track by the amount of harm your foe inflicts, per their rank. If appropriate to the NPC, they can also inflict stress (page 20) equal to their rank when you fail to resist an action which frightens, demoralizes, or rattles you.\n\nUse the End the Fight move (page 82), adding your progress against this foe, when you attempt to resolve the combat. To learn more about progress, see page 14.\n\nThe ranks for the sample NPCs in this chapter represent a typical individual of that type. For unusually powerful NPCs, increase their rank by one (to a maximum of epic). For less powerful foes, decrease their rank by one (to a minimum of troublesome). You can also adjust the rank of a foe when circumstances give you significant narrative disadvantage or advantage before the fight. See page 208 for more on adjusting challenge ranks.",
		"text_tr": "## Derece\n\nOYK'ların tek bir mekanik niteliği vardır: dereceleri (rank). Bundan, savaşta hasara (page 19) direnme ve hasar verme kabiliyetleri şu şekilde türetilir:\n\n- __Sıradan (Troublesome)__ — Sıradan düşmanlar. Hasar başına 3 İlerleme. 1 Hasar verir.\n- __Tehlikeli (Dangerous)__ — Yetkin dövüşçüler ve ölümcül yaratıklar. Hasar başına 2 İlerleme. 2 Hasar verir.\n- __Zorlu (Formidable)__ — Olağanüstü dövüşçüler ve güçlü yaratıklar. Hasar başına 1 İlerleme. 3 Hasar verir.\n- __Aşırı (Extreme)__ — Ezici beceri ya da güce sahip düşmanlar. Hasar başına 2 çentik. 4 Hasar verir.\n- __Destansı (Epic)__ — Efsanevi, mitik güçte düşmanlar. Hasar başına 1 çentik. 5 Hasar verir.\n\nBir düşmanla savaşa tutuştuğunda, ona standart bir İlerleme İzi (Progress Track) ver (10 kutu). Saldır (Strike) ya da Çatış (Clash) hamlesini yapıp hasar verdiğinde, düşmanın derecesine göre verdiğin her hasar puanı için İlerleme işaretle. Örneğin, aşırı bir düşmana verdiğin her hasar puanı için 2 çentik; tehlikeli bir düşmana verdiğin her hasar puanı için 2 İlerleme (2 dolu kutu) işaretlersin.\n\nBir düşmanın saldırısına karşı kendini savunamayıp fiziksel hasarla yüzleştiğinde, Hasara Katlan (Endure Harm) hamlesini (page 91) yaparsın. O hamlenin bir parçası olarak, can (health) izini düşmanının derecesine göre verdiği hasar kadar azaltırsın. OYK'ya uygun düşüyorsa, seni korkutan, moralini bozan ya da sarsan bir eyleme direnemediğinde, derecesi kadar stres (page 20) de verebilir.\n\nSavaşı çözmeye çalışırken, Savaşı Bitir (End the Fight) hamlesini (page 82) kullan ve bu düşmana karşı kaydettiğin İlerlemeyi ekle. İlerleme hakkında daha fazla bilgi için sayfa 14'e bak.\n\nBu bölümdeki örnek OYK'ların dereceleri, o türün tipik bir bireyini temsil eder. Olağandışı güçlü OYK'lar için derecelerini bir kademe artır (en fazla destansıya kadar). Daha zayıf düşmanlar için derecelerini bir kademe azalt (en az sıradana kadar). Ayrıca, dövüşten önce koşullar sana önemli ölçüde anlatısal dezavantaj ya da avantaj sağladığında, bir düşmanın derecesini ayarlayabilirsin. Zorluk derecelerini ayarlamak hakkında daha fazlası için sayfa 208'e bak."
	},
	{
		"page": 135,
		"img": "/rulebook/dusmanlar/p135.webp",
		"title_en": "Features, Drives, Tactics & Quest Starters",
		"title_tr": "Özellikler, Güdüler, Taktikler ve Görev Başlangıçları",
		"text_en": "## Features\n\nThese are the typical characteristics of appearance and personality for an NPC. They are not universally true, especially within diverse societies such as Ironlanders and the firstborn, but can provide some common impressions as a starting point.\n\n## Drives\n\nDrives reflect the motivations and instincts of an NPC. For creatures, these are relatively simple: Hunt, eat, defend territory. For intelligent beings, drives are the typical goals and beliefs of their society, but do not represent the complex range of motivations you will encounter. Drives are a starting place, giving you the rough outline of a typical NPC to be fleshed out (or contradicted) appropriate to their role in the fiction.\n\nNPCs who are prominent in your campaign will have more detail. Depending on their role in your story, their drives may support—or conflict with—your own goals. As you discover details about an important NPC, make note of it. Look for opportunities to introduce interesting and surprising backstories and motivations for these characters.\n\n## Tactics\n\nTactics provide a reference for how an NPC might act in combat. These give you a sense of typical maneuvers, but do not represent the possibilities of a complex and dramatic combat scene. You should let NPC actions flow out of the fiction. What is the situation? What is their goal? What will add to the excitement and danger of this moment? Make it happen. When in doubt, Ask the Oracle.\n\nYour foes should do more than simply try to inflict harm. A fearsome roar or demoralizing boast might cause you to Endure Stress. Tactical maneuvers reduce your momentum. Fictional complications—the appearance of new foes, putting companions or allies at risk, or a realization that undermines your quest—will heighten the drama of the scene.\n\n## Quest Starter\n\nAll NPCs include a quest starter, which can serve as inspiration for one of your vows.\n\n## Your Truth\n\nSome NPCs include a question for you to answer. This is an opportunity to customize the NPC to your vision of the Ironlands. You can do this as you define your world or discover through play. Truths may represent an absolute fact, or merely something the people of your world believe.",
		"text_tr": "## Özellikler\n\nBunlar, bir OYK'nın görünüş ve kişilik açısından tipik nitelikleridir. Özellikle Demir Diyar sakinleri ve İlk Doğanlar gibi çeşitlilik gösteren toplumlarda evrensel olarak doğru değildirler; ancak başlangıç noktası olarak ortak izlenimler sunabilirler.\n\n## Güdüler\n\nGüdüler, bir OYK'nın güdülerini ve içgüdülerini yansıtır. Yaratıklar için bunlar görece basittir: Avlanmak, yemek, bölgeyi savunmak. Zeki varlıklar içinse güdüler, toplumlarının tipik amaçları ve inançlarıdır; fakat karşılaşacağın karmaşık güdü yelpazesini temsil etmez. Güdüler bir başlangıç noktasıdır; sana kurgudaki rolüne göre etiyle kemiğiyle dolduracağın (ya da aksini kuracağın) tipik bir OYK'nın kaba taslağını verir.\n\nSeferinde öne çıkan OYK'lar daha ayrıntılı olacaktır. Hikâyendeki rollerine bağlı olarak, güdüleri senin kendi amaçlarını destekleyebilir ya da onlarla çatışabilir. Önemli bir OYK hakkında ayrıntılar keşfettikçe, bunları not al. Bu karakterler için ilginç ve şaşırtıcı geçmişler ve güdüler katmak için fırsatlar kolla.\n\n## Taktikler\n\nTaktikler, bir OYK'nın savaşta nasıl davranabileceğine dair bir başvuru sunar. Bunlar sana tipik manevralara dair bir fikir verir; ancak karmaşık ve dramatik bir savaş sahnesinin olasılıklarını temsil etmez. OYK eylemlerinin kurgudan doğmasına izin vermelisin. Durum nedir? Amaçları ne? Bu ânın heyecanına ve tehlikesine ne katar? Onu gerçekleştir. Tereddütteysen, Kehanetin Sesini Dinle.\n\nDüşmanların yalnızca hasar vermeye çalışmaktan fazlasını yapmalı. Ürkütücü bir kükreme ya da moral bozucu bir övünme seni Strese Katlan'maya zorlayabilir. Taktik manevralar Momentum'unu düşürür. Kurgusal karmaşalar — yeni düşmanların belirmesi, yoldaşlarının ya da müttefiklerinin tehlikeye girmesi ya da görevini sarsan bir farkındalık — sahnenin dramını yükseltir.\n\n## Görev Başlangıcı\n\nTüm OYK'lar, antlarından biri için ilham kaynağı olabilecek bir Görev Başlangıcı (Quest Starter) içerir.\n\n## Senin Hakikatin\n\nKimi OYK'lar, yanıtlaman için bir soru içerir. Bu, OYK'yı Demir Diyarlar'a dair kendi vizyonuna göre özelleştirme fırsatıdır. Bunu dünyanı tanımlarken yapabilir ya da oyun boyunca keşfedebilirsin. Hakikatler mutlak bir gerçeği temsil edebilir ya da yalnızca dünyandaki insanların inandığı bir şey olabilir."
	},
	{
		"page": 136,
		"img": "/rulebook/dusmanlar/p136.webp",
		"title_en": "NPC Packs & Joining Forces with NPCs",
		"title_tr": "OYK Sürüleri ve OYK'larla Güç Birliği",
		"text_en": "## NPC Packs\n\nWhen you fight a group of troublesome or dangerous foes, you may combine them into a single progress track. This is called a pack. It's more convenient than tracking progress for each individual foe, and the scene will move faster.\n\nWhen you group foes into a pack, increase their rank to represent their combined ability to inflict and resist harm. For a small pack (about 3 to 5), increase the rank by one. For a large pack (about 6 to 10) increase the rank by two. For example, a pack of 4 troublesome foes are treated as a single dangerous foe. If you are facing more than 10 troublesome or dangerous foes, you can group them into smaller packs and associated progress tracks.\n\nWhen you inflict harm on the pack, you can envision it as appropriate to the fiction. You might wound them, put one or more of them out of action, or drive some back. When you successfully End the Fight, you have defeated the last of them, or broken their fighting spirit.\n\nFormidable, extreme, and epic foes may not be grouped into a pack. Each must have its own progress track.\n\n## Joining Forces with NPCs\n\nIf your story leads you to cooperating with helper NPCs to overcome challenges, you need to consider how they impact the fiction and your moves. NPCs—unless they are a companion asset (page 39)—won't give you mechanical bonuses on your moves. They also won't make moves of their own. They are simply a part of your story, perhaps impacting the moves you make, the results of those moves, and the rank of your challenges. Gaining the aid of an important NPC might also allow you to Reach a Milestone (page 100).\n\nFor example:\n\n- If you are charged with protecting NPCs, they might be placed in danger or suffer losses as a result of your failures on moves.\n- If you are fighting alongside NPCs, you can reduce the rank of your foes. For example, battling alone against a large pack of raiders might be an extreme challenge. If you are aided by a stalwart band of villagers, you could shift the enemies' rank to formidable.\n- If you are being led by an experienced scout, you might choose to skip the Undertake a Journey move, or reduce the rank of the journey.",
		"text_tr": "## OYK Sürüleri\n\nBir grup sıradan ya da tehlikeli düşmanla dövüştüğünde, onları tek bir İlerleme İzi'nde birleştirebilirsin. Buna sürü (pack) denir. Her bir düşman için ayrı İlerleme tutmaktan daha kullanışlıdır ve sahne daha hızlı ilerler.\n\nDüşmanları bir sürüde topladığında, hasar verme ve hasara direnme kabiliyetlerinin birleşimini temsil etmek için derecelerini artır. Küçük bir sürü için (yaklaşık 3 ila 5) dereceyi bir kademe artır. Büyük bir sürü için (yaklaşık 6 ila 10) dereceyi iki kademe artır. Örneğin, 4 sıradan düşmandan oluşan bir sürü, tek bir tehlikeli düşman gibi ele alınır. 10'dan fazla sıradan ya da tehlikeli düşmanla karşı karşıyaysan, onları daha küçük sürülere ve bunlara bağlı İlerleme İzleri'ne bölebilirsin.\n\nSürüye hasar verdiğinde, bunu kurguya uygun biçimde gözünde canlandırabilirsin. Onları yaralayabilir, bir ya da birkaçını saf dışı bırakabilir ya da bir kısmını geri püskürtebilirsin. Savaşı Bitir hamlesini başarıyla yaptığında, sonuncularını da alt etmiş ya da dövüşme azimlerini kırmışsındır.\n\nZorlu, aşırı ve destansı düşmanlar bir sürüde toplanamaz. Her birinin kendi İlerleme İzi olmalıdır.\n\n## OYK'larla Güç Birliği\n\nHikâyen seni, güçlükleri aşmak için yardımcı OYK'larla iş birliği yapmaya götürürse, onların kurguyu ve hamlelerini nasıl etkilediğini düşünmen gerekir. OYK'lar — bir yoldaş Yetenek Kartı (page 39) olmadıkça — hamlelerinde sana mekanik bonus vermez. Kendi hamlelerini de yapmazlar. Onlar yalnızca hikâyenin bir parçasıdır; belki yaptığın hamleleri, o hamlelerin sonuçlarını ve güçlüklerinin derecesini etkilerler. Önemli bir OYK'nın yardımını almak, ayrıca Bir Dönüm Noktasına Ulaş (page 100) hamlesini yapmana da olanak tanıyabilir.\n\nÖrneğin:\n\n- OYK'ları korumakla görevliysen, hamlelerindeki başarısızlıkların sonucunda tehlikeye girebilir ya da kayıp verebilirler.\n- OYK'ların yanında dövüşüyorsan, düşmanlarının derecesini düşürebilirsin. Örneğin, büyük bir yağmacı sürüsüne tek başına karşı koymak aşırı bir güçlük olabilir. Yiğit bir köylü bölüğü sana yardım ederse, düşmanların derecesini zorluya kaydırabilirsin.\n- Deneyimli bir izciye yol gösteriyorsa, Yolculuğa Çık hamlesini atlamayı ya da yolculuğun derecesini düşürmeyi seçebilirsin."
	},
	{
		"page": 137,
		"img": "/rulebook/dusmanlar/p137.webp",
		"title_en": "Creating NPCs",
		"title_tr": "OYK Yaratmak",
		"text_en": "- If an NPC leader agrees to support your quest by allowing passage through contested lands, you might Reach a Milestone and mark progress.\n\nAs with any NPC, you can Ask the Oracle to see how a helper NPC responds, how they fare in a challenge, or what they do next. You can make moves to influence them, such as Compel. If you develop a strong relationship through your story, or if you Fulfill Your Vow in their service, you can choose to Forge a Bond.\n\nIn short, make them characters, not numbers. Give them personalities. Give them quirks and motivations. Let them impact your story and your quests, for better or worse, but always keep the focus on your character and your allies.\n\n## Creating NPCs\n\nYou should create NPCs that fit your version of the Ironlands, enhance your story, and enrich your character's adventures. Use the sample NPCs as a starting place, or start from scratch. Because NPCs don't have mechanical detail, it's easy to bring them to life without advance preparation.\n\nIf you face an NPC in combat, give them a rank. If you like, you can also make note of their drives and tactics. Otherwise, their motivations, abilities, and actions are entirely part of your fiction. They may ignore you, aid you, or oppose you. Make moves to resolve your intentions with them as appropriate. Springboard off those moves with new details and complications to flesh out these characters.\n\nFor reoccurring NPCs, make note of what you learn of them over time. If you share a bond, mark it down.",
		"text_tr": "- Bir OYK lideri, tartışmalı topraklardan geçişe izin vererek görevini desteklemeyi kabul ederse, Bir Dönüm Noktasına Ulaş hamlesini yapıp İlerleme işaretleyebilirsin.\n\nHer OYK'da olduğu gibi, yardımcı bir OYK'nın nasıl karşılık verdiğini, bir güçlükte nasıl başa çıktığını ya da sıradaki eyleminin ne olduğunu görmek için Kehanetin Sesini Dinleyebilirsin. Onları etkilemek için İkna Et gibi hamleler yapabilirsin. Hikâyen boyunca güçlü bir ilişki geliştirirsen ya da onların hizmetinde Antını Tamamlarsan, Bağ Kurmayı seçebilirsin.\n\nKısacası, onları sayı değil, karakter yap. Onlara kişilikler ver. Onlara kendine has özellikler ve güdüler ver. İyisiyle kötüsüyle, hikâyeni ve görevlerini etkilemelerine izin ver; ama odağı her zaman kendi karakterinde ve müttefiklerinde tut.\n\n## OYK Yaratmak\n\nDemir Diyarlar'ın senin sürümüne uyan, hikâyeni güçlendiren ve karakterinin maceralarını zenginleştiren OYK'lar yaratmalısın. Örnek OYK'ları bir başlangıç noktası olarak kullan ya da sıfırdan başla. OYK'ların mekanik ayrıntısı olmadığından, önceden hazırlık yapmadan onları hayata geçirmek kolaydır.\n\nBir OYK'yla savaşta yüzleşirsen, ona bir derece ver. İstersen güdülerini ve taktiklerini de not edebilirsin. Bunun dışında, güdüleri, kabiliyetleri ve eylemleri tümüyle senin kurgunun parçasıdır. Seni görmezden gelebilir, sana yardım edebilir ya da sana karşı koyabilirler. Onlarla niyetlerini çözmek için duruma uygun hamleler yap. Bu karakterleri etiyle kemiğiyle doldurmak için, o hamlelerden yeni ayrıntılar ve karmaşalarla sıçra.\n\nYinelenen OYK'lar için, zamanla onlar hakkında öğrendiklerini not al. Bir bağ paylaşıyorsanız, bunu işaretle."
	},
	{
		"page": 138,
		"img": "/rulebook/dusmanlar/p138.webp",
		"title_en": "Ironlanders / Broken",
		"title_tr": "Demir Diyar Sakinleri / Yıkıklar",
		"text_en": "## Ironlanders\n\nIronlanders are the human inhabitants of these lands. Unless your story emphasizes adventures well outside of the settled regions, the majority of your interactions will be with fellow Ironlanders.\n\nThis section covers a few broad categories of Ironlanders. They are not representative of the variety of people and cultures in these lands. When you are forced to fight an Ironlander and need to determine their rank, you can Ask the Oracle, or follow these guidelines:\n\n- A common citizen or brute is troublesome.\n- A trained warrior is dangerous.\n- A powerful or veteran warrior is formidable.\n\n## Broken\n\n- __Rank:__ Troublesome (3 progress per harm; inflicts 1 harm)\n- __Features:__ Crazed eyes; painted skin; feral screams; scavenged clothing and weapons\n- __Drives:__ Show my power; share my pain\n- __Tactics:__ Spring from hiding; ferocious attacks\n\nAnother people sailed to the Ironlands from the Old World long before our kin settled here. Something happened. Something changed them. Whether it was the long struggle in a harsh land, the ravages of war, or the corruption of some dark force, they left their humanity behind and became what we call the broken. Now, they exist only to kill, to destroy.\n\nWe fear the broken for their savagery. But, more than this, we fear them as a dark portent of what we might one day become.\n\n__Quest Starter:__ Years ago, an Ironlander child was taken by a broken tribe. Now they are seen living among them. What is your connection to this person? Can they be brought home, or are they forever lost?",
		"text_tr": "## Demir Diyar Sakinleri\n\nDemir Diyar sakinleri (Ironlanders), bu toprakların insan halkıdır. Hikâyen, yerleşik bölgelerin epey dışındaki maceraları öne çıkarmadıkça, etkileşimlerinin çoğu hemcinslerin olan Demir Diyar sakinleriyle olacaktır.\n\nBu bölüm, Demir Diyar sakinlerinin birkaç geniş kategorisini ele alır. Bunlar, bu topraklardaki insan ve kültür çeşitliliğini temsil etmez. Bir Demir Diyar sakiniyle dövüşmek zorunda kalıp derecesini belirlemen gerektiğinde, Kehanetin Sesini Dinleyebilir ya da şu yönergeleri izleyebilirsin:\n\n- Sıradan bir yurttaş ya da kabadayı sıradandır.\n- Eğitimli bir savaşçı tehlikelidir.\n- Güçlü ya da kıdemli bir savaşçı zorludur.\n\n## Yıkıklar\n\n- __Derece:__ Sıradan (hasar başına 3 İlerleme; 1 hasar verir)\n- __Özellikler:__ Çılgın gözler; boyalı ten; vahşi çığlıklar; yağmadan toplanmış giysiler ve silahlar\n- __Güdüler:__ Gücümü göster; acımı paylaş\n- __Taktikler:__ Saklandığı yerden fırla; gözü dönmüş saldırılar\n\nBizim soyumuz buraya yerleşmeden çok önce, başka bir halk Eski Dünya'dan (The Old World) Demir Diyarlar'a yelken açtı. Bir şey oldu. Bir şey onları değiştirdi. İster sert bir toprakta verilen uzun mücadele, ister savaşın yıkımı, ister karanlık bir gücün yozlaştırması olsun, insanlıklarını geride bırakıp bizim Yıkıklar (Broken) dediğimiz şeye dönüştüler. Artık yalnızca öldürmek, yok etmek için varlar.\n\nYıkıklar'dan vahşetleri yüzünden korkarız. Ama bundan da fazlası, bir gün ne olabileceğimizin karanlık bir habercisi olarak korkarız onlardan.\n\n__Görev Başlangıcı:__ Yıllar önce, bir Demir Diyar sakini çocuk bir Yıkıklar kabilesince kaçırıldı. Şimdi onların arasında yaşarken görülüyor. Bu kişiyle bağın nedir? Evine geri getirilebilir mi, yoksa sonsuza dek kayıp mı?"
	},
	{
		"page": 139,
		"img": "/rulebook/dusmanlar/p139.webp",
		"title_en": "Common Folk / Hunter",
		"title_tr": "Sıradan Halk / Avcı",
		"text_en": "## Common Folk\n\n- __Rank:__ Troublesome (3 progress per harm; inflicts 1 harm)\n- __Traits:__ Diverse looks; weary and worried; suspicious of strangers\n- __Drives:__ Prepare for the winter; protect family\n- __Tactics:__ Desperate defense; stand together\n\nMost of us in the Ironlands are common folk. We are farmers, laborers, crafters, sailors, and traders. When trouble comes, we know which way the pointy end goes, and we stand together to protect our homes and kin.\n\n__Quest Starter:__ Two prominent families are at odds. What is the source of the conflict? What is your relationship to them? What danger threatens to destroy their community if they can't put aside their petty squabble?\n\n## Hunter\n\n- __Rank:__ Dangerous (2 progress per harm; inflicts 2 harm)\n- __Traits:__ Wearing hides and furs to ward away the cold; steely gaze; at home in the woodlands\n- __Drives:__ A clean kill; survive the hunt\n- __Tactics:__ Set traps; keep to the shadows; deadly shot\n\nHunters face brutal weather, difficult terrain, dangerous animals, and worse. Many never return from their hunts. Others return, but are forever changed.\n\n__Quest Starter:__ A hunter returns to her village, panic-stricken and pleading for help. The rest of her party is still out there. What happened to them?",
		"text_tr": "## Sıradan Halk\n\n- __Derece:__ Sıradan (hasar başına 3 İlerleme; 1 hasar verir)\n- __Hususiyetler:__ Çeşitli görünüşler; yorgun ve kaygılı; yabancılara karşı kuşkulu\n- __Güdüler:__ Kışa hazırlan; aileyi koru\n- __Taktikler:__ Çaresiz savunma; bir arada dur\n\nDemir Diyarlar'da çoğumuz sıradan halkız. Çiftçiyiz, emekçiyiz, zanaatkârız, denizciyiz, tüccarız. Bela kapıya dayandığında, sivri ucun hangi yöne gittiğini biliriz; evlerimizi ve soyumuzu korumak için bir arada dururuz.\n\n__Görev Başlangıcı:__ İki saygın aile birbirine düşmüş. Çekişmenin kaynağı nedir? Onlarla ilişkin ne? Bu küçük kavgayı bir kenara koyamazlarsa, topluluklarını yok etmekle tehdit eden tehlike nedir?\n\n## Avcı\n\n- __Derece:__ Tehlikeli (hasar başına 2 İlerleme; 2 hasar verir)\n- __Hususiyetler:__ Soğuğu savuşturmak için post ve kürk giyer; çelik gibi bakış; ormanlık arazide kendi evindedir\n- __Güdüler:__ Temiz bir av; avdan sağ çık\n- __Taktikler:__ Tuzak kur; gölgelerde kal; ölümcül atış\n\nAvcılar acımasız havaya, zorlu araziye, tehlikeli hayvanlara ve daha beterine göğüs gerer. Birçoğu avlarından hiç dönmez. Başkaları döner, ama sonsuza dek değişmiş olarak.\n\n__Görev Başlangıcı:__ Bir avcı kadın, panik içinde ve yardım için yalvararak köyüne döner. Tayfasının geri kalanı hâlâ dışarıda. Onlara ne oldu?"
	},
	{
		"page": 140,
		"img": "/rulebook/dusmanlar/p140.webp",
		"title_en": "Mystic / Raider",
		"title_tr": "Mistik / Yağmacı",
		"text_en": "## Mystic\n\n- __Rank:__ Dangerous (2 progress per harm; inflicts 2 harm)\n- __Features:__ Knowing eyes; tattooed skin\n- __Drives:__ Respect the old ways; seek the paths of power\n- __Tactics:__ Foresee the intent of my enemies; prepare rituals; use trickery\n\nSome say you can tell a mystic by looking them in the eye. They walk in two worlds, and their eyes shimmer with that dark reflection of realms beyond our own. We call it the sight. Some hold that darkness in check. Others are consumed by it.\n\n__Quest Starter:__ A mystic returns to their home after a years-long journey. They are changed. What new power or knowledge do now they wield? What do they seek to do with it? Why do you oppose them?\n\n## Raider\n\n- __Rank:__ Dangerous (2 progress per harm; inflicts 2 harm)\n- __Features:__ Geared for war; battle fervor\n- __Drives:__ What is theirs will be ours; stand with my kin; die a glorious death\n- __Tactics:__ Intimidate; shield wall; burn it down\n\nRaiders survive by seizing what they need from others. Our grain. Our meat. Our animals. Our iron. They'll take it all, and leave us facing the long winter with nothing to sustain us but prayers to indifferent gods.",
		"text_tr": "## Mistik\n\n- __Derece:__ Tehlikeli (hasar başına 2 İlerleme; 2 hasar verir)\n- __Özellikler:__ Her şeyi bilen gözler; dövmeli ten\n- __Güdüler:__ Eski yollara saygı göster; güç yollarını ara\n- __Taktikler:__ Düşmanlarımın niyetini önceden gör; ritüeller hazırla; hile kullan\n\nKimileri, bir mistiği (mystic) gözlerine bakarak anlayabileceğini söyler. İki dünyada birden yürürler ve gözleri, bizimkinin ötesindeki âlemlerin o karanlık yansımasıyla parıldar. Biz buna görü (sight) deriz. Kimisi o karanlığı dizginler. Kimisini ise o karanlık yutar.\n\n__Görev Başlangıcı:__ Bir mistik, yıllar süren bir yolculuğun ardından evine döner. Değişmiştir. Şimdi ne yeni güç ya da bilgiyi elinde tutuyor? Bununla ne yapmaya çalışıyor? Ona neden karşı koyuyorsun?\n\n## Yağmacı\n\n- __Derece:__ Tehlikeli (hasar başına 2 İlerleme; 2 hasar verir)\n- __Özellikler:__ Savaşa donanmış; savaş coşkusu\n- __Güdüler:__ Onların olan bizim olacak; soyumla yan yana dur; şanlı bir ölümle öl\n- __Taktikler:__ Gözdağı ver; kalkan duvarı; yakıp kül et\n\nYağmacılar (Raiders), ihtiyaç duyduklarını başkalarından zorla alarak hayatta kalır. Tahılımızı. Etimizi. Hayvanlarımızı. Demirimizi. Hepsini alır, bizi uzun kışla karşı karşıya bırakırlar; bizi ayakta tutacak, kayıtsız tanrılara edilen dualardan başka hiçbir şey kalmaz."
	},
	{
		"page": 141,
		"img": "/rulebook/dusmanlar/p141.webp",
		"title_en": "Raider (cont.) / Warrior",
		"title_tr": "Yağmacı (devam) / Savaşçı",
		"text_en": "__Quest Starter:__ You were raised as a raider, born to battle, but long ago left that life. Troubled by your past, you vow to wipe this powerful clan from the Ironlands. How can you defeat them? What will happen when you must face your former shield-kin?\n\n__Your Truth:__ A large raider clan is known and feared throughout the Ironlands. What is it called? Who leads it?\n\n## Warrior\n\n- __Rank:__ Dangerous (2 progress per harm; inflicts 2 harm)\n- __Traits:__ Battle-hardened; scarred\n- __Drives:__ The thrill of the fight; protect those in my charge; survive another day\n- __Tactics:__ Maneuver for advantage; find an opening\n\nSome Ironlanders, through strength of arms, set themselves apart from the common rabble. They are trained to fight, or simply born to it. For them, a sword, spear, or axe is as natural a tool as any hammer or spade.\n\n__Quest Starter:__ A legendary warrior, now well past their prime, swears to face a daunting foe in one final battle. What help do they ask of you and why? Who is their enemy?\n\n__Your Truth:__ Warrior's shields are often emblazoned with meaningful symbols. What are they? Family crests? Animal totems? Mystical sigils? Motifs honoring the nations of the Old World? If you carry a shield, what is painted on yours?",
		"text_tr": "__Görev Başlangıcı:__ Bir yağmacı olarak büyütüldün, savaşa doğdun, ama o hayatı çoktan geride bıraktın. Geçmişinden rahatsız, bu güçlü klanı Demir Diyarlar'dan silmeye ant içersin. Onları nasıl yenebilirsin? Eski kalkan-yoldaşlarınla yüzleşmek zorunda kaldığında ne olacak?\n\n__Senin Hakikatin:__ Büyük bir yağmacı klanı, Demir Diyarlar boyunca tanınır ve korkulur. Adı nedir? Onu kim yönetiyor?\n\n## Savaşçı\n\n- __Derece:__ Tehlikeli (hasar başına 2 İlerleme; 2 hasar verir)\n- __Hususiyetler:__ Savaşta çelikleşmiş; yara izli\n- __Güdüler:__ Dövüşün verdiği heyecan; sorumluluğumdakileri koru; bir gün daha hayatta kal\n- __Taktikler:__ Avantaj için manevra yap; bir açık bul\n\nKimi Demir Diyar sakinleri, silah gücüyle kendilerini sıradan ayaktakımından ayırır. Dövüşmek için eğitilmiş ya da düpedüz dövüşmek için doğmuşlardır. Onlar için kılıç, mızrak ya da balta; bir çekiç ya da kürek kadar doğal bir alettir.\n\n__Görev Başlangıcı:__ Efsanevi bir savaşçı, artık en parlak çağını çoktan geçmiş, son bir muharebede ürkütücü bir düşmanla yüzleşmeye ant içer. Senden ne yardım istiyor ve neden? Düşmanı kim?\n\n__Senin Hakikatin:__ Savaşçıların kalkanları çoğu kez anlamlı simgelerle bezenir. Bunlar nedir? Aile armaları mı? Hayvan totemleri mi? Mistik mühürler mi? Eski Dünya'nın uluslarını onurlandıran motifler mi? Eğer bir kalkan taşıyorsan, üzerinde ne resmedilmiş?"
	},
	{
		"page": 142,
		"img": "/rulebook/dusmanlar/p142.webp",
		"title_en": "Firstborn / Elf",
		"title_tr": "İlk Doğanlar / Elf",
		"text_en": "## Firstborn\n\nThe firstborn lived here long before the humans landed on these shores. The humans, in their arrogance, named this peninsula the Ironlands and called themselves Ironlanders—but the firstborn gave it names of their own in a time beyond the reach of memory.\n\nTo determine the role of the firstborn in your setting, see page 128.\n\n## Elf\n\n- __Rank:__ Dangerous (2 progress per harm; inflicts 2 harm)\n- __Features:__ Large, luminous eyes seen through a wooden mask; gray-green skin the texture of dry leaves; sonorous voice; wielding bow and spear\n- __Drives:__ Protect the wilds; drive out trespassers, or see them pay\n- __Tactics:__ Strike from shadow; force their surrender; turn the forest against them\n\nElves are strange beings of the forest, seldom seen beyond the ancient woods of the Deep Wilds. They are fiercely protective of their lands and suspicious of humans. Their scouts patrol the borderlands, riding the fearsome mounts we call gaunts (page 148). Others of their kind watch us from the shadow of the deep woods, spears and bow at the ready. Some say elven mystics can bind the animals and beasts of the forest to aid in the defense of the Wilds.\n\nA few warn that the elves are biding their time, readying the attack which will drive us from these lands.\n\n__Quest Starter:__ The leader of an Ironlander community seeks an audience with the elves. For what purpose? Why are you compelled to help?\n\n__Your Truth:__ Elves conceal their faces behind ornate wooden masks. What do these masks signify?",
		"text_tr": "## İlk Doğanlar\n\nİlk Doğanlar (Firstborn), insanlar bu kıyılara ayak basmadan çok önce burada yaşıyordu. İnsanlar kibirleriyle bu yarımadaya Demir Diyarlar adını verip kendilerine Demir Diyar sakinleri dediler — ama İlk Doğanlar, hafızanın erişemeyeceği bir çağda ona kendi adlarını koymuştu.\n\nİlk Doğanlar'ın dünyandaki rolünü belirlemek için sayfa 128'e bak.\n\n## Elf\n\n- __Derece:__ Tehlikeli (hasar başına 2 İlerleme; 2 hasar verir)\n- __Özellikler:__ Ahşap bir maskenin ardından görünen iri, ışıltılı gözler; kuru yaprak dokusunda gri-yeşil ten; tınılı bir ses; yay ve mızrak kullanır\n- __Güdüler:__ Yabanı koru; davetsizleri kov ya da bedelini ödet\n- __Taktikler:__ Gölgeden saldır; teslim olmaya zorla; ormanı onlara karşı çevir\n\nElfler, ormanın tuhaf varlıklarıdır; Derin Yabanlar'ın (Deep Wilds) kadim ormanlarının ötesinde nadiren görülürler. Topraklarını hararetle korur, insanlara karşı kuşku duyarlar. İzcileri, bizim Gauntlar (page 148) dediğimiz ürkütücü binekleri sürerek sınır boylarında devriye gezer. Türlerinin diğerleri ise derin ormanların gölgesinden, mızrak ve yay hazır, bizi izler. Kimileri, Elf mistiklerin ormanın hayvanlarını ve canavarlarını Yaban'ın savunmasına yardım için bağlayabildiğini söyler.\n\nBirkaçı, Elflerin vaktini kolladığını, bizi bu topraklardan kovacak saldırıyı hazırladığını söyleyerek uyarır.\n\n__Görev Başlangıcı:__ Bir Demir Diyar sakini topluluğunun lideri, Elflerle bir görüşme arar. Ne amaçla? Yardım etmeye neden mecbur hissediyorsun?\n\n__Senin Hakikatin:__ Elfler yüzlerini süslü ahşap maskelerin ardına gizler. Bu maskeler neyi simgeler?"
	},
	{
		"page": 143,
		"img": "/rulebook/dusmanlar/p143.webp",
		"title_en": "Giant",
		"title_tr": "Dev",
		"text_en": "## Giant\n\n- __Rank:__ Extreme (2 ticks per harm; inflicts 4 harm)\n- __Features:__ Dark hair and ruddy skin; twice the size of a tall human, or more; wearing layers of wool, hide, and furs; stoic and observant\n- __Drives:__ Survive the winter; protect the herd\n- __Tactics:__ Fight as a last resort; sweeping strike; make them flee\n\nGiants dwell in the Tempest Hills and Veiled Mountains. They live a nomadic life alone or in small family units, herding oxen, mountain goats, and sheep. In their own language they are called the Jokul.\n\nMany Ironlanders misinterpret their quiet nature for dullness, but giants are keenly intelligent and observant. They have a great respect for life, even for our kind, and use trickery and negotiation to avoid fights. When they are left without other options, an enraged giant is a devastating, relentless force.\n\n__Quest Starter:__ A pair of giants are raiding human settlements, stealing supplies and livestock. With winter coming, the survival of those settlements is threatened. What is driving the giants down from the hills?\n\n__Your Truth:__ Every fifth spring, the giant clans meet for a gathering. There, the memory-keepers sing of a great giant hero, revered by all. Who is this hero?",
		"text_tr": "## Dev\n\n- __Derece:__ Aşırı (hasar başına 2 çentik; 4 hasar verir)\n- __Özellikler:__ Koyu saç ve kızıl ten; uzun bir insanın iki katı boyunda ya da daha fazla; kat kat yün, post ve kürk giyer; sakin ve dikkatli\n- __Güdüler:__ Kıştan sağ çık; sürüyü koru\n- __Taktikler:__ Son çare olarak dövüş; savuran darbe; onları kaçmaya zorla\n\nDevler (Giants), Fırtına Tepeleri (Tempest Hills) ile Örtülü Dağlar'da (Veiled Mountains) yaşar. Tek başına ya da küçük aile birimleri hâlinde göçebe bir hayat sürer; öküz, dağ keçisi ve koyun güderler. Kendi dillerinde onlara Jokul denir.\n\nBirçok Demir Diyar sakini, onların sessiz tabiatını ahmaklık sanır; oysa Devler son derece zeki ve dikkatlidir. Yaşama, bizim türümüze bile büyük bir saygı duyar; dövüşten kaçınmak için hile ve müzakereye başvururlar. Başka seçenek kalmadığında, öfkelenmiş bir Dev, yıkıcı ve amansız bir kuvvettir.\n\n__Görev Başlangıcı:__ İki Dev, insan yerleşimlerini yağmalayıp erzak ve hayvan çalıyor. Kış gelirken, o yerleşimlerin hayatta kalması tehdit altında. Devleri tepelerden aşağı sürükleyen nedir?\n\n__Senin Hakikatin:__ Her beşinci baharda, Dev klanları bir toplanma için bir araya gelir. Orada, hafıza-tutucular herkesçe saygı duyulan büyük bir Dev kahramanın türküsünü söyler. Bu kahraman kim?"
	},
	{
		"page": 144,
		"img": "/rulebook/dusmanlar/p144.webp",
		"title_en": "Primordial",
		"title_tr": "İlksel",
		"text_en": "## Primordial\n\n- __Rank:__ Extreme (2 ticks per harm; inflicts 4 harm)\n- __Features:__ Personification of the natural world; turbulent, changing visage; vaguely human-like or animal-like form\n- __Drives:__ Embody chaos; cling to vestiges of power\n- __Tactics:__ Control the elements; destroy with primal rage\n\nThe primordials, said to be the vestigial spirits of long-forgotten gods, are the most ancient of the firstborn. Each embodies some aspect of the natural world, bound in a crude mimicry of a human or large animal. A river primordial is a mass of rock, gravel, and flowing water. A forest primordial is formed of wood, earth, rocks, and plants. A mountain primordial is a lumbering being of glacier stone and ice. A fire primordial, depending on its mood, might take form as embers, ash, and smoke—or as a raging pyre.\n\nThey range in size from the height of an Ironlander to half-again as tall as a giant. Rumors persist of primordials who dwell in the deepest parts of the Wilds, or high in the ranges of the Veiled Mountains, who are as tall as an ancient tree. Beyond, some suggest, in the Shattered Wastes, live primordials who tower into the clouds. Is the sound of distant thunder sometimes the footfalls of mountain-sized primordials who dwell beyond the edge of the known world?\n\nPrimordials are solitary beings as unpredictable as the natural forces they personify. They might ignore you. They might lurk at a distance, as if observing you. Or, they might attack. They do not speak in any language we can understand. Some suggest they have no intelligence, and are merely a manifestation of the natural world, no different than a winter storm.\n\nHow do you kill a primordial? Most scoff at the idea. You are just as likely to kill the rain or the sea. A mystic might tell you to use a weapon imbued with elemental power. Don't trust them. If you see a primordial, keep your distance. Better yet, run.\n\n__Quest Starter:__ In the dead of winter, a fire primordial is razing homes and burning a nearby wood. At night, orange flames light the sky. What can be done to stop this destruction?",
		"text_tr": "## İlksel\n\n- __Derece:__ Aşırı (hasar başına 2 çentik; 4 hasar verir)\n- __Özellikler:__ Doğal dünyanın bir cisimlenişi; çalkantılı, değişen bir çehre; belli belirsiz insan ya da hayvan benzeri bir biçim\n- __Güdüler:__ Kaosu cisimlendir; gücün kalıntılarına tutun\n- __Taktikler:__ Unsurları yönet; ilkel öfkeyle yık\n\nÇoktan unutulmuş tanrıların artakalan ruhları olduğu söylenen İlkseller (Primordials), İlk Doğanlar'ın en kadimleridir. Her biri doğal dünyanın bir yönünü cisimlendirir; bir insanın ya da büyük bir hayvanın kaba bir taklidine bağlanmış olarak. Bir nehir İlkseli; kaya, çakıl ve akan suyun bir yığınıdır. Bir orman İlkseli; ahşap, toprak, kaya ve bitkiden oluşur. Bir dağ İlkseli; buzul taşı ve buzdan, ağır ağır yürüyen bir varlıktır. Bir ateş İlkseli ise, ruh hâline göre köz, kül ve duman olarak ya da kudurmuş bir ateş yığını olarak biçimlenebilir.\n\nBoyları, bir Demir Diyar sakininin boyundan, bir Devin bir buçuk katı uzunluğuna dek değişir. Yaban'ın en derin yerlerinde ya da Örtülü Dağlar'ın silsilelerinde yüksekte yaşayan, kadim bir ağaç kadar uzun İlkseller hakkındaki söylentiler hiç dinmez. Kimilerine göre daha ötede, Paramparça Çoraklıklar'da (Shattered Wastes), bulutlara yükselen İlkseller yaşar. Uzaktan gelen gök gürültüsünün sesi, bazen bilinen dünyanın kıyısının ötesinde yaşayan dağ boyutundaki İlksellerin ayak sesleri midir?\n\nİlkseller, cisimlendirdikleri doğa kuvvetleri kadar öngörülemez, yalnız varlıklardır. Seni görmezden gelebilirler. Seni gözlüyormuşçasına bir mesafede pusuya yatabilirler. Ya da saldırabilirler. Anlayabileceğimiz hiçbir dilde konuşmazlar. Kimilerine göre hiç zekâları yoktur ve yalnızca doğal dünyanın bir tezahürüdürler — bir kış fırtınasından farksız.\n\nBir İlkseli nasıl öldürürsün? Çoğu kişi bu fikirle alay eder. Yağmuru ya da denizi öldürmen kadar olası bir şeydir bu. Bir mistik sana unsur gücüyle yüklenmiş bir silah kullanmanı söyleyebilir. Onlara güvenme. Bir İlksel görürsen, mesafeni koru. Daha iyisi, koş.\n\n__Görev Başlangıcı:__ Kışın en koyu vaktinde, bir ateş İlkseli evleri yerle bir ediyor ve yakındaki bir ormanı yakıyor. Geceleri, turuncu alevler göğü aydınlatıyor. Bu yıkımı durdurmak için ne yapılabilir?"
	},
	{
		"page": 145,
		"img": "/rulebook/dusmanlar/p145.webp",
		"title_en": "Troll",
		"title_tr": "Troll",
		"text_en": "## Troll\n\n- __Rank:__ Formidable (1 progress per harm; inflicts 3 harm)\n- __Features:__ Long limbs; sunken, beady eyes; translucent skin camouflaged to the environment; keen sense of smell; speaks in gibberish\n- __Drives:__ Find pretty things; keep it secret\n- __Tactics:__ Be sneaky; bite and claw; run and hide\n\nTrolls mostly live in the Flooded Land, but it's not unusual to encounter one in the Hinterlands or even in the southern reaches of the Havens. They are solitary creatures, wary of contact with Ironlanders but likely to attack if scared or provoked.\n\nThey move with their back hunched, often skulking on all four gangly limbs. When they stand straight they are much taller than humans—nearly as tall as a giant. Their skin is a sickly pale gray, but they can camouflage themselves by changing it to match their environment.\n\nTrolls collect objects of all sorts, and particularly value Ironlander trinkets. They are tormented by the fear of others stealing their hoard, and are constantly seeking out new, better hiding places. The items are mostly junk to anyone but a troll, but occasionally an object of real value finds its way into the dregs.\n\n__Quest Starter:__ The villagers tolerate the troll who lives nearby because its presence serves to dissuade a greater threat. They even donate items for its hoard, and put up with its occasional thievery. But now, the troll is missing. What is the looming threat the troll helped avert?",
		"text_tr": "## Troll\n\n- __Derece:__ Zorlu (hasar başına 1 İlerleme; 3 hasar verir)\n- __Özellikler:__ Uzun uzuvlar; çukura kaçmış, boncuk gibi gözler; çevreye göre kamufle olan yarı saydam ten; keskin bir koku alma duyusu; anlaşılmaz bir dilde konuşur\n- __Güdüler:__ Güzel şeyler bul; gizli tut\n- __Taktikler:__ Sinsi ol; ısır ve pençele; kaç ve saklan\n\nTroller çoğunlukla Su Basmış Topraklar'da (Flooded Lands) yaşar, ama bir Trolle Ardtopraklar'da (Hinterlands), hatta Sığınaklar'ın (Havens) güney uçlarında bile karşılaşmak olağandışı değildir. Yalnız yaratıklardır; Demir Diyar sakinleriyle temastan çekinirler, ama korkutulur ya da kışkırtılırlarsa saldırmaları olasıdır.\n\nSırtları kambur hâlde hareket eder, çoğu kez sıska dört uzvunun üzerinde sinsice süzülürler. Dik durduklarında insanlardan çok daha uzundurlar — neredeyse bir Dev kadar. Tenleri hastalıklı, soluk bir gridir; ama tenlerini çevreye uyacak şekilde değiştirerek kamufle olabilirler.\n\nTroller her türden nesneyi toplar, özellikle Demir Diyar sakinlerinin biblolarına değer verirler. Başkalarının hazinelerini çalma korkusuyla kıvranır, sürekli yeni ve daha iyi saklanma yerleri ararlar. Bu eşyalar bir Trolden başka herkes için çoğunlukla çer çöptür; ama ara sıra gerçekten değerli bir nesne de bu döküntülerin arasına karışır.\n\n__Görev Başlangıcı:__ Köylüler, yakında yaşayan Trole katlanır; çünkü onun varlığı daha büyük bir tehdidi caydırmaya yarar. Hazinesi için eşyalar bile bağışlar, ara sıraki hırsızlığına göz yumarlar. Ama şimdi Trol ortadan kayboldu. Trolün savuşturmaya yardım ettiği, ufukta beliren tehdit nedir?"
	},
	{
		"page": 146,
		"img": "/rulebook/dusmanlar/p146.webp",
		"title_en": "Varou",
		"title_tr": "Varou",
		"text_en": "## Varou\n\n- __Rank:__ Dangerous (2 progress per harm; inflicts 2 harm)\n- __Features:__ Yellow eyes shining in moonlight; pointed ears and snout-like face\n- __Drives:__ Take their land; defend my kin; keep the bloodcall at bay\n- __Tactics:__ Strike at night; leap into combat; let loose the bloodcall\n\nThe varou are humanoid beings who dwell within the Deep Wilds and in the woods of the Hinterlands. Their features are fierce and wolf-like. They are broad-shouldered and a head taller than the average Ironlander. Their long hair is ornately groomed and decorated with beads and other trinkets.\n\nThe varou value territory above all things. They often war amongst themselves and against the elves to gain or defend holdings. They mark their claims by carving clan symbols into trees. Only the foolish ignore the warning of these border signs. Several of our settlements—built too close to varou territory—are now abandoned ruins bearing the mark of a victorious varou clan.\n\n__Quest Starter:__ A varou clan has carved their mark into the trees surrounding an Ironlander community, claiming it as their territory. An attack is surely imminent. What will you do to prevent it?\n\n__Your Truth:__ A young varou receives their keth—a curved dagger—before undergoing a rite of passage. What must they do to take their place among the adults of the clan?",
		"text_tr": "## Varou\n\n- __Derece:__ Tehlikeli (hasar başına 2 İlerleme; 2 hasar verir)\n- __Özellikler:__ Ay ışığında parıldayan sarı gözler; sivri kulaklar ve burunsu bir yüz\n- __Güdüler:__ Topraklarını al; soyumu savun; kan çağrısını uzak tut\n- __Taktikler:__ Geceleyin saldır; dövüşe atıl; kan çağrısını salıver\n\nVarou'lar, Derin Yabanlar'da ve Ardtopraklar'ın ormanlarında yaşayan insansı varlıklardır. Hatları vahşi ve kurt benzeridir. Geniş omuzludurlar ve ortalama bir Demir Diyar sakininden bir baş daha uzundurlar. Uzun saçları süslü biçimde taranmış, boncuklar ve başka biblolarla bezenmiştir.\n\nVarou'lar her şeyden çok bölgeye değer verir. Topraklar kazanmak ya da savunmak için sık sık kendi aralarında ve Elflere karşı savaşırlar. İddialarını, ağaçlara klan simgeleri oyarak işaretlerler. Yalnızca ahmaklar bu sınır işaretlerinin uyarısını görmezden gelir. Varou bölgesine fazla yakın kurulan birkaç yerleşimimiz, artık muzaffer bir Varou klanının işaretini taşıyan terk edilmiş kalıntılardır.\n\n__Görev Başlangıcı:__ Bir Varou klanı, bir Demir Diyar sakini topluluğunu çevreleyen ağaçlara işaretini oyarak orayı kendi bölgesi ilan etti. Bir saldırı kesinlikle yakın. Bunu önlemek için ne yapacaksın?\n\n__Senin Hakikatin:__ Genç bir Varou, bir geçiş ayinine girmeden önce keth'ini — eğri bir hançer — alır. Klanın yetişkinleri arasında yerini almak için ne yapması gerekir?"
	},
	{
		"page": 147,
		"img": "/rulebook/dusmanlar/p147.webp",
		"title_en": "Animals / Bear",
		"title_tr": "Hayvanlar / Ayı",
		"text_en": "## Animals\n\nAnimals are the mundane creatures which dwell in the Ironlands. Some animals are native to these lands; others were also common in the Old World. Most wild animals are skittish and do not pose a threat to humans. Those creatures have no rank, and can be attacked or interacted with using appropriate moves. For example, Resupply (page 63) can represent hunting for deer or small game.\n\nA few notable exceptions—predators, aggressive creatures, and animals trained to fight—are noted here.\n\n## Bear\n\n- __Rank:__ Formidable (1 progress per harm; inflicts 3 harm)\n- __Features:__ Fearsome teeth and claws; thick hide\n- __Drives:__ Find food; defend cubs\n- __Tactics:__ Roar; pin down; maul with savage force\n\nMost bears are not aggressive. They avoid Ironlanders and are unlikely to attack unless they see you as a threat.\n\nThere are exceptions. The silver bears of the Veiled Mountains, which sometimes range as far south as the Tempest Hills, are territorial, powerful, and aggressive. Likewise, the ash bear, encountered in woodlands throughout the Ironlands, is known for its ferocity and cunning. If either catch your scent, they are likely to hunt you down and attack.\n\n__Quest Starter:__ A group of hunters felled a large ash bear with several arrows. It tumbled into a river and was swept away. Unfortunately, the bear they thought dead is now stalking the group as they make their way back home.",
		"text_tr": "## Hayvanlar\n\nHayvanlar, Demir Diyarlar'da yaşayan sıradan yaratıklardır. Kimi hayvanlar bu topraklara özgüdür; kimileri Eski Dünya'da da yaygındı. Çoğu yabani hayvan ürkektir ve insanlara tehdit oluşturmaz. Bu yaratıkların derecesi yoktur; uygun hamleler kullanılarak onlara saldırılabilir ya da onlarla etkileşime girilebilir. Örneğin İkmal Et (page 63) hamlesi, geyik ya da küçük av avlamayı temsil edebilir.\n\nBirkaç dikkate değer istisna — yırtıcılar, saldırgan yaratıklar ve dövüşmek için eğitilmiş hayvanlar — burada belirtilmiştir.\n\n## Ayı\n\n- __Derece:__ Zorlu (hasar başına 1 İlerleme; 3 hasar verir)\n- __Özellikler:__ Ürkütücü dişler ve pençeler; kalın post\n- __Güdüler:__ Yiyecek bul; yavruları savun\n- __Taktikler:__ Kükre; yere mıhla; vahşi bir güçle paralayıp parçala\n\nAyıların çoğu saldırgan değildir. Demir Diyar sakinlerinden uzak durur ve seni bir tehdit olarak görmedikçe saldırmaları beklenmez.\n\nİstisnalar vardır. Bazen Fırtına Tepeleri kadar güneye inen Örtülü Dağlar'ın gümüş ayıları; bölgelerine düşkün, güçlü ve saldırgandır. Aynı şekilde, Demir Diyarlar boyunca ormanlık alanlarda karşılaşılan kül ayısı da vahşeti ve kurnazlığıyla bilinir. İkisinden biri kokunu alırsa, seni izleyip avlaması ve saldırması olasıdır.\n\n__Görev Başlangıcı:__ Bir grup avcı, büyük bir kül ayısını birkaç okla devirdi. Ayı bir nehre yuvarlandı ve sürüklenip gitti. Ne yazık ki öldü sandıkları ayı, şimdi eve dönerlerken grubu sinsice takip ediyor."
	},
	{
		"page": 148,
		"img": "/rulebook/dusmanlar/p148.webp",
		"title_en": "Boar / Gaunt",
		"title_tr": "Yaban Domuzu / Gaunt",
		"text_en": "## BOAR\n\n**Rank:** Dangerous (2 progress per harm; inflicts 2 harm)\n\n**Features:**\n\n- Wiry coat\n- Long tusks\n- Vicious\n\n**Drives:**\n\n- Forage\n- Protect territory\n- Defend sows\n\n**Tactics:**\n\n- Charge and gore\n- Circle and attack again\n\nIn the Old World, wild boars were belligerent and dangerous animals. Here in the Ironlands? They are even bigger and meaner. They attack without warning or provocation. They will run you down, gore you, bite you, and circle around to do it all again. And again. And again.\n\n*Quest Starter:* A boar hunt ends in tragedy when an Ironlander is gored and grievously wounded. How do you know this person? What terrible truth do they reveal as they lay dying?\n\n## GAUNT\n\n**Rank:** Dangerous (2 progress per harm; inflicts 2 harm)\n\n**Features:**\n\n- Horse-like creature with a lean, skeletal frame\n- Ghostly pale eyes\n- Black, scaled hide\n\n**Drives:**\n\n- Run like the wind\n\n**Tactics:**\n\n- Rear up\n- Charge\n- Trample",
		"text_tr": "## YABAN DOMUZU\n\n**Derece:** Tehlikeli (Her hasar başına 2 İlerleme; 2 hasar verir)\n\n**Özellikler:**\n\n- Sert kıllı postlar\n- Uzun azı dişleri\n- Acımasız\n\n**Güdüler:**\n\n- Yiyecek aramak\n- Toprağını korumak\n- Dişilerini savunmak\n\n**Taktikler:**\n\n- Hücum edip deşmek\n- Dönüp yeniden saldırmak\n\nEski Dünya'da yaban domuzları kavgacı ve tehlikeli hayvanlardı. Burada, Demir Diyarlar'da mı? Daha da iri ve daha da gaddarlar. Uyarmadan, kışkırtılmadan saldırırlar. Üstüne çullanır, boynuzlarıyla deşer, ısırır ve hepsini yeniden yapmak için dönüp gelirler. Yine. Yine. Yine.\n\n*Görev Başlangıcı:* Bir yaban domuzu avı, bir Demir Diyar sakini boynuzlarla deşilip ağır yaralandığında trajediyle son bulur. Bu kişiyi nereden tanıyorsun? Can çekişirken hangi korkunç gerçeği açığa vuruyor?\n\n## GAUNT\n\n**Derece:** Tehlikeli (Her hasar başına 2 İlerleme; 2 hasar verir)\n\n**Özellikler:**\n\n- İnce, iskelet gibi bir gövdeye sahip, ata benzer bir yaratık\n- Hayalet gibi soluk gözler\n- Siyah, pullu deri\n\n**Güdüler:**\n\n- Rüzgâr gibi koşmak\n\n**Taktikler:**\n\n- Şaha kalkmak\n- Hücum etmek\n- Çiğnemek"
	},
	{
		"page": 149,
		"img": "/rulebook/dusmanlar/p149.webp",
		"title_en": "Gaunt / Marsh Rat",
		"title_tr": "Gaunt / Bataklık Sıçanı",
		"text_en": "A gaunt is a creature unique to the Ironlands. They maneuver across the rough, dense terrain of the Deep Wilds and Hinterlands with uncanny speed and grace. This makes them ideal as mounts for the elves (page 142), who breed and train them.\n\nA gaunt will not usually act aggressively without provocation, but they are as deadly as the fiercest warhorse under the command of a talented rider.\n\n*Quest Starter:* Villages in the Hinterlands have fallen prey to a large band of gaunt-riding elves. They attack with sudden and violent force, and are gone before any sort of defense can be mustered. Their leader, a warrior of unmatched skill, rides a distinctive white gaunt. What has driven these elves to strike out against the Ironlanders?\n\n### YOUR TRUTH\n\nSome gaunts live in wild herds. They once roamed the wilds in countless numbers, but few now remain. What has happened to thin these herds so dramatically?\n\n## MARSH RAT\n\n**Rank:** Troublesome (3 progress per harm; inflicts 1 harm)\n\n**Features:**\n\n- Beady eyes\n- Long tail\n\n**Drives:**\n\n- Eat everything\n- Breed\n\n**Tactics:**\n\n- Swarm and bite\n\nThe marsh rat is a rodent of unusual size. They are all-too-common in the Flooded Lands or in wetlands within the Hinterlands and Deep Wilds. They eat almost anything, including carrion and waste. Our grain stores and pantries are an easy target for marsh rats, who dig tunnels or chew through walls to get at the food. They will also try to make a meal out of living prey—deer, cattle, or even an unlucky Ironlander. A pack of marsh rats can kill a horse and reduce it to bone in a matter of hours.\n\n*Quest Starter:* Marsh rats raided the stores of an isolated settlement. How will you ensure the Ironlanders have enough food to survive the coming winter?",
		"text_tr": "Gaunt, Demir Diyarlar'a özgü bir yaratıktır. Derin Yabanlar (Deep Wilds) ve Ardtopraklar'ın (Hinterlands) engebeli, sık arazisinde tekinsiz bir hız ve zarafetle hareket ederler. Bu da onları, kendilerini yetiştirip eğiten elfler (sayfa 142) için ideal binekler kılar.\n\nBir gaunt genellikle kışkırtılmadan saldırgan davranmaz, ama yetenekli bir binicinin komutası altında en azılı savaş atı kadar ölümcüldür.\n\n*Görev Başlangıcı:* Ardtopraklar'daki köyler, gaunt sırtında giden büyük bir elf çetesinin avı olmuştur. Ani ve şiddetli bir güçle saldırır, herhangi bir savunma toparlanmadan kaybolurlar. Eşsiz hünere sahip bir savaşçı olan liderleri, ayırt edici beyaz bir gaunt'a binmektedir. Bu elfleri Demir Diyar sakinlerine saldırmaya iten nedir?\n\n### SENİN GERÇEĞİN\n\nBazı gaunt'lar yabani sürüler hâlinde yaşar. Bir zamanlar yabanı sayısız sürüler hâlinde arşınlarlardı, ama artık pek azı kaldı. Bu sürüleri böylesine çarpıcı biçimde inceltecek ne oldu?\n\n## BATAKLIK SIÇANI\n\n**Derece:** Sıradan (Her hasar başına 3 İlerleme; 1 hasar verir)\n\n**Özellikler:**\n\n- Boncuk gibi gözler\n- Uzun kuyruk\n\n**Güdüler:**\n\n- Her şeyi yemek\n- Üremek\n\n**Taktikler:**\n\n- Sürüyle saldırıp ısırmak\n\nBataklık sıçanı, olağandışı boyutta bir kemirgendir. Su Basmış Topraklar'da (Flooded Lands) ya da Ardtopraklar ve Derin Yabanlar içindeki sulak alanlarda fazlasıyla yaygındırlar. Leş ve atık dahil neredeyse her şeyi yerler. Tahıl ambarlarımız ve kilerlerimiz, yiyeceğe ulaşmak için tüneller kazan ya da duvarları kemiren bataklık sıçanları için kolay bir hedeftir. Canlı avları da yemeğe çevirmeye çalışırlar — geyiği, sığırı, hatta talihsiz bir Demir Diyar sakinini. Bir bataklık sıçanı sürüsü bir atı öldürüp birkaç saat içinde kemiğe indirebilir.\n\n*Görev Başlangıcı:* Bataklık sıçanları, ücra bir yerleşimin ambarlarını bastı. Demir Diyar sakinlerinin gelecek kıştan sağ çıkacak kadar yiyeceği olmasını nasıl sağlayacaksın?"
	},
	{
		"page": 150,
		"img": "/rulebook/dusmanlar/p150.webp",
		"title_en": "Wolf",
		"title_tr": "Kurt",
		"text_en": "## WOLF\n\n**Rank:** Dangerous (2 progress per harm; inflicts 2 harm)\n\n**Features:**\n\n- Keen senses\n\n**Drives:**\n\n- Fight rivals\n- Mark territory\n- Run with the pack\n\n**Tactics:**\n\n- Stalk\n- Pack rush\n- Drag to the ground\n\nThe Ironlands are home to several breeds of wolves. Most are not aggressive and stay clear of settlements and travelers. Despite that, attacks against Ironlanders are not unknown. A harsh winter and insufficient prey can drive a pack to hunt livestock or even an unwary Ironlander. As night falls we hear their howls, and hope they are well fed.\n\n*Quest Starter:* You find the grisly remains of a pack of wolves. All are dead, even the cubs. What caused this? Why is it a harbinger of a greater danger?",
		"text_tr": "## KURT\n\n**Derece:** Tehlikeli (Her hasar başına 2 İlerleme; 2 hasar verir)\n\n**Özellikler:**\n\n- Keskin duyular\n\n**Güdüler:**\n\n- Rakipleriyle dövüşmek\n- Toprağını işaretlemek\n- Sürüyle koşmak\n\n**Taktikler:**\n\n- Sinsice izlemek\n- Sürü hücumu\n- Yere devirmek\n\nDemir Diyarlar, çeşit çeşit kurt cinsine ev sahipliği yapar. Çoğu saldırgan değildir, yerleşimlerden ve yolculardan uzak durur. Buna rağmen Demir Diyar sakinlerine yönelik saldırılar bilinmez değildir. Sert bir kış ve yetersiz av, bir sürüyü davar avlamaya, hatta tedbirsiz bir Demir Diyar sakinini avlamaya itebilir. Gece çökerken ulumalarını duyar ve karınlarının tok olmasını umarız.\n\n*Görev Başlangıcı:* Bir kurt sürüsünün ürkütücü kalıntılarını bulursun. Hepsi ölmüş, yavrular bile. Buna ne sebep oldu? Bu neden daha büyük bir tehlikenin habercisi?"
	},
	{
		"page": 151,
		"img": "/rulebook/dusmanlar/p151.webp",
		"title_en": "Beasts / Basilisk",
		"title_tr": "Canavarlar / Basilisk",
		"text_en": "## BEASTS\n\nBeasts are monstrous creatures of great size and power. They are natural beings—not supernatural entities—but were unknown in the Old World.\n\nTo determine the role of beasts in your version of the Ironlands, see page 128.\n\n## BASILISK\n\n**Rank:** Extreme (2 ticks per harm; inflicts 4 harm)\n\n**Features:**\n\n- Giant snake\n- Dull yellow-brown skin\n- Vibrant yellow eyes\n\n**Drives:**\n\n- Devour\n\n**Tactics:**\n\n- Lay in wait\n- Mesmerizing gaze\n- Sudden bite\n- Crush\n\nBasilisks dwell in the Flooded Lands, lurking in the murky waters of the swamps or within marshy thickets. There, they wait patiently for prey. They regularly feed on marsh rats or deer, but will eagerly make a meal out of a passing Ironlander.\n\n*Quest Starter:* The adventurer set out to slay a basilisk, only to become its next meal. Because the serpent digests its prey slowly, the remains of the adventurer are still undoubtedly within the beast—along with the heirloom sword he wielded. What is your relationship to this person? Why is recovering the sword so important to you?\n\n### YOUR TRUTH\n\nSome piece of a basilisk anatomy is prized by the Ironlanders. What is it? How is it used?",
		"text_tr": "## CANAVARLAR\n\nCanavarlar (Beasts), büyük boyut ve güce sahip canavarsı yaratıklardır. Doğal varlıklardır — doğaüstü değiller — ama Eski Dünya'da bilinmezlerdi.\n\nCanavarların senin Demir Diyarlar versiyonundaki rolünü belirlemek için bkz. sayfa 128.\n\n## BASILISK\n\n**Derece:** Aşırı (Her hasar başına 2 çentik; 4 hasar verir)\n\n**Özellikler:**\n\n- Dev yılan\n- Donuk sarı-kahve deri\n- Capcanlı sarı gözler\n\n**Güdüler:**\n\n- Yutmak\n\n**Taktikler:**\n\n- Pusu kurmak\n- Hipnotize eden bakış\n- Ani ısırık\n- Ezmek\n\nBasilisk'ler Su Basmış Topraklar'da yaşar; bataklıkların bulanık sularında ya da sazlık çalılıkların içinde pusuya yatarlar. Orada avlarını sabırla beklerler. Düzenli olarak bataklık sıçanı ya da geyikle beslenir, ama yoldan geçen bir Demir Diyar sakinini de iştahla yemeğe çevirirler.\n\n*Görev Başlangıcı:* Maceracı, bir basilisk'i öldürmek için yola çıktı ama onun bir sonraki öğünü oldu. Yılan avını yavaş sindirdiğinden, maceracının kalıntıları hiç şüphesiz hâlâ canavarın içindedir — taşıdığı yadigâr kılıçla birlikte. Bu kişiyle ilişkin nedir? Kılıcı geri almak senin için neden bu kadar önemli?\n\n### SENİN GERÇEĞİN\n\nBasilisk anatomisinin bir parçası Demir Diyar sakinlerince değer görür. Bu nedir? Nasıl kullanılır?"
	},
	{
		"page": 152,
		"img": "/rulebook/dusmanlar/p152.webp",
		"title_en": "Elder Beast",
		"title_tr": "Kadim Canavar",
		"text_en": "## ELDER BEAST\n\n**Rank:** Extreme (2 ticks per harm; inflicts 4 harm)\n\n**Features:**\n\n- Twice the size of their common kin, or more\n\n**Drives:**\n\n- Dominate\n- Protect territory\n\n**Tactics:**\n\n- Intimidating display\n- Overwhelming attack\n\nElder beasts—including wolves, bears, and boars—are huge, monstrous versions of their common kin. They are primarily solitary creatures, though elder wolves have been known to lead a pack of normal wolves. Some call them guardians, avatars of the land itself, and say they are as long-lived as the oldest trees.\n\n*Quest Starter:* An elder wolf, white as snow, appears to you in a dream. When you wake, the memory of its piercing gaze lingers. Is the vision a dark portent or a promise? Why are you compelled to seek this beast out?\n\n### YOUR TRUTH\n\nWhat people of the Ironlands revere and protect the elder beasts? What group hunts them and why?",
		"text_tr": "## KADİM CANAVAR\n\n**Derece:** Aşırı (Her hasar başına 2 çentik; 4 hasar verir)\n\n**Özellikler:**\n\n- Sıradan akrabalarının iki katı, hatta daha büyük\n\n**Güdüler:**\n\n- Hükmetmek\n- Toprağını korumak\n\n**Taktikler:**\n\n- Korkutucu gösteri\n- Ezip geçen saldırı\n\nKadim Canavarlar — kurtlar, ayılar ve yaban domuzları dahil — sıradan akrabalarının kocaman, canavarsı versiyonlarıdır. Çoğunlukla yalnız yaratıklardır, ama kadim kurtların normal kurtlardan bir sürüye önderlik ettiği bilinir. Bazıları onlara koruyucular, toprağın bizzat tecessümleri der ve en yaşlı ağaçlar kadar uzun ömürlü olduklarını söyler.\n\n*Görev Başlangıcı:* Kar gibi beyaz bir kadim kurt, bir rüyada karşına çıkar. Uyandığında, delici bakışının anısı içinde kalır. Bu hayal kara bir alâmet mi yoksa bir vaat mi? Bu canavarın peşine düşmeye seni iten nedir?\n\n### SENİN GERÇEĞİN\n\nDemir Diyarlar'ın hangi halkı kadim canavarlara saygı duyup onları korur? Hangi topluluk onları avlar ve neden?"
	},
	{
		"page": 153,
		"img": "/rulebook/dusmanlar/p153.webp",
		"title_en": "Harrow Spider",
		"title_tr": "Dehşet Örümceği",
		"text_en": "## HARROW SPIDER\n\n**Rank:** Dangerous (2 progress per harm; inflicts 2 harm)\n\n**Features:**\n\n- Massive fangs\n- Long legs and bloated body\n- Eight iridescent black eyes\n\n**Drives:**\n\n- Lurk\n- Feed\n\n**Tactics:**\n\n- Drop atop prey\n- Bite with pincers\n- Trap in webbing\n\nThese gigantic creatures are a menace in woodlands throughout the Ironlands. Despite their size, they move through high branches with uncanny grace, dropping suddenly to grapple their prey and entomb them in webbing.\n\n*Quest Starter:* A brood of harrow spiders attacked a contingent of Ironlanders. The single survivor tells of the horrifying encounter and the monstrous brood mother—a harrow spider larger and stronger than a warhorse. What was this group’s mission? What important item are you sworn to recover from one of the victims?",
		"text_tr": "## DEHŞET ÖRÜMCEĞİ\n\n**Derece:** Tehlikeli (Her hasar başına 2 İlerleme; 2 hasar verir)\n\n**Özellikler:**\n\n- Kocaman zehir dişleri\n- Uzun bacaklar ve şişkin gövde\n- Sekiz adet pırıltılı siyah göz\n\n**Güdüler:**\n\n- Pusuya yatmak\n- Beslenmek\n\n**Taktikler:**\n\n- Avın üstüne düşmek\n- Kıskaçlarla ısırmak\n- Ağına hapsetmek\n\nBu devasa yaratıklar, Demir Diyarlar'ın dört bir yanındaki ormanlık alanlarda bir beladır. Boyutlarına rağmen yüksek dalların arasında tekinsiz bir zarafetle hareket eder, avlarını yakalayıp ağlarına gömmek için aniden üstlerine düşerler.\n\n*Görev Başlangıcı:* Bir dehşet örümceği yumurtası, bir Demir Diyar müfrezesine saldırdı. Tek hayatta kalan, o korkunç karşılaşmayı ve canavarsı yumurta anasını anlatıyor — bir savaş atından daha büyük ve daha güçlü bir dehşet örümceği. Bu grubun görevi neydi? Kurbanlardan birinden geri almaya ant içtiğin önemli eşya nedir?"
	},
	{
		"page": 154,
		"img": "/rulebook/dusmanlar/p154.webp",
		"title_en": "Leviathan",
		"title_tr": "Leviathan",
		"text_en": "## LEVIATHAN\n\n**Rank:** Epic (1 tick per harm; inflicts 5 harm)\n\n**Features:**\n\n- Massive bulk\n- Flesh as tough as iron\n- Cold black eyes\n- Sinuous grace\n\n**Drives:**\n\n- Slumber in the depths\n- Destroy those who trespass\n\n**Tactics:**\n\n- Rise from the depths\n- Ram and swamp ships\n- Devour prey whole\n\nThese massive sea beasts lurk in the darkness of the deepest fjords and in the abyssal depths beyond the Barrier Islands. They sometimes surface to hunt within shallower waters. They will indiscriminately destroy any Ironlander vessel which strays too close to their hunting grounds.\n\nWatchful sailors might catch sight of a leviathan circling their boat, studying them, in the moments before it attacks. Their dagger-shaped head is as tough and destructive as any battering ram, able to shatter a ship in a single blow.\n\n*Quest Starter:* A leviathan lurks off the coast, preying on fishing boats and trade ships. Among the dead is someone important to you. Who is it? You have vowed to send this beast back to the depths, but doing so will require a mythic weapon—The Abyssal Harpoon, an Old World artifact said to be carved from the bones of a long-dead sea god. Where is this weapon rumored to be held?\n\n### YOUR TRUTH\n\nSome coastal people believe leviathans are a manifestation of an ancient spirit. What is it?",
		"text_tr": "## LEVIATHAN\n\n**Derece:** Destansı (Her hasar başına 1 çentik; 5 hasar verir)\n\n**Özellikler:**\n\n- Devasa kütle\n- Demir kadar sert et\n- Soğuk siyah gözler\n- Kıvrak bir zarafet\n\n**Güdüler:**\n\n- Derinliklerde uyuklamak\n- Sınırını çiğneyenleri yok etmek\n\n**Taktikler:**\n\n- Derinliklerden yükselmek\n- Gemileri toslayıp batırmak\n- Avı bütün halde yutmak\n\nBu devasa deniz canavarları, en derin fiyortların karanlığında ve Set Adaları'nın (Barrier Islands) ötesindeki dipsiz derinliklerde pusuya yatar. Bazen daha sığ sularda avlanmak için yüzeye çıkarlar. Av sahalarına fazla yaklaşan herhangi bir Demir Diyar teknesini ayrım gözetmeden yok ederler.\n\nUyanık denizciler, saldırmadan önceki anlarda bir leviathan'ın teknelerinin etrafında dönüp onları inceler hâlde olduğunu görebilir. Hançer biçimindeki başı, herhangi bir koçbaşı kadar sert ve yıkıcıdır; bir gemiyi tek vuruşta paramparça edebilir.\n\n*Görev Başlangıcı:* Bir leviathan kıyının açığında pusu kurmuş, balıkçı tekneleri ile ticaret gemilerini avlamaktadır. Ölüler arasında senin için önemli biri var. Bu kim? Bu canavarı derinliklere geri yollamaya ant içtin, ama bunu yapmak için destansı bir silah gerekecek — uzun zaman önce ölmüş bir deniz tanrısının kemiklerinden oyulduğu söylenen, bir Eski Dünya eseri olan Dipsiz Zıpkın (The Abyssal Harpoon). Bu silahın nerede tutulduğu söyleniyor?\n\n### SENİN GERÇEĞİN\n\nBazı kıyı halkları leviathan'ların kadim bir ruhun tecessümü olduğuna inanır. Bu ruh nedir?"
	},
	{
		"page": 155,
		"img": "/rulebook/dusmanlar/p155.webp",
		"title_en": "Mammoth",
		"title_tr": "Mamut",
		"text_en": "## MAMMOTH\n\n**Rank:** Extreme (2 ticks per harm; inflicts 4 harm)\n\n**Features:**\n\n- Woolly fur\n- Large head and curved tusks\n- Prehensile trunk\n\n**Drives:**\n\n- Migrate to fertile ground\n- Forage for food\n- Protect the young of the herd\n\n**Tactics:**\n\n- Form a protective circle\n- Charge\n- Trample\n- Gore\n\nThese beasts resemble the elephants of the Old World’s southern realms, but are larger and covered in a coat of thick fur. They travel in herds among the Tempest Hills, migrating south with the winter and north with the spring. They are not aggressive creatures, but are fearless and will fight to the death to protect their young.\n\nA herd of mammoths is an amazing and humbling sight, but smart Ironlanders keep their distance and stay downwind.\n\n*Quest Starter:* A mammoth calf wanders alone into an Ironlander settlement. Why do you swear to reunite it with its herd?",
		"text_tr": "## MAMUT\n\n**Derece:** Aşırı (Her hasar başına 2 çentik; 4 hasar verir)\n\n**Özellikler:**\n\n- Yünlü post\n- İri baş ve kıvrık fildişleri\n- Kavrayabilen hortum\n\n**Güdüler:**\n\n- Bereketli topraklara göç etmek\n- Yiyecek aramak\n- Sürünün yavrularını korumak\n\n**Taktikler:**\n\n- Koruyucu bir çember oluşturmak\n- Hücum etmek\n- Çiğnemek\n- Deşmek\n\nBu canavarlar Eski Dünya'nın güney diyarlarındaki fillere benzer, ama daha iri ve kalın bir post tabakasıyla kaplıdırlar. Fırtına Tepeleri (Tempest Hills) arasında sürüler hâlinde dolaşır, kışın güneye, baharda kuzeye göç ederler. Saldırgan yaratıklar değildirler, ama korkusuzdurlar ve yavrularını korumak için ölümüne savaşırlar.\n\nBir mamut sürüsü hayranlık verici ve insanı küçük düşüren bir manzaradır, ama akıllı Demir Diyar sakinleri mesafelerini korur ve rüzgâraltında dururlar.\n\n*Görev Başlangıcı:* Bir mamut yavrusu tek başına bir Demir Diyar yerleşimine girip dolaşır. Onu sürüsüne kavuşturmaya neden ant içiyorsun?"
	},
	{
		"page": 156,
		"img": "/rulebook/dusmanlar/p156.webp",
		"title_en": "Wyvern",
		"title_tr": "Wyvern",
		"text_en": "## WYVERN\n\n**Rank:** Extreme (2 ticks per harm; inflicts 4 harm)\n\n**Features:**\n\n- Huge, bat-like wings\n- Rows of knife-sized teeth\n- Thick hide with a metallic sheen\n- Long tail\n\n**Drives:**\n\n- Watch for prey from high above\n- Feed\n\n**Tactics:**\n\n- Swoop down\n- Snap up prey\n- Fearsome roar\n- Bash with tail\n\nThere are several breeds of wyverns in the Ironlands. To the west, tawny wyverns nest in the cliffs of the Barrier Islands and Ragged Coast, diving for fish in the surrounding waters. Inland, the verdant wyverns dwell in forested regions. The largest and most fearsome breed, the iron wyverns, hunt among the Tempest Hills and along the flanks of the Veiled Mountains.\n\nAll wyverns have wolfish heads with wide jaws, thick bodies, and sinuous tails. They have short hind limbs and elongated forelimbs which extend along their wings. In flight, they are a terrifying but awe-inspiring creature. On the ground, they lumber heavily on all four limbs, their wings folded back, jaws agape, gaze fixed on their prey. They are the grim cruelty of the Ironlands given form. They are death.\n\n*Quest Starter:* Ancient cave paintings in the Tempest Hills show humanoids riding atop wyverns. Perhaps these beasts can be tamed. Why are you obsessed with this possibility?\n\n### YOUR TRUTH\n\nRumors persist of a wyvern graveyard where wyverns instinctively go when their death is near. Where is this supposedly located? In what way do Ironlanders make use of wyvern bones?",
		"text_tr": "## WYVERN\n\n**Derece:** Aşırı (Her hasar başına 2 çentik; 4 hasar verir)\n\n**Özellikler:**\n\n- Kocaman, yarasaya benzer kanatlar\n- Bıçak boyutunda diş sıraları\n- Madeni bir parıltıya sahip kalın deri\n- Uzun kuyruk\n\n**Güdüler:**\n\n- Yükseklerden avını gözlemek\n- Beslenmek\n\n**Taktikler:**\n\n- Süzülüp inmek\n- Avı kapmak\n- Korkunç kükreme\n- Kuyruğuyla vurmak\n\nDemir Diyarlar'da çeşit çeşit wyvern cinsi vardır. Batıda, sarımsı wyvern'ler Set Adaları ve Parçalı Kıyı'nın (Ragged Coast) kayalıklarında yuvalanır, çevredeki sulara balık avlamak için dalarlar. İç kesimlerde, yemyeşil wyvern'ler ormanlık bölgelerde yaşar. En büyük ve en korkunç cins olan demir wyvern'ler ise Fırtına Tepeleri arasında ve Örtülü Dağlar'ın (Veiled Mountains) yamaçları boyunca avlanır.\n\nTüm wyvern'lerin geniş çeneli, kurdumsu başları, kalın gövdeleri ve kıvrak kuyrukları vardır. Kısa arka uzuvlara ve kanatları boyunca uzanan upuzun ön uzuvlara sahiptirler. Uçarken korkunç ama hayranlık uyandıran bir yaratıktırlar. Yerde, dört uzvunun üstünde ağır ağır sürünür; kanatları geriye katlanmış, çeneleri açık, bakışları avına kilitlenmiştir. Onlar, Demir Diyarlar'ın acımasız gaddarlığının cisme bürünmüş hâlidir. Onlar ölümdür.\n\n*Görev Başlangıcı:* Fırtına Tepeleri'ndeki kadim mağara resimleri, wyvern'lerin sırtında giden insansılar gösterir. Belki bu canavarlar ehlileştirilebilir. Bu olasılığa neden böylesine takıntılısın?\n\n### SENİN GERÇEĞİN\n\nWyvern'lerin ölümleri yaklaştığında içgüdüsel olarak gittiği bir wyvern mezarlığına dair söylentiler hep dolaşır. Bunun nerede olduğu sanılıyor? Demir Diyar sakinleri wyvern kemiklerinden ne şekilde yararlanır?"
	},
	{
		"page": 157,
		"img": "/rulebook/dusmanlar/p157.webp",
		"title_en": "Horrors / Bonewalker",
		"title_tr": "Dehşetler / Kemikyürüyen",
		"text_en": "## HORRORS\n\nHorrors are supernatural entities. In the Old World, they were superstition and legend. Here, they are nightmares made real. The Ironlands is fertile ground for darkness and evil to take hold, spawning these undead beings of pure vengeance or mindless hate.\n\nMany horrors can be temporarily defeated through physical attacks, but cannot be killed. They are beyond death.\n\nTo determine the role of horrors in your setting, see page 129.\n\n## BONEWALKER\n\n**Rank:** Dangerous (2 progress per harm; inflicts 2 harm)\n\n**Features:**\n\n- Skeletal corpse\n- Yellowed bones\n- Tattered remains of clothing and armor\n\n**Drives:**\n\n- Destroy life\n\n**Tactics:**\n\n- Rush with unexpected speed\n- Attack with the weapons they bore in life\n- Grasp and claw\n\nBonewalkers are human remains given unnatural life. The source of the dark energy animating them is a mystery. Some say it is the will of dark gods. Others say an ancient evil permeates this land and seeps into porous bones of the dead. Or, perhaps it is the work of corrupt mystics.\n\nBonewalkers usually roam the location of their final resting place—a burial site, a cursed battlefield, or a settlement blighted by disease or violence. Nothing remains of their previous selves. They are soulless monsters driven only to destroy the living.\n\n*Quest Starter:* A horde of bonewalkers marches relentlessly towards the Havens. What dark force has gathered this army of the undead? How will you stop them?",
		"text_tr": "## DEHŞETLER\n\nDehşetler (Horrors), doğaüstü varlıklardır. Eski Dünya'da batıl inanç ve efsaneydiler. Burada ise gerçeğe dönüşmüş kâbuslardır. Demir Diyarlar, karanlığın ve kötülüğün kök salması için bereketli bir topraktır; salt intikamdan ya da akılsız nefretten ibaret bu ölümsüz varlıkları doğurur.\n\nBirçok dehşet, fiziksel saldırılarla geçici olarak alt edilebilir ama öldürülemez. Onlar ölümün ötesindedir.\n\nDehşetlerin senin oyun dünyandaki rolünü belirlemek için bkz. sayfa 129.\n\n## KEMİKYÜRÜYEN\n\n**Derece:** Tehlikeli (Her hasar başına 2 İlerleme; 2 hasar verir)\n\n**Özellikler:**\n\n- İskelet hâline gelmiş ceset\n- Sararmış kemikler\n- Giysi ve zırhtan kalan paçavralar\n\n**Güdüler:**\n\n- Yaşamı yok etmek\n\n**Taktikler:**\n\n- Beklenmedik bir hızla saldırmak\n- Yaşarken taşıdıkları silahlarla saldırmak\n- Kavramak ve pençelemek\n\nKemikyürüyenler, doğaüstü bir yaşamla diriltilmiş insan kalıntılarıdır. Onları canlandıran kara enerjinin kaynağı bir muammadır. Kimisi bunun kara tanrıların iradesi olduğunu söyler. Kimisi de bu toprağa kadim bir kötülüğün sindiğini ve ölülerin gözenekli kemiklerine işlediğini söyler. Ya da belki yozlaşmış mistiklerin işidir.\n\nKemikyürüyenler genellikle son istirahatgâhlarının bulunduğu yerde dolaşır — bir mezar yeri, lanetli bir savaş alanı ya da hastalık veya şiddetin kırıp geçirdiği bir yerleşim. Önceki benliklerinden geriye hiçbir şey kalmamıştır. Onlar, yalnızca yaşayanları yok etmeye sürüklenen ruhsuz canavarlardır.\n\n*Görev Başlangıcı:* Bir kemikyürüyen güruhu, amansızca Sığınaklar'a (Havens) doğru ilerliyor. Bu ölümsüzler ordusunu hangi kara güç bir araya topladı? Onları nasıl durduracaksın?"
	},
	{
		"page": 158,
		"img": "/rulebook/dusmanlar/p158.webp",
		"title_en": "Chimera / Frostbound",
		"title_tr": "Kimera / Ayazabağlı",
		"text_en": "## CHIMERA\n\n**Rank:** Extreme (2 ticks per harm; inflicts 4 harm)\n\n**Features:**\n\n- Shambling mass of dead creatures and offal\n- Rotting stench\n\n**Drives:**\n\n- Insatiable hunger\n\n**Tactics:**\n\n- Horrifying wail\n- Relentless assault\n- Claw, bite and rend\n\nA chimera is the corrupted form of dead animal flesh given horrible life. Its body is a collection of various creatures, fused together into a twisted, massive entity which knows only pain and hunger. When a dozen blood-tinged eyes focus on you, when its gibbering mouths open at once to scream, your only hope is a quick death.\n\n*Quest Starter:* Multiple chimera have spawned from the heart of a deep wood. What evil is at work there?\n\n## FROSTBOUND\n\n**Rank:** Formidable (1 progress per harm; inflicts 3 harm)\n\n**Features:**\n\n- Mummified, desiccated flesh\n- Frozen blue eyes\n- A sorrowful, hollow scream\n\n**Drives:**\n\n- Absorb the warmth of the living\n\n**Tactics:**\n\n- Sense heat\n- Life-draining grasp\n\nSome who fall prey to the long winters or the wild storms of the northern regions are given a horrible new life as the frostbound. These animated corpses are cursed to forever seek out the warmth their death took from them.\n\n*Quest Starter:* A group of frostbound lurk along a mountain trail. This path is the only safe route to the lowlands from a mining village.",
		"text_tr": "## KİMERA\n\n**Derece:** Aşırı (Her hasar başına 2 çentik; 4 hasar verir)\n\n**Özellikler:**\n\n- Ölü yaratıklar ve sakatattan oluşan, sürünen bir kütle\n- Çürük kokusu\n\n**Güdüler:**\n\n- Doymak bilmez açlık\n\n**Taktikler:**\n\n- Korkunç feryat\n- Amansız saldırı\n- Pençelemek, ısırmak ve parçalamak\n\nKimera, ölü hayvan etinin yozlaşmış, korkunç bir yaşam kazanmış hâlidir. Gövdesi, çarpık ve devasa bir varlıkta birbirine kaynamış çeşitli yaratıklardan oluşan bir derlemedir; bu varlık yalnızca acıyı ve açlığı bilir. Bir düzine kana bulanmış göz sana kilitlendiğinde, anlaşılmaz sesler çıkaran ağızları çığlık atmak için bir anda açıldığında, tek umudun çabuk bir ölümdür.\n\n*Görev Başlangıcı:* Derin bir ormanın göbeğinden birden çok kimera türedi. Orada hangi kötülük iş başında?\n\n## AYAZABAĞLI\n\n**Derece:** Zorlu (Her hasar başına 1 İlerleme; 3 hasar verir)\n\n**Özellikler:**\n\n- Mumyalaşmış, kurumuş et\n- Donmuş mavi gözler\n- Kederli, boş bir çığlık\n\n**Güdüler:**\n\n- Yaşayanların sıcaklığını emmek\n\n**Taktikler:**\n\n- Isıyı sezmek\n- Yaşam çeken kavrayış\n\nKuzey bölgelerinin uzun kışlarına ya da yabani fırtınalarına kurban gidenlerden bazılarına, ayazabağlı olarak korkunç bir yeni yaşam verilir. Bu diriltilmiş cesetler, ölümlerinin onlardan aldığı sıcaklığı ebediyen aramaya lanetlidir.\n\n*Görev Başlangıcı:* Bir grup ayazabağlı, bir dağ patikası boyunca pusuya yatmıştır. Bu patika, bir maden köyünden ovalara giden tek güvenli yoldur."
	},
	{
		"page": 159,
		"img": "/rulebook/dusmanlar/p159.webp",
		"title_en": "Frostbound / Haunt",
		"title_tr": "Ayazabağlı / Tayf",
		"text_en": "### YOUR TRUTH\n\nCan creatures other than Ironlanders become frostbound? If so, undeath gives them uncanny strength. Make them one rank higher than their living form.\n\n## HAUNT\n\n**Rank:** Formidable (1 progress per harm; inflicts 3 harm)\n\n**Features:**\n\n- Subtle, unsettling manifestations\n- Appear as they did in life\n- Lay bare the ravages of death\n- Stench of the grave\n\n**Drives:**\n\n- Torment the living\n- Find rest\n\n**Tactics:**\n\n- Vanish and reappear\n- Horrifying visage\n- Unleash chaos\n\nHaunts are restless spirits bound to this world by a traumatic or unjust death. They may be tied to a location, an object, or even a person.\n\nA haunt who manifests as a physical being can be dispelled by overcoming them in a fight, but only temporarily. They will only be at peace when their death is avenged or resolved. Some say a haunt can be banished through a ritual, but few possess the knowledge.\n\n*Quest Starter:* You are plagued by a haunt. Who is it? What do they want of you?\n\n### YOUR TRUTH\n\nWhen someone dies a violent death, or at the hand of another, they are often laid to rest using a specific, ceremonial rite. This, it is believed, prevents them from returning as a haunt. What is this ritual? What rare material is required?",
		"text_tr": "### SENİN GERÇEĞİN\n\nDemir Diyar sakinleri dışındaki yaratıklar ayazabağlı olabilir mi? Olabilirse, ölümsüzlük onlara tekinsiz bir güç verir. Onları yaşayan hâllerinden bir derece daha yüksek yap.\n\n## TAYF\n\n**Derece:** Zorlu (Her hasar başına 1 İlerleme; 3 hasar verir)\n\n**Özellikler:**\n\n- Belli belirsiz, tedirgin edici tezahürler\n- Yaşarken oldukları gibi görünmek\n- Ölümün tahribatını gözler önüne sermek\n- Mezar kokusu\n\n**Güdüler:**\n\n- Yaşayanlara eziyet etmek\n- Huzur bulmak\n\n**Taktikler:**\n\n- Yok olup yeniden belirmek\n- Korkunç çehre\n- Kaos saçmak\n\nTayflar, travmatik ya da haksız bir ölümle bu dünyaya bağlanmış huzursuz ruhlardır. Bir yere, bir nesneye, hatta bir kişiye bağlı olabilirler.\n\nFiziksel bir varlık olarak beliren bir tayf, bir dövüşte alt edilerek dağıtılabilir, ama yalnızca geçici olarak. Ancak ölümlerinin öcü alındığında ya da meselesi çözüldüğünde huzura ererler. Kimisi bir tayfın bir ritüelle kovulabileceğini söyler, ama bu bilgiye pek azı sahiptir.\n\n*Görev Başlangıcı:* Bir tayfın musallat olduğu birisin. Bu kim? Senden ne istiyor?\n\n### SENİN GERÇEĞİN\n\nBiri şiddetli bir ölümle ya da bir başkasının eliyle öldüğünde, çoğu zaman belirli, törensel bir ayinle defnedilir. Bunun, kişinin bir tayf olarak geri dönmesini engellediğine inanılır. Bu ritüel nedir? Hangi nadir madde gereklidir?"
	},
	{
		"page": 160,
		"img": "/rulebook/dusmanlar/p160.webp",
		"title_en": "Hollow",
		"title_tr": "Kovukvaran",
		"text_en": "## HOLLOW\n\n**Rank:** Extreme (2 ticks per harm; inflicts 4 harm)\n\n**Features:**\n\n- Vaguely humanoid shape formed of earth, plants, and insects\n- Empty black eyes behind an elven mask\n- Smells of wet soil and dead things\n\n**Drives:**\n\n- See justice done\n\n**Tactics:**\n\n- Bash with savage strength\n- Draw in a whirlwind of materials to reform and enlarge\n- Envelop and suffocate\n\nIt is said that elves who die an unjust death or have cause to seek retribution can rise as a hollow. Their form is a rippling mass of dead leaves, plants, soil, carrion, and insects. They move with a nightmarish, shambling gait. Their face is the wooden mask they wore in life. Their voice is the rattle of the wind through dry leaves.\n\nAs with haunts, they can be temporarily defeated but cannot be killed by physical means. They are a relentless force, bound to this world by a singular motivation—vengeance.\n\n*Quest Starter:* A hollow terrorizes an Ironlander village. What does it seek? What will you do to stop it?\n\n### YOUR TRUTH\n\nHow do elven communities view a risen hollow? Are they seen as spirits of righteous vengeance or as dangerous aberrations?",
		"text_tr": "## KOVUKVARAN\n\n**Derece:** Aşırı (Her hasar başına 2 çentik; 4 hasar verir)\n\n**Özellikler:**\n\n- Topraktan, bitkilerden ve böceklerden oluşmuş, belli belirsiz insansı bir biçim\n- Bir elf maskesinin ardındaki boş siyah gözler\n- Islak toprak ve ölü şeyler kokar\n\n**Güdüler:**\n\n- Adaletin yerini bulduğunu görmek\n\n**Taktikler:**\n\n- Vahşi bir güçle vurmak\n- Yeniden şekillenip büyümek için bir madde kasırgasını içine çekmek\n- Sarıp boğmak\n\nHaksız bir ölümle ölen ya da öç alma sebebi olan elflerin bir kovukvaran olarak dirilebileceği söylenir. Biçimleri; ölü yapraklardan, bitkilerden, topraktan, leşten ve böceklerden oluşan, dalgalanan bir kütledir. Kâbus gibi, sürünen bir yürüyüşle hareket ederler. Yüzleri, yaşarken taktıkları ahşap maskedir. Sesleri, rüzgârın kuru yapraklar arasındaki hışırtısıdır.\n\nTayflar gibi, geçici olarak alt edilebilir ama fiziksel araçlarla öldürülemezler. Bu dünyaya tek bir saik tarafından bağlanmış amansız bir güçtürler — intikam.\n\n*Görev Başlangıcı:* Bir kovukvaran, bir Demir Diyar köyünü dehşete salıyor. Peşinde olduğu şey nedir? Onu durdurmak için ne yapacaksın?\n\n### SENİN GERÇEĞİN\n\nElf toplulukları dirilmiş bir kovukvaranı nasıl görür? Onları haklı bir intikamın ruhları olarak mı yoksa tehlikeli sapkınlıklar olarak mı görürler?"
	},
	{
		"page": 161,
		"img": "/rulebook/dusmanlar/p161.webp",
		"title_en": "Iron Revenant",
		"title_tr": "Demir Hortlak",
		"text_en": "## IRON REVENANT\n\n**Rank:** Extreme (2 ticks per harm; inflicts 4 harm)\n\n**Features:**\n\n- Empty, patchwork shell of armor and other hunks of metal\n- Wielding iron weapons\n- A low, reverberating voice\n\n**Drives:**\n\n- Fulfill the vow\n- Destroy any who stand in their way\n\n**Tactics:**\n\n- Steadfast attacks\n- Pull in iron with an unyielding, magnetic force\n\nSome vows are held so fiercely that they survive even after death. An iron revenant is an incorporeal force of furious resolve, the unfinished vow of an Ironsworn given horrible form as a construct of metal.\n\nAttacks may slow them down or temporarily break apart their armored form, but they have no flesh to pierce and cannot be killed. An iron revenant won’t stop until their vow is fulfilled.\n\n*Quest Starter:* Someone you knew has taken form as an iron revenant. Who is it? What is their vow?",
		"text_tr": "## DEMİR HORTLAK\n\n**Derece:** Aşırı (Her hasar başına 2 çentik; 4 hasar verir)\n\n**Özellikler:**\n\n- Zırh ve başka metal parçalarından oluşan boş, yamalı bir kabuk\n- İçinde demir silahlar taşıyan\n- Alçak, yankılanan bir ses\n\n**Güdüler:**\n\n- Andı yerine getirmek\n- Yoluna çıkan herkesi yok etmek\n\n**Taktikler:**\n\n- Sarsılmaz saldırılar\n- Boyun eğmez, mıknatıssı bir kuvvetle demiri kendine çekmek\n\nKimi antlar öyle hararetle tutulur ki ölümden sonra bile yaşamaya devam eder. Demir Hortlak, öfkeli bir azmin cisimsiz gücüdür; bir Demir-Andlının tamamlanmamış andının, metalden bir yapı olarak korkunç bir biçime bürünmüş hâlidir.\n\nSaldırılar onları yavaşlatabilir ya da zırhlı biçimlerini geçici olarak parçalayabilir, ama delinecek etleri yoktur ve öldürülemezler. Bir Demir Hortlak, andı yerine gelene dek durmaz.\n\n*Görev Başlangıcı:* Tanıdığın biri bir Demir Hortlak biçimine bürünmüş. Bu kim? Andı nedir?"
	},
	{
		"page": 162,
		"img": "/rulebook/dusmanlar/p162.webp",
		"title_en": "Sodden",
		"title_tr": "Sucul",
		"text_en": "## SODDEN\n\n**Rank:** Formidable (1 progress per harm; inflicts 3 harm)\n\n**Features:**\n\n- Milky eyes\n- Mottled flesh\n\n**Drives:**\n\n- Drown the living\n\n**Tactics:**\n\n- Draw victims to the water\n- Grab and scratch with jagged claws\n- Chilling embrace\n- Drag into the depths\n\nA sodden is the restless spirit of someone who drowned or was put to rest in water. They can appear in seas, rivers, lakes, ponds, or marshes. Their loneliness and grief compels them to draw living victims into their watery lairs.\n\nA sodden is not confined to its resting place. In fact, some believe that surviving an encounter with a sodden leaves you vulnerable around any body of water until the spirit finishes its work.\n\n*Quest Starter:* Someone you know died and appears to you as a sodden. Who are they? Can anything be done to put them to rest?\n\n### YOUR TRUTH\n\nMany Ironlanders habitually perform a quick ritual when near a body of water, believing it keeps any lurking sodden at bay. What do they do? Is there any truth to this custom?",
		"text_tr": "## SUCUL\n\n**Derece:** Zorlu (Her hasar başına 1 İlerleme; 3 hasar verir)\n\n**Özellikler:**\n\n- Sütlü gözler\n- Alacalı et\n\n**Güdüler:**\n\n- Yaşayanları boğmak\n\n**Taktikler:**\n\n- Kurbanları suya çekmek\n- Pürtüklü pençelerle kavrayıp tırmalamak\n- Ürperten kucaklama\n- Derinliklere sürüklemek\n\nSucul, boğulan ya da suya defnedilen birinin huzursuz ruhudur. Denizlerde, nehirlerde, göllerde, göletlerde ya da bataklıklarda belirebilirler. Yalnızlıkları ve kederleri, onları yaşayan kurbanları sulu inlerine çekmeye zorlar.\n\nBir Sucul, istirahatgâhıyla sınırlı değildir. Hatta kimisi, bir Sucul'la karşılaşmadan sağ çıkmanın, ruh işini bitirene dek seni herhangi bir su kütlesinin yanında savunmasız bıraktığına inanır.\n\n*Görev Başlangıcı:* Tanıdığın biri öldü ve sana bir Sucul olarak görünüyor. Bu kim? Onu huzura kavuşturmak için bir şey yapılabilir mi?\n\n### SENİN GERÇEĞİN\n\nBirçok Demir Diyar sakini, bir su kütlesinin yakınındayken alışkanlıkla çabucak bir ritüel yapar; bunun pusuya yatmış herhangi bir Sucul'u uzak tuttuğuna inanır. Ne yaparlar? Bu âdetin bir doğruluk payı var mı?"
	}
];
