// Otomatik üretildi: Ironsworn Bölüm 2 "Your Character" (PDF s.42–58) sayfa-sayfa.
// Görseller static/rulebook/karakterin/*.webp; çeviri /ceviri (Opus, glossary).
import type { RulebookPage } from './types.js';

export const karakterinPages: RulebookPage[] = [
	{
		"page": 31,
		"img": "/rulebook/karakterin/p31.webp",
		"title_en": "You Are Ironsworn",
		"title_tr": "Sen Demir-Andlısın",
		"text_en": "## You Are Ironsworn\n\nOthers live out their lives hardly venturing beyond the walls of their village or steading, but you are different. Your sworn vows will lead to a life of danger, heroism, and sacrifice at the edge of the known world.\n\n### Envision Your Character\n\nBefore you jump into the mechanics of your character, consider their motivations, interests, skills, personality, and weaknesses. It's fine to start with one or two ideas about your background and goals. You can flesh out your character as you play.\n\n### Be Awesome\n\nYour character is highly competent. You're smart, brave, and driven. You can hold your own in a fight. When you Swear an Iron Vow, you mean it.\n\nYou are not without your limitations. You'll face hardship. You'll make bad decisions. You will fail. Overcoming those failures, pushing on, is what makes you heroic.\n\n### Be Who You Want\n\nThe people of the Ironlands are diverse. Communities are formed through shared interests, mutual protection, or strong leadership. Respect is still paid to traditions of the Old World, but Ironlanders largely left behind their cultural divisions when they crossed the vast northern ocean. Even within a single community, you'll find a fusion of Old World and Ironland influences.\n\nYou can envision your character however you like—unbound by geography, lineage, sexual orientation, and gender. Your character can be inspired directly by a real-world or historical culture, or you might weave a blend of cultural influences into your concept.\n\nThe default setting is human-centric, and these rules do not include specific options to play fantasy races. However, you can adjust to your liking. The mechanics of your character are relatively light and can be themed to support several types of fantasy or historical fiction.\n\n### Where to Start?\n\nYou can build your world, build your character, or do both in tandem. If you have a clear idea for your character, start there and build your world around them, as if you're building a set to suit your actor. If you need inspiration, start with the world. Chapter 4 (page 111) includes prompts for situations and quests to help you envision your character and your place in the Ironlands.",
		"text_tr": "## Sen Demir-Andlısın\n\nBaşkaları ömürlerini köylerinin ya da yerleşimlerinin (steading) duvarlarının ötesine nadiren adım atarak geçirir, ama sen farklısın. İçtiğin antlar seni bilinen dünyanın ucunda tehlike, kahramanlık ve fedakârlıkla dolu bir hayata sürükleyecek.\n\n### Karakterini Tasavvur Et\n\nKarakterinin mekaniklerine dalmadan önce onun güdülerini, ilgilerini, becerilerini, kişiliğini ve zayıflıklarını düşün. Geçmişin ve amaçların hakkında bir iki fikirle başlamak yeterlidir. Karakterini oynadıkça etiyle kemiğiyle var edebilirsin.\n\n### Olağanüstü Ol\n\nKarakterin son derece yetkindir. Zekisin, cesursun, azimlisin. Bir kavgada kendini savunabilirsin. Bir Demir Ant İçtiğinde (Swear an Iron Vow), bunu ciddiye alırsın.\n\nSınırların olmadan değilsin. Zorluklarla yüzleşeceksin. Kötü kararlar vereceksin. Başarısız olacaksın. Seni kahraman yapan şey, bu başarısızlıkların üstesinden gelmek, yürümeye devam etmektir.\n\n### İstediğin Kişi Ol\n\nDemir Diyarlar (The Ironlands) halkı çeşitlidir. Topluluklar ortak ilgiler, karşılıklı koruma ya da güçlü liderlikle kurulur. Eski Dünya (The Old World) geleneklerine hâlâ saygı gösterilir, ama Demir Diyar sakinleri o uçsuz bucaksız kuzey okyanusunu aştıklarında kültürel ayrımlarını büyük ölçüde geride bıraktılar. Tek bir topluluğun içinde bile Eski Dünya ile Demir Diyar etkilerinin bir kaynaşmasını bulursun.\n\nKarakterini istediğin gibi tasavvur edebilirsin—coğrafya, soy, cinsel yönelim ve cinsiyet seni bağlamaz. Karakterin doğrudan gerçek bir kültürden ya da tarihsel bir kültürden ilham alabilir, ya da konseptine farklı kültürel etkilerin bir harmanını dokuyabilirsin.\n\nVarsayılan ortam insan merkezlidir ve bu kurallar fantastik ırkları oynamak için özel seçenekler içermez. Yine de zevkine göre uyarlayabilirsin. Karakterinin mekanikleri görece hafiftir ve birçok fantastik ya da tarihsel kurgu türünü destekleyecek şekilde temalandırılabilir.\n\n### Nereden Başlamalı?\n\nDünyanı kurabilir, karakterini kurabilir ya da ikisini birlikte yürütebilirsin. Karakterin için net bir fikrin varsa oradan başla ve dünyanı onun etrafında inşa et; tıpkı oyuncuna uygun bir sahne kurar gibi. İlhama ihtiyacın varsa dünyadan başla. 4. Bölüm (sayfa 111), karakterini ve Demir Diyarlardaki yerini tasavvur etmene yardımcı olacak durum ve görev önerileri içerir."
	},
	{
		"page": 32,
		"img": "/rulebook/karakterin/p32.webp",
		"title_en": "Character Sheet Example",
		"title_tr": "Örnek Karakter Kâğıdı",
		"text_en": "An example character sheet for Asha Shadiya records her name, stats, and status tracks. Her stats are Edge +2, Heart +1, Iron +2, Shadow +1, and Wits +3. Her health, spirit, and supply tracks are tracked separately, along with her momentum (max +10, reset +2).\n\nHer vows include: \"Find my sister,\" \"Guide the caravan safely through the mournwood,\" and \"Kill the wyvern,\" each with its own progress track ranked from troublesome to epic.\n\nHer debilities are listed under conditions (wounded, shaken, unprepared, encumbered), banes (corrupted, maimed), and burdens (cursed, tormented)—all unmarked.\n\nShe carries three assets:\n\n**Hawk (companion).** Your hawk can aid you when it is aloft.\n- Far-seeing: When you Undertake a Journey, or when you Resupply by hunting for small game, add +1.\n- Fierce: When you Secure an Advantage +edge using your hawk to harass and distract your foes, add +1 and take +1 momentum on a hit.\n- Vigilant: When you Face Danger +wits to detect an approaching threat, or when you Enter the Fray +wits against an ambush, add +2.\n\n**Storyweaver (path).** When you Secure an Advantage, Compel, or Forge a Bond by sharing an inspiring or enlightening song, poem, or tale, envision the story you tell. Then, add +1 and take +1 momentum on a hit.\n- When you Make Camp and choose the option to relax, you may share a story with your allies or compose a new story if alone. If you do, envision the story you tell and take +1 spirit or +1 momentum. Any allies who choose to relax in your company may also take +1 spirit or +1 momentum.\n- When you Sojourn within a community with which you share a bond, add +2 (instead of +1).\n\n**Shield-Bearer (combat talent).** If you wield a shield... When you Face Danger using your shield as cover, add +1. When you Clash in close quarters, take +1 momentum on a strong hit.\n- When you bear a shield painted with a meaningful symbol, and you Endure Stress as you face off against a fearsome foe, add +1 and take +1 momentum on a hit.\n- When forced to Endure Harm in a fight, you may instead sacrifice your shield and ignore all harm. If you do, your shield is destroyed or will require extensive repair; suffer -2 momentum.",
		"text_tr": "Asha Shadiya için örnek bir karakter kâğıdı; adını, statlarını ve durum izlerini kaydeder. Statları: Edge +2, Heart +1, Iron +2, Shadow +1, Wits +3. Can (Health), Ruh (Spirit) ve İkmal (Supply) izleri ayrı ayrı işlenir; Momentum da öyle (azami +10, sıfırlama +2).\n\nAntları şunlardır: \"Kız kardeşimi bul,\" \"Kervanı yas ormanından sağ salim geçir\" ve \"Wyvern'i öldür\"; her biri kendi İlerleme İzine (Progress Track) sahip olup Sıradan'dan Destansı'ya kadar derecelendirilmiştir.\n\nOlumsuz etkileri (debilities) durumlar (yaralı, yıkılmış, hazırlıksız, yüklü), belalar (yozlaşmış, sakat) ve yükler (lanetli, ezilmiş) altında listelenir—hepsi işaretsizdir.\n\nÜç Yetenek Kartı (Asset) taşır:\n\n**Şahin (Yoldaş).** Şahinin havadayken sana yardım edebilir.\n- Uzak Gören: Yolculuğa Çıktığında ya da küçük av peşinde İkmal Et yaptığında, +1 ekle.\n- Vahşi: Düşmanlarını taciz edip dikkatlerini dağıtmak için şahinini kullanarak Avantaj Sağla +edge yaptığında, +1 ekle ve başarıda +1 momentum al.\n- Tetikte: Yaklaşan bir tehdidi sezmek için Tehlikeyle Yüzleş +wits yaptığında ya da bir pusuya karşı Savaşa Gir +wits yaptığında, +2 ekle.\n\n**Öykü Dokuyucu (Yol).** İlham verici ya da aydınlatıcı bir şarkı, şiir veya öykü paylaşarak Avantaj Sağla, İkna Et ya da Bağ Kur yaptığında, anlattığın hikâyeyi tasavvur et. Sonra +1 ekle ve başarıda +1 momentum al.\n- Kamp Kur yapıp dinlenme seçeneğini seçtiğinde, müttefiklerinle bir hikâye paylaşabilir ya da yalnızsan yeni bir hikâye yazabilirsin. Bunu yaparsan anlattığın hikâyeyi tasavvur et ve +1 Ruh ya da +1 momentum al. Yanında dinlenmeyi seçen müttefikler de +1 Ruh ya da +1 momentum alabilir.\n- Bağ paylaştığın bir toplulukta Konaklama yaptığında, +2 ekle (+1 yerine).\n\n**Kalkan Taşıyıcısı (Savaş Yeteneği).** Bir kalkan kuşandıysan... Kalkanını siper olarak kullanarak Tehlikeyle Yüzleş yaptığında, +1 ekle. Yakın mesafede Çatış yaptığında, güçlü başarıda +1 momentum al.\n- Anlamlı bir sembolle boyanmış bir kalkan taşıdığında ve korkunç bir düşmanla karşı karşıya gelirken Strese Katlan yaptığında, +1 ekle ve başarıda +1 momentum al.\n- Bir kavgada Hasara Katlan yapmaya zorlandığında, bunun yerine kalkanını feda edip tüm hasarı yok sayabilirsin. Bunu yaparsan kalkanın paramparça olur ya da uzun bir tamir gerektirir; -2 momentum çek."
	},
	{
		"page": 33,
		"img": "/rulebook/karakterin/p33.webp",
		"title_en": "Character Basics",
		"title_tr": "Karakterin Temelleri",
		"text_en": "## Character Basics\n\n### Name\n\nYou have a name. Perhaps others will honor it someday in stories and songs. Give your character a name. For inspiration, you can roll on the Ironlander Names tables on page 184.\n\n### Stats\n\nThere are five stats. Each is given a value from 1 to 3. When you make a move and roll dice, you usually add one of your stats to your action die. The move will tell you which stat to add, or give you a choice.\n\n- **Edge:** Quickness, agility, and prowess in ranged combat.\n- **Heart:** Courage, willpower, empathy, sociability, and loyalty.\n- **Iron:** Physical strength, endurance, aggressiveness, and prowess in close combat.\n- **Shadow:** Sneakiness, deceptiveness, and cunning.\n- **Wits:** Expertise, knowledge, and observation.\n\nTo start, arrange these bonuses across your five stats in any order: 3, 2, 2, 1, 1.\n\n### Health\n\nHealth represents your current physical condition and stamina, ranked from 0 to +5. Health is reduced when you Endure Harm (page 91), and increased when you rest or receive care through moves such as Heal (page 63) or Sojourn (page 71).\n\nIf you are at 0 health, scoring a miss when you Endure Harm puts you at risk of suffering a debility or dying.\n\nTo start, set your health track to +5.",
		"text_tr": "## Karakterin Temelleri\n\n### İsim\n\nBir adın var. Belki bir gün başkaları onu hikâyelerde ve şarkılarda anacak. Karakterine bir ad ver. İlham için sayfa 184'teki Demir Diyar İsimleri tablolarında zar atabilirsin.\n\n### Statlar (Stats)\n\nBeş stat vardır. Her birine 1 ile 3 arasında bir değer verilir. Bir Hamle (Move) yapıp zar attığında, genellikle statlarından birini eylem zarına eklersin. Hamle, hangi statı ekleyeceğini söyler ya da sana bir seçenek verir.\n\n- **Edge:** Çabukluk, çeviklik ve menzilli dövüşte ustalık.\n- **Heart:** Cesaret, irade gücü, empati, sosyallik ve sadakat.\n- **Iron:** Bedensel güç, dayanıklılık, saldırganlık ve yakın dövüşte ustalık.\n- **Shadow:** Sinsilik, hilekârlık ve kurnazlık.\n- **Wits:** Uzmanlık, bilgi ve gözlem.\n\nBaşlangıç için bu bonusları beş statına istediğin sırada dağıt: 3, 2, 2, 1, 1.\n\n### Can (Health)\n\nCan, o anki bedensel durumunu ve dayanma gücünü temsil eder; 0 ile +5 arasında derecelendirilir. Hasara Katlan (sayfa 91) yaptığında Can azalır; dinlendiğinde ya da Şifa Bul (sayfa 63) veya Konaklama (sayfa 71) gibi hamlelerle bakım gördüğünde artar.\n\n0 Can'daysan, Hasara Katlan yaptığında başarısızlık atman seni bir olumsuz etki çekme ya da ölme riskiyle karşı karşıya bırakır.\n\nBaşlangıç için Can izini +5'e ayarla."
	},
	{
		"page": 34,
		"img": "/rulebook/karakterin/p34.webp",
		"title_en": "Spirit and Supply",
		"title_tr": "Ruh ve İkmal",
		"text_en": "### Spirit\n\nSpirit is your current mental state, ranked from 0 to +5. Spirit is reduced when you Endure Stress (page 95). It is increased when you find comfort in companionship, success, or relaxed moments through moves such as Make Camp (page 64) or Forge a Bond (page 74).\n\nIf you are at 0 spirit, scoring a miss when you Endure Stress puts you at risk of suffering a debility or falling into desolation.\n\nTo start, set your spirit track to +5.\n\n### Supply\n\nSupply is an abstract representation of your preparedness, including ammo, food, water, and general upkeep. It is ranked from 0 to +5. Instead of keeping track of a detailed inventory, you can consider most of your mundane gear as covered under supply.\n\nSupply is decreased when you make the Undertake a Journey move (page 65). You might also reduce supply as a narrative cost when you face hardships as an outcome of other moves. For example, if you make the Face Danger move (page 60) to ford a wild river, you might lose some gear as a result of a weak hit or miss. Supply is increased when you gather provisions through moves such as Resupply (page 63).\n\nThe supply track represents the shared assets among your party. You and your allies use the same supply value while you travel together. If any of you make a move to increase supply, or suffer the result of a move that reduces your supply, each of you adjust your supply track accordingly.\n\nWhen your supply falls to 0, all characters make the Out of Supply move (page 97). If you are at 0 supply and suffer additional -supply, you each must reduce your health, spirit, or momentum tracks by that amount.\n\nTo start, set your supply track to +5. You and your allies share the same supply value while you adventure together. When one of you makes a move that raises or lowers the supply track, each of you should make the adjustment on your character sheet.",
		"text_tr": "### Ruh (Spirit)\n\nRuh, o anki zihinsel durumundur; 0 ile +5 arasında derecelendirilir. Strese Katlan (sayfa 95) yaptığında Ruh azalır. Yoldaşlıkta, başarıda ya da huzurlu anlarda Kamp Kur (sayfa 64) veya Bağ Kur (sayfa 74) gibi hamlelerle teselli bulduğunda artar.\n\n0 Ruh'taysan, Strese Katlan yaptığında başarısızlık atman seni bir olumsuz etki çekme ya da yıkıma (desolation) düşme riskiyle karşı karşıya bırakır.\n\nBaşlangıç için Ruh izini +5'e ayarla.\n\n### İkmal (Supply)\n\nİkmal; cephane, yiyecek, su ve genel bakımı içeren hazırlığının soyut bir temsilidir. 0 ile +5 arasında derecelendirilir. Ayrıntılı bir envanter tutmak yerine, sıradan teçhizatının çoğunu İkmal kapsamında sayabilirsin.\n\nYolculuğa Çık hamlesini (sayfa 65) yaptığında İkmal azalır. Başka hamlelerin sonucu olarak zorluklarla yüzleştiğinde de İkmal'i anlatısal bir bedel olarak düşürebilirsin. Örneğin, azgın bir nehri geçmek için Tehlikeyle Yüzleş hamlesini (sayfa 60) yaparsan, zayıf bir başarı ya da başarısızlık sonucu bir kısım teçhizatını kaybedebilirsin. İkmal Et (sayfa 63) gibi hamlelerle erzak topladığında İkmal artar.\n\nİkmal izi, grubunuzdaki ortak kaynakları temsil eder. Sen ve müttefiklerin birlikte yol alırken aynı İkmal değerini kullanırsınız. İçinizden biri İkmal'i artıran bir hamle yapar ya da İkmal'inizi azaltan bir hamlenin sonucunu çekerse, her biriniz İkmal izini buna göre ayarlar.\n\nİkmal'in 0'a düştüğünde, tüm karakterler İkmal Tükendi hamlesini (sayfa 97) yapar. 0 İkmal'deysen ve ek -ikmal çekersen, her biriniz Can, Ruh ya da Momentum izlerini o kadar düşürmelidir.\n\nBaşlangıç için İkmal izini +5'e ayarla. Sen ve müttefiklerin birlikte maceraya atılırken aynı İkmal değerini paylaşırsınız. İçinizden biri İkmal izini yükselten ya da düşüren bir hamle yaptığında, her biriniz bu ayarlamayı kendi karakter kâğıdında yapmalıdır."
	},
	{
		"page": 35,
		"img": "/rulebook/karakterin/p35.webp",
		"title_en": "Momentum and Vows",
		"title_tr": "Momentum ve Antlar",
		"text_en": "### Momentum\n\nMomentum represents how you are faring in your quests. It is gained and lost through moves. If you have positive momentum, you are building on your successes and ready to make decisive moves. If you have negative momentum, you have suffered setbacks and your quest is in jeopardy.\n\nTo learn more about momentum and how it helps and hinders your character, see page 11.\n\nUse the momentum track on the left side of your character sheet to record your current momentum. Your character sheet also includes boxes to mark your max momentum and momentum reset.\n\n- Your max momentum starts at +10, and is reduced by one for every marked debility.\n- Your momentum reset starts at +2. If you have one debility marked, your reset is +1. If you have more than one debility marked, your reset is 0.\n\nTo learn more about debilities, see page 36.\n\nTo start, set your current momentum to +2, your max momentum to +10, and your momentum reset to +2.\n\n### Vows\n\nWhen you Swear an Iron Vow (page 98), you give it a rank (troublesome, dangerous, formidable, extreme, or epic), and record it on your character sheet. You then use a vow progress track to mark when you Reach a Milestone (page 100).\n\nYou should start your first session with two vows: A long term goal (your background vow) and an immediate situation which must be dealt with (your inciting incident). You'll find quest starters in chapter 4 - 'Your World' (page 111) and chapter 5 - 'Foes and Encounters' (page 133).\n\nTo learn more about your starting vows, see page 195.",
		"text_tr": "### Momentum\n\nMomentum, görevlerinde nasıl gittiğini temsil eder. Hamlelerle kazanılır ve kaybedilir. Pozitif momentumun varsa, başarılarının üstüne koyuyorsun ve belirleyici hamleler yapmaya hazırsın demektir. Negatif momentumun varsa, aksilikler yaşamışsın ve görevin tehlikededir.\n\nMomentum hakkında ve karakterine nasıl yardım edip engel olduğu konusunda daha fazla bilgi için sayfa 11'e bak.\n\nGüncel momentumunu kaydetmek için karakter kâğıdının sol tarafındaki momentum izini kullan. Karakter kâğıdın ayrıca azami momentumunu ve momentum sıfırlamanı işaretleyecek kutular içerir.\n\n- Azami momentumun +10'dan başlar ve işaretli her olumsuz etki için bir azalır.\n- Momentum sıfırlaman +2'den başlar. Bir olumsuz etki işaretliyse, sıfırlaman +1 olur. Birden fazla olumsuz etki işaretliyse, sıfırlaman 0 olur.\n\nOlumsuz etkiler hakkında daha fazla bilgi için sayfa 36'ya bak.\n\nBaşlangıç için güncel momentumunu +2'ye, azami momentumunu +10'a ve momentum sıfırlamanı +2'ye ayarla.\n\n### Antlar (Vows)\n\nBir Demir Ant İçtiğinde (sayfa 98), ona bir derece verirsin (sıradan, tehlikeli, zorlu, aşırı ya da destansı) ve karakter kâğıdına kaydedersin. Sonra bir Dönüm Noktasına Ulaştığında (sayfa 100) işaretlemek için bir ant ilerleme izi kullanırsın.\n\nİlk oturumuna iki antla başlamalısın: uzun vadeli bir amaç (geçmiş antın) ve hemen ele alınması gereken acil bir durum (seni harekete geçiren olay). Görev başlangıçlarını 4. Bölüm - 'Dünyan' (sayfa 111) ve 5. Bölüm - 'Düşmanlar ve Karşılaşmalar' (sayfa 133) içinde bulacaksın.\n\nBaşlangıç antların hakkında daha fazla bilgi için sayfa 195'e bak."
	},
	{
		"page": 36,
		"img": "/rulebook/karakterin/p36.webp",
		"title_en": "Bonds and Debilities",
		"title_tr": "Bağlar ve Olumsuz Etkiler",
		"text_en": "### Bonds\n\nAs you build relationships and complete quests in the service of others, you create bonds by making the Forge a Bond move (page 74).\n\nBonds provide narrative texture to your world by fleshing out other characters and communities. They give you places to return to, and people to reconnect with, when your life as Ironsworn has taken its toll. Bonds also provide mechanical benefits when you act within a community or interact with someone with whom you share a bond. For example, the Sojourn move (page 71) gives you a bonus to your action roll if you have a bond with that community.\n\nThe bonds progress track on your character sheet represents the connections you have made. When you successfully Forge a Bond, you mark progress (one tick). When your time as Ironsworn is done, you Write Your Epilogue (page 77). When you make that move, you tally the number of filled boxes on your bonds progress track as your progress score. See page 14 to learn more about progress tracks and progress moves.\n\nYou should start your first session with up to three background bonds. Make a note of the people or communities you share bonds with, and mark up to three ticks on your bond progress track. To learn more about your first session and your starting bonds, see page 193.\n\n### Debilities\n\nAs you suffer hardships and setbacks in your quests, you may need to mark debilities as a result of moves or narrative events. Moves will tell you which debility to mark, or give you a choice. Debilities represent temporary, long-term, and permanent disadvantages. Some can be easily cleared through an appropriate move. Others will forever become a part of your character.\n\nDebilities should have a narrative impact on how you envision your character's actions and how others react to you. They also have a mechanical impact by reducing your momentum track.\n\n- Each marked debility reduces your max momentum by 1.\n- If you have one marked debility, your momentum reset is +1 instead of +2.\n- If you have more than one marked debility, your momentum reset is 0.",
		"text_tr": "### Bağlar (Bonds)\n\nİlişkiler kurdukça ve başkalarının hizmetinde görevleri tamamladıkça, Bağ Kur hamlesini (sayfa 74) yaparak bağlar yaratırsın.\n\nBağlar, diğer karakterleri ve toplulukları etiyle kemiğiyle var ederek dünyana anlatısal doku katar. Demir-Andlı yaşamın bedelini ödettiğinde, geri dönecek yerler ve yeniden bağ kuracak insanlar sunar. Bağlar ayrıca bir topluluk içinde davrandığında ya da bağ paylaştığın biriyle etkileşime girdiğinde mekanik faydalar sağlar. Örneğin, o toplulukla bir bağın varsa Konaklama hamlesi (sayfa 71) eylem zarına bonus verir.\n\nKarakter kâğıdındaki bağlar ilerleme izi, kurduğun bağlantıları temsil eder. Bağ Kur'u başarıyla yaptığında ilerleme işaretlersin (bir çentik). Demir-Andlı olarak zamanın dolduğunda, Sonsözünü Yaz (sayfa 77) yaparsın. O hamleyi yaptığında, bağlar ilerleme izindeki dolu kutuların sayısını ilerleme puanın olarak sayarsın. İlerleme izleri ve ilerleme hamleleri hakkında daha fazla bilgi için sayfa 14'e bak.\n\nİlk oturumuna en fazla üç geçmiş bağla başlamalısın. Bağ paylaştığın insanları ya da toplulukları not et ve bağ ilerleme izine en fazla üç çentik işaretle. İlk oturumun ve başlangıç bağların hakkında daha fazla bilgi için sayfa 193'e bak.\n\n### Olumsuz Etkiler (Debilities)\n\nGörevlerinde zorluklar ve aksilikler yaşadıkça, hamlelerin ya da anlatısal olayların sonucu olarak olumsuz etkiler işaretlemen gerekebilir. Hamleler, hangi olumsuz etkiyi işaretleyeceğini söyler ya da sana bir seçenek verir. Olumsuz etkiler geçici, uzun vadeli ve kalıcı dezavantajları temsil eder. Bazıları uygun bir hamleyle kolayca temizlenebilir. Bazıları ise sonsuza dek karakterinin bir parçası olur.\n\nOlumsuz etkiler, karakterinin eylemlerini nasıl tasavvur ettiğine ve başkalarının sana nasıl tepki verdiğine anlatısal bir etki yapmalıdır. Ayrıca momentum izini düşürerek mekanik bir etki de yaparlar.\n\n- İşaretli her olumsuz etki azami momentumunu 1 düşürür.\n- Bir olumsuz etkin işaretliyse, momentum sıfırlaman +2 yerine +1 olur.\n- Birden fazla olumsuz etkin işaretliyse, momentum sıfırlaman 0 olur."
	},
	{
		"page": 37,
		"img": "/rulebook/karakterin/p37.webp",
		"title_en": "Conditions",
		"title_tr": "Durumlar",
		"text_en": "## Conditions\n\n- **Wounded** may be marked when you are at 0 health and fail to Endure Harm (page 91). You are severely injured and need treatment to recover.\n- **Shaken** may be marked when you are at 0 spirit and fail to Endure Stress (page 95). You are despairing or distraught, and need comfort to recover.\n- **Unprepared** is marked when you are at 0 supply and are Out of Supply (page 97). You and your allies share the same supply value, and will mark unprepared together.\n- **Encumbered** is marked as appropriate to the circumstances when you are carrying excessive or cumbersome weight.\n\nAs with all debilities, conditions impact your max momentum and momentum reset. In addition, if you are wounded, shaken, or unprepared, you cannot increase the associated track.\n\n- If you are wounded, you cannot increase health.\n- If you are shaken, you cannot increase spirit.\n- If you are unprepared, you cannot increase supply.\n\nIf a move gives you an opportunity to raise your health, spirit, or supply while the associated condition is marked, you can't take that option. You must clear the condition before improving the related status track.\n\nWounded, shaken, and unprepared can be cleared when you succeed on appropriate moves. For example, scoring a hit on the Heal move (page 63) can clear the wounded condition. The shaken and unprepared conditions can generally only be cleared as you find fellowship and gather provisions in a community through the Sojourn move (page 71). Once you clear a condition, you restore your max momentum and momentum reset, and you can once again increase the associated track through moves.\n\nUnlike other conditions, encumbered is not specifically triggered or resolved by a move. Instead, it should be marked when appropriate to the circumstances. For example, you would mark encumbered if you are carrying an unconscious ally to safety in a perilous situation. Encumbered can also be triggered by the Ironclad asset, which allows you to gain an advantage for heavy armor in exchange for marking the condition. Encumbered is cleared when you lighten your load.",
		"text_tr": "## Durumlar (Conditions)\n\n- **Yaralı (Wounded)**, 0 Can'dayken Hasara Katlan (sayfa 91) yapıp başarısız olduğunda işaretlenebilir. Ağır yaralandın ve iyileşmek için tedaviye ihtiyacın var.\n- **Yıkılmış (Shaken)**, 0 Ruh'tayken Strese Katlan (sayfa 95) yapıp başarısız olduğunda işaretlenebilir. Umutsuz ya da perişan haldesin ve iyileşmek için teselliye ihtiyacın var.\n- **Hazırlıksız (Unprepared)**, 0 İkmal'deyken İkmal Tükendi (sayfa 97) olduğunda işaretlenir. Sen ve müttefiklerin aynı İkmal değerini paylaşırsınız ve hazırlıksızı birlikte işaretlersiniz.\n- **Yüklü (Encumbered)**, aşırı ya da hantal bir ağırlık taşıdığında koşullara uygun olarak işaretlenir.\n\nTüm olumsuz etkilerde olduğu gibi, durumlar da azami momentumunu ve momentum sıfırlamanı etkiler. Ayrıca yaralı, yıkılmış ya da hazırlıksızsan, ilgili izi artıramazsın.\n\n- Yaralıysan, Can artıramazsın.\n- Yıkılmışsan, Ruh artıramazsın.\n- Hazırlıksızsan, İkmal artıramazsın.\n\nİlgili durum işaretliyken bir hamle sana Can'ını, Ruh'unu ya da İkmal'ini yükseltme fırsatı verirse, o seçeneği alamazsın. İlgili durum izini iyileştirmeden önce durumu temizlemelisin.\n\nYaralı, yıkılmış ve hazırlıksız, uygun hamlelerde başarılı olduğunda temizlenebilir. Örneğin, Şifa Bul hamlesinde (sayfa 63) başarı atmak yaralı durumunu temizleyebilir. Yıkılmış ve hazırlıksız durumları genellikle ancak bir toplulukta Konaklama hamlesiyle (sayfa 71) yoldaşlık bulup erzak topladığında temizlenebilir. Bir durumu temizledikten sonra azami momentumunu ve momentum sıfırlamanı geri kazanırsın ve ilgili izi hamlelerle yeniden artırabilirsin.\n\nDiğer durumların aksine, yüklü belirli bir hamleyle tetiklenmez ya da çözülmez. Bunun yerine koşullara uygun olduğunda işaretlenmelidir. Örneğin, tehlikeli bir durumda baygın bir müttefiki güvenli bir yere taşıyorsan yüklü işaretlersin. Yüklü, ağır zırh için bir avantaj kazanmana karşılık bu durumu işaretlemeni gerektiren Zırhlı yetenek kartıyla da tetiklenebilir. Yüklü, yükünü hafiflettiğinde temizlenir."
	},
	{
		"page": 38,
		"img": "/rulebook/karakterin/p38.webp",
		"title_en": "Banes and Burdens",
		"title_tr": "Belalar ve Yükler",
		"text_en": "## Banes\n\n- **Maimed** may be marked when you are at 0 health and fail to Endure Harm (page 91). You have suffered a wound which causes you ongoing physical challenges, such as the loss of an eye or hand. Or, you bear horrific scars which serve as a constant reminder of your failures.\n- **Corrupted** may be marked when you are at 0 spirit and fail to Endure Stress (page 95). Your experiences have left you emotionally scarred. You are at the threshold of losing yourself to darkness.\n\nBanes are permanent. They forever impact your character through the momentum penalty and—more importantly—through the narrative impact of being maimed or corrupted. You should factor this debility into how you perform moves and how you interact with the world. You may have physical or emotional limitations you must cope with. Your outlook may change. Your goals and methods may change. How others behave toward you may change.\n\nIf you are maimed, envision the injury and make note of it. Consider how this impacts your approach when facing physical challenges, and weave it into your roleplaying and the narrative of your moves.\n\nWhen you are corrupted, envision how this impacts your personality and motivations. You might struggle with a new compulsion, quirk, or fear. You might even bear a physical, supernatural sign of the corruption. If so, what is it?\n\n## Burdens\n\n- **Cursed** is marked when you Face Death (page 93) and return with a soul-bound quest. This burden can only be cleared by completing the quest.\n- **Tormented** is marked when you Face Desolation (page 96) and undertake a quest to prevent a dire future.\n\nBurdens are a result of life-changing experiences that leave you bound to quests. Clearing a burden can only be accomplished by resolving the quest. When you are cursed or tormented, you should consider the physical or emotional manifestations of these conditions. You have walked the lands beyond death or suffered visions of your greatest fears. What signs do you bear? How do these experiences affect your relationships?\n\nWhen you create your character, all debilities should be unmarked.",
		"text_tr": "## Belalar (Banes)\n\n- **Sakat (Maimed)**, 0 Can'dayken Hasara Katlan (sayfa 91) yapıp başarısız olduğunda işaretlenebilir. Bir göz ya da elin kaybı gibi, sana sürekli bedensel zorluklar yaşatan bir yara aldın. Ya da başarısızlıklarının daimi bir hatırlatıcısı olan korkunç yara izleri taşıyorsun.\n- **Yozlaşmış (Corrupted)**, 0 Ruh'tayken Strese Katlan (sayfa 95) yapıp başarısız olduğunda işaretlenebilir. Yaşadıkların seni duygusal olarak yaralı bıraktı. Kendini karanlığa kaptırmanın eşiğindesin.\n\nBelalar kalıcıdır. Momentum cezasıyla ve—daha da önemlisi—sakat ya da yozlaşmış olmanın anlatısal etkisiyle karakterini sonsuza dek etkilerler. Bu olumsuz etkiyi, hamleleri nasıl yaptığına ve dünyayla nasıl etkileşime girdiğine katmalısın. Başa çıkman gereken bedensel ya da duygusal sınırlamaların olabilir. Bakış açın değişebilir. Amaçların ve yöntemlerin değişebilir. Başkalarının sana karşı davranışı değişebilir.\n\nSakatsan, yaralanmayı tasavvur et ve not al. Bunun bedensel zorluklarla yüzleşirken yaklaşımını nasıl etkilediğini düşün ve rol yapışına ve hamlelerinin anlatısına dokur.\n\nYozlaşmışsan, bunun kişiliğini ve güdülerini nasıl etkilediğini tasavvur et. Yeni bir takıntı, tuhaflık ya da korkuyla boğuşuyor olabilirsin. Hatta yozlaşmanın bedensel, doğaüstü bir işaretini taşıyor olabilirsin. Öyleyse, nedir bu?\n\n## Yükler (Burdens)\n\n- **Lanetli (Cursed)**, Ölümle Yüzleş (sayfa 93) yapıp ruhuna bağlı bir görevle döndüğünde işaretlenir. Bu yük yalnızca görevi tamamlayarak temizlenebilir.\n- **Ezilmiş (Tormented)**, Yıkımla Yüzleş (sayfa 96) yapıp korkunç bir geleceği önlemek için bir göreve giriştiğinde işaretlenir.\n\nYükler, seni görevlere bağlayan, hayatını değiştiren deneyimlerin sonucudur. Bir yükü temizlemek yalnızca görevi çözerek başarılabilir. Lanetli ya da ezilmişken, bu durumların bedensel ya da duygusal tezahürlerini düşünmelisin. Ölümün ötesindeki diyarlarda yürüdün ya da en büyük korkularının imgelerini çektin. Hangi işaretleri taşıyorsun? Bu deneyimler ilişkilerini nasıl etkiliyor?\n\nKarakterini yarattığında, tüm olumsuz etkiler işaretsiz olmalıdır."
	},
	{
		"page": 39,
		"img": "/rulebook/karakterin/p39.webp",
		"title_en": "Assets",
		"title_tr": "Yetenek Kartları",
		"text_en": "## Assets\n\nAssets represent your background, skills, and traits. They give you additional options and bonuses when making a move—or sometimes act as their own self-contained moves.\n\nAssets provide both mechanical and narrative benefits. For example, if you are an Herbalist, you gain bonuses to your moves when treating injuries or sicknesses. You can envision your character identifying plants, diagnosing rare illnesses, and summoning up obscure facts about herbal remedies. Even when you aren't making moves, your role colors the interests and manner of your character. Also, your expertise might offer story possibilities and new quests as you interact with others in need of your services.\n\nIronsworn assets are formatted as printable cards, available for download at ironswornrpg.com. Put them alongside your character sheet for easy reference. Each asset card includes three abilities.\n\n### Asset Types\n\nThere are four types of assets: Companions, paths, combat talents, and rituals. You can mix-and-match assets as you like—whatever fits your vision for your character and their experiences and goals.\n\n### Companions\n\n**Hawk (companion).** Your hawk can aid you when it is aloft.\n- Far-seeing: When you Undertake a Journey, or when you Resupply by hunting for small game, add +1.\n- Fierce: When you Secure an Advantage +edge using your hawk to harass and distract your foes, add +1 and take +1 momentum on a hit.\n- Vigilant: When you Face Danger +wits to detect an approaching threat, or when you Enter the Fray +wits against an ambush, add +2.\n\nCompanions are your NPC helpers. When you acquire a companion, give them a name and envision their appearance and personality. If they don't have a starting ability, choose one. Upgrading a companion enables additional abilities. Companions utilize a health track and may suffer harm as a result of one of your moves. When your companion takes damage, make the Companion Endure Harm move (page 94) to determine the outcome. See page 43 to learn more.",
		"text_tr": "## Yetenek Kartları (Assets)\n\nYetenek Kartları geçmişini, becerilerini ve özelliklerini temsil eder. Bir Hamle yaparken sana ek seçenekler ve bonuslar verir—ya da bazen kendi başlarına birer hamle gibi işlerler.\n\nYetenek Kartları hem mekanik hem anlatısal faydalar sağlar. Örneğin bir Şifacı Otçuysan, yaraları ya da hastalıkları tedavi ederken hamlelerine bonus kazanırsın. Karakterini bitkileri tanırken, nadir hastalıkları teşhis ederken ve bitkisel ilaçlara dair gizli kalmış bilgileri ortaya çıkarırken tasavvur edebilirsin. Hamle yapmadığın zamanlarda bile, rolün karakterinin ilgilerine ve tavrına renk katar. Ayrıca uzmanlığın, hizmetlerine ihtiyaç duyan başkalarıyla etkileşime girdiğinde hikâye olanakları ve yeni görevler sunabilir.\n\n*Ironsworn* yetenek kartları, ironswornrpg.com adresinden indirilebilen yazdırılabilir kartlar olarak biçimlendirilmiştir. Kolay başvuru için onları karakter kâğıdının yanına koy. Her yetenek kartı üç yetenek içerir.\n\n### Yetenek Kartı Türleri\n\nDört tür yetenek kartı vardır: Yoldaşlar, yollar, savaş yetenekleri ve ritüeller. Yetenek kartlarını istediğin gibi karıştırıp eşleştirebilirsin—karakterinle, deneyimleriyle ve amaçlarıyla ilgili tasavvuruna ne uyuyorsa.\n\n### Yoldaşlar (Companions)\n\n**Şahin (Yoldaş).** Şahinin havadayken sana yardım edebilir.\n- Uzak Gören: Yolculuğa Çıktığında ya da küçük av peşinde İkmal Et yaptığında, +1 ekle.\n- Vahşi: Düşmanlarını taciz edip dikkatlerini dağıtmak için şahinini kullanarak Avantaj Sağla +edge yaptığında, +1 ekle ve başarıda +1 momentum al.\n- Tetikte: Yaklaşan bir tehdidi sezmek için Tehlikeyle Yüzleş +wits yaptığında ya da bir pusuya karşı Savaşa Gir +wits yaptığında, +2 ekle.\n\nYoldaşlar senin OYK yardımcılarındır. Bir Yoldaş edindiğinde ona bir ad ver, görünüşünü ve kişiliğini tasavvur et. Başlangıç yeteneği yoksa birini seç. Bir Yoldaşı geliştirmek ek yetenekler açar. Yoldaşlar bir Can izi kullanır ve hamlelerinden birinin sonucu olarak hasar görebilir. Yoldaşın hasar aldığında, sonucu belirlemek için Yoldaş Hasara Katlan hamlesini (sayfa 94) yap. Daha fazlası için sayfa 43'e bak."
	},
	{
		"page": 40,
		"img": "/rulebook/karakterin/p40.webp",
		"title_en": "Paths and Combat Talents",
		"title_tr": "Yollar ve Savaş Yetenekleri",
		"text_en": "## Paths\n\nPaths represent your background, interests, training, and skills. They provide mechanical and narrative advantages, but also reflect who you are and how you interact with the world. For example, a Ritualist would likely have a different outlook than a Veteran. Choosing both those paths can reflect an evolution of your character or an interesting background.\n\n**Storyweaver (path).** When you Secure an Advantage, Compel, or Forge a Bond by sharing an inspiring or enlightening song, poem, or tale, envision the story you tell. Then, add +1 and take +1 momentum on a hit.\n- When you Make Camp and choose the option to relax, you may share a story with your allies or compose a new story if alone. If you do, envision the story you tell and take +1 spirit or +1 momentum. Any allies who choose to relax in your company may also take +1 spirit or +1 momentum.\n- When you Sojourn within a community with which you share a bond, add +2 (instead of +1).\n\n## Combat Talents\n\nIronsworn characters are assumed to be skilled fighters. Even without a combat talent, you can wield weapons and perform combat moves (page 78). A combat talent reflects a particular area of expertise, and gives you additional options and bonuses. Combat talent assets typically require you to wield a specific weapon, as noted in the asset text. For example, if you are a Shield-Bearer and don't have a shield at the ready, you can't use the asset's abilities.\n\n**Shield-Bearer (combat talent).** If you wield a shield... When you Face Danger using your shield as cover, add +1. When you Clash in close quarters, take +1 momentum on a strong hit.\n- When you bear a shield painted with a meaningful symbol, and you Endure Stress as you face off against a fearsome foe, add +1 and take +1 momentum on a hit.\n- When forced to Endure Harm in a fight, you may instead sacrifice your shield and ignore all harm. If you do, your shield is destroyed or will require extensive repair; suffer -2 momentum.",
		"text_tr": "## Yollar (Paths)\n\nYollar; geçmişini, ilgilerini, eğitimini ve becerilerini temsil eder. Mekanik ve anlatısal avantajlar sağlarlar, ama aynı zamanda kim olduğunu ve dünyayla nasıl etkileşime girdiğini de yansıtırlar. Örneğin bir Ritüelci'nin bakış açısı muhtemelen bir Kıdemli Savaşçı'nınkinden farklı olurdu. Her iki yolu da seçmek karakterinin bir gelişimini ya da ilginç bir geçmişi yansıtabilir.\n\n**Öykü Dokuyucu (Yol).** İlham verici ya da aydınlatıcı bir şarkı, şiir veya öykü paylaşarak Avantaj Sağla, İkna Et ya da Bağ Kur yaptığında, anlattığın hikâyeyi tasavvur et. Sonra +1 ekle ve başarıda +1 momentum al.\n- Kamp Kur yapıp dinlenme seçeneğini seçtiğinde, müttefiklerinle bir hikâye paylaşabilir ya da yalnızsan yeni bir hikâye yazabilirsin. Bunu yaparsan anlattığın hikâyeyi tasavvur et ve +1 Ruh ya da +1 momentum al. Yanında dinlenmeyi seçen müttefikler de +1 Ruh ya da +1 momentum alabilir.\n- Bağ paylaştığın bir toplulukta Konaklama yaptığında, +2 ekle (+1 yerine).\n\n## Savaş Yetenekleri (Combat Talents)\n\n*Ironsworn* karakterlerinin yetenekli dövüşçüler olduğu varsayılır. Bir savaş yeteneğin olmasa bile silah kuşanabilir ve savaş hamleleri (sayfa 78) yapabilirsin. Bir savaş yeteneği belirli bir uzmanlık alanını yansıtır ve sana ek seçenekler ve bonuslar verir. Savaş yeteneği kartları, kart metninde belirtildiği gibi, genellikle belirli bir silah kuşanmanı gerektirir. Örneğin bir Kalkan Taşıyıcısı'san ve elinin altında bir kalkan yoksa, kartın yeteneklerini kullanamazsın.\n\n**Kalkan Taşıyıcısı (Savaş Yeteneği).** Bir kalkan kuşandıysan... Kalkanını siper olarak kullanarak Tehlikeyle Yüzleş yaptığında, +1 ekle. Yakın mesafede Çatış yaptığında, güçlü başarıda +1 momentum al.\n- Anlamlı bir sembolle boyanmış bir kalkan taşıdığında ve korkunç bir düşmanla karşı karşıya gelirken Strese Katlan yaptığında, +1 ekle ve başarıda +1 momentum al.\n- Bir kavgada Hasara Katlan yapmaya zorlandığında, bunun yerine kalkanını feda edip tüm hasarı yok sayabilirsin. Bunu yaparsan kalkanın paramparça olur ya da uzun bir tamir gerektirir; -2 momentum çek."
	},
	{
		"page": 41,
		"img": "/rulebook/karakterin/p41.webp",
		"title_en": "Rituals and Acquiring Assets",
		"title_tr": "Ritüeller ve Yetenek Kartı Edinme",
		"text_en": "## Rituals\n\nMagic in Ironsworn is cast through rituals which help support your actions or act as unique moves. Like all assets, rituals can be selected as you gain experience and can be upgraded over time to make them more flexible or powerful. All rituals utilize a move as their default marked ability. You must make this move and the associated action roll to trigger the effect. Any secondary abilities you gain by upgrading the asset are dependent on performing the ritual described as the default ability.\n\n**Communion (ritual).** When you surround the remains of a recently deceased intelligent creature with lit candles, and summon its spirit, roll +heart. Add +1 if you share a bond. On a strong hit, the spirit appears and you may converse for a few minutes. Make moves as appropriate (add +1). On a weak hit, as above, but the spirit also delivers troubling news unrelated to your purpose. Envision what it tells you (Ask the Oracle if unsure) and Endure Stress (1 stress).\n- As above, and you may also commune with the long-dead.\n- When you perform this ritual, add +1 and take +1 momentum on a hit.\n\n## Acquiring Assets\n\nYou may select three assets when you create your character. Additional assets can be acquired with experience points when you Advance (page 103). Some assets can only be obtained after you have fulfilled narrative or mechanical requirements. This is in addition to the experience point cost. The text of the assets will outline the requirements. For example:\n\n- Banner-Sworn requires that you have marked a bond with a leader or faction. If you have an appropriate background bond, or have made the Forge a Bond move with a leader or faction, you may add the asset.\n- Battle-Scarred requires that you are maimed (page 38). If you have marked the debility, you may add the asset.\n- Ritualist requires that you Fulfill Your Vow in service to an elder mystic, and Forge a Bond to train with them. Once you've done that, you may add the asset.\n\nFor assets without a requirement, you should consider the narrative justification when you add it to your character. What have you done to gain these abilities? How have your goals changed to support this new focus? Make your selection meaningful in the context of your story.",
		"text_tr": "## Ritüeller (Rituals)\n\n*Ironsworn*'de büyü, eylemlerini desteklemeye yardım eden ya da benzersiz hamleler gibi işleyen ritüellerle yapılır. Tüm yetenek kartları gibi ritüeller de deneyim kazandıkça seçilebilir ve zamanla daha esnek veya güçlü hale getirmek için geliştirilebilir. Tüm ritüeller, varsayılan işaretli yeteneği olarak bir hamle kullanır. Etkiyi tetiklemek için bu hamleyi ve ilgili eylem zarını atmalısın. Kartı geliştirerek kazandığın ikincil yetenekler, varsayılan yetenek olarak tanımlanan ritüeli yapmana bağlıdır.\n\n**Ruhla Görüşme (Communion) (Ritüel).** Yeni ölmüş zeki bir yaratığın kalıntılarını yanan mumlarla çevreleyip ruhunu çağırdığında, +heart at. Bir bağ paylaşıyorsan +1 ekle. Güçlü başarıda, ruh belirir ve birkaç dakika konuşabilirsin. Uygun hamleleri yap (+1 ekle). Zayıf başarıda, yukarıdaki gibi, ama ruh ayrıca amacınla ilgisiz tedirgin edici bir haber de verir. Sana ne söylediğini tasavvur et (emin değilsen Kehanetin Sesini Dinle) ve Strese Katlan (1 stres).\n- Yukarıdaki gibi, ayrıca çoktan ölmüş olanlarla da anma yapabilirsin.\n- Bu ritüeli yaptığında, +1 ekle ve başarıda +1 momentum al.\n\n## Yetenek Kartı Edinme\n\nKarakterini yarattığında üç yetenek kartı seçebilirsin. İlerle (sayfa 103) yaptığında deneyim puanlarıyla ek yetenek kartları edinilebilir. Bazı yetenek kartları yalnızca anlatısal ya da mekanik gereklilikleri yerine getirdikten sonra elde edilebilir. Bu, deneyim puanı bedeline ektir. Yetenek kartlarının metni gereklilikleri ana hatlarıyla belirtir. Örneğin:\n\n- Sancağa Antlı, bir lider ya da hizip ile bir bağ işaretlemiş olmanı gerektirir. Uygun bir geçmiş bağın varsa ya da bir lider veya hizip ile Bağ Kur hamlesini yapmışsan, bu kartı ekleyebilirsin.\n- Savaş Yaralı, sakat (sayfa 38) olmanı gerektirir. Bu olumsuz etkiyi işaretlemişsen, bu kartı ekleyebilirsin.\n- Ritüelci, yaşlı bir mistiğin hizmetinde Antını Tamamlamanı ve onunla eğitim almak için Bağ Kur yapmanı gerektirir. Bunu yaptıktan sonra bu kartı ekleyebilirsin.\n\nGerekliliği olmayan kartlar için, karakterine eklerken anlatısal gerekçeyi düşünmelisin. Bu yetenekleri kazanmak için ne yaptın? Bu yeni odağı desteklemek için amaçların nasıl değişti? Seçimini hikâyenin bağlamında anlamlı kıl."
	},
	{
		"page": 42,
		"img": "/rulebook/karakterin/p42.webp",
		"title_en": "Upgrading Assets",
		"title_tr": "Yetenek Kartlarını Geliştirme",
		"text_en": "## Upgrading Assets\n\nWhen you spend experience (page 44) to upgrade an asset, you fill in the dot on your asset card to show you've acquired the ability. All assets include three abilities. The first will probably be filled in when you purchase the asset. If not, you get to choose one of the three abilities to start.\n\nUpgrading an asset costs 2 experience. Abilities may be selected in any order. You don't have to activate the second ability to upgrade the third one.\n\n## Asset Abilities\n\nAssets provide one or more functions.\n\n- They provide bonuses (adds) for specific moves.\n- They allow you to alter the outcome of a move by rerolling dice.\n- They provide improved outcomes for successful moves, such as taking +1 momentum on a hit.\n- They give you an option to exchange one resource for another, such as trading momentum for inflicting additional harm.\n- They allow you to use moves in unusual circumstances, such as using the Scrying ritual to Gather Information remotely.\n- They allow you to use a different stat instead of the one normally required by a move.\n- They provide unique self-contained moves.\n- They add narrative detail and create situations where you can reveal more about your character or your world.\n\nFollow the directions on the asset to apply its abilities to your current situation.\n\n## Ability Requirements\n\nNarrative circumstances and the outcome of failed moves may force you into situations where you can't leverage a key asset, making your adventure more challenging and dramatic.\n\nFor example, if you don't have an animal pelt, you can't perform the Bind ritual. If you Undertake a Journey without your Horse companion, you won't gain the bonus. If you are an Archer who's run out of arrows, you'll have to try something else. Before you make a move using an asset, take a moment to ensure you are properly positioned and equipped to use those abilities.",
		"text_tr": "## Yetenek Kartlarını Geliştirme\n\nBir yetenek kartını geliştirmek için deneyim (sayfa 44) harcadığında, yeteneği edindiğini göstermek için yetenek kartındaki noktayı doldurursun. Tüm yetenek kartları üç yetenek içerir. İlki muhtemelen kartı aldığında dolu gelir. Değilse, başlamak için üç yetenekten birini seçersin.\n\nBir yetenek kartını geliştirmek 2 deneyime mal olur. Yetenekler istediğin sırada seçilebilir. Üçüncüyü geliştirmek için ikinci yeteneği etkinleştirmek zorunda değilsin.\n\n## Yetenek Kartı Yetenekleri\n\nYetenek kartları bir ya da daha fazla işlev sunar.\n\n- Belirli hamleler için bonuslar (eklentiler) sağlar.\n- Zarları yeniden atarak bir hamlenin sonucunu değiştirmene izin verir.\n- Başarılı hamleler için, başarıda +1 momentum almak gibi, iyileştirilmiş sonuçlar sağlar.\n- Bir kaynağı bir başkasıyla takas etme seçeneği verir; ek hasar vermek için momentum takas etmek gibi.\n- Olağandışı koşullarda hamle kullanmana izin verir; uzaktan Bilgi Topla yapmak için Alevde Görme (Scrying) ritüelini kullanmak gibi.\n- Bir hamlenin normalde gerektirdiği statın yerine farklı bir stat kullanmana izin verir.\n- Benzersiz, kendi başına işleyen hamleler sunar.\n- Anlatısal ayrıntı katar ve karakterin ya da dünyan hakkında daha fazlasını açığa çıkarabileceğin durumlar yaratır.\n\nYeteneklerini güncel durumuna uygulamak için yetenek kartındaki yönergeleri izle.\n\n## Yetenek Gereklilikleri\n\nAnlatısal koşullar ve başarısız hamlelerin sonucu, seni önemli bir yetenek kartını kullanamayacağın durumlara sokabilir; bu da maceranı daha zorlu ve dramatik kılar.\n\nÖrneğin, bir hayvan postun yoksa Bağla (Bind) ritüelini yapamazsın. Atın olmadan Yolculuğa Çıkarsan, bonusu kazanamazsın. Okları biten bir Okçu'ysan, başka bir şey denemen gerekir. Bir yetenek kartını kullanarak hamle yapmadan önce, o yetenekleri kullanmak için doğru konumda ve donanımda olduğundan emin olmak için bir an dur."
	},
	{
		"page": 43,
		"img": "/rulebook/karakterin/p43.webp",
		"title_en": "Using Companion Abilities",
		"title_tr": "Yoldaş Yeteneklerini Kullanma",
		"text_en": "## Using Companion Abilities\n\nIf you have a companion, leveraging their abilities is an option, not a requirement. Through the fiction, you can interact with your companion and have them perform tasks or assist you without using one of the asset abilities. For example, a Horse companion can put you in position to travel at speed or get away from danger.\n\nWhen you leverage a companion's ability, you are inherently putting them at risk. If you roll a 1 on your action die when aided by a companion, any negative outcome of the move should involve your companion. Depending on the circumstances, they might suffer harm, be put in danger, become separated from you, or refuse your commands.\n\n## Inflicting Harm on Companions\n\nWhen a companion suffers physical damage, you make the Companion Endure Harm move (page 94). When their health is at 0, they are in danger of being killed. Some moves, such as Sojourn (page 71) and Make Camp (page 64), offer options for your companion to recover health.\n\n## Slain Companions\n\nIf your companion is killed, give yourself 1 experience point for each marked ability. Then, remove the asset. If you acquire the same type of companion through the narrative of your quest and journeys, you can rebuy the asset at the normal cost.",
		"text_tr": "## Yoldaş Yeteneklerini Kullanma\n\nBir Yoldaşın varsa, yeteneklerinden yararlanmak bir seçenektir, zorunluluk değil. Kurgu aracılığıyla Yoldaşınla etkileşime girebilir ve yetenek kartı yeteneklerinden birini kullanmadan ona görevler yaptırabilir ya da senden yardım almasını sağlayabilirsin. Örneğin bir At yoldaşı, seni hızla yol almaya ya da tehlikeden kaçmaya elverişli bir konuma sokabilir.\n\nBir Yoldaşın yeteneğinden yararlandığında, doğası gereği onu riske atarsın. Bir Yoldaşın yardımıyla eylem zarında 1 atarsan, hamlenin herhangi bir olumsuz sonucu Yoldaşını da içermelidir. Koşullara bağlı olarak, hasar görebilir, tehlikeye atılabilir, senden ayrı düşebilir ya da emirlerini reddedebilir.\n\n## Yoldaşlara Hasar Verme\n\nBir Yoldaş bedensel hasar gördüğünde, Yoldaş Hasara Katlan hamlesini (sayfa 94) yaparsın. Can'ı 0'a düştüğünde, öldürülme tehlikesindedir. Konaklama (sayfa 71) ve Kamp Kur (sayfa 64) gibi bazı hamleler, Yoldaşının Can geri kazanması için seçenekler sunar.\n\n## Öldürülen Yoldaşlar\n\nYoldaşın öldürülürse, işaretli her yetenek için kendine 1 deneyim puanı ver. Sonra kartı çıkar. Görevinin ve yolculuklarının anlatısı aracılığıyla aynı türden bir Yoldaş edinirsen, kartı normal bedeliyle yeniden satın alabilirsin."
	},
	{
		"page": 44,
		"img": "/rulebook/karakterin/p44.webp",
		"title_en": "Failing Asset Moves and Experience",
		"title_tr": "Yetenek Kartı Hamlelerinde Başarısızlık ve Deneyim",
		"text_en": "## Failing an Asset Move\n\nFor the sake of brevity, moves within an asset do not usually describe the result of a miss. If an asset offers a self-contained move, and doesn't provide a specific consequence for a miss, you can leverage the miss result of the Face Danger move (page 60): \"On a miss, you fail, or your progress is undermined by a dramatic and costly turn of events. Pay the Price.\" In short, make something negative happen as appropriate to the circumstances.\n\n## Failed Rituals\n\nDabbling in the mystic arts is dangerous, and the results can be unpredictable. If the ritual goes wrong, envision what sort of backlash might be possible, or Ask the Oracle. You'll also find a Mystic Backlash table on page 189.\n\nFailing a ritual might also lead to an entirely mundane result. Perhaps you were ambushed in the midst of the ritual. Or, you waste time (suffer -momentum) or resources (suffer -supply). You might choose to save any overt supernatural backlash for special circumstances, such as when you roll a match.\n\n## Using Asset Cards\n\nBooklets of asset cards are available for download at ironswornrpg.com. You can print and cut out individual cards, and each is sized for use with standard 3.5x2.5 in (88x63mm) card protectors. Or, you can purchase decks of preprinted asset cards. Visit ironswornrpg.com to learn more.\n\nTo start, select three assets. Since this is a key aspect of your character, feel free to choose assets as the first step in character creation. You can let your assets guide your concept, or vice versa.\n\n## Experience\n\nWhen you Fulfill Your Vow (page 101), you gain experience. The amount of experience is based on the rank of the quest, and ranges from 1 to 5 points. Mark an 'X' on your character sheet for each point you've earned.",
		"text_tr": "## Yetenek Kartı Hamlesinde Başarısızlık\n\nKısalık adına, bir yetenek kartındaki hamleler genellikle bir başarısızlığın sonucunu anlatmaz. Bir yetenek kartı kendi başına işleyen bir hamle sunuyor ve başarısızlık için belirli bir sonuç vermiyorsa, Tehlikeyle Yüzleş hamlesinin (sayfa 60) başarısızlık sonucundan yararlanabilirsin: \"Başarısızlıkta, başarısız olursun ya da ilerlemen dramatik ve ağır bedelli bir gelişmeyle baltalanır. Bedelini Öde.\" Kısacası, koşullara uygun olumsuz bir şey yaşat.\n\n## Başarısız Ritüeller\n\nMistik sanatlarla oynamak tehlikelidir ve sonuçlar öngörülemez olabilir. Ritüel ters giderse, ne tür bir geri tepmenin mümkün olabileceğini tasavvur et ya da Kehanetin Sesini Dinle. Ayrıca sayfa 189'da bir Mistik Geri Tepme tablosu bulacaksın.\n\nBir ritüelde başarısız olmak tümüyle sıradan bir sonuca da yol açabilir. Belki ritüelin ortasında pusuya düşürüldün. Ya da zaman (-momentum çek) veya kaynak (-ikmal çek) kaybedersin. Bariz doğaüstü geri tepmeleri, eşleşme (match) attığın gibi özel durumlara saklamayı seçebilirsin.\n\n## Yetenek Kartlarını Kullanma\n\nYetenek kartı kitapçıkları ironswornrpg.com adresinden indirilebilir. Kartları tek tek yazdırıp kesebilirsin; her biri standart 3.5x2.5 inç (88x63mm) kart korumalarıyla kullanım için boyutlandırılmıştır. Ya da önceden basılmış yetenek kartı desteleri satın alabilirsin. Daha fazlası için ironswornrpg.com'u ziyaret et.\n\nBaşlangıç için üç yetenek kartı seç. Bu, karakterinin önemli bir yönü olduğundan, yetenek kartlarını karakter yaratmanın ilk adımı olarak seçmekten çekinme. Yetenek kartlarının konseptine yön vermesine ya da tersini yapmasına izin verebilirsin.\n\n## Deneyim (Experience)\n\nAntını Tamamla (sayfa 101) yaptığında deneyim kazanırsın. Deneyim miktarı görevin derecesine bağlıdır ve 1 ile 5 puan arasında değişir. Kazandığın her puan için karakter kâğıdına bir 'X' işaretle."
	},
	{
		"page": 45,
		"img": "/rulebook/karakterin/p45.webp",
		"title_en": "Spending Experience and Equipment",
		"title_tr": "Deneyim Harcama ve Teçhizat",
		"text_en": "When you Advance (page 103), you spend experience to purchase assets or upgrade an asset. Replace the 'X' for each point spent with a filled-in dot.\n\nPer the Advance move, you may:\n- Add a new asset by spending 3 experience.\n- Upgrade an asset by spending 2 experience.\n\nTo start, your experience is unmarked.\n\n## Equipment\n\nMake note of any important equipment or items you start with. These are things that might impact the narrative and the moves you make, or provide texture to your character's background. They don't offer mechanical bonuses unless they are represented by an asset, such as a weapon used in a combat talent.\n\nYou can assume you are equipped for travel and adventure as represented by your supply track. Don't worry about managing rations or ammo or other mundane necessities.\n\nThere are no limitations by the rules, but envision your character's place in society and consider the availability of resources in your version of the Ironlands. By default, a fine sword or a set of quality armor is rare, and marks you as someone of note. It influences how others react to you in the fiction of your game.\n\nIf you want to begin your adventures as a typical Ironlander, envision yourself outfitted with cheap, mundane gear. A hand-me-down set of quilted armor. A ratty traveling cloak. A battered wooden shield. A spear and a worn knife. Improving your lot in life can be part of your narrative journey.\n\nTo start, make note of any items which have a narrative impact and equipment which relates to your assets. Keep it simple.",
		"text_tr": "İlerle (sayfa 103) yaptığında, yetenek kartları satın almak ya da bir yetenek kartını geliştirmek için deneyim harcarsın. Harcanan her puan için 'X'i dolu bir noktayla değiştir.\n\nİlerle hamlesi uyarınca şunları yapabilirsin:\n- 3 deneyim harcayarak yeni bir yetenek kartı ekle.\n- 2 deneyim harcayarak bir yetenek kartını geliştir.\n\nBaşlangıç için deneyimin işaretsizdir.\n\n## Teçhizat (Equipment)\n\nBaşladığın önemli teçhizat ya da eşyaları not et. Bunlar, anlatıyı ve yaptığın hamleleri etkileyebilecek ya da karakterinin geçmişine doku katabilecek şeylerdir. Bir savaş yeteneğinde kullanılan bir silah gibi bir yetenek kartıyla temsil edilmedikleri sürece mekanik bonus sunmazlar.\n\nİkmal izinin temsil ettiği gibi, yolculuk ve macera için donanımlı olduğunu varsayabilirsin. Erzakı, cephaneyi ya da diğer sıradan zorunlulukları yönetmek için endişelenme.\n\nKurallarda sınırlama yoktur, ama karakterinin toplumdaki yerini tasavvur et ve Demir Diyarlar'ın senin versiyonunda kaynakların ne kadar bulunur olduğunu düşün. Varsayılan olarak, güzel bir kılıç ya da nitelikli bir zırh takımı nadirdir ve seni dikkat çeken biri olarak işaretler. Oyununun kurgusunda başkalarının sana nasıl tepki verdiğini etkiler.\n\nMaceralarına sıradan bir Demir Diyar sakini olarak başlamak istiyorsan, kendini ucuz, sıradan teçhizatla donanmış olarak tasavvur et. Elden düşme kapitone bir zırh. Eski püskü bir yolculuk pelerini. Yıpranmış tahta bir kalkan. Bir mızrak ve aşınmış bir bıçak. Hayattaki konumunu iyileştirmek anlatısal yolculuğunun bir parçası olabilir.\n\nBaşlangıç için anlatısal etkisi olan eşyaları ve yetenek kartlarınla ilgili teçhizatı not et. Basit tut."
	},
	{
		"page": 46,
		"img": "/rulebook/karakterin/p46.webp",
		"title_en": "Becoming Ironsworn",
		"title_tr": "Demir-Andlı Olmak",
		"text_en": "## Becoming Ironsworn\n\nIn your first session, envision your current situation. Something has happened—or is about to happen—which puts you on the path of the Ironsworn. This is your inciting incident. Make it personal. Give it teeth. It's not a situation you can just walk away from. You must set things right.\n\nIf you need inspiration for this starting situation, have a look at the prompts for vows in chapter 4 - 'Your World' (page 111) and chapter 5 - 'Foes and Encounters' (page 133). Or, you can Ask the Oracle (page 107) and interpret the meaning of the answer.\n\nTo learn more about starting your campaign, see page 193. Then, Swear an Iron Vow and play to see what happens.",
		"text_tr": "## Demir-Andlı Olmak\n\nİlk oturumunda, içinde bulunduğun durumu tasavvur et. Seni Demir-Andlı yoluna sokan bir şey oldu—ya da olmak üzere. Bu, seni harekete geçiren olaydır. Onu kişisel kıl. Ona diş ver. Öylece çekip gidebileceğin bir durum değil. İşleri yoluna koymalısın.\n\nBu başlangıç durumu için ilhama ihtiyacın varsa, 4. Bölüm - 'Dünyan' (sayfa 111) ve 5. Bölüm - 'Düşmanlar ve Karşılaşmalar' (sayfa 133) içindeki ant önerilerine bir göz at. Ya da Kehanetin Sesini Dinle (sayfa 107) yapıp cevabın anlamını yorumlayabilirsin.\n\nKampanyanı başlatmak hakkında daha fazla bilgi için sayfa 193'e bak. Sonra bir Demir Ant İç ve neler olacağını görmek için oyna."
	},
	{
		"page": 47,
		"img": "/rulebook/karakterin/p47.webp",
		"title_en": "Character Creation Summary",
		"title_tr": "Karakter Yaratma Özeti",
		"text_en": "## Character Creation Summary\n\nWork through the following steps in whatever order you prefer.\n\n1. Envision your character (page 31).\n2. Choose a name (page 33).\n3. Set your stats by arranging these bonuses across edge, heart, iron, shadow, and wits in any order: 3, 2, 2, 1, 1 (page 33).\n4. Set your health, spirit, and supply to +5 (page 33).\n5. Set your momentum to +2, your max momentum to +10, and your momentum reset to +2 (page 35).\n6. Mark up to three background bonds (page 36).\n7. Pick three assets (page 39).\n8. Make note of any important equipment or items (page 45).\n9. Set a background vow, and give it a rank of extreme or epic. Then, envision your inciting incident and Swear an Iron Vow. For details on setting up your campaign, see page 193.",
		"text_tr": "## Karakter Yaratma Özeti\n\nAşağıdaki adımları tercih ettiğin sırada yürüt.\n\n1. Karakterini tasavvur et (sayfa 31).\n2. Bir ad seç (sayfa 33).\n3. Bu bonusları Edge, Heart, Iron, Shadow ve Wits arasında istediğin sırada dağıtarak statlarını ayarla: 3, 2, 2, 1, 1 (sayfa 33).\n4. Can'ını, Ruh'unu ve İkmal'ini +5'e ayarla (sayfa 33).\n5. Momentumunu +2'ye, azami momentumunu +10'a ve momentum sıfırlamanı +2'ye ayarla (sayfa 35).\n6. En fazla üç geçmiş bağ işaretle (sayfa 36).\n7. Üç yetenek kartı seç (sayfa 39).\n8. Önemli teçhizat ya da eşyaları not et (sayfa 45).\n9. Bir geçmiş antı belirle ve ona aşırı ya da destansı bir derece ver. Sonra seni harekete geçiren olayı tasavvur et ve bir Demir Ant İç. Kampanyanı kurma ayrıntıları için sayfa 193'e bak."
	}
];
