// Otomatik üretildi: Ironsworn Bölüm 6 "Oracles" (PDF s.176–202) sayfa-sayfa.
// Görseller static/rulebook/kehanetler/*.webp; çeviri /ceviri (Opus, glossary).
import type { RulebookPage } from './types.js';

export const kehanetlerPages: RulebookPage[] = [
	{
		"page": 165,
		"img": "/rulebook/kehanetler/p165.webp",
		"title_en": "Seeking Inspiration",
		"title_tr": "İlham Aramak",
		"text_en": "## Seeking Inspiration\n\nIn *Ironsworn*, an oracle is anything which generates random results to help determine the outcome of a move, a detail in your world, an NPC action, or a narrative event.\n\nAmong the choices provided in the Ask the Oracle move is \"spark an idea\" (page 108). You can use this option (instead of or in addition to the yes/no table) to answer open-ended questions or inspire new situations.\n\nRolling a match on a move (page 9) can also trigger opportunities to introduce narrative complications and surprises through random prompts.\n\nThis chapter includes a series of random prompts in the form of tables. You can use these oracle tables to answer questions about your world, drive the narrative, and inspire dramatic events and revelations. Some oracles are for specific, mundane questions to streamline play (\"What is the healer's name?\"). Others provide more abstract results which you interpret based on the current situation (\"What happens next?\").\n\n## Oracles in Solo and Co-op Play\n\nIronsworn oracles don't function as a GM simulator. Instead, they leverage the power of your creative interpretation. Ask your question, roll on a table, and consider the answer in the context of your current situation and story. What comes to mind first? Did you think of something which reinforces a dramatic narrative or takes things in an interesting and surprising direction? Does it feel right? If so, make it happen.\n\nIf you follow your instincts while staying open to twists and turns, you will find your game offering many of the same narrative rewards as if you were playing with a GM. In fact, you'll be surprised how often a seemingly random result seems to feed directly into your character's story and the world you've established through play. This is the power of creative interpretation at work.\n\nYou score a miss on your Undertake a Journey move, and roll \"A new danger or foe is revealed\" on the Pay the Price table (page 105). You're not sure what this means in the context of your current journey, and decide to spark an idea to see what happens. You roll on the Action and Theme tables (page 174), and the oracle answers, \"Bolster vengeance.\" Playing off this prompt, you decide it would be interesting to bring back a particular enemy, one who holds a grudge against you. They've gathered allies and are tracking you on your journey.",
		"text_tr": "## İlham Aramak\n\n*Ironsworn*'de bir kehanet (oracle), bir hamlenin sonucunu, dünyandaki bir ayrıntıyı, bir OYK eylemini ya da bir anlatı olayını belirlemene yardım etmek için rastgele sonuçlar üreten her şeydir.\n\nKehanetin Sesini Dinle hamlesindeki seçeneklerden biri de \"bir fikir kıvılcımı yak\"tır (sayfa 108). Bu seçeneği (evet/hayır tablosunun yerine ya da ona ek olarak) açık uçlu soruları yanıtlamak veya yeni durumlara ilham vermek için kullanabilirsin.\n\nBir hamlede eşleşme (match) atmak (sayfa 9) da rastgele yönlendirmeler aracılığıyla anlatıya zorluklar ve sürprizler katma fırsatlarını tetikleyebilir.\n\nBu bölüm, tablolar biçiminde bir dizi rastgele yönlendirme içerir. Bu kehanet tablolarını dünyan hakkında soruları yanıtlamak, anlatıyı sürüklemek ve dramatik olaylara ve açığa çıkışlara ilham vermek için kullanabilirsin. Bazı kehanetler oyunu akıcı kılmak için belirli, sıradan sorulara yöneliktir (\"Şifacının adı ne?\"). Diğerleri, mevcut duruma göre yorumlayacağın daha soyut sonuçlar sunar (\"Sırada ne var?\").\n\n## Tek Kişilik ve İşbirlikli Oyunda Kehanetler\n\n*Ironsworn* kehanetleri bir OY simülatörü gibi işlemez. Bunun yerine, yaratıcı yorumunun gücünden yararlanır. Sorunu sor, bir tabloya zar at ve cevabı mevcut durumunun ve hikâyenin bağlamında değerlendir. Aklına ilk ne geliyor? Dramatik bir anlatıyı pekiştiren ya da olayları ilginç ve şaşırtıcı bir yöne taşıyan bir şey mi düşündün? Doğru hissettiriyor mu? Öyleyse, gerçekleşmesini sağla.\n\nİçgüdülerini izlerken beklenmedik dönemeçlere de açık kalırsan, oyununun, bir OY ile oynuyormuşçasına pek çok aynı anlatı ödülünü sunduğunu göreceksin. Hatta, görünüşte rastgele bir sonucun ne sıklıkla doğrudan karakterinin hikâyesine ve oyun boyunca kurduğun dünyaya beslendiğine şaşıracaksın. İşte yaratıcı yorumun gücü budur.\n\nYolculuğa Çık hamlende başarısızlık atarsın ve Bedelini Öde tablosunda (sayfa 105) \"Yeni bir tehlike ya da düşman ortaya çıkar\" sonucunu atarsın. Bunun mevcut yolculuğunun bağlamında ne anlama geldiğinden emin değilsin ve ne olacağını görmek için bir fikir kıvılcımı yakmaya karar verirsin. Eylem ve Tema tablolarına (sayfa 174) zar atarsın ve kehanet, \"İntikamı güçlendir\" yanıtını verir. Bu yönlendirmeden yola çıkarak, sana kin besleyen belirli bir düşmanı geri getirmenin ilginç olacağına karar verirsin. Müttefikler toplamış ve yolculuğunda seni takip ediyorlar."
	},
	{
		"page": 166,
		"img": "/rulebook/kehanetler/p166.webp",
		"title_en": "Oracles in Guided Play",
		"title_tr": "Rehberli Oyunda Kehanetler",
		"text_en": "## Oracles in Guided Play\n\nGM's can use oracles for support during play and to supplement their narrative decision-making. Mundane oracles, such as names (page 184), are helpful to quickly flesh out details. Interpretative oracles, such as the Action and Theme tables (page 174), can be used to spark new ideas.\n\nWhen the characters Sojourn at a small settlement deep in the Flooded Lands, they roll a match. Everyone is interested in using that match to drive a new quest. The GM rolls on the Settlement Trouble table (page 181). The oracle answers, \"Production halts.\"\n\nThe GM interprets this result. \"This settlement relies on a steady harvest of a rare medicinal plant found in the depths of the swamp\", she tells her players. \"But, a huge basilisk they call 'one-eye' lurks there. A group of able hunters set out last week to kill the beast. They did not return.\"\n\nYou can also use oracles as a prompt for sharing control of the narrative with your players. Not sure what happens next? Not sure how to answer a character's question? Roll on an appropriate table, or have a player make the roll, and talk it out with everyone at the table.",
		"text_tr": "## Rehberli Oyunda Kehanetler\n\nOyun Yöneticileri, kehanetleri oyun sırasında destek almak ve anlatı kararlarını desteklemek için kullanabilir. İsimler (sayfa 184) gibi sıradan kehanetler, ayrıntıları hızla canlandırmak için işe yarar. Eylem ve Tema tabloları (sayfa 174) gibi yorumsal kehanetler ise yeni fikirler kıvılcımlandırmak için kullanılabilir.\n\nKarakterler Su Basmış Toprakların derinliklerindeki küçük bir yerleşimde Konaklama yaparken bir eşleşme atarlar. Herkes bu eşleşmeyi yeni bir görevi sürüklemek için kullanmak ister. OY, Yerleşim Sorunu tablosuna (sayfa 181) zar atar. Kehanet, \"Üretim durur\" yanıtını verir.\n\nOY bu sonucu yorumlar. \"Bu yerleşim, bataklığın derinliklerinde bulunan nadir bir şifalı bitkinin düzenli hasadına dayanıyor\" der oyuncularına. \"Ama orada 'tek-göz' dedikleri devasa bir basilisk pusuda bekliyor. Geçen hafta yetenekli bir avcı grubu canavarı öldürmeye gitti. Geri dönmediler.\"\n\nKehanetleri, anlatının denetimini oyuncularınla paylaşmak için bir yönlendirme olarak da kullanabilirsin. Sırada ne olacağından emin değil misin? Bir karakterin sorusunu nasıl yanıtlayacağını bilmiyor musun? Uygun bir tabloya zar at ya da bir oyuncuya attır ve masadaki herkesle konuşarak çözün."
	},
	{
		"page": 167,
		"img": "/rulebook/kehanetler/p167.webp",
		"title_en": "Ironland Oracles — How to Use the Tables",
		"title_tr": "Demir Diyar Kehanetleri — Tabloları Nasıl Kullanırsın",
		"text_en": "## Ironland Oracles\n\n### How to Use the Tables\n\n- Ask your question and choose an appropriate oracle table.\n- Roll your oracle dice (page 22) to generate a number from 1-100.\n- Check your roll against the table. The oracle will reveal its answer.\n- Consider the answer in the context of your question and the current situation. Is the result a good fit? Does it trigger a spark of inspiration?\n- If the answer is difficult to interpret for your situation, you can check up or down one row from your original answer, or reverse the digits (37=73).\n- If you've got your answer, you're all set! Play to see what happens. If you want further detail, you can talk it out with other players or roll on another oracle table.\n- If you're having trouble, you can roll again, try a different table, or just fall back to your instincts and decide what happens next.",
		"text_tr": "## Demir Diyar Kehanetleri\n\n### Tabloları Nasıl Kullanırsın\n\n- Sorunu sor ve uygun bir kehanet tablosu seç.\n- 1-100 arası bir sayı üretmek için kehanet zarlarını (sayfa 22) at.\n- Atışını tabloyla karşılaştır. Kehanet cevabını açığa çıkaracaktır.\n- Cevabı, sorunun ve mevcut durumun bağlamında değerlendir. Sonuç iyi oturuyor mu? Bir ilham kıvılcımı tetikliyor mu?\n- Cevabı durumun için yorumlamak güçse, ilk cevabından bir satır yukarı ya da aşağı bakabilir ya da rakamları ters çevirebilirsin (37=73).\n- Cevabını bulduysan, hazırsın! Ne olacağını görmek için oyna. Daha fazla ayrıntı istersen, diğer oyuncularla konuşabilir ya da başka bir kehanet tablosuna zar atabilirsin.\n- Zorlanıyorsan, yeniden zar atabilir, farklı bir tablo deneyebilir ya da yalnızca içgüdülerine güvenip sırada ne olacağına karar verebilirsin."
	},
	{
		"page": 168,
		"img": "/rulebook/kehanetler/p168.webp",
		"title_en": "When Answers Lead to More Questions",
		"title_tr": "Cevaplar Daha Fazla Soruya Yol Açtığında",
		"text_en": "## When Answers Lead to More Questions\n\nYou aren't limited to a single roll on a single oracle table when asking a question. If you like, you can let the result from one table inform your interpretation of the result on another. You can even refer back to the Ask the Oracle table (page 107) to clarify an answer with a yes/no question.\n\nHowever, use caution with this technique. Too many questions and too many rolls makes your session feel like an exercise in randomness. Lead with your instincts. Leverage the oracles to fill in the gaps. Keep it moving.\n\nYou use the Character Goal oracle (page 182) to identify an NPC's primary motivation. The answer is \"Avenge a wrong.\" You don't have any immediate ideas on how this relates to this character, so you roll on the Theme table (page 175) for more detail. \"Land\", the oracle answers. You decide the NPC's home and farm was taken by a rival. This is the wrong she seeks to put right.\n\n## Oracle Tables and Matches\n\nMatches don't have special significance when rolling on these oracle tables. They can be ignored.\n\n## Intro to the Oracles\n\nThis chapter includes a variety of oracle tables. Use them in whatever way best fits your preferences and the needs of your story, but here's some basic recommendations.\n\n### Oracle 1: Action (page 174)\n\nUse this table to inspire a discovery, event, character goal, or situation. A roll on this table can be combined with a Theme (see below) to provide an action and a subject. Then, interpret the result based on the context of the question and your current situation.\n\n### Oracle 2: Theme (page 175)\n\nAs with the Action oracle, this is an interpretative table which you can use to answer questions or generate new situations. Combined, the Action and Theme tables provide creative prompts suitable for most situations and questions. In fact, with some creative interpretations, it's entirely possible to play with only these two tables.",
		"text_tr": "## Cevaplar Daha Fazla Soruya Yol Açtığında\n\nBir soru sorarken tek bir kehanet tablosuna tek bir zar atışıyla sınırlı değilsin. İstersen, bir tablodan çıkan sonucun, bir başkasındaki sonucu yorumlamanı şekillendirmesine izin verebilirsin. Bir cevabı evet/hayır sorusuyla netleştirmek için Kehanetin Sesini Dinle tablosuna (sayfa 107) bile geri dönebilirsin.\n\nAncak bu tekniği dikkatle kullan. Çok fazla soru ve çok fazla zar atışı, oturumunun bir rastgelelik egzersizi gibi hissettirmesine yol açar. İçgüdülerinle yön ver. Boşlukları doldurmak için kehanetlerden yararlan. Akışı sürdür.\n\nBir OYK'nın temel güdüsünü belirlemek için Karakter Hedefi kehanetini (sayfa 182) kullanırsın. Cevap \"Bir haksızlığın öcünü al\"dır. Bunun bu karakterle nasıl ilişkili olduğuna dair hemen bir fikrin yoktur, bu yüzden daha fazla ayrıntı için Tema tablosuna (sayfa 175) zar atarsın. Kehanet \"Toprak\" yanıtını verir. OYK'nın evinin ve çiftliğinin bir rakip tarafından gasp edildiğine karar verirsin. Düzeltmeye çalıştığı haksızlık budur.\n\n## Kehanetler ve Eşleşmeler\n\nBu kehanet tablolarına zar atarken eşleşmelerin özel bir önemi yoktur. Göz ardı edilebilirler.\n\n## Kehanetlere Giriş\n\nBu bölüm çeşitli kehanet tabloları içerir. Onları tercihlerine ve hikâyenin ihtiyaçlarına en iyi uyan şekilde kullan, ama işte birkaç temel öneri.\n\n### Kehanet 1: Eylem (sayfa 174)\n\nBu tabloyu bir keşfe, olaya, karakter amacına ya da duruma ilham vermek için kullan. Bu tabloya atılan bir zar, bir eylem ve bir özne sağlamak için bir Tema (aşağıya bak) ile birleştirilebilir. Ardından sonucu sorunun ve mevcut durumunun bağlamına göre yorumla.\n\n### Kehanet 2: Tema (sayfa 175)\n\nEylem kehaneti gibi, bu da soruları yanıtlamak ya da yeni durumlar üretmek için kullanabileceğin yorumsal bir tablodur. Birlikte, Eylem ve Tema tabloları çoğu durum ve soru için uygun yaratıcı yönlendirmeler sunar. Hatta, biraz yaratıcı yorumla, yalnızca bu iki tabloyla oynamak tümüyle mümkündür."
	},
	{
		"page": 169,
		"img": "/rulebook/kehanetler/p169.webp",
		"title_en": "Region and Location Oracles",
		"title_tr": "Bölge ve Konum Kehanetleri",
		"text_en": "You are sworn to recover a stolen artifact which is sacred to a community. In your search for suspects, you make a Gather Information move as you question the village leader.\n\nYou roll a strong hit, but where do the clues lead? You Ask the Oracle and roll against the Action and Theme tables. \"Leave mysticism,\" the oracle responds.\n\nInterpreting this result, you decide the likely suspect is a traveling mystic who left shortly before the theft was discovered.\n\n## Oracle 3: Region (page 176)\n\nUse this oracle when you want to randomly select a region within the Ironlands.\n\n## Oracle 4: Location (page 176)\n\nUse this oracle when traveling to generate a point-of-interest or to answer a question about a place where someone or something can be found.\n\nYour roll may generate a place or geographical feature which doesn't make sense in the context of your current location. If so, follow the guidelines on page 167 to generate a different result (look at adjacent rows or reverse the digits). Or, play off the original answer to introduce something unexpected.\n\nYou ask, \"Where was the traveling mystic bound?\" The Location oracle answers, \"River.\" You decide she traveled south from the village aboard a merchant's boat.",
		"text_tr": "Bir topluluk için kutsal olan, çalınmış bir eseri geri getirmeye ant içmişsin. Şüphelileri ararken, köy lideriyle konuşurken bir Bilgi Topla hamlesi yaparsın.\n\nGüçlü Başarı atarsın, ama ipuçları nereye götürüyor? Kehanetin Sesini Dinle yaparsın ve Eylem ve Tema tablolarına zar atarsın. Kehanet, \"Mistisizmi terk et\" yanıtını verir.\n\nBu sonucu yorumlayarak, olası şüphelinin, hırsızlık keşfedilmeden kısa süre önce ayrılan gezgin bir mistik olduğuna karar verirsin.\n\n## Kehanet 3: Bölge (sayfa 176)\n\nDemir Diyarlar içinde rastgele bir bölge seçmek istediğinde bu kehaneti kullan.\n\n## Kehanet 4: Konum (sayfa 176)\n\nYolculuk ederken bir ilgi noktası üretmek ya da birinin veya bir şeyin bulunabileceği bir yer hakkındaki bir soruyu yanıtlamak için bu kehaneti kullan.\n\nAtışın, mevcut konumunun bağlamında anlam ifade etmeyen bir yer ya da coğrafi özellik üretebilir. Öyleyse, farklı bir sonuç üretmek için sayfa 167'deki kuralları izle (komşu satırlara bak ya da rakamları ters çevir). Ya da beklenmedik bir şey katmak için ilk cevaptan yola çık.\n\n\"Gezgin mistik nereye gidiyordu?\" diye sorarsın. Konum kehaneti, \"Nehir\" yanıtını verir. Köyden güneye, bir tüccarın teknesiyle yolculuk ettiğine karar verirsin."
	},
	{
		"page": 170,
		"img": "/rulebook/kehanetler/p170.webp",
		"title_en": "Coastal Waters, Location Description, and Settlement Name Oracles",
		"title_tr": "Kıyı Suları, Konum Tasviri ve Yerleşim Adı Kehanetleri",
		"text_en": "## Oracle 5: Coastal Waters Location (page 176)\n\nUse this oracle to identify a point-of-interest or destination when you are traveling by ship or boat along the coast.\n\n## Oracle 6: Location Description (page 177)\n\nUse this oracle to add detail to the Location or Coastal Waters Location oracles, or by itself to generate a description of a location. Roll more than once for extra detail.\n\nYou travel downriver on a hired boat. You want to add a bit of color to your journey, so you use the Location Description oracle for some detail. It answers, \"Inaccessible.\"\n\nYou interpret this result to mean segments of the river are shallow, forcing the crew to portage the boat along the shore. This sounds like a perfect opportunity for an ambush...\n\n## Oracle 7: Settlement Name (page 178)\n\nAsk this oracle for a thematic name for an Ironlander settlement. Roll once for the category, and again to pick from the examples. Alternatively, just roll for the category and come up with a name that fits the theme. In either case, consider the meaning of the name and how it impacts this settlement's surroundings, livelihood, culture, or history. This may, in turn, inspire narrative hooks and opportunities for new quests.\n\n## Oracle 8: Quick Settlement Name Generator (page 180)\n\nUse this oracle as a simpler alternative for settlement names. Roll once for the prefix, and once for the suffix. If the combination doesn't quite work, look at adjacent rows or reverse the digits. Once you have your answer, envision what feature, person, or event inspired the name.",
		"text_tr": "## Kehanet 5: Kıyı Suları Konumu (sayfa 176)\n\nKıyı boyunca gemiyle ya da tekneyle yolculuk ederken bir ilgi noktası ya da varış noktası belirlemek için bu kehaneti kullan.\n\n## Kehanet 6: Konum Tasviri (sayfa 177)\n\nKonum ya da Kıyı Suları Konumu kehanetlerine ayrıntı katmak için ya da tek başına bir konumun tasvirini üretmek için bu kehaneti kullan. Fazladan ayrıntı için birden çok kez zar at.\n\nKiralık bir tekneyle nehirden aşağı yolculuk edersin. Yolculuğuna biraz renk katmak istersin, bu yüzden ayrıntı için Konum Tasviri kehanetini kullanırsın. \"Ulaşılmaz\" yanıtını verir.\n\nBu sonucu, nehrin bazı kesimlerinin sığ olduğu, mürettebatı tekneyi kıyı boyunca karadan taşımaya zorladığı şeklinde yorumlarsın. Bu, bir pusu için kusursuz bir fırsat gibi görünüyor...\n\n## Kehanet 7: Yerleşim Adı (sayfa 178)\n\nBir Demir Diyar sakini yerleşimi için temalı bir ad sormak üzere bu kehaneti kullan. Kategori için bir kez, örneklerden seçmek için bir kez daha zar at. Alternatif olarak, yalnızca kategori için zar at ve temaya uyan bir ad bul. Her iki durumda da, adın anlamını ve bu yerleşimin çevresini, geçim kaynağını, kültürünü ya da tarihini nasıl etkilediğini düşün. Bu da yeni görevler için anlatı çengelleri ve fırsatlara ilham verebilir.\n\n## Kehanet 8: Hızlı Yerleşim Adı Üreteci (sayfa 180)\n\nYerleşim adları için daha basit bir alternatif olarak bu kehaneti kullan. Ön ek için bir kez, son ek için bir kez zar at. Bileşim tam oturmazsa, komşu satırlara bak ya da rakamları ters çevir. Cevabını aldığında, hangi özelliğin, kişinin ya da olayın bu ada ilham verdiğini gözünde canlandır."
	},
	{
		"page": 171,
		"img": "/rulebook/kehanetler/p171.webp",
		"title_en": "Settlement Trouble and Character Oracles",
		"title_tr": "Yerleşim Sorunu ve Karakter Kehanetleri",
		"text_en": "## Oracle 9: Settlement Trouble (page 181)\n\nUse this table to generate a narrative hook for a problem faced by a community. This oracle can help inspire a vow for your character or serve as a prompt for a trouble you encounter when you interact with a settlement. Use other oracles, as appropriate, to help flesh out the answer.\n\nYou were attacked by raiders while portaging the boat around some shallows, and barely managed to fend off the attack. Now, you seek out healing, rest, and supplies at a nearby village.\n\nFirst, you generate a name for the settlement. You use the Ironlander Settlement Name oracle and roll \"A historical event\" as the category, and \"Firstmeet\" from the examples. You decide this village sits on the site of the first encounter between elves and humans.\n\nYou roll a match on your Sojourn move, and opt to trigger a new narrative hook. You ask, \"What's the problem here?\" and roll on the Settlement Trouble table. The oracle answers, \"Debt comes due.\"\n\nPerhaps the band of raiders you encountered along the river have also been making demands of Firstmeet to supply them with food. The raiders are due to return soon, but the villagers won't survive the winter without the meager provisions they have left. You Swear an Iron Vow to help them.\n\n## Oracle 10: Character Role (page 182)\n\nUse this oracle to define the background for a character, or to generate a random encounter.\n\n## Oracle 11: Character Goal (page 182)\n\nUse this oracle to define the primary motivation of an NPC or a faction. It can also be used to kick-off a personal quest for your own character.\n\n## Oracle 12: Character Descriptor (page 183)\n\nUse this oracle to help flesh out a character's personality or physical characteristics. Roll more than once to add additional detail. You can combine all three character oracles (10, 11 and 12), plus a roll on an appropriate name table, to build an outline of an NPC.",
		"text_tr": "## Kehanet 9: Yerleşim Sorunu (sayfa 181)\n\nBu tabloyu bir topluluğun karşılaştığı bir sorun için anlatı çengeli üretmek üzere kullan. Bu kehanet, karakterin için bir anda ilham verebilir ya da bir yerleşimle etkileşime girdiğinde karşılaştığın bir sorun için yönlendirme görevi görebilir. Cevabı canlandırmaya yardımcı olmak için uygun şekilde diğer kehanetleri kullan.\n\nTekneyi bazı sığlıkların etrafından karadan taşırken yağmacılar tarafından saldırıya uğradın ve saldırıyı güçbela savuşturabildin. Şimdi yakındaki bir köyde şifa, dinlenme ve erzak ararsın.\n\nİlkin, yerleşim için bir ad üretirsin. Demir Diyar Sakini Yerleşim Adı kehanetini kullanırsın ve kategori olarak \"Tarihi bir olay\", örneklerden de \"Firstmeet\" atarsın. Bu köyün, elflerle insanlar arasındaki ilk karşılaşmanın olduğu yerde kurulu olduğuna karar verirsin.\n\nKonaklama hamlende bir eşleşme atarsın ve yeni bir anlatı çengelini tetiklemeyi seçersin. \"Buradaki sorun ne?\" diye sorar ve Yerleşim Sorunu tablosuna zar atarsın. Kehanet, \"Borcun vadesi dolar\" yanıtını verir.\n\nBelki nehir boyunca karşılaştığın yağmacı çetesi, Firstmeet'ten de kendilerine yiyecek tedarik etmesini istiyordur. Yağmacıların yakında dönmesi bekleniyor, ama köylüler ellerinde kalan kıt erzakla kışı atlatamayacaklar. Onlara yardım etmek için Demir Ant İçersin.\n\n## Kehanet 10: Karakter Rolü (sayfa 182)\n\nBir karakterin geçmişini tanımlamak ya da rastgele bir karşılaşma üretmek için bu kehaneti kullan.\n\n## Kehanet 11: Karakter Hedefi (sayfa 182)\n\nBir OYK'nın ya da bir hizbin temel güdüsünü tanımlamak için bu kehaneti kullan. Kendi karakterin için kişisel bir görevi başlatmak için de kullanılabilir.\n\n## Kehanet 12: Karakter Tanımı (sayfa 183)\n\nBir karakterin kişiliğini ya da fiziksel özelliklerini canlandırmaya yardımcı olmak için bu kehaneti kullan. Ek ayrıntı katmak için birden çok kez zar at. Bir OYK'nın taslağını oluşturmak için üç karakter kehanetinin (10, 11 ve 12) tümünü, ayrıca uygun bir isim tablosuna atılan bir zarı birleştirebilirsin."
	},
	{
		"page": 172,
		"img": "/rulebook/kehanetler/p172.webp",
		"title_en": "Name and Combat Action Oracles",
		"title_tr": "İsim ve Savaş Eylemi Kehanetleri",
		"text_en": "## Oracle 13: Ironlander Names (page 184)\n\nUse this oracle to quickly generate a name for an Ironlander character. Roll on either table. Surnames are not used in the Ironlands and names are often gender-neutral. If a name doesn't fit a character, or you don't like the sound of it, look up or down a row for your answer, or reverse the digits.\n\nYou can also ignore this oracle and use your own preferred naming conventions or name generators for your Ironland characters.\n\nWhat do the villagers know of the raider chief? You roll on the character oracles to learn more about him. The Role oracle tells you his background is a \"Leader.\" The Character Goal oracle tells you his mission is to \"Fulfill a duty.\" Then, you ask what makes him distinctive by rolling on the Descriptor table, and the oracle answers, \"Obsessed.\"\n\nPutting these pieces together, you decide the bandit chief was once the leader of a settlement to the north. He and his allies were exiled following a coup. He is sworn to protect his followers and see them through their life as outcasts, but he is also obsessed with someday reclaiming his home.\n\nWith a few rolls and a bit of interpretation, you've added a fair bit of texture and pathos to what might otherwise be a stock villain character. You roll for his name and the oracle tells you, \"Khulan.\"\n\n## Oracle 14: Elf Names (page 186)\n\nUse this oracle to generate a name for an elf character. To learn more about elves in the Ironlands, see page 142.\n\n## Oracle 15: Other Names (page 187)\n\nUse this oracle for other firstborn characters, including giants, varou, and trolls.\n\n## Oracle 16: Combat Action (page 188)\n\nUse this oracle to help inspire an action for an NPC in combat. When you're not sure what your foe does next, particularly when they have initiative, roll on this table and interpret the result as appropriate to your foe and the situation.",
		"text_tr": "## Kehanet 13: Demir Diyar Sakini İsimleri (sayfa 184)\n\nBir Demir Diyar sakini karakteri için hızla bir isim üretmek üzere bu kehaneti kullan. İki tablodan birine zar at. Demir Diyarlar'da soyadı kullanılmaz ve isimler çoğunlukla cinsiyetten bağımsızdır. Bir isim bir karaktere uymazsa ya da kulağa gelişini beğenmezsen, cevabın için bir satır yukarı ya da aşağı bak veya rakamları ters çevir.\n\nBu kehaneti göz ardı edip Demir Diyar karakterlerin için kendi tercih ettiğin adlandırma yöntemlerini ya da isim üreteçlerini de kullanabilirsin.\n\nKöylüler yağmacı reisi hakkında ne biliyor? Onun hakkında daha fazla şey öğrenmek için karakter kehanetlerine zar atarsın. Rol kehaneti, geçmişinin bir \"Lider\" olduğunu söyler. Karakter Hedefi kehaneti, görevinin \"Bir görevi yerine getir\" olduğunu söyler. Sonra, Niteleyici tablosuna zar atarak onu ayırt edici kılan şeyi sorarsın ve kehanet, \"Takıntılı\" yanıtını verir.\n\nBu parçaları bir araya getirerek, haydut reisin bir zamanlar kuzeydeki bir yerleşimin lideri olduğuna karar verirsin. O ve müttefikleri bir darbenin ardından sürgün edildi. Takipçilerini korumaya ve onları dışlanmışlar olarak yaşamları boyunca götürmeye ant içmiştir, ama bir gün evini geri almaya da takıntılıdır.\n\nBirkaç zar atışı ve biraz yorumla, aksi halde sıradan bir kötü karakter olabilecek birine epeyce doku ve duygu kattın. İsmi için zar atarsın ve kehanet sana, \"Khulan\" der.\n\n## Kehanet 14: Elf İsimleri (sayfa 186)\n\nBir elf karakteri için isim üretmek üzere bu kehaneti kullan. Demir Diyarlar'daki elfler hakkında daha fazla bilgi için sayfa 142'ye bak.\n\n## Kehanet 15: Diğer İsimler (sayfa 187)\n\nDevler, varou ve troller dahil diğer İlk Doğan karakterler için bu kehaneti kullan.\n\n## Kehanet 16: Savaş Eylemi (sayfa 188)\n\nSavaşta bir OYK için bir eyleme ilham vermeye yardımcı olmak üzere bu kehaneti kullan. Düşmanının sırada ne yapacağından emin değilken, özellikle de inisiyatif onlardayken, bu tabloya zar at ve sonucu düşmanına ve duruma uygun şekilde yorumla."
	},
	{
		"page": 173,
		"img": "/rulebook/kehanetler/p173.webp",
		"title_en": "Mystic Backlash, Major Plot Twist, and Challenge Rank Oracles",
		"title_tr": "Mistik Tepki, Büyük Olay Örgüsü Sürprizi ve Zorluk Derecesi Kehanetleri",
		"text_en": "You face off against Khulan, the leader of the raiding party. You charge at him, sword swinging. He easily parries the blow, and takes initiative. What does he do next? You roll on the Combat Action table. The oracle answers, \"Provoke a reckless response.\"\n\nKhulan laughs at you, slamming the haft of his axe against his shield. \"C'mon!\" he yells, goading you into a hasty attack. \"You can do better than that.\"\n\nYou Face Danger to try to resist the taunt...\n\n## Oracle 17: Mystic Backlash (page 189)\n\nThose who deal in magic may find themselves at the mercy of chaos. This oracle can supplement, or replace, the Pay the Price table (page 105) when resolving the outcome of a failed ritual or other negative interaction with mystical forces. Use this oracle in dramatic moments, or to introduce an unexpected outcome triggered by a match.\n\n## Oracle 18: Major Plot Twist (page 190)\n\nUse this oracle to introduce a narrative surprise or revelation. Most of these results have a negative implication, and can be used to resolve a match at a crucial moment in your story. In particular, this is an effective tool to leverage when you make a move with matched 10's on the challenge dice.\n\nThis oracle offers similar results to the Pay the Price table (page 105), but is more focused on dramatic events tied to your current quests.\n\nKhulan has been defeated, but you roll a miss with matched 10's when you Fulfill Your Vow. Perhaps these raiders are part of a larger force? The village is still in danger, leaving your vow unfulfilled. To get some more detail and resolve the match, you check the Major Plot Twist oracle. The oracle responds, \"Two seemingly unrelated situations are shown to be connected.\"\n\nBased on that answer, you decide to connect this encounter to your original quest. The raider and his clan all bear branded scars in the shape of the stolen relic. What does it mean? Play to find out.\n\n## Oracle 19: Challenge Rank (page 190)\n\nUse this oracle when you want to randomly determine the challenge rank of a quest, journey, or fight.",
		"text_tr": "Yağma müfrezesinin lideri Khulan'la karşı karşıya gelirsin. Kılıcını savurarak ona doğru atılırsın. Darbeyi kolayca savuşturur ve inisiyatifi alır. Sırada ne yapar? Savaş Eylemi tablosuna zar atarsın. Kehanet, \"Pervasız bir tepki kışkırt\" yanıtını verir.\n\nKhulan sana güler, baltasının sapını kalkanına vurur. \"Hadi!\" diye bağırır, seni aceleci bir saldırıya kışkırtarak. \"Bundan daha iyisini yapabilirsin.\"\n\nİğnelemeye direnmeye çalışmak için Tehlikeyle Yüzleşirsin...\n\n## Kehanet 17: Mistik Tepki (sayfa 189)\n\nBüyüyle uğraşanlar kendilerini kaosun insafına kalmış bulabilirler. Bu kehanet, başarısız bir ritüelin ya da mistik güçlerle başka bir olumsuz etkileşimin sonucunu çözerken Bedelini Öde tablosunu (sayfa 105) destekleyebilir ya da onun yerini alabilir. Bu kehaneti dramatik anlarda ya da bir eşleşmeyle tetiklenen beklenmedik bir sonuç katmak için kullan.\n\n## Kehanet 18: Büyük Olay Örgüsü Sürprizi (sayfa 190)\n\nAnlatıya bir sürpriz ya da açığa çıkış katmak için bu kehaneti kullan. Bu sonuçların çoğu olumsuz bir ima taşır ve hikâyenin can alıcı bir anındaki bir eşleşmeyi çözmek için kullanılabilir. Özellikle, zorluk zarlarında eşleşmiş 10'larla bir hamle yaptığında yararlanılacak etkili bir araçtır.\n\nBu kehanet, Bedelini Öde tablosuna (sayfa 105) benzer sonuçlar sunar, ama mevcut görevlerine bağlı dramatik olaylara daha çok odaklanır.\n\nKhulan yenildi, ama Antını Tamamla yaparken eşleşmiş 10'larla başarısızlık atarsın. Belki bu yağmacılar daha büyük bir gücün parçasıdır? Köy hâlâ tehlikede ve andın tamamlanmamış kalır. Biraz daha ayrıntı almak ve eşleşmeyi çözmek için Büyük Olay Örgüsü Sürprizi kehanetine bakarsın. Kehanet, \"Birbiriyle ilgisiz görünen iki durumun bağlantılı olduğu açığa çıkar\" yanıtını verir.\n\nBu cevaba dayanarak, bu karşılaşmayı asıl görevine bağlamaya karar verirsin. Yağmacı ve klanının hepsi, çalınan kutsal emanetin biçiminde dağlanmış yara izleri taşır. Bu ne anlama geliyor? Öğrenmek için oyna.\n\n## Kehanet 19: Zorluk Derecesi (sayfa 190)\n\nBir görevin, yolculuğun ya da dövüşün zorluk derecesini rastgele belirlemek istediğinde bu kehaneti kullan."
	},
	{
		"page": 174,
		"img": "/rulebook/kehanetler/p174.webp",
		"title_en": "Oracle 1: Action",
		"title_tr": "Kehanet 1: Eylem",
		"text_en": "## Oracle 1: Action\n\n- 1: Scheme\n- 2: Clash\n- 3: Weaken\n- 4: Initiate\n- 5: Create\n- 6: Swear\n- 7: Avenge\n- 8: Guard\n- 9: Defeat\n- 10: Control\n- 11: Break\n- 12: Risk\n- 13: Surrender\n- 14: Inspect\n- 15: Raid\n- 16: Evade\n- 17: Assault\n- 18: Deflect\n- 19: Threaten\n- 20: Attack\n- 21: Leave\n- 22: Preserve\n- 23: Manipulate\n- 24: Remove\n- 25: Eliminate\n- 26: Withdraw\n- 27: Abandon\n- 28: Investigate\n- 29: Hold\n- 30: Focus\n- 31: Uncover\n- 32: Breach\n- 33: Aid\n- 34: Uphold\n- 35: Falter\n- 36: Suppress\n- 37: Hunt\n- 38: Share\n- 39: Destroy\n- 40: Avoid\n- 41: Reject\n- 42: Demand\n- 43: Explore\n- 44: Bolster\n- 45: Seize\n- 46: Mourn\n- 47: Reveal\n- 48: Gather\n- 49: Defy\n- 50: Transform\n- 51: Persevere\n- 52: Serve\n- 53: Begin\n- 54: Move\n- 55: Coordinate\n- 56: Resist\n- 57: Await\n- 58: Impress\n- 59: Take\n- 60: Oppose\n- 61: Capture\n- 62: Overwhelm\n- 63: Challenge\n- 64: Acquire\n- 65: Protect\n- 66: Finish\n- 67: Strengthen\n- 68: Restore\n- 69: Advance\n- 70: Command\n- 71: Refuse\n- 72: Find\n- 73: Deliver\n- 74: Hide\n- 75: Fortify\n- 76: Betray\n- 77: Secure\n- 78: Arrive\n- 79: Affect\n- 80: Change\n- 81: Defend\n- 82: Debate\n- 83: Support\n- 84: Follow\n- 85: Construct\n- 86: Locate\n- 87: Endure\n- 88: Release\n- 89: Lose\n- 90: Reduce\n- 91: Escalate\n- 92: Distract\n- 93: Journey\n- 94: Escort\n- 95: Learn\n- 96: Communicate\n- 97: Depart\n- 98: Search\n- 99: Charge\n- 00: Summon",
		"text_tr": "## Kehanet 1: Eylem\n\n- 1: Entrika kur\n- 2: Çatış\n- 3: Zayıflat\n- 4: Başlat\n- 5: Yarat\n- 6: Ant iç\n- 7: Öcünü al\n- 8: Gözcülük et\n- 9: Alt et\n- 10: Denetle\n- 11: Kır\n- 12: Riske at\n- 13: Teslim ol\n- 14: İncele\n- 15: Yağmala\n- 16: Sıyrıl\n- 17: Hücum et\n- 18: Savuştur\n- 19: Tehdit et\n- 20: Saldır\n- 21: Ayrıl\n- 22: Muhafaza et\n- 23: Yönlendir\n- 24: Kaldır\n- 25: Ortadan kaldır\n- 26: Geri çekil\n- 27: Terk et\n- 28: Soruştur\n- 29: Tut\n- 30: Odaklan\n- 31: Açığa çıkar\n- 32: Yar\n- 33: Yardım et\n- 34: Kolla\n- 35: Sendele\n- 36: Bastır\n- 37: Avla\n- 38: Paylaş\n- 39: Mahvet\n- 40: Kaçın\n- 41: Reddet\n- 42: Talep et\n- 43: Keşfet\n- 44: Güçlendir\n- 45: Ele geçir\n- 46: Yas tut\n- 47: İfşa et\n- 48: Topla\n- 49: Karşı gel\n- 50: Dönüştür\n- 51: Sebat et\n- 52: Hizmet et\n- 53: Başla\n- 54: Hareket et\n- 55: Eşgüdümle\n- 56: Diren\n- 57: Bekle\n- 58: Etkile\n- 59: Al\n- 60: Karşı çık\n- 61: Esir al\n- 62: Bunalt\n- 63: Meydan oku\n- 64: Edin\n- 65: Himaye et\n- 66: Bitir\n- 67: Kuvvetlendir\n- 68: Onar\n- 69: İlerle\n- 70: Buyur\n- 71: Geri çevir\n- 72: Bul\n- 73: Ulaştır\n- 74: Gizlen\n- 75: Tahkim et\n- 76: İhanet et\n- 77: Güvenceye al\n- 78: Ulaş\n- 79: Tesir et\n- 80: Değiştir\n- 81: Savun\n- 82: Tartış\n- 83: Destekle\n- 84: İzle\n- 85: İnşa et\n- 86: Konumunu belirle\n- 87: Katlan\n- 88: Serbest bırak\n- 89: Kaybet\n- 90: Azalt\n- 91: Tırmandır\n- 92: Dikkatini dağıt\n- 93: Yolculuk et\n- 94: Refakat et\n- 95: Öğren\n- 96: İletişim kur\n- 97: Yola çık\n- 98: Ara\n- 99: Saldırıya geç\n- 00: Çağır"
	},
	{
		"page": 175,
		"img": "/rulebook/kehanetler/p175.webp",
		"title_en": "Oracle 2: Theme",
		"title_tr": "Kehanet 2: Tema",
		"text_en": "## Oracle 2: Theme\n\n- 1: Risk\n- 2: Ability\n- 3: Price\n- 4: Ally\n- 5: Battle\n- 6: Safety\n- 7: Survival\n- 8: Weapon\n- 9: Wound\n- 10: Shelter\n- 11: Leader\n- 12: Fear\n- 13: Time\n- 14: Duty\n- 15: Secret\n- 16: Innocence\n- 17: Renown\n- 18: Direction\n- 19: Death\n- 20: Honor\n- 21: Labor\n- 22: Solution\n- 23: Tool\n- 24: Balance\n- 25: Love\n- 26: Barrier\n- 27: Creation\n- 28: Decay\n- 29: Trade\n- 30: Bond\n- 31: Hope\n- 32: Superstition\n- 33: Peace\n- 34: Deception\n- 35: History\n- 36: World\n- 37: Vow\n- 38: Protection\n- 39: Nature\n- 40: Opinion\n- 41: Burden\n- 42: Vengeance\n- 43: Opportunity\n- 44: Faction\n- 45: Danger\n- 46: Corruption\n- 47: Freedom\n- 48: Debt\n- 49: Hate\n- 50: Possession\n- 51: Stranger\n- 52: Passage\n- 53: Land\n- 54: Creature\n- 55: Disease\n- 56: Advantage\n- 57: Blood\n- 58: Language\n- 59: Rumor\n- 60: Weakness\n- 61: Greed\n- 62: Family\n- 63: Resource\n- 64: Structure\n- 65: Dream\n- 66: Community\n- 67: War\n- 68: Portent\n- 69: Prize\n- 70: Destiny\n- 71: Momentum\n- 72: Power\n- 73: Memory\n- 74: Ruin\n- 75: Mysticism\n- 76: Rival\n- 77: Problem\n- 78: Idea\n- 79: Revenge\n- 80: Health\n- 81: Fellowship\n- 82: Enemy\n- 83: Religion\n- 84: Spirit\n- 85: Fame\n- 86: Desolation\n- 87: Strength\n- 88: Knowledge\n- 89: Truth\n- 90: Quest\n- 91: Pride\n- 92: Loss\n- 93: Law\n- 94: Path\n- 95: Warning\n- 96: Relationship\n- 97: Wealth\n- 98: Home\n- 99: Strategy\n- 00: Supply",
		"text_tr": "## Kehanet 2: Tema\n\n- 1: Risk\n- 2: Yetenek\n- 3: Bedel\n- 4: Müttefik\n- 5: Muharebe\n- 6: Güvenlik\n- 7: Hayatta kalma\n- 8: Silah\n- 9: Yara\n- 10: Barınak\n- 11: Lider\n- 12: Korku\n- 13: Zaman\n- 14: Görev\n- 15: Sır\n- 16: Masumiyet\n- 17: Şöhret\n- 18: Yön\n- 19: Ölüm\n- 20: Onur\n- 21: Emek\n- 22: Çözüm\n- 23: Alet\n- 24: Denge\n- 25: Aşk\n- 26: Engel\n- 27: Yaratım\n- 28: Çürüme\n- 29: Ticaret\n- 30: Bağ\n- 31: Umut\n- 32: Batıl inanç\n- 33: Barış\n- 34: Aldatmaca\n- 35: Tarih\n- 36: Dünya\n- 37: Ant\n- 38: Koruma\n- 39: Doğa\n- 40: Görüş\n- 41: Yük\n- 42: Öç\n- 43: Fırsat\n- 44: Hizip\n- 45: Tehlike\n- 46: Yozlaşma\n- 47: Özgürlük\n- 48: Borç\n- 49: Nefret\n- 50: Mülk\n- 51: Yabancı\n- 52: Geçit\n- 53: Toprak\n- 54: Yaratık\n- 55: Hastalık\n- 56: Avantaj\n- 57: Kan\n- 58: Dil\n- 59: Söylenti\n- 60: Zayıflık\n- 61: Açgözlülük\n- 62: Aile\n- 63: Kaynak\n- 64: Yapı\n- 65: Rüya\n- 66: Topluluk\n- 67: Savaş\n- 68: Alâmet\n- 69: Ödül\n- 70: Yazgı\n- 71: Momentum\n- 72: Güç\n- 73: Anı\n- 74: Yıkım\n- 75: Mistisizm\n- 76: Rakip\n- 77: Sorun\n- 78: Fikir\n- 79: İntikam\n- 80: Can\n- 81: Yoldaşlık\n- 82: Düşman\n- 83: Din\n- 84: Ruh\n- 85: Ün\n- 86: Issızlık\n- 87: Kuvvet\n- 88: Bilgi\n- 89: Hakikat\n- 90: Görev\n- 91: Gurur\n- 92: Kayıp\n- 93: Yasa\n- 94: Yol\n- 95: Uyarı\n- 96: İlişki\n- 97: Servet\n- 98: Yurt\n- 99: Strateji\n- 00: İkmal"
	},
	{
		"page": 176,
		"img": "/rulebook/kehanetler/p176.webp",
		"title_en": "Oracle 3: Region · Oracle 4: Location · Oracle 5: Coastal Waters Location",
		"title_tr": "Kehanet 3: Bölge · Kehanet 4: Konum · Kehanet 5: Kıyı Suları Konumu",
		"text_en": "## Oracle 3: Region\n\n- 1-12: Barrier Islands\n- 13-24: Ragged Coast\n- 25-34: Deep Wilds\n- 35-46: Flooded Lands\n- 47-60: Havens\n- 61-72: Hinterlands\n- 73-84: Tempest Hills\n- 85-94: Veiled Mountains\n- 95-99: Shattered Wastes\n- 00: Elsewhere\n\n## Oracle 4: Location\n\n- 1: Hideout\n- 2: Ruin\n- 3: Mine\n- 4: Waste\n- 5: Mystical Site\n- 6: Path\n- 7: Outpost\n- 8: Wall\n- 9: Battlefield\n- 10: Hovel\n- 11: Spring\n- 12: Lair\n- 13: Fort\n- 14: Bridge\n- 15: Camp\n- 16: Cairn/Grave\n- 17-18: Caravan\n- 19-20: Waterfall\n- 21-22: Cave\n- 23-24: Swamp\n- 25-26: Fen\n- 27-28: Ravine\n- 29-30: Road\n- 31-32: Tree\n- 33-34: Pond\n- 35-36: Fields\n- 37-38: Marsh\n- 39-40: Steading\n- 41-42: Rapids\n- 43-44: Pass\n- 45-46: Trail\n- 47-48: Glade\n- 49-50: Plain\n- 51-52: Ridge\n- 53-54: Cliff\n- 55-56: Grove\n- 57-58: Village\n- 59-60: Moor\n- 61-62: Thicket\n- 63-64: River Ford\n- 65-66: Valley\n- 67-68: Bay/Fjord\n- 69-70: Foothills\n- 71-72: Lake\n- 73-75: River\n- 76-79: Forest\n- 80-83: Coast\n- 84-88: Hill\n- 89-93: Mountain\n- 94-99: Woods\n- 00: Anomaly\n\n## Oracle 5: Coastal Waters Location\n\n- 1: Fleet\n- 2: Sargassum\n- 3: Flotsam\n- 4: Mystical Site\n- 5: Lair\n- 6-10: Wreck\n- 11-15: Harbor\n- 16-23: Ship\n- 24-30: Rocks\n- 31-38: Fjord\n- 39-46: Estuary\n- 47-54: Cove\n- 55-62: Bay\n- 63-70: Ice\n- 71-85: Island\n- 86-99: Open Water\n- 00: Anomaly",
		"text_tr": "## Kehanet 3: Bölge\n\n- 1-12: Set Adaları\n- 13-24: Parçalı Kıyı\n- 25-34: Derin Yabanlar\n- 35-46: Su Basmış Topraklar\n- 47-60: Sığınaklar\n- 61-72: Ardtopraklar\n- 73-84: Fırtına Tepeleri\n- 85-94: Örtülü Dağlar\n- 95-99: Paramparça Çoraklıklar\n- 00: Başka bir yer\n\n## Kehanet 4: Konum\n\n- 1: Saklanak\n- 2: Harabe\n- 3: Maden\n- 4: Çoraklık\n- 5: Mistik Mekân\n- 6: Yol\n- 7: İleri Karakol\n- 8: Sur\n- 9: Savaş Meydanı\n- 10: Viran Kulübe\n- 11: Pınar\n- 12: İn\n- 13: Hisar\n- 14: Köprü\n- 15: Kamp\n- 16: Höyük/Mezar\n- 17-18: Kervan\n- 19-20: Şelale\n- 21-22: Mağara\n- 23-24: Bataklık\n- 25-26: Sazlık\n- 27-28: Yarıntı\n- 29-30: Patika\n- 31-32: Ağaç\n- 33-34: Gölet\n- 35-36: Tarlalar\n- 37-38: Batak\n- 39-40: Yerleşim\n- 41-42: İvinti\n- 43-44: Geçit\n- 45-46: İz\n- 47-48: Kayrak\n- 49-50: Ova\n- 51-52: Sırt\n- 53-54: Uçurum\n- 55-56: Koru\n- 57-58: Köy\n- 59-60: Fundalık\n- 61-62: Çalılık\n- 63-64: Nehir Geçidi\n- 65-66: Vadi\n- 67-68: Körfez/Fiyort\n- 69-70: Etekler\n- 71-72: Göl\n- 73-75: Nehir\n- 76-79: Orman\n- 80-83: Kıyı\n- 84-88: Tepe\n- 89-93: Dağ\n- 94-99: Ağaçlık\n- 00: Anomali\n\n## Kehanet 5: Kıyı Suları Konumu\n\n- 1: Filo\n- 2: Sargassum\n- 3: Enkaz Döküntüsü\n- 4: Mistik Mekân\n- 5: İn\n- 6-10: Batık\n- 11-15: Liman\n- 16-23: Gemi\n- 24-30: Kayalıklar\n- 31-38: Fiyort\n- 39-46: Haliç\n- 47-54: Koy\n- 55-62: Körfez\n- 63-70: Buz\n- 71-85: Ada\n- 86-99: Açık Su\n- 00: Anomali"
	},
	{
		"page": 177,
		"img": "/rulebook/kehanetler/p177.webp",
		"title_en": "Oracle 6: Location Descriptor",
		"title_tr": "Kehanet 6: Konum Tanımı",
		"text_en": "## Oracle 6: Location Descriptor\n\n- 1-2: High\n- 3-4: Remote\n- 5-6: Exposed\n- 7-8: Small\n- 9-10: Broken\n- 11-12: Diverse\n- 13-14: Rough\n- 15-16: Dark\n- 17-18: Shadowy\n- 19-20: Contested\n- 21-22: Grim\n- 23-24: Wild\n- 25-26: Fertile\n- 27-28: Blocked\n- 29-30: Ancient\n- 31-32: Perilous\n- 33-34: Hidden\n- 35-36: Occupied\n- 37-38: Rich\n- 39-40: Big\n- 41-42: Savage\n- 43-44: Defended\n- 45-46: Withered\n- 47-48: Mystical\n- 49-50: Inaccessible\n- 51-52: Protected\n- 53-54: Abandoned\n- 55-56: Wide\n- 57-58: Foul\n- 59-60: Dead\n- 61-62: Ruined\n- 63-64: Barren\n- 65-66: Cold\n- 67-68: Blighted\n- 69-70: Low\n- 71-72: Beautiful\n- 73-74: Abundant\n- 75-76: Lush\n- 77-78: Flooded\n- 79-80: Empty\n- 81-82: Strange\n- 83-84: Corrupted\n- 85-86: Peaceful\n- 87-88: Forgotten\n- 89-90: Expansive\n- 91-92: Settled\n- 93-94: Dense\n- 95-96: Civilized\n- 97-98: Desolate\n- 99-00: Isolated",
		"text_tr": "## Kehanet 6: Konum Tanımı\n\n- 1-2: Yüksek\n- 3-4: Ücra\n- 5-6: Açıkta\n- 7-8: Küçük\n- 9-10: Yıkık\n- 11-12: Çeşitli\n- 13-14: Engebeli\n- 15-16: Karanlık\n- 17-18: Gölgeli\n- 19-20: Çekişmeli\n- 21-22: Acımasız\n- 23-24: Vahşi\n- 25-26: Verimli\n- 27-28: Tıkalı\n- 29-30: Kadim\n- 31-32: Tehlikeli\n- 33-34: Gizli\n- 35-36: İşgal altında\n- 37-38: Zengin\n- 39-40: Büyük\n- 41-42: Yabani\n- 43-44: Korunan\n- 45-46: Solmuş\n- 47-48: Mistik\n- 49-50: Ulaşılmaz\n- 51-52: Himaye altında\n- 53-54: Terk edilmiş\n- 55-56: Geniş\n- 57-58: Pis\n- 59-60: Ölü\n- 61-62: Harap\n- 63-64: Çorak\n- 65-66: Soğuk\n- 67-68: Kavruk\n- 69-70: Alçak\n- 71-72: Güzel\n- 73-74: Bereketli\n- 75-76: Gür\n- 77-78: Su basmış\n- 79-80: Boş\n- 81-82: Tuhaf\n- 83-84: Yozlaşmış\n- 85-86: Huzurlu\n- 87-88: Unutulmuş\n- 89-90: Engin\n- 91-92: İskânlı\n- 93-94: Sık\n- 95-96: Medeni\n- 97-98: Issız\n- 99-00: Tecrit edilmiş"
	},
	{
		"page": 178,
		"img": "/rulebook/kehanetler/p178.webp",
		"title_en": "Oracle 7: Settlement Name",
		"title_tr": "Kehanet 7: Yerleşim Adı",
		"text_en": "## Oracle 7: Settlement Name\n\n### 01-15: A feature of the landscape.\nEnvision what it is. What makes it unusual or distinctive?\n\nExamples:\n- 1-10: Highmount\n- 11-20: Brackwater\n- 21-30: Frostwood\n- 31-40: Redcrest\n- 41-50: Grimtree\n- 51-60: Boarwood\n- 61-70: Foxhollow\n- 71-80: Elderwatch\n- 81-90: Elkfield\n- 91-00: Dragonshadow\n\n### 16-30: A historical event.\nWhat happened here? What place or practice commemorates this event?\n\nExamples:\n- 1-10: Swordbreak\n- 11-20: Fool's Fall\n- 21-30: Firstmeet\n- 31-40: Brokenhelm\n- 41-50: Mournhaunt\n- 51-60: Olgar's Stand\n- 61-70: Lostwater\n- 71-80: Rojirra's Lament\n- 81-90: Lastmarch\n- 91-00: Rockfall\n\n### 31-45: A manmade edifice.\nWhat is it? Why is it important to this settlement's history?\n\nExamples:\n- 1-10: Whitebridge\n- 11-20: Lonefort\n- 21-30: Highcairn\n- 31-40: Redhall\n- 41-50: Darkwell\n- 51-60: Timberwall\n- 61-70: Stonetower\n- 71-80: Thornhall\n- 81-90: Cinderhome\n- 91-00: Fallowfield\n\n### 46-60: A creature.\nWhy have the people of this settlement chosen this creature as their totem? How is it represented in art or rituals?\n\nExamples:\n- 1-10: Ravencliff\n- 11-20: Bearmark\n- 21-30: Wolfcrag\n- 31-40: Eaglespire\n- 41-50: Wyvern's Rest\n- 51-60: Stoneford\n- 61-70: Deepwater\n- 71-80: Whitefall\n- 81-90: Graycliff\n- 91-00: Three Rivers",
		"text_tr": "## Kehanet 7: Yerleşim Adı\n\n### 01-15: Bir arazi özelliği.\nNe olduğunu gözünde canlandır. Onu sıra dışı ya da ayırt edici kılan nedir?\n\nÖrnekler:\n- 1-10: Highmount\n- 11-20: Brackwater\n- 21-30: Frostwood\n- 31-40: Redcrest\n- 41-50: Grimtree\n- 51-60: Boarwood\n- 61-70: Foxhollow\n- 71-80: Elderwatch\n- 81-90: Elkfield\n- 91-00: Dragonshadow\n\n### 16-30: Tarihî bir olay.\nBurada ne oldu? Bu olayı hangi yer ya da gelenek anıyor?\n\nÖrnekler:\n- 1-10: Swordbreak\n- 11-20: Fool's Fall\n- 21-30: Firstmeet\n- 31-40: Brokenhelm\n- 41-50: Mournhaunt\n- 51-60: Olgar's Stand\n- 61-70: Lostwater\n- 71-80: Rojirra's Lament\n- 81-90: Lastmarch\n- 91-00: Rockfall\n\n### 31-45: İnsan eliyle yapılmış bir yapı.\nNedir? Bu yerleşimin tarihi için neden önemlidir?\n\nÖrnekler:\n- 1-10: Whitebridge\n- 11-20: Lonefort\n- 21-30: Highcairn\n- 31-40: Redhall\n- 41-50: Darkwell\n- 51-60: Timberwall\n- 61-70: Stonetower\n- 71-80: Thornhall\n- 81-90: Cinderhome\n- 91-00: Fallowfield\n\n### 46-60: Bir yaratık.\nBu yerleşimin halkı neden bu yaratığı totemleri olarak seçti? Sanatta ya da ritüellerde nasıl temsil ediliyor?\n\nÖrnekler:\n- 1-10: Ravencliff\n- 11-20: Bearmark\n- 21-30: Wolfcrag\n- 31-40: Eaglespire\n- 41-50: Wyvern's Rest\n- 51-60: Stoneford\n- 61-70: Deepwater\n- 71-80: Whitefall\n- 81-90: Graycliff\n- 91-00: Three Rivers"
	},
	{
		"page": 179,
		"img": "/rulebook/kehanetler/p179.webp",
		"title_en": "Oracle 7: Settlement Name (continued)",
		"title_tr": "Kehanet 7: Yerleşim Adı (devam)",
		"text_en": "### 61-75: A word in an Old World language.\nWhat culture is represented by this word? What does it translate to?\n\nExamples:\n- 1-10: Abon\n- 11-20: Daveza\n- 21-30: Damula\n- 31-40: Essus\n- 41-50: Sina\n- 51-60: Kazeera\n- 61-70: Khazu\n- 71-80: Sova\n- 81-90: Nabuma\n- 91-00: Tiza\n\n### 76-90: A season or environmental aspect.\nWhat influence does the weather have on this settlement?\n\nExamples:\n- 1-10: Winterhome\n- 11-20: Windhaven\n- 21-30: Stormrest\n- 31-40: Bleakfrost\n- 41-50: Springtide\n- 51-60: Duskmoor\n- 61-70: Frostcrag\n- 71-80: Springbrook\n- 81-90: Icebreak\n- 91-00: Summersong\n\n### 91-100: Something Else....\nExamples:\n- 1-10: A trade good (Ironhome)\n- 11-20: An Old World city (New Arkesh)\n- 21-30: A founder or famous settler (Kei's Hall)\n- 31-40: A god (Elisora)\n- 41-50: A historical item (Blackhelm)\n- 51-60: A firstborn race (Elfbrook)\n- 61-70: An elvish word or name (Nessana)\n- 71-80: A mythic belief or event (Ghostwalk)\n- 81-90: A positive term (Hope)\n- 91-00: A negative term (Forsaken)",
		"text_tr": "### 61-75: Eski Dünya dilinde bir sözcük.\nBu sözcük hangi kültürü temsil ediyor? Anlamı nedir?\n\nÖrnekler:\n- 1-10: Abon\n- 11-20: Daveza\n- 21-30: Damula\n- 31-40: Essus\n- 41-50: Sina\n- 51-60: Kazeera\n- 61-70: Khazu\n- 71-80: Sova\n- 81-90: Nabuma\n- 91-00: Tiza\n\n### 76-90: Bir mevsim ya da çevresel özellik.\nHavanın bu yerleşim üzerinde nasıl bir etkisi var?\n\nÖrnekler:\n- 1-10: Winterhome\n- 11-20: Windhaven\n- 21-30: Stormrest\n- 31-40: Bleakfrost\n- 41-50: Springtide\n- 51-60: Duskmoor\n- 61-70: Frostcrag\n- 71-80: Springbrook\n- 81-90: Icebreak\n- 91-00: Summersong\n\n### 91-100: Başka bir şey....\nÖrnekler:\n- 1-10: Bir ticaret malı (Ironhome)\n- 11-20: Bir Eski Dünya kenti (New Arkesh)\n- 21-30: Bir kurucu ya da ünlü yerleşimci (Kei's Hall)\n- 31-40: Bir tanrı (Elisora)\n- 41-50: Tarihî bir eşya (Blackhelm)\n- 51-60: Bir İlk Doğan ırk (Elfbrook)\n- 61-70: Bir Elf sözcüğü ya da adı (Nessana)\n- 71-80: Mitik bir inanç ya da olay (Ghostwalk)\n- 81-90: Olumlu bir terim (Hope)\n- 91-00: Olumsuz bir terim (Forsaken)"
	},
	{
		"page": 180,
		"img": "/rulebook/kehanetler/p180.webp",
		"title_en": "Oracle 8: Quick Settlement Name Generator",
		"title_tr": "Kehanet 8: Hızlı Yerleşim Adı Üreteci",
		"text_en": "## Oracle 8: Quick Settlement Name Generator\n\nRoll once for a prefix and once for a suffix.\n\n| Roll | Prefix | Suffix |\n|---|---|---|\n| 1-4 | Bleak- | -moor |\n| 5-8 | Green- | -ford |\n| 9-12 | Wolf- | -crag |\n| 13-16 | Raven- | -watch |\n| 17-20 | Gray- | -hope |\n| 21-24 | Red- | -wood |\n| 25-28 | Axe- | -ridge |\n| 29-32 | Great- | -stone |\n| 33-36 | Wood- | -haven |\n| 37-40 | Low- | -fall(s) |\n| 41-44 | White- | -river |\n| 45-48 | Storm- | -field |\n| 49-52 | Black- | -hill |\n| 53-56 | Mourn- | -bridge |\n| 57-60 | New- | -mark |\n| 61-64 | Stone- | -cairn |\n| 65-68 | Grim- | -land |\n| 69-72 | Lost- | -hall |\n| 73-76 | High- | -mount |\n| 77-80 | Rock- | -rock |\n| 81-84 | Shield- | -brook |\n| 85-88 | Sword- | -barrow |\n| 89-92 | Frost- | -stead |\n| 93-96 | Thorn- | -home |\n| 97-00 | Long- | -wick |",
		"text_tr": "## Kehanet 8: Hızlı Yerleşim Adı Üreteci\n\nBir ön ek için bir kez, bir son ek için bir kez zar at.\n\n| Zar | Ön ek | Son ek |\n|---|---|---|\n| 1-4 | Bleak- | -moor |\n| 5-8 | Green- | -ford |\n| 9-12 | Wolf- | -crag |\n| 13-16 | Raven- | -watch |\n| 17-20 | Gray- | -hope |\n| 21-24 | Red- | -wood |\n| 25-28 | Axe- | -ridge |\n| 29-32 | Great- | -stone |\n| 33-36 | Wood- | -haven |\n| 37-40 | Low- | -fall(s) |\n| 41-44 | White- | -river |\n| 45-48 | Storm- | -field |\n| 49-52 | Black- | -hill |\n| 53-56 | Mourn- | -bridge |\n| 57-60 | New- | -mark |\n| 61-64 | Stone- | -cairn |\n| 65-68 | Grim- | -land |\n| 69-72 | Lost- | -hall |\n| 73-76 | High- | -mount |\n| 77-80 | Rock- | -rock |\n| 81-84 | Shield- | -brook |\n| 85-88 | Sword- | -barrow |\n| 89-92 | Frost- | -stead |\n| 93-96 | Thorn- | -home |\n| 97-00 | Long- | -wick |"
	},
	{
		"page": 181,
		"img": "/rulebook/kehanetler/p181.webp",
		"title_en": "Oracle 9: Settlement Trouble",
		"title_tr": "Kehanet 9: Yerleşim Sıkıntısı",
		"text_en": "## Oracle 9: Settlement Trouble\n\n- 1-2: Outsiders rejected\n- 3-4: Dangerous discovery\n- 5-6: Dreadful omens\n- 7-8: Natural disaster\n- 9-10: Old wounds reopened\n- 11-12: Important object is lost\n- 13-14: Someone is captured\n- 15-16: Mysterious phenomenon\n- 17-18: Revolt against a leader\n- 19-20: Vengeful outcast\n- 21-22: Rival settlement\n- 23-24: Nature strikes back\n- 25-26: Someone is missing\n- 27-28: Production halts\n- 29-30: Mysterious murders\n- 31-32: Debt comes due\n- 33-34: Unjust leadership\n- 35-36: Disastrous accident\n- 37-38: In league with the enemy\n- 39-40: Raiders prey on the weak\n- 41-42: Cursed past\n- 43-44: An innocent is accused\n- 45-46: Corrupted by dark magic\n- 47-48: Isolated by brutal weather\n- 49-50: Provisions are scarce\n- 51-52: Sickness run amok\n- 53-54: Allies become enemies\n- 55-56: Attack is imminent\n- 57-58: Lost caravan\n- 59-60: Dark secret revealed\n- 61-62: Urgent expedition\n- 63-64: A leader falls\n- 65-66: Families in conflict\n- 67-68: Incompetent leadership\n- 69-70: Reckless warmongering\n- 71-72: Beast on the hunt\n- 73-74: Betrayed from within\n- 75-76: Broken truce\n- 77-78: Wrathful haunt\n- 79-80: Conflict with firstborn\n- 81-82: Trade route blocked\n- 83-84: In the crossfire\n- 85-86: Stranger causes discord\n- 87-88: Important event threatened\n- 89-90: Dangerous tradition\n- 91-00: Roll twice",
		"text_tr": "## Kehanet 9: Yerleşim Sıkıntısı\n\n- 1-2: Yabancılar geri çevrilir\n- 3-4: Tehlikeli bir keşif\n- 5-6: Korkunç alametler\n- 7-8: Doğal afet\n- 9-10: Eski yaralar yeniden açılır\n- 11-12: Önemli bir eşya kaybolur\n- 13-14: Biri esir alınır\n- 15-16: Gizemli bir olgu\n- 17-18: Bir lidere karşı isyan\n- 19-20: İntikam peşindeki bir dışlanmış\n- 21-22: Rakip bir yerleşim\n- 23-24: Doğa karşılık verir\n- 25-26: Biri kayıp\n- 27-28: Üretim durur\n- 29-30: Gizemli cinayetler\n- 31-32: Borcun vadesi gelir\n- 33-34: Adaletsiz yönetim\n- 35-36: Felaketle sonuçlanan bir kaza\n- 37-38: Düşmanla iş birliği\n- 39-40: Yağmacılar güçsüzleri avlar\n- 41-42: Lanetli bir geçmiş\n- 43-44: Bir masum suçlanır\n- 45-46: Kara büyüyle yozlaşmış\n- 47-48: Acımasız havayla izole olmuş\n- 49-50: Erzak kıt\n- 51-52: Hastalık kol gezer\n- 53-54: Müttefikler düşman olur\n- 55-56: Saldırı yakın\n- 57-58: Kayıp kervan\n- 59-60: Karanlık bir sır açığa çıkar\n- 61-62: Acil bir sefer\n- 63-64: Bir lider düşer\n- 65-66: Aileler çatışır\n- 67-68: Beceriksiz yönetim\n- 69-70: Pervasız savaş kışkırtıcılığı\n- 71-72: Av peşindeki bir canavar\n- 73-74: İçeriden ihanet\n- 75-76: Bozulan ateşkes\n- 77-78: Gazaba gelmiş bir tayf\n- 79-80: İlk Doğanlarla çatışma\n- 81-82: Ticaret yolu kapanır\n- 83-84: İki ateş arasında\n- 85-86: Bir yabancı nifak sokar\n- 87-88: Önemli bir olay tehdit altında\n- 89-90: Tehlikeli bir gelenek\n- 91-00: İki kez zar at"
	},
	{
		"page": 182,
		"img": "/rulebook/kehanetler/p182.webp",
		"title_en": "Oracle 10: Character Role / Oracle 11: Character Goal",
		"title_tr": "Kehanet 10: Karakter Rolü / Kehanet 11: Karakter Hedefi",
		"text_en": "## Oracle 10: Character Role\n\n- 1-2: Criminal\n- 3-4: Healer\n- 5-6: Bandit\n- 7-9: Guide\n- 10-12: Performer\n- 13-15: Miner\n- 16-18: Mercenary\n- 19-21: Outcast\n- 22-24: Vagrant\n- 25-27: Forester\n- 28-30: Traveler\n- 31-33: Mystic\n- 34-36: Priest\n- 37-39: Sailor\n- 40-42: Pilgrim\n- 43-45: Thief\n- 46-48: Adventurer\n- 49-51: Forager\n- 52-54: Leader\n- 55-58: Guard\n- 59-62: Artisan\n- 63-66: Scout\n- 67-70: Herder\n- 71-74: Fisher\n- 75-79: Warrior\n- 80-84: Hunter\n- 85-89: Raider\n- 90-94: Trader\n- 95-99: Farmer\n- 00: Unusual role\n\n## Oracle 11: Character Goal\n\n- 1-3: Obtain an object\n- 4-6: Make an agreement\n- 7-9: Build a relationship\n- 10-12: Undermine a relationship\n- 13-15: Seek a truth\n- 16-18: Pay a debt\n- 19-21: Refute a falsehood\n- 22-24: Harm a rival\n- 25-27: Cure an ill\n- 28-30: Find a person\n- 31-33: Find a home\n- 34-36: Seize power\n- 37-39: Restore a relationship\n- 40-42: Create an item\n- 43-45: Travel to a place\n- 46-48: Secure provisions\n- 49-51: Rebel against power\n- 52-54: Collect a debt\n- 55-57: Protect a secret\n- 58-60: Spread faith\n- 61-63: Enrich themselves\n- 64-66: Protect a person\n- 67-69: Protect the status quo\n- 70-72: Advance status\n- 73-75: Defend a place\n- 76-78: Avenge a wrong\n- 79-81: Fulfill a duty\n- 82-84: Gain knowledge\n- 85-87: Prove worthiness\n- 88-90: Find redemption\n- 91-92: Escape from something\n- 93-95: Resolve a dispute\n- 96-00: Roll twice",
		"text_tr": "## Kehanet 10: Karakter Rolü\n\n- 1-2: Suçlu\n- 3-4: Şifacı\n- 5-6: Haydut\n- 7-9: Kılavuz\n- 10-12: Hokkabaz\n- 13-15: Madenci\n- 16-18: Paralı asker\n- 19-21: Dışlanmış\n- 22-24: Serseri\n- 25-27: Ormancı\n- 28-30: Gezgin\n- 31-33: Mistik\n- 34-36: Rahip\n- 37-39: Denizci\n- 40-42: Hacı\n- 43-45: Hırsız\n- 46-48: Maceracı\n- 49-51: Yiyecek toplayıcı\n- 52-54: Lider\n- 55-58: Muhafız\n- 59-62: Zanaatkâr\n- 63-66: İzci\n- 67-70: Çoban\n- 71-74: Balıkçı\n- 75-79: Savaşçı\n- 80-84: Avcı\n- 85-89: Yağmacı\n- 90-94: Tüccar\n- 95-99: Çiftçi\n- 00: Sıra dışı rol\n\n## Kehanet 11: Karakter Hedefi\n\n- 1-3: Bir eşyaya kavuşmak\n- 4-6: Bir anlaşma yapmak\n- 7-9: Bir ilişki kurmak\n- 10-12: Bir ilişkiyi baltalamak\n- 13-15: Bir hakikatin peşine düşmek\n- 16-18: Bir borcu ödemek\n- 19-21: Bir yalanı çürütmek\n- 22-24: Bir rakibe zarar vermek\n- 25-27: Bir hastalığı iyileştirmek\n- 28-30: Bir kişiyi bulmak\n- 31-33: Bir yuva bulmak\n- 34-36: İktidarı ele geçirmek\n- 37-39: Bir ilişkiyi onarmak\n- 40-42: Bir eşya yapmak\n- 43-45: Bir yere yolculuk etmek\n- 46-48: Erzak sağlamak\n- 49-51: İktidara başkaldırmak\n- 52-54: Bir borcu tahsil etmek\n- 55-57: Bir sırrı korumak\n- 58-60: İnancı yaymak\n- 61-63: Kendini zenginleştirmek\n- 64-66: Bir kişiyi korumak\n- 67-69: Mevcut düzeni korumak\n- 70-72: Mevki yükseltmek\n- 73-75: Bir yeri savunmak\n- 76-78: Bir haksızlığın öcünü almak\n- 79-81: Bir görevi yerine getirmek\n- 82-84: Bilgi edinmek\n- 85-87: Layık olduğunu kanıtlamak\n- 88-90: Kurtuluşu bulmak\n- 91-92: Bir şeyden kaçmak\n- 93-95: Bir anlaşmazlığı çözmek\n- 96-00: İki kez zar at"
	},
	{
		"page": 183,
		"img": "/rulebook/kehanetler/p183.webp",
		"title_en": "Oracle 12: Character Descriptor",
		"title_tr": "Kehanet 12: Karakter Tanımı",
		"text_en": "## Oracle 12: Character Descriptor\n\n- 1: Stoic\n- 2: Attractive\n- 3: Passive\n- 4: Aloof\n- 5: Affectionate\n- 6: Generous\n- 7: Smug\n- 8: Armed\n- 9: Clever\n- 10: Brave\n- 11: Ugly\n- 12: Sociable\n- 13: Doomed\n- 14: Connected\n- 15: Bold\n- 16: Jealous\n- 17: Angry\n- 18: Active\n- 19: Suspicious\n- 20: Hostile\n- 21: Hardhearted\n- 22: Successful\n- 23: Talented\n- 24: Experienced\n- 25: Deceitful\n- 26: Ambitious\n- 27: Aggressive\n- 28: Conceited\n- 29: Proud\n- 30: Stern\n- 31: Dependent\n- 32: Wary\n- 33: Strong\n- 34: Insightful\n- 35: Dangerous\n- 36: Quirky\n- 37: Cheery\n- 38: Disfigured\n- 39: Intolerant\n- 40: Skilled\n- 41: Stingy\n- 42: Timid\n- 43: Insensitive\n- 44: Wild\n- 45: Bitter\n- 46: Cunning\n- 47: Remorseful\n- 48: Kind\n- 49: Charming\n- 50: Oblivious\n- 51: Critical\n- 52: Cautious\n- 53: Resourceful\n- 54: Weary\n- 55: Wounded\n- 56: Anxious\n- 57: Powerful\n- 58: Athletic\n- 59: Driven\n- 60: Cruel\n- 61: Quiet\n- 62: Honest\n- 63: Infamous\n- 64: Dying\n- 65: Reclusive\n- 66: Artistic\n- 67: Disabled\n- 68: Confused\n- 69: Manipulative\n- 70: Relaxed\n- 71: Stealthy\n- 72: Confident\n- 73: Weak\n- 74: Friendly\n- 75: Wise\n- 76: Influential\n- 77: Young\n- 78: Adventurous\n- 79: Oppressed\n- 80: Vengeful\n- 81: Cooperative\n- 82: Armored\n- 83: Apathetic\n- 84: Determined\n- 85: Loyal\n- 86: Sick\n- 87: Religious\n- 88: Selfish\n- 89: Old\n- 90: Fervent\n- 91: Violent\n- 92: Agreeable\n- 93: Hot-tempered\n- 94: Stubborn\n- 95: Incompetent\n- 96: Greedy\n- 97: Cowardly\n- 98: Obsessed\n- 99: Careless\n- 00: Ironsworn",
		"text_tr": "## Kehanet 12: Karakter Tanımı\n\n- 1: Sabırlı\n- 2: Çekici\n- 3: Edilgen\n- 4: Mesafeli\n- 5: Sevecen\n- 6: Cömert\n- 7: Kendini beğenmiş\n- 8: Silahlı\n- 9: Zeki\n- 10: Cesur\n- 11: Çirkin\n- 12: Girişken\n- 13: Lanetlenmiş\n- 14: Nüfuzlu çevreye sahip\n- 15: Atılgan\n- 16: Kıskanç\n- 17: Öfkeli\n- 18: Hareketli\n- 19: Şüpheci\n- 20: Düşmanca\n- 21: Katı yürekli\n- 22: Başarılı\n- 23: Yetenekli\n- 24: Tecrübeli\n- 25: Hilekâr\n- 26: Hırslı\n- 27: Saldırgan\n- 28: Kibirli\n- 29: Gururlu\n- 30: Sert\n- 31: Başkalarına bağımlı\n- 32: İhtiyatlı\n- 33: Güçlü\n- 34: Sezgili\n- 35: Tehlikeli\n- 36: Acayip\n- 37: Neşeli\n- 38: Yüzü gözü dağılmış\n- 39: Hoşgörüsüz\n- 40: Hünerli\n- 41: Cimri\n- 42: Çekingen\n- 43: Duyarsız\n- 44: Vahşi\n- 45: Kindar\n- 46: Kurnaz\n- 47: Pişman\n- 48: İyi kalpli\n- 49: Büyüleyici\n- 50: Habersiz\n- 51: Eleştirel\n- 52: Temkinli\n- 53: Becerikli\n- 54: Bitkin\n- 55: Yaralı\n- 56: Endişeli\n- 57: Güçlü kuvvetli\n- 58: Atletik\n- 59: Hırsla güdülenen\n- 60: Zalim\n- 61: Sessiz\n- 62: Dürüst\n- 63: Adı kötüye çıkmış\n- 64: Ölmekte olan\n- 65: Münzevi\n- 66: Sanatçı ruhlu\n- 67: Sakat\n- 68: Şaşkın\n- 69: Manipülatif\n- 70: Rahat\n- 71: Sinsi\n- 72: Özgüvenli\n- 73: Zayıf\n- 74: Dostça\n- 75: Bilge\n- 76: Sözü geçen\n- 77: Genç\n- 78: Maceraperest\n- 79: Ezilmiş\n- 80: İntikam peşinde\n- 81: İş birliğine açık\n- 82: Zırhlı\n- 83: Vurdumduymaz\n- 84: Kararlı\n- 85: Sadık\n- 86: Hasta\n- 87: Dindar\n- 88: Bencil\n- 89: Yaşlı\n- 90: Coşkulu\n- 91: Şiddet yanlısı\n- 92: Uyumlu\n- 93: Aksi huylu\n- 94: İnatçı\n- 95: Beceriksiz\n- 96: Açgözlü\n- 97: Korkak\n- 98: Saplantılı\n- 99: Dikkatsiz\n- 00: Ironsworn"
	},
	{
		"page": 184,
		"img": "/rulebook/kehanetler/p184.webp",
		"title_en": "Oracle 13: Ironlander Names",
		"title_tr": "Kehanet 13: Demir Diyar Sakini Adları",
		"text_en": "## Oracle 13: Ironlander Names\n\n- 1: Solana\n- 2: Keelan\n- 3: Cadigan\n- 4: Sola\n- 5: Kodroth\n- 6: Kione\n- 7: Katja\n- 8: Tio\n- 9: Artiga\n- 10: Eos\n- 11: Bastien\n- 12: Elli\n- 13: Maura\n- 14: Haleema\n- 15: Abella\n- 16: Morter\n- 17: Wulan\n- 18: Mai\n- 19: Farina\n- 20: Pearce\n- 21: Wynne\n- 22: Haf\n- 23: Aeddon\n- 24: Khinara\n- 25: Milla\n- 26: Nakata\n- 27: Kynan\n- 28: Kiah\n- 29: Jaggar\n- 30: Beca\n- 31: Ikram\n- 32: Melia\n- 33: Sidan\n- 34: Deshi\n- 35: Tessa\n- 36: Sibila\n- 37: Morien\n- 38: Mona\n- 39: Padma\n- 40: Avella\n- 41: Naila\n- 42: Lio\n- 43: Cera\n- 44: Ithela\n- 45: Zhan\n- 46: Kaivan\n- 47: Valeri\n- 48: Hirsham\n- 49: Pemba\n- 50: Edda\n- 51: Lestara\n- 52: Lago\n- 53: Elstan\n- 54: Saskia\n- 55: Kabeera\n- 56: Caldas\n- 57: Nisus\n- 58: Serene\n- 59: Chenda\n- 60: Themon\n- 61: Erin\n- 62: Alban\n- 63: Parcell\n- 64: Jelma\n- 65: Willa\n- 66: Nadira\n- 67: Gwen\n- 68: Amara\n- 69: Masias\n- 70: Kanno\n- 71: Razeena\n- 72: Mira\n- 73: Perella\n- 74: Myrick\n- 75: Qamar\n- 76: Kormak\n- 77: Zura\n- 78: Zanita\n- 79: Brynn\n- 80: Tegan\n- 81: Pendry\n- 82: Quinn\n- 83: Fanir\n- 84: Glain\n- 85: Emelyn\n- 86: Kendi\n- 87: Althus\n- 88: Leela\n- 89: Ishana\n- 90: Flint\n- 91: Delkash\n- 92: Nia\n- 93: Nan\n- 94: Keeara\n- 95: Katania\n- 96: Morell\n- 97: Temir\n- 98: Bas\n- 99: Sabine\n- 00: Tallus",
		"text_tr": "## Kehanet 13: Demir Diyar Sakini Adları\n\n- 1: Solana\n- 2: Keelan\n- 3: Cadigan\n- 4: Sola\n- 5: Kodroth\n- 6: Kione\n- 7: Katja\n- 8: Tio\n- 9: Artiga\n- 10: Eos\n- 11: Bastien\n- 12: Elli\n- 13: Maura\n- 14: Haleema\n- 15: Abella\n- 16: Morter\n- 17: Wulan\n- 18: Mai\n- 19: Farina\n- 20: Pearce\n- 21: Wynne\n- 22: Haf\n- 23: Aeddon\n- 24: Khinara\n- 25: Milla\n- 26: Nakata\n- 27: Kynan\n- 28: Kiah\n- 29: Jaggar\n- 30: Beca\n- 31: Ikram\n- 32: Melia\n- 33: Sidan\n- 34: Deshi\n- 35: Tessa\n- 36: Sibila\n- 37: Morien\n- 38: Mona\n- 39: Padma\n- 40: Avella\n- 41: Naila\n- 42: Lio\n- 43: Cera\n- 44: Ithela\n- 45: Zhan\n- 46: Kaivan\n- 47: Valeri\n- 48: Hirsham\n- 49: Pemba\n- 50: Edda\n- 51: Lestara\n- 52: Lago\n- 53: Elstan\n- 54: Saskia\n- 55: Kabeera\n- 56: Caldas\n- 57: Nisus\n- 58: Serene\n- 59: Chenda\n- 60: Themon\n- 61: Erin\n- 62: Alban\n- 63: Parcell\n- 64: Jelma\n- 65: Willa\n- 66: Nadira\n- 67: Gwen\n- 68: Amara\n- 69: Masias\n- 70: Kanno\n- 71: Razeena\n- 72: Mira\n- 73: Perella\n- 74: Myrick\n- 75: Qamar\n- 76: Kormak\n- 77: Zura\n- 78: Zanita\n- 79: Brynn\n- 80: Tegan\n- 81: Pendry\n- 82: Quinn\n- 83: Fanir\n- 84: Glain\n- 85: Emelyn\n- 86: Kendi\n- 87: Althus\n- 88: Leela\n- 89: Ishana\n- 90: Flint\n- 91: Delkash\n- 92: Nia\n- 93: Nan\n- 94: Keeara\n- 95: Katania\n- 96: Morell\n- 97: Temir\n- 98: Bas\n- 99: Sabine\n- 00: Tallus"
	},
	{
		"page": 185,
		"img": "/rulebook/kehanetler/p185.webp",
		"title_en": "Oracle 13: Ironlander Names (continued)",
		"title_tr": "Kehanet 13: Demir Diyar Sakini Adları (devam)",
		"text_en": "- 1: Segura\n- 2: Gethin\n- 3: Bataar\n- 4: Basira\n- 5: Joa\n- 6: Glynn\n- 7: Toran\n- 8: Arasen\n- 9: Kuron\n- 10: Griff\n- 11: Owena\n- 12: Adda\n- 13: Euros\n- 14: Kova\n- 15: Kara\n- 16: Morgan\n- 17: Nanda\n- 18: Tamara\n- 19: Asha\n- 20: Delos\n- 21: Torgan\n- 22: Makari\n- 23: Selva\n- 24: Kimura\n- 25: Rhian\n- 26: Tristan\n- 27: Siorra\n- 28: Sayer\n- 29: Cortina\n- 30: Vesna\n- 31: Kataka\n- 32: Keyshia\n- 33: Mila\n- 34: Lili\n- 35: Vigo\n- 36: Sadia\n- 37: Malik\n- 38: Dag\n- 39: Kuno\n- 40: Reva\n- 41: Kai\n- 42: Kalina\n- 43: Jihan\n- 44: Hennion\n- 45: Abram\n- 46: Aida\n- 47: Myrtle\n- 48: Nekun\n- 49: Menna\n- 50: Tahir\n- 51: Sarria\n- 52: Nakura\n- 53: Akiya\n- 54: Talan\n- 55: Mattick\n- 56: Okoth\n- 57: Khulan\n- 58: Verena\n- 59: Beltran\n- 60: Del\n- 61: Ranna\n- 62: Alina\n- 63: Muna\n- 64: Mura\n- 65: Torrens\n- 66: Yuda\n- 67: Nazmi\n- 68: Ghalen\n- 69: Sarda\n- 70: Shona\n- 71: Kalidas\n- 72: Wena\n- 73: Sendra\n- 74: Kori\n- 75: Setara\n- 76: Lucia\n- 77: Maya\n- 78: Reema\n- 79: Yorath\n- 80: Rhoddri\n- 81: Shekhar\n- 82: Servan\n- 83: Reese\n- 84: Kenrick\n- 85: Indirra\n- 86: Giliana\n- 87: Jebran\n- 88: Kotama\n- 89: Fara\n- 90: Katrin\n- 91: Namba\n- 92: Lona\n- 93: Taylah\n- 94: Kato\n- 95: Esra\n- 96: Eleri\n- 97: Irsia\n- 98: Kayu\n- 99: Bevan\n- 00: Chandra",
		"text_tr": "- 1: Segura\n- 2: Gethin\n- 3: Bataar\n- 4: Basira\n- 5: Joa\n- 6: Glynn\n- 7: Toran\n- 8: Arasen\n- 9: Kuron\n- 10: Griff\n- 11: Owena\n- 12: Adda\n- 13: Euros\n- 14: Kova\n- 15: Kara\n- 16: Morgan\n- 17: Nanda\n- 18: Tamara\n- 19: Asha\n- 20: Delos\n- 21: Torgan\n- 22: Makari\n- 23: Selva\n- 24: Kimura\n- 25: Rhian\n- 26: Tristan\n- 27: Siorra\n- 28: Sayer\n- 29: Cortina\n- 30: Vesna\n- 31: Kataka\n- 32: Keyshia\n- 33: Mila\n- 34: Lili\n- 35: Vigo\n- 36: Sadia\n- 37: Malik\n- 38: Dag\n- 39: Kuno\n- 40: Reva\n- 41: Kai\n- 42: Kalina\n- 43: Jihan\n- 44: Hennion\n- 45: Abram\n- 46: Aida\n- 47: Myrtle\n- 48: Nekun\n- 49: Menna\n- 50: Tahir\n- 51: Sarria\n- 52: Nakura\n- 53: Akiya\n- 54: Talan\n- 55: Mattick\n- 56: Okoth\n- 57: Khulan\n- 58: Verena\n- 59: Beltran\n- 60: Del\n- 61: Ranna\n- 62: Alina\n- 63: Muna\n- 64: Mura\n- 65: Torrens\n- 66: Yuda\n- 67: Nazmi\n- 68: Ghalen\n- 69: Sarda\n- 70: Shona\n- 71: Kalidas\n- 72: Wena\n- 73: Sendra\n- 74: Kori\n- 75: Setara\n- 76: Lucia\n- 77: Maya\n- 78: Reema\n- 79: Yorath\n- 80: Rhoddri\n- 81: Shekhar\n- 82: Servan\n- 83: Reese\n- 84: Kenrick\n- 85: Indirra\n- 86: Giliana\n- 87: Jebran\n- 88: Kotama\n- 89: Fara\n- 90: Katrin\n- 91: Namba\n- 92: Lona\n- 93: Taylah\n- 94: Kato\n- 95: Esra\n- 96: Eleri\n- 97: Irsia\n- 98: Kayu\n- 99: Bevan\n- 00: Chandra"
	},
	{
		"page": 186,
		"img": "/rulebook/kehanetler/p186.webp",
		"title_en": "Oracle 14: Elf Names",
		"title_tr": "Kehanet 14: Elf Adları",
		"text_en": "## Oracle 14: Elf Names\n\n- 1-2: Arsula\n- 3-4: Naidita\n- 5-6: Belesunna\n- 7-8: Vidarna\n- 9-10: Ninsunu\n- 11-12: Balathu\n- 13-14: Dorosi\n- 15-16: Gezera\n- 17-18: Zursan\n- 19-20: Seleeku\n- 21-22: Utamara\n- 23-24: Nebakay\n- 25-26: Dismashk\n- 27-28: Mitunu\n- 29-30: Atani\n- 31-32: Kinzura\n- 33-34: Sumula\n- 35-36: Ukames\n- 37-38: Ahmeshki\n- 39-40: Ilsit\n- 41-42: Mayatanay\n- 43-44: Etana\n- 45-46: Gamanna\n- 47-48: Nessana\n- 49-50: Uralar\n- 51-52: Tishetu\n- 53-54: Leucia\n- 55-56: Sutahe\n- 57-58: Dotani\n- 59-60: Uktannu\n- 61-62: Retenay\n- 63-64: Kendalanu\n- 65-66: Tahuta\n- 67-68: Mattissa\n- 69-70: Anatu\n- 71-72: Aralu\n- 73-74: Arakhi\n- 75-76: Ibrahem\n- 77-78: Sinosu\n- 79-80: Jemshida\n- 81-82: Visapni\n- 83-84: Hullata\n- 85-86: Sidura\n- 87-88: Kerihu\n- 89-90: Ereshki\n- 91-92: Cybela\n- 93-94: Anunna\n- 95-96: Otani\n- 97-98: Ditani\n- 99-00: Faraza",
		"text_tr": "## Kehanet 14: Elf Adları\n\n- 1-2: Arsula\n- 3-4: Naidita\n- 5-6: Belesunna\n- 7-8: Vidarna\n- 9-10: Ninsunu\n- 11-12: Balathu\n- 13-14: Dorosi\n- 15-16: Gezera\n- 17-18: Zursan\n- 19-20: Seleeku\n- 21-22: Utamara\n- 23-24: Nebakay\n- 25-26: Dismashk\n- 27-28: Mitunu\n- 29-30: Atani\n- 31-32: Kinzura\n- 33-34: Sumula\n- 35-36: Ukames\n- 37-38: Ahmeshki\n- 39-40: Ilsit\n- 41-42: Mayatanay\n- 43-44: Etana\n- 45-46: Gamanna\n- 47-48: Nessana\n- 49-50: Uralar\n- 51-52: Tishetu\n- 53-54: Leucia\n- 55-56: Sutahe\n- 57-58: Dotani\n- 59-60: Uktannu\n- 61-62: Retenay\n- 63-64: Kendalanu\n- 65-66: Tahuta\n- 67-68: Mattissa\n- 69-70: Anatu\n- 71-72: Aralu\n- 73-74: Arakhi\n- 75-76: Ibrahem\n- 77-78: Sinosu\n- 79-80: Jemshida\n- 81-82: Visapni\n- 83-84: Hullata\n- 85-86: Sidura\n- 87-88: Kerihu\n- 89-90: Ereshki\n- 91-92: Cybela\n- 93-94: Anunna\n- 95-96: Otani\n- 97-98: Ditani\n- 99-00: Faraza"
	},
	{
		"page": 187,
		"img": "/rulebook/kehanetler/p187.webp",
		"title_en": "Oracle 15: Other Names",
		"title_tr": "Kehanet 15: Diğer Adlar",
		"text_en": "## Oracle 15: Other Names\n\n| Roll | Giants | Varou | Trolls |\n|---|---|---|---|\n| 1-4 | Chony | Vata | Rattle |\n| 5-8 | Banda | Zora | Scratch |\n| 9-12 | Jochu | Jasna | Wallow |\n| 13-16 | Kira | Charna | Groak |\n| 17-20 | Khatir | Tana | Gimble |\n| 21-24 | Chaidu | Soveen | Scar |\n| 25-28 | Atan | Radka | Cratch |\n| 29-32 | Buandu | Zlata | Creech |\n| 33-36 | Javyn | Leesla | Shush |\n| 37-40 | Khashin | Byna | Glush |\n| 41-44 | Bayara | Meeka | Slar |\n| 45-48 | Temura | Iskra | Gnash |\n| 49-52 | Kidha | Jarek | Stoad |\n| 53-56 | Kathos | Darva | Grig |\n| 57-60 | Tanua | Neda | Bleat |\n| 61-64 | Bashtu | Keha | Chortle |\n| 65-68 | Jaran | Zhivka | Cluck |\n| 69-72 | Othos | Kvata | Slith |\n| 73-76 | Khutan | Staysa | Mongo |\n| 77-80 | Otaan | Evka | Creak |\n| 81-84 | Martu | Vuksha | Burble |\n| 85-88 | Baku | Muko | Vrusk |\n| 89-92 | Tuban | Dreko | Snuffle |\n| 93-96 | Qudan | Aleko | Leech |\n| 97-00 | Denua | Vojan | Herk |",
		"text_tr": "## Kehanet 15: Diğer Adlar\n\n| Zar | Devler | Varou | Troller |\n|---|---|---|---|\n| 1-4 | Chony | Vata | Rattle |\n| 5-8 | Banda | Zora | Scratch |\n| 9-12 | Jochu | Jasna | Wallow |\n| 13-16 | Kira | Charna | Groak |\n| 17-20 | Khatir | Tana | Gimble |\n| 21-24 | Chaidu | Soveen | Scar |\n| 25-28 | Atan | Radka | Cratch |\n| 29-32 | Buandu | Zlata | Creech |\n| 33-36 | Javyn | Leesla | Shush |\n| 37-40 | Khashin | Byna | Glush |\n| 41-44 | Bayara | Meeka | Slar |\n| 45-48 | Temura | Iskra | Gnash |\n| 49-52 | Kidha | Jarek | Stoad |\n| 53-56 | Kathos | Darva | Grig |\n| 57-60 | Tanua | Neda | Bleat |\n| 61-64 | Bashtu | Keha | Chortle |\n| 65-68 | Jaran | Zhivka | Cluck |\n| 69-72 | Othos | Kvata | Slith |\n| 73-76 | Khutan | Staysa | Mongo |\n| 77-80 | Otaan | Evka | Creak |\n| 81-84 | Martu | Vuksha | Burble |\n| 85-88 | Baku | Muko | Vrusk |\n| 89-92 | Tuban | Dreko | Snuffle |\n| 93-96 | Qudan | Aleko | Leech |\n| 97-00 | Denua | Vojan | Herk |"
	},
	{
		"page": 188,
		"img": "/rulebook/kehanetler/p188.webp",
		"title_en": "Oracle 16: Combat Action",
		"title_tr": "Kehanet 16: Muharebe Eylemi",
		"text_en": "## Oracle 16: Combat Action\n\n- 1-3: Compel a surrender.\n- 4-6: Coordinate with allies.\n- 7-9: Gather reinforcements.\n- 10-13: Seize something or someone.\n- 14-17: Provoke a reckless response.\n- 18-21: Intimidate or frighten.\n- 22-25: Reveal a surprising truth.\n- 26-29: Shift focus to someone or something else.\n- 30-33: Destroy something, or render it useless.\n- 34-39: Take a decisive action.\n- 40-45: Reinforce defenses.\n- 46-52: Ready an action.\n- 53-60: Use the terrain to gain advantage.\n- 61-68: Leverage the advantage of a weapon or ability.\n- 69-78: Create an opportunity.\n- 79-89: Attack with precision.\n- 90-99: Attack with power.\n- 00: Take a completely unexpected action.",
		"text_tr": "## Kehanet 16: Muharebe Eylemi\n\n- 1-3: Teslim olmaya zorla.\n- 4-6: Müttefiklerle uyum içinde hareket et.\n- 7-9: Takviye topla.\n- 10-13: Bir şeyi ya da birini ele geçir.\n- 14-17: Pervasız bir tepkiyi kışkırt.\n- 18-21: Gözünü kork ya da yıldır.\n- 22-25: Şaşırtıcı bir hakikati açığa çıkar.\n- 26-29: Odağı başka birine ya da bir şeye kaydır.\n- 30-33: Bir şeyi yok et ya da işe yaramaz hale getir.\n- 34-39: Belirleyici bir eylemde bulun.\n- 40-45: Savunmayı güçlendir.\n- 46-52: Bir eyleme hazırlan.\n- 53-60: Avantaj kazanmak için araziyi kullan.\n- 61-68: Bir silahın ya da yeteneğin avantajından yararlan.\n- 69-78: Bir fırsat yarat.\n- 79-89: İsabetle saldır.\n- 90-99: Güçle saldır.\n- 00: Tamamen beklenmedik bir eylemde bulun."
	},
	{
		"page": 189,
		"img": "/rulebook/kehanetler/p189.webp",
		"title_en": "Oracle 17: Mystic Backlash",
		"title_tr": "Kehanet 17: Mistik Tepki",
		"text_en": "## Oracle 17: Mystic Backlash\n\n- 1-4: Your ritual has the opposite affect.\n- 5-8: You are sapped of strength.\n- 9-12: Your friend, ally, or companion is adversely affected.\n- 13-16: You destroy an important object.\n- 17-20: You inadvertently summon a horror.\n- 21-24: You collapse, and drift into a troubled sleep.\n- 25-28: You undergo a physical torment which leaves its mark upon you.\n- 29-32: You hear ghostly voices whispering of dark portents.\n- 33-36: You are lost in shadow, and find yourself in another place without memory of how you got there.\n- 37-40: You alert someone or something to your presence.\n- 41-44: You are not yourself, and act against a friend, ally, or companion.\n- 45-48: You affect or damage your surroundings, causing a disturbance or potential harm.\n- 49-52: You waste resources.\n- 53-56: You suffer the loss of a sense for several hours.\n- 57-60: You lose your connection to magic for a day or so, and cannot perform rituals.\n- 61-64: Your ritual affects the target in an unexpected and problematic way.\n- 65-68: Your ritual reveals a surprising and troubling truth.\n- 69-72: You are tempted by dark powers.\n- 73-76: You see a troubling vision of your future.\n- 77-80: You can't perform this ritual again until you acquire an important component.\n- 81-84: You develop a strange fear or compulsion.\n- 85-88: Your ritual causes creatures to exhibit strange or aggressive behavior.\n- 89-92: You are tormented by an apparition from your past.\n- 93-96: You are wracked with sudden sickness.\n- 97-00: Roll twice more on this table. Both results occur. If they are the same result, make it worse.",
		"text_tr": "## Kehanet 17: Mistik Tepki\n\n- 1-4: Ritüelin ters etki yapar.\n- 5-8: Gücün tükenir.\n- 9-12: Arkadaşın, müttefikin ya da yoldaşın olumsuz etkilenir.\n- 13-16: Önemli bir eşyayı yok edersin.\n- 17-20: İstemeden bir dehşet çağırırsın.\n- 21-24: Yığılır kalır, huzursuz bir uykuya dalarsın.\n- 25-28: Üzerinde iz bırakan bedensel bir ıstıraptan geçersin.\n- 29-32: Kara alametleri fısıldayan hayalet sesler duyarsın.\n- 33-36: Gölgede kaybolur, oraya nasıl geldiğini hatırlamadan kendini başka bir yerde bulursun.\n- 37-40: Birini ya da bir şeyi varlığından haberdar edersin.\n- 41-44: Kendinde değilsin ve bir arkadaşına, müttefikine ya da yoldaşına karşı harekete geçersin.\n- 45-48: Çevreni etkiler ya da ona zarar verir, bir karışıklığa ya da olası hasara yol açarsın.\n- 49-52: Kaynakları boşa harcarsın.\n- 53-56: Birkaç saatliğine bir duyunu yitirirsin.\n- 57-60: Bir gün kadar büyüyle bağını yitirir, ritüel yapamazsın.\n- 61-64: Ritüelin hedefi beklenmedik ve sorunlu bir biçimde etkiler.\n- 65-68: Ritüelin şaşırtıcı ve rahatsız edici bir hakikati açığa çıkarır.\n- 69-72: Karanlık güçler seni baştan çıkarır.\n- 73-76: Geleceğine dair rahatsız edici bir görü görürsün.\n- 77-80: Önemli bir bileşen edinene kadar bu ritüeli bir daha yapamazsın.\n- 81-84: Tuhaf bir korku ya da takıntı geliştirirsin.\n- 85-88: Ritüelin yaratıkların tuhaf ya da saldırgan davranmasına yol açar.\n- 89-92: Geçmişinden bir hayalet seni ezer.\n- 93-96: Ansızın gelen bir hastalık seni kıvrandırır.\n- 97-00: Bu tabloda iki kez daha zar at. İki sonuç da gerçekleşir. Aynı sonuç çıkarsa onu daha da kötüleştir."
	},
	{
		"page": 190,
		"img": "/rulebook/kehanetler/p190.webp",
		"title_en": "Oracle 18: Major Plot Twist / Oracle 19: Challenge Rank",
		"title_tr": "Kehanet 18: Büyük Olay Örgüsü Sürprizi / Kehanet 19: Zorluk Derecesi",
		"text_en": "## Oracle 18: Major Plot Twist\n\n- 1-5: It was all a diversion.\n- 6-10: A dark secret is revealed.\n- 11-15: A trap is sprung.\n- 16-20: An assumption is revealed to be false.\n- 21-25: A secret alliance is revealed.\n- 26-30: Your actions benefit an enemy.\n- 31-35: Someone returns unexpectedly.\n- 36-40: A more dangerous foe is revealed.\n- 41-45: You and an enemy share a common goal.\n- 46-50: A true identity is revealed.\n- 51-55: You are betrayed by someone who was trusted.\n- 56-60: You are too late.\n- 61-65: The true enemy is revealed.\n- 66-70: The enemy gains new allies.\n- 71-75: A new danger appears.\n- 76-80: Someone or something goes missing.\n- 81-85: The truth of a relationship is revealed.\n- 86-90: Two seemingly unrelated situations are shown to be connected.\n- 91-95: Unexpected powers or abilities are revealed.\n- 96-00: Roll twice more on this table. Both results occur. If they are the same result, make it more dramatic.\n\n## Oracle 19: Challenge Rank\n\n- 1-20: Troublesome\n- 21-55: Dangerous\n- 56-80: Formidable\n- 81-93: Extreme\n- 94-00: Epic",
		"text_tr": "## Kehanet 18: Büyük Olay Örgüsü Sürprizi\n\n- 1-5: Hepsi bir saptırmacaymış.\n- 6-10: Karanlık bir sır açığa çıkar.\n- 11-15: Bir tuzak tetiklenir.\n- 16-20: Bir varsayımın yanlış olduğu ortaya çıkar.\n- 21-25: Gizli bir ittifak açığa çıkar.\n- 26-30: Eylemlerin bir düşmanın işine yarar.\n- 31-35: Biri beklenmedik biçimde geri döner.\n- 36-40: Daha tehlikeli bir hasım ortaya çıkar.\n- 41-45: Bir düşmanla ortak bir amacınız vardır.\n- 46-50: Gerçek bir kimlik açığa çıkar.\n- 51-55: Güvenilen biri sana ihanet eder.\n- 56-60: Çok geç kaldın.\n- 61-65: Gerçek düşman açığa çıkar.\n- 66-70: Düşman yeni müttefikler kazanır.\n- 71-75: Yeni bir tehlike belirir.\n- 76-80: Biri ya da bir şey kaybolur.\n- 81-85: Bir ilişkinin hakikati açığa çıkar.\n- 86-90: Birbiriyle ilgisiz görünen iki durumun bağlantılı olduğu ortaya çıkar.\n- 91-95: Beklenmedik güçler ya da yetenekler açığa çıkar.\n- 96-00: Bu tabloda iki kez daha zar at. İki sonuç da gerçekleşir. Aynı sonuç çıkarsa onu daha da dramatik kıl.\n\n## Kehanet 19: Zorluk Derecesi\n\n- 1-20: Sıradan\n- 21-55: Tehlikeli\n- 56-80: Zorlu\n- 81-93: Aşırı\n- 94-00: Destansı"
	},
	{
		"page": 191,
		"img": "/rulebook/kehanetler/p191.webp",
		"title_en": "More Oracles / Creating Your Own Oracles",
		"title_tr": "Daha Fazla Kehanet / Kendi Kehanetlerini Yaratmak",
		"text_en": "## More Oracles\n\nRoleplaying games have a long tradition of using random generators as a play aid. If you're an avid collector of RPG's, you may wish to leverage oracles from other systems. You can also find a limitless supply of random generators and tables online—names, people, creatures, places, plot hooks, and much more.\n\nPhysical randomizers can also be helpful. You can purchase dice with various icons that can be interpreted to resolve questions and trigger new situations. Or, you can play with tarot cards or rune stones.\n\nWhatever aids you use, don't let randomness overwhelm your narrative. Your own story instincts are the most powerful tool in your gaming kit.\n\n## Creating Your Own Oracles\n\nYou will find a blank worksheet at ironswornrpg.com to create your own oracle tables. You can make tables which better fit your preferences or support the tone of your game.\n\nYou can also create specific tables for certain narrative situations. Heading out for a dangerous journey into the mountains? Create a table of things you might encounter. Then, roll on the table when you want to introduce an encounter or event.",
		"text_tr": "## Daha Fazla Kehanet\n\nRol yapma oyunlarının, rastgele üreteçleri bir oyun yardımcısı olarak kullanma konusunda köklü bir geleneği vardır. Tutkulu bir RYO koleksiyoncuysan, başka sistemlerin kehanetlerinden yararlanmak isteyebilirsin. Ayrıca internette sınırsız sayıda rastgele üreteç ve tablo bulabilirsin: adlar, kişiler, yaratıklar, yerler, olay kancaları ve çok daha fazlası.\n\nFiziksel rastgeleleştiriciler de işe yarayabilir. Soruları yanıtlamak ve yeni durumlar tetiklemek için yorumlanabilecek çeşitli simgelere sahip zarlar satın alabilirsin. Ya da tarot kartları veya rün taşlarıyla oynayabilirsin.\n\nHangi yardımcıları kullanırsan kullan, rastgeleliğin anlatını boğmasına izin verme. Kendi öykü içgüdülerin, oyun çantandaki en güçlü araçtır.\n\n## Kendi Kehanetlerini Yaratmak\n\nKendi kehanet tablolarını yaratmak için ironswornrpg.com adresinde boş bir çalışma sayfası bulacaksın. Tercihlerine daha iyi uyan ya da oyununun tonunu destekleyen tablolar yapabilirsin.\n\nBelirli anlatı durumları için özel tablolar da yaratabilirsin. Dağlara tehlikeli bir yolculuğa mı çıkıyorsun? Karşılaşabileceğin şeylerden oluşan bir tablo yarat. Sonra bir karşılaşma ya da olay sunmak istediğinde tabloda zar at."
	}
];
